Netflix/atlas

- atlas-core/src/main/scala/com/netflix/atlas/core/model/MathExpr.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/model/TimeSeriesExprSuite.scala
It wasn't checking if the input was empty like the other
aggregate functions. Now it performs the same check which
avoids errors like:
```
must have 1 or more time series to perform aggregation
```
> fix empty data case for math/count

- atlas-core/src/main/resources/reference.conf
This is a newer version that avoids the need for regex and
follows current conventions.
/cc @vfilanovsky
> switch to discovery.status metric for eureka-avg

- atlas-json/src/main/scala/com/netflix/atlas/json/Json.scala
- atlas-json/src/test/scala/com/netflix/atlas/json/JsonSuite.scala
- build.sbt
- project/Dependencies.scala
Uses for Atlas moved to `java.time` a long time ago. Users can
add this manually by calling `Json.registerModule` if it is
still needed.
> remove jackson-datatype-joda usage

- .travis.yml
- project/Dependencies.scala
Use 1.6.x if 2.11 support is still needed.
> remove cross build for 2.11

- atlas-akka/src/main/scala/com/netflix/atlas/akka/StreamOps.scala
- atlas-akka/src/main/scala/com/netflix/atlas/akka/WebServer.scala
- atlas-akka/src/test/scala/com/netflix/atlas/akka/StreamOpsSuite.scala
- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/EvaluationFlows.scala
- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/EvaluatorImpl.scala
- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/StreamContext.scala
- atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/StreamApi.scala
- atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/SubscribeApi.scala
- atlas-lwcapi/src/test/scala/com/netflix/atlas/lwcapi/SubscribeApiSuite.scala
- atlas-module-akka/src/main/scala/com/netflix/atlas/akka/AkkaModule.scala
- atlas-poller/src/main/scala/com/netflix/atlas/poller/ClientActor.scala
- atlas-poller/src/test/scala/com/netflix/atlas/poller/ClientActorSuite.scala
Setup a default binding for the materializer using a
supervision strategy that will provide better visibility
into failures.
> add binding for materializer

- project/BuildSettings.scala
Before it was looking specifically for version 12. For now
we still need to be able to run on jdk8+. The specific issue
encountered was:
```
java.lang.NoSuchMethodError: java.nio.CharBuffer.clear()Ljava/nio/CharBuffer;
at com.netflix.atlas.core.model.TaggedItem$.writePair(TaggedItem.scala:59)
at com.netflix.atlas.core.model.TaggedItem$.computeId(TaggedItem.scala:105)
at com.netflix.atlas.core.model.TimeSeries$.<clinit>(TimeSeries.scala:22)
at com.netflix.atlas.core.model.EvalContext.<init>(EvalContext.scala:32)
at com.netflix.atlas.druid.DruidDatabaseActorSuite.<init>(DruidDatabaseActorSuite.scala:259)
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at …
```
> 1.6: fix build settings for 2.13 to use `-release 8`

- project/BuildSettings.scala
Port #1055 from 1.6.x branch to master.
Before it was looking specifically for version 12. For now
we still need to be able to run on jdk8+. The specific issue
encountered was:
```
java.lang.NoSuchMethodError: java.nio.CharBuffer.clear()Ljava/nio/CharBuffer;
at com.netflix.atlas.core.model.TaggedItem$.writePair(TaggedItem.scala:59)
at com.netflix.atlas.core.model.TaggedItem$.computeId(TaggedItem.scala:105)
at com.netflix.atlas.core.model.TimeSeries$.<clinit>(TimeSeries.scala:22)
at com.netflix.atlas.core.model.EvalContext.<init>(EvalContext.scala:32)
at com.netflix.atlas.druid.DruidDatabaseActorSuite.<init>(DruidDatabaseActorSuite.scala:259)
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAcc …
```
> fix build settings for 2.13 to use `-release 8`

- atlas-poller-cloudwatch/src/main/resources/ec2.conf
map the `system` id to `StatusCheckFailed_System`, instead of
`StatusCheckFailed_Instance`
> fix aws.ec2.badInstances mapping

- atlas-poller-cloudwatch/src/main/resources/es.conf
From the ElasticSearch CloudWatch metrics documentation:
https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-managedomains.html#es-managedomains-cloudwatchmetrics-master-node-metrics
This metric is not relevant and can be ignored. The service does not use
master nodes as data nodes.
> remove ElasticSearch MasterFreeStorageSpace metric

- atlas-core/src/main/scala/com/netflix/atlas/core/model/CustomVocabulary.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/model/CustomVocabularySuite.scala
Before it was creating a new instance of a function when
generating the `MathExpr.NamedRewrite` object so the equality
would never match.
> fix equality for custom averages

- project/sbt
Backport #1064 to 1.6.x.
Setting in the `build.properties` file doesn't seem to work
for this setting (tried in #1062).
> 1.6: try disabling gigahorse

- atlas-core/src/main/scala/com/netflix/atlas/core/model/CustomVocabulary.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/model/CustomVocabularySuite.scala
Backport #1063 to 1.6.x.
Before it was creating a new instance of a function when
generating the `MathExpr.NamedRewrite` object so the equality
would never match.
> 1.6: fix equality for custom averages

- atlas-akka/src/main/scala/com/netflix/atlas/akka/RequestHandler.scala
It was hitting the fallback before and using a status code
of 500 instead of a 4xx status code. This would cause some
clients to retry when they shouldn't.
> fix status code for requests that are too large

- atlas-core/src/main/scala/com/netflix/atlas/core/validation/NameValueLengthRule.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/validation/NameValueLengthRuleSuite.scala
- atlas-webapi/src/main/resources/reference.conf
Allows different limits to be used for the value of the
name key compared to other keys. This is mostly to remove
a difference between the internal Atlas setup at Netflix
and OSS. Internally for historical reasons the value for
the name key is allowed to be longer than other values.
With this change there is no longer a need to have custom
rules.
> add NameValueLengthRule

- atlas-poller-cloudwatch/src/main/resources/rds.conf
This commit adds collection of AWS/RDS/OldestReplicationSlotLag. Other
`Lag` metrics represent time lag. This metric represents more data
coming in that being replicated. So, in order to avoid confusion with
those other lag metrics, I've suffixed this with `DataBacklog`.
Resolves #1067
> Add RDS OldestReplicationSlotLag

- atlas-poller-cloudwatch/src/main/scala/com/netflix/atlas/cloudwatch/CloudWatchPoller.scala
- build.sbt
- project/Dependencies.scala
Use iep-leader library to check leadership status and only publish
metrics if instance has leadership. This is primarily to prevent
duplicate metrics on the streaming path.
> Only publish metrics if instance has leadership

- atlas-core/src/main/scala/com/netflix/atlas/core/norm/MaxValueFunction.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/norm/NormalizationCache.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/norm/MaxValueFunctionSuite.scala
For use-cases where we perform inline aggregation this
gives the expected value and avoids the need for an
additional disambiguation tag for the aggregator instance.
This also means that if no custom rollups are done the sum
of the gauge values would match expectations rather than
being a multiple of the number of aggregator instances.
> switch to max normalization for gauges

- project/Dependencies.scala
As our deployments are switching over, it makes sense to
have this be the default we use for development.
> make 2.13 the default scala version

- project/Dependencies.scala
Fixes serialization issue with case objects on scala 2.13.
> jackson 2.9.10

- atlas-webapi/src/main/resources/reference.conf
Include `atlas.aggr` used for inline aggregation. Remove the
`atlas.rollup` which was for an experimental rollup support
that we ended up not doing.
> update default set of `atlas.` reserved keys

- atlas-akka/src/main/scala/com/netflix/atlas/akka/ByteStringInputStream.scala
- atlas-akka/src/main/scala/com/netflix/atlas/akka/CustomDirectives.scala
- atlas-akka/src/test/scala/com/netflix/atlas/akka/ByteStringInputStreamSuite.scala
- atlas-jmh/src/main/scala/com/netflix/atlas/akka/ByteStringReading.scala
Adds a ByteStringInputStream so we can read the data
directly from the ByteString without copying to an
intermediate array.
> reduce allocations for parsing payloads

- atlas-akka/src/main/resources/reference.conf
- atlas-akka/src/main/scala/com/netflix/atlas/akka/CustomDirectives.scala
- atlas-akka/src/main/scala/com/netflix/atlas/akka/RequestHandler.scala
- atlas-akka/src/test/scala/com/netflix/atlas/akka/RequestHandlerNoCompressionSuite.scala
There are options now to disable automatic handling
of compression and whether or not to setup access
logging. For high volume services the automatic
compression results in a lot of allocations for
intermediate ByteStrings. The json directives will
not automatically wrap with a GZIPInputStream if
the data is GZIP compressed. For some services this
drastically reduces the allocation rate.
> add options to tune request handler

- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/Evaluator.java
- atlas-eval/src/test/scala/com/netflix/atlas/eval/stream/DataSourceSuite.scala
If the step size is not in the JSON payload, then extract
from the URI as expected rather than leave it as null.
> extract step when creating DataSource from JSON

- atlas-core/src/main/scala/com/netflix/atlas/core/validation/CompositeTagRule.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/validation/Rule.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/validation/RuleSuite.scala
- atlas-jmh/src/main/scala/com/netflix/atlas/core/validation/TagRules.scala
A lot of time is spent iterating the maps. It is faster to
iterate over the set of rules for each key/value pair.
> optimization for tag validation

- atlas-akka/src/main/scala/com/netflix/atlas/akka/ByteStringInputStream.scala
- atlas-jmh/src/main/scala/com/netflix/atlas/akka/ByteStringReading.scala
Uses the `asByteBuffer` conversion to allow for more
efficient reads. The `copyToArray` was really slow and
was worse than just always using `apply` and reading
a single byte. The byte buffer approach avoids the
intermediate array allocation and supports a fast copy
to another array. For the sample benchmark it is about
10x faster.
> optimize ByteStringInputStream for large payloads

- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/EurekaGroupsLookup.scala
- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/TimeGrouped.scala
- atlas-eval/src/test/scala/com/netflix/atlas/eval/stream/EurekaGroupsLookupSuite.scala
- atlas-eval/src/test/scala/com/netflix/atlas/eval/stream/EvaluatorSuite.scala
When using the eval processor for local data, it should
stop quickly after the upstream is complete. Before the
throttling on the Eureka lookup would cause about a 30s
delay.
This changes the Eureka lookup to use an empty source
if there are no remote data sources. Also fixes a bug
with TimeGrouped where it could potentially push without
a downstream pull when the upstream finishes.
> avoid delay on finish for local eval processor

- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/EvaluatorImpl.scala
Fix stream result aggregation issue when multiple URLs with same query in one session
When multiple urls have the same query but different host, the result is aggregation of all data from urls with the same query ignoring different host. Fixed by grouping by host, processing them in sub-streams with the exact existing flow and then merging results back to one stream.
> fix stream aggregation issue by grouping DataSources by host first

- conf/lwcapi.conf
Redis hasn't been used in a long time. See #561.
> remove old redis conf settings

- atlas-poller-cloudwatch/src/main/resources/reference.conf
- atlas-poller-cloudwatch/src/main/resources/tgw.conf
CloudWatch mappings for [TGW metrics]. Note, in CW there
are drop counts for bytes as well as packets, though the
docs only shows packets.
[TGW metrics]: https://docs.aws.amazon.com/vpc/latest/tgw/transit-gateway-cloudwatch-metrics.html
> add mapping for transit gateway metrics

- atlas-core/src/main/scala/com/netflix/atlas/core/model/TagKey.scala
The prefixes list is not used anywhere and it is faster
as a simple condition.
> simplify condition for isRestricted

- atlas-core/src/main/scala/com/netflix/atlas/core/util/Shards.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/util/ShardsSuite.scala
In intermediate deployment stages, some of the shard
groups may be empty. Before this would result in a
divide by zero error. Now it will return null. Null
is used instead of `Option[T]` to maintain backwards
compatibility and avoid the extra allocation if used
in a hot path.
> handle some shard groups being empty

- atlas-akka/src/main/scala/com/netflix/atlas/akka/RequestHandler.scala
Renamed to PayloadTooLarge in latest version of akka-http.
> fix RequestEntityTooLarge deprecation

- atlas-akka/src/main/scala/com/netflix/atlas/akka/StreamOps.scala
- atlas-akka/src/test/scala/com/netflix/atlas/akka/StreamOpsSuite.scala
Works similar to the `uniq` command on unix and filters
out consecutive values that are repeated.
> stream helper to filter out duplicates

- atlas-akka/src/main/scala/com/netflix/atlas/akka/ClusterOps.scala
- atlas-akka/src/main/scala/com/netflix/atlas/akka/StreamOps.scala
- atlas-akka/src/test/scala/com/netflix/atlas/akka/ClusterOpsSuite.scala
Maintains a sub-flow for each member of a cluster. The set
of flows can change as the membership of the cluster changes.
This is a more generic version of the connection manager
logic from the eval library.
Primary use-case is for operations that require communication
with all members of a cluster.
> add cluster group by operator

- atlas-lwcapi/src/main/resources/reference.conf
- atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/ApiSettings.scala
- atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/ExpressionMetadata.scala
- atlas-lwcapi/src/test/scala/com/netflix/atlas/lwcapi/ApiSettingsSuite.scala
- atlas-lwcapi/src/test/scala/com/netflix/atlas/lwcapi/ExpressionMetadataSuite.scala
- atlas-lwcapi/src/test/scala/com/netflix/atlas/lwcapi/SubscribeApiSuite.scala
The goal is to try and make the naming more consistent
and standardize on `step` everywhere. Parts of lwcapi
were the only places that referred to this as `frequency`.
This updates the `ExpressionMetadata` class so it will
treat `step` as an alias. This will allow the eval library
to be updated. For now the output of the expressions api
needs to keep it as `frequency` to ensure backwards
compatibility with clients.
> update lwcapi to accept `step`

- atlas-webapi/src/main/resources/reference.conf
In order to support a new method of sharding internally at Netflix,
allow `nf.shard1` and `nf.shard2` tags
> Allow nf.shard tags

- atlas-core/src/main/scala/com/netflix/atlas/core/model/TagKey.scala
Cleanup some of the unused methods and fields for
TagKey object. The validation is handled based on
the config now.
> remove unused methods from TagKey

- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/EurekaGroupsLookup.scala
- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/EvaluationFlows.scala
There's a delay on stopping host lookup caused by EvaluationFlows.repeatWhile, use EvaluationFlows.stoppableSource instead. 
The delay can cause temporary incorrect lwc subscriptions when subscriptions change.
> fix delay of stopping host lookup

- atlas-poller-cloudwatch/src/main/resources/ec2.conf
Tracks the number of requests to IMDSv1. Used to help with
tracking migration to IMDSv2.
> add mapping for MetadataNoToken

- atlas-poller-cloudwatch/src/main/resources/reference.conf
A user can opt-in if desired. This makes the default config
line up with internal usage.
> exclude ec2 cloudwatch category by default

- atlas-poller-cloudwatch/src/main/resources/ec2.conf
During the transition period it is desirable to have
this metric for ASGs even though we do not need other
EC2 CW data.
> move metadata counter to separate category

- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/EvaluatorImpl.scala
- atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/SubscribeApi.scala
- atlas-lwcapi/src/test/scala/com/netflix/atlas/lwcapi/SubscribeApiSuite.scala
Currently WebSocket handler is singleton with the same streamID shared by different client connection, so only the first connection works. The fix is to create 1 instance of handler per request, also getting streamId from request allows client to have same streamId for all LWC API calls.
> fix shared WebSocket handler issue

- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/EurekaGroupsLookup.scala
- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/EvaluatorImpl.scala
- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/FillRemovedKeysWith.scala
- atlas-eval/src/test/scala/com/netflix/atlas/eval/stream/EurekaGroupsLookupSuite.scala
- atlas-eval/src/test/scala/com/netflix/atlas/eval/stream/FillRemovedKeysWithSuite.scala
Emit empty DataSources for a host if no more DataSource so that downstream can stop stream from LWC timely for this host, this is preparing for single evaluator at atlas-stream API.
> emit empty DataSources for a host if no more DataSource

- conf/memory.conf
Update the memory.conf example to reflect move of graphing
logic to eval library.
Fixes #1135.
> update settings in memory.conf

- conf/memory.conf
Update the memory.conf example to reflect move of graphing
logic to eval library.
Fixes #1135
> 1.6: update settings in memory.conf

- Makefile
Bintray now requires HTTPS for downloading the artifacts. Also
bump to the latest version.
> update launcher url to use HTTPS

- Makefile
Backport of #1141.
Bintray now requires HTTPS for downloading the artifacts. Also
bump to the latest version.
> 1.6: update launcher url to use HTTPS

- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/Evaluator.java
- atlas-eval/src/test/scala/com/netflix/atlas/eval/stream/EvaluatorSuite.scala
- atlas-json/src/main/scala/com/netflix/atlas/json/Json.scala
- atlas-json/src/test/scala/com/netflix/atlas/json/JsonSuite.scala
Set the default serialization to use millisecond timestamps.
This keeps it more consistent with other usage in Atlas.
> adjust default serialization for java.time

- atlas-eval/src/main/scala/com/netflix/atlas/eval/model/LwcDataExpr.scala
- atlas-eval/src/main/scala/com/netflix/atlas/eval/model/LwcMessages.scala
- atlas-eval/src/test/scala/com/netflix/atlas/eval/model/LwcMessagesSuite.scala
- atlas-jmh/src/main/scala/com/netflix/atlas/eval/model/LwcMessagesParse.scala
- atlas-json/src/main/scala/com/netflix/atlas/json/JsonParserHelper.scala
- atlas-json/src/test/scala/com/netflix/atlas/json/JsonParserHelperSuite.scala
For some recent tests around 9% of the CPU time was spent
parsing these messages when under heavy load. Using the JMH
benchmark this provides a little over 2x faster parsing and
similar reduction in allocations.
> optimize parsing of LWC messages

- atlas-eval/src/main/scala/com/netflix/atlas/eval/model/LwcMessages.scala
- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/LwcToAggrDatapoint.scala
- atlas-jmh/src/main/scala/com/netflix/atlas/eval/model/LwcMessagesParse.scala
When parsing the LWC messages converting to a string first
is unnecessary. Avoiding this results in about 30% improvement
in the throughput.
> avoid unnecessary string conversion

- atlas-core/src/main/scala/com/netflix/atlas/core/model/DataExpr.scala
- atlas-eval/src/test/scala/com/netflix/atlas/eval/model/LwcDataExprSuite.scala
For streaming evaluation the DataExpr is the key in the
time grouping stage. The largest expense in the time
grouping stage was computing the hash code of the DataExpr
to aggregate the datapoints as they were flowing through.
> cache the hash code for DataExprs

- atlas-eval/src/main/resources/reference.conf
- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/EvaluatorImpl.scala
atlas-eval: make queue size configurable for lwc call
> atlas-eval: make queue size configurable for lwc call

- atlas-poller-cloudwatch/src/main/resources/reference.conf
The trusted advisor data in cloudwatch is only updated
when something refreshes the checks. Unless something
is doing that, there isn't much point in collecting
the cloudwatch data.
> disable trusted advisor collection by default

- atlas-akka/src/main/scala/com/netflix/atlas/akka/ClusterOps.scala
- atlas-eval/src/main/resources/reference.conf
- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/EvaluatorImpl.scala
atlas-eval: lower eval input queue-size, it's for the DataSources updates at low rate
> atlas-eval: lower eval input queue-size, it's for the DataSources updates at low rate

- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/EvaluatorImpl.scala
Converting to Processor disables operator fusion at the boundary, and reduces overall throughput. This change exposes the Flow directly and enables operator fusion optimization, and downstream delay of the boundary reduced from hundreds of microseconds to tens of microseconds.
> atlas-eval: expose Flow api in Executor to maximize throughput

- atlas-core/src/main/scala-2.13+/com/netflix/atlas/core/util/SmallHashMap.scala
- atlas-jmh/src/main/scala/com/netflix/atlas/core/util/SmallHashMapModify.scala
Loop over the array directly to avoid the lambda overhead
for adding or removing an item. This can be a hot path for
some use-cases.
> SmallHashMap: avoid lambda overhead for add/remove

- atlas-core/src/main/scala-2.13+/com/netflix/atlas/core/util/SmallHashMap.scala
- atlas-core/src/main/scala-2.13-/com/netflix/atlas/core/util/SmallHashMap.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/model/TaggedItem.scala
- atlas-eval/src/main/scala/com/netflix/atlas/eval/model/TimeSeriesMessage.scala
- atlas-webapi/src/main/scala/com/netflix/atlas/webapi/PublishApi.scala
This method is available for maps in scala 2.13.0. This makes
the custom SmallHashMap more inline with the scala maps.
> switch to foreachEntry for SmallHashMap

- atlas-core/src/main/scala/com/netflix/atlas/core/index/QueryIndex.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/index/QueryIndexSuite.scala
Update QueryIndex matching methods to use foreachEntry
to avoid temporary tuples.
> avoid intermediate tuple allocations

- atlas-akka/src/main/scala/com/netflix/atlas/akka/ClusterOps.scala
- atlas-chart/src/main/scala/com/netflix/atlas/chart/JsonCodec.scala
- atlas-chart/src/main/scala/com/netflix/atlas/chart/JsonGraphEngine.scala
- atlas-chart/src/main/scala/com/netflix/atlas/chart/StatsJsonGraphEngine.scala
- atlas-chart/src/main/scala/com/netflix/atlas/chart/util/PngImage.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/util/IdentityMap.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/util/IdentityMapSuite.scala
- atlas-eval/src/main/scala/com/netflix/atlas/eval/model/LwcDatapoint.scala
- atlas-webapi/src/main/scala/com/netflix/atlas/webapi/PublishApi.scala
This method is more efficient in many cases and avoids
temporary tuple objects. Now that we do not need to worry
about 2.12 compatibility, switch to using it where possible.
> switch to foreachEntry iterating maps

- atlas-core/src/main/scala/com/netflix/atlas/core/model/Query.scala
- atlas-eval/src/main/scala/com/netflix/atlas/eval/model/TimeSeriesMessage.scala
- atlas-jmh/src/main/scala/com/netflix/atlas/core/index/QueryIndexMatching.scala
This get computed a lot when leveraging a query index. In
some cases it is over 5% of the time. Current JMH benchmark
shows a similar improvement after caching.
| Benchmark            |        Before |         After | % Delta |
|----------------------|---------------|---------------|---------|
| index_100            |   2,950,658.3 |   3,032,810.1 |     2.8 |
| index_1000           |   2,072,328.3 |   2,122,367.3 |     2.4 |
| index_10000          |   2,527,147.8 |   2,714,280.1 |     7.4 |
| index_100000         |   2,028,644.4 |   2,152,331.2 |     6.1 |
> cache hash code for Query

- atlas-core/src/main/scala/com/netflix/atlas/core/model/ItemId.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/util/Shards.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/model/ItemIdSuite.scala
This method is compatible with what you would get by calling
`toBigInteger.intValue` but avoids the overhead of creating
an intermediate BigInteger object if that is the only use.
> add helper for getting intValue from ItemId

- atlas-json/src/main/scala/com/netflix/atlas/json/JsonParserHelper.scala
- atlas-json/src/test/scala/com/netflix/atlas/json/JsonParserHelperSuite.scala
The `skipNext` helper did not work correctly in the case
of some complex objects with nested arrays. This change
fixes the logic and adds more extensive testing with
randomly generated JSON objects.
> fix logic for skipNext

- project/BuildSettings.scala
Not needed now that we are on 2.13 only. Clears up warnings
during the build.
> remove -Xexperimental flag

- atlas-akka/src/main/scala/com/netflix/atlas/akka/ClusterOps.scala
Currently the whole eval flow may fail when a lwc instance is removed. There's a subflow for lwc api call of each lwc instance, and that subflow is wrapped around by "RestartFlow" to enable auto-retry. The subflow is finished from upstream when a lwc instance is removed, and when upstream of RestartFlow is finished, RestartFlow also finishes and propagate the failure from the current ongoing attempt if any, to downstream, and eventually propagate to main flow.
The fix is to have downstream of RestartFlow suppress the failure with Flow.recoverWithRetries, since the failure is expected and should be ignored on lwc instance removal.
> atlas-eval: fix eval flow failure on lwc instance removal

- conf/memory.conf
Before depending on how the path for the `memory.conf` file
was specified, it would try to load from the file system
instead of the classpath and the base config would be missing.
Now it is explicit about including from the classpath.
Fixes #1146.
> fix memory.conf to include from classpath

- atlas-core/src/main/scala/com/netflix/atlas/core/algorithm/AlgoState.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/algorithm/AlgoStateSuite.scala
- atlas-json/src/main/scala/com/netflix/atlas/json/Json.scala
- atlas-json/src/test/scala/com/netflix/atlas/json/JsonSuite.scala
Historically some endpoints wrote the special double values
without quotes to make it clear they were numeric. However,
that creates problems with tools using standard JSON parsing
libraries. New uses should always emit standard JSON so this
change updates the default so these values are quoted.
The encoding for the legacy `json` format on the graph API
still emits data without the quotes for backwards compatibility.
> enable WRITE_NAN_AS_STRINGS by default

- .travis.yml
- atlas-akka/src/main/scala/com/netflix/atlas/akka/ClusterOps.scala
- atlas-chart/src/main/scala/com/netflix/atlas/chart/DefaultGraphEngine.scala
- atlas-chart/src/main/scala/com/netflix/atlas/chart/graphics/Scales.scala
- atlas-chart/src/main/scala/com/netflix/atlas/chart/graphics/Text.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/model/MathExpr.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/model/Query.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/model/QuerySuite.scala
- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/FillRemovedKeysWith.scala
- atlas-eval/src/test/scala/com/netflix/atlas/eval/stream/LwcToAggrDatapointSuite.scala
- atlas-json/src/main/scala/com/netflix/atlas/json/JsonParserHelper.scala
- project/BuildSettings.scala
Most of the new warnings were for widening conversions from
long to double. Since cross-building has been disabled, all
warnings have been cleared up with no issues. Enabled fatal
warnings to help keep the build clean.
> fix compiler warnings for 2.13.2

- atlas-akka/src/main/scala/com/netflix/atlas/akka/ByteStringInputStream.scala
- atlas-akka/src/test/scala/com/netflix/atlas/akka/ByteStringInputStreamSuite.scala
- atlas-jmh/src/main/scala/com/netflix/atlas/akka/ByteStringReading.scala
Adjusts the ByteStringInputStream to work better for composite
ByteString objects. Before it was using `asByteBuffer` which
forces a compaction on composite types. Now it uses the
`asByteBuffers` method. This results in a large reduction in
allocations and increase in throughput.
**Throughput**
| Benchmark            |        Before |         After | % Delta |
|----------------------|---------------|---------------|---------|
| compositeInputStream |          31.8 |         137.6 |   332.9 |
| compositeToArray     |          44.6 |          46.2 |     3.5 |
| inputStream          |         115.1 |         126.5 |     9.9 |
| toArray              |          42.8 |          45.0 |     5.2 |
**Allocations**
| Benchmark            |        Before |         After | % Delta | …
> tune ByteStringInputStream for composites

- atlas-core/src/main/scala/com/netflix/atlas/core/util/Streams.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/util/StreamsSuite.scala
This is the base interface for Closeable so it is more
generic than it was before. Allows this helper to be used
with Stream's that need to be closed such as those returned
by `Files.list`.
> update Streams.scope to work with AutoCloseable

- atlas-core/src/main/scala/com/netflix/atlas/core/util/SmallHashMap.scala
It can be quite a bit slower if not inlined.
> SmallHashMap: avoid BoxesRunTime.equals

- atlas-poller-cloudwatch/src/main/resources/iot.conf
- atlas-poller-cloudwatch/src/main/resources/reference.conf
Adds initial mapping. Omits a few of the metrics where
we do not have any samples to test with current usage.
> add mapping for CloudWatch IoT metrics

- atlas-core/src/main/scala/com/netflix/atlas/core/norm/NormalizationCache.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/norm/SumValueFunction.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/norm/SumValueFunctionSuite.scala
- atlas-webapi/src/main/scala/com/netflix/atlas/webapi/LocalPublishActor.scala
This should be used carefully as it could cause overcounting.
The primary use-case is for inline aggregation of values that
are already normalized to the step size. For example, the
aggregator cluster could use this to avoid a multiple on
counters that are flowing through.
> add support for dstype of sum

- .travis.yml
Update travis build for 2.11 to use xenial.
> 1.6: switch from trusty to xenial

- atlas-core/src/main/scala/com/netflix/atlas/core/util/Step.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/util/StepSuite.scala
It doesn't matter as much for these larger ranges and
this can sometimes be useful for longer term graphs.
Before it would only allow 1d and 7d.
> allow arbitrary number of days for larger step

- atlas-poller-cloudwatch/src/main/resources/kinesis.conf
This causes it to get double published which can cause
minor differences depending on the order when the values
are normalized.
> remove duplicate mapping for GetRecords.Bytes

- build.sbt
rename root project to atlas to be more IDE friendly
> rename root project to atlas 

- atlas-core/src/main/scala/com/netflix/atlas/core/util/IsoDateTimeParser.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/util/Strings.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/util/IsoDateTimeParserSuite.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/util/StringsSuite.scala
In particular, it will now support zone offsets that do not
have the colons to make integration easier for some JS use
case.
/cc @nathfisher
> make datetime zone parsing more lenient

- .travis.yml
- atlas-core/src/main/scala/com/netflix/atlas/core/db/AggregateCollector.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/db/BlockStore.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/model/EvalContext.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/norm/ValueFunction.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/index/TagIndexSuite.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/util/StreamsSuite.scala
- atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/SubscriptionManager.scala
- atlas-webapi/src/main/scala/com/netflix/atlas/webapi/PublishApi.scala
Updates the travis build to use 2.13.3 and fixes the new
deprecation warnings that were introduced.
> fix deprecation warnings for 2.13.3

- atlas-akka/src/main/scala/com/netflix/atlas/akka/DiagnosticMessage.scala
- atlas-eval/README.md
- atlas-eval/src/main/scala/com/netflix/atlas/eval/model/AggrDatapoint.scala
- atlas-eval/src/main/scala/com/netflix/atlas/eval/model/EvalDataRate.scala
- atlas-eval/src/main/scala/com/netflix/atlas/eval/model/TimeGroup.scala
- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/EvalDataRateCollector.scala
- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/EvaluatorImpl.scala
- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/FinalExprEval.scala
- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/TimeGrouped.scala
- atlas-eval/src/test/scala/com/netflix/atlas/eval/stream/FinalExprEvalSuite.scala
- atlas-eval/src/test/scala/com/netflix/atlas/eval/stream/TimeGroupedSuite.scala
Expose raw data rate (from LWC) and final data out put rate for each DataSource. 
Raw data rate is collected at TimedGroup for each DataExpr and carry it to down stream, and summarized in FinalExprEval and emit.
> atlas-eval: expose data rate per datasource via diagnostic messages

- atlas-eval/src/main/resources/reference.conf
- atlas-eval/src/main/scala/com/netflix/atlas/eval/graph/DefaultSettings.scala
- atlas-eval/src/main/scala/com/netflix/atlas/eval/graph/Grapher.scala
- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/ExprInterpreter.scala
- atlas-eval/src/main/scala/com/netflix/atlas/eval/util/HostRewriter.scala
- atlas-eval/src/test/resources/application.conf
- atlas-eval/src/test/scala/com/netflix/atlas/eval/graph/GrapherSuite.scala
- atlas-eval/src/test/scala/com/netflix/atlas/eval/stream/TestContext.scala
- atlas-eval/src/test/scala/com/netflix/atlas/eval/util/HostRewriterSuite.scala
In some cases we have multiple DNS names for the same
backend, but the behavior varies a bit depending on the
host name. Internally this has been done for quite a
while on the main backends, but was not done for the
streaming execution. This change adds support for host
based rewrite that will be consistent between streaming
and the main backends.
> add support for rewrite based on host name

- atlas-core/src/main/scala/com/netflix/atlas/core/stacklang/Context.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/stacklang/Interpreter.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/stacklang/FreezeSuite.scala
The freeze operation is meant to reset the state of the
interpreter to isolate expressions. Before it was clearing
the variables meaning that after a freeze operation any
variables passed in at the start of the execution would
not be available. This change fixes it to reset to the
initial set of variables used when starting the execution.
> freeze should reset to initial variables

- atlas-core/src/main/scala/com/netflix/atlas/core/util/SmallHashMap.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/util/SmallHashMapSuite.scala
- atlas-jmh/src/main/scala/com/netflix/atlas/core/util/SmallHashMapJavaEntrySet.scala
Updates the `SmallHashMap.asJavaMap` implementation to
override `entrySet()`. The new implementation avoids
allocations for each item in the map.
**Throughput**
| Benchmark            |        Before |         After | % Delta |
|----------------------|---------------|---------------|---------|
| customEntrySet       |   8,400,934.3 |  13,480,190.3 |    60.5 |
**Allocations**
| Benchmark            |        Before |         After | % Delta |
|----------------------|---------------|---------------|---------|
| customEntrySet       |         296.0 |          24.0 |   -91.9 |
> reduce allocations for asJavaMap.entrySet

- atlas-akka/src/main/scala/com/netflix/atlas/akka/StreamOps.scala
- atlas-akka/src/test/scala/com/netflix/atlas/akka/StreamOpsSuite.scala
Add an API to indicate whether a queue should take more data, useful for health check. 
The existing API isDone also checks if queue is empty so it's not a fit for health check.
> Add an API to indicate whether a queue should take more data

- atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/EvaluateApi.scala
Adds the remote address to the trace log messages for
the `/evaluate` endpoint. Can help with debugging which
clients are responsible for producing ignored messages
if they have a stale expression set.
> lwcapi: add remote address to trace logs

- atlas-core/src/main/scala/com/netflix/atlas/core/validation/CompositeTagRule.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/validation/HasKeyRule.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/validation/KeyLengthRule.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/validation/KeyPatternRule.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/validation/MaxUserTagsRule.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/validation/NameValueLengthRule.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/validation/ReservedKeyRule.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/validation/Rule.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/validation/TagRule.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/validation/ValidCharactersRule.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/validation/ValidationResult.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/validation/ValueLengthRule.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/validation/ValuePatternRule.scala
- atlas-core/src/test/java/com/netflix/atlas/core/validation/JavaTestRule.java
- atlas-core/src/test/scala/com/netflix/atlas/core/validation/ConfigConstructorTestRule.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/validation/KeyLengthRuleSuite.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/validation/KeyPatternRuleSuite.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/validation/NameValueLengthRuleSuite.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/validation/ReservedKeyRuleSuite.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/validation/ValidCharactersRuleSuite.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/validation/ValueLengthRuleSuite.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/validation/ValuePatternRuleSuite.scala
- atlas-webapi/src/main/scala/com/netflix/atlas/webapi/LocalPublishActor.scala
- atlas-webapi/src/main/scala/com/netflix/atlas/webapi/PublishApi.scala
Metrics are typically submitted in large batches and
without this context it can be difficult for users to
narrow it down to particular data points that are
problematic.
Sample of updated response:
```json
{
"type": "partial",
"errorCount": 1,
"message": [
"invalid characters in value: name = [answerTo Everything] ([--.0-9A-Z^_a-z~] are allowed) (tags={\"nf.node\":\"i-123\",\"atlas.dstype\":\"gauge\",\"name\":\"answerTo Everything\"})"
]
}
```
Fixes #1199
> include tags in validation result responses

- atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/EvaluateApi.scala
Using different level for regular and ignored message, big cpu and disk hit to log every message for debugging.
> lwc: change log level for ignored msg

- atlas-akka/src/main/scala/com/netflix/atlas/akka/StreamOps.scala
- atlas-akka/src/test/scala/com/netflix/atlas/akka/StreamOpsSuite.scala
- atlas-eval/src/main/resources/reference.conf
- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/EvaluatorImpl.scala
Allow unique operator to emit repeated element after given time elapses. This should help keep subscriptions update to date for all lwc api instances in a cluster.
> allow timeout for unique operator

- atlas-module-akka/src/main/scala/com/netflix/atlas/akka/AkkaModule.scala
- atlas-standalone/src/main/scala/com/netflix/atlas/standalone/Main.scala
Ensures that it will get started even if the app doesn't
explicitly instantiate another class that uses it.
> make WebServer initialization eager

- atlas-poller-cloudwatch/src/main/resources/dx.conf
Two minor adjustments for the DX metric mapping:
1. Adjust period count to exceed the offset. It seems to
always use now as the end time and the period count needs
to exceed the offset to get data. That can be fixed later
to respect the offset for the time fetched and sanity check
the configs as part of tests.
2. Fix the name for the throughput metric. The unit is specified
and the ingestion code will automatically normalize to a base
unit of `bytes/second`. Update the name to reduce confusion.
> adjust names for DX metrics

- atlas-webapi/src/main/scala/com/netflix/atlas/webapi/FetchRequestSource.scala
When generating the fetch response it was always using the
default legend for the time series messages. Now it will
use the legend set by the user and fallback to the default.
> honor user specified legend for fetch response

- atlas-chart/src/main/scala/com/netflix/atlas/chart/JsonGraphEngine.scala
- atlas-chart/src/main/scala/com/netflix/atlas/chart/StatsJsonGraphEngine.scala
- atlas-chart/src/main/scala/com/netflix/atlas/chart/StdJsonGraphEngine.scala
- atlas-chart/src/test/scala/com/netflix/atlas/chart/JsonGraphEngineSuite.scala
Updates the `json` and `stats.json` formats to output
standard json data. Before special double values like
NaN and Infinity were emitted without qoutes breaking
some systems that expected standard json. This should
make them more straightforward to consume, however it
is a potentially breaking change for some users.
Fixes #1080
> quote special double values for all json formats

- atlas-chart/src/main/scala/com/netflix/atlas/chart/util/PngImage.scala
This should cleanup imageio* files in the temp directory
for image caching. Still need to investigate why they are
being created in the first place since we disable the on
disk caching (`ImageIO.setUseCache(false)`).
> ensure image writer is disposed

- atlas-core/src/main/scala/com/netflix/atlas/core/util/Hash.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/util/IntHashSet.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/util/IntIntHashMap.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/util/IntRefHashMap.scala
For some data sets we are seeing it take a long time
to rebuild the index with most of the time being spent
doing get/put for the `RefIntHashMap`s used. Testing
with an improved int hash reduces collisions providing
a significant improvement.
Table showing reduction in build time using the newer
hash:
| Index size | Before | After  |
|------------|--------|--------|
| 1M         |    11s |    11s |
| 2M         |  1m43s |    20s |
| 5M         | 12m34s |    55s |
> improve hash function for int collections

- atlas-core/src/main/scala/com/netflix/atlas/core/model/MathExpr.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/util/Hash.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/util/LongHashSet.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/util/LongIntHashMap.scala
Avoids thread local and testing with some actual datasets
plus 100M random long values shows it has about the same
collision rate as the previous implementation.
> simplify hash for long values

- .github/workflows/pr.yml
- .github/workflows/release.yml
- .github/workflows/snapshot.yml
- .travis.yml
- project/Bintray.scala
- project/BuildSettings.scala
- project/GitVersion.scala
Test out build and release using GitHub Actions.
> enable github actions

- .github/workflows/pr.yml
- atlas-core/src/main/scala/com/netflix/atlas/core/algorithm/AlgoState.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/db/BlockStore.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/model/Block.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/stacklang/Interpreter.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/util/SmallHashMap.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/model/CustomVocabularySuite.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/model/NamedRewriteSuite.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/model/StyleVocabularySuite.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/stacklang/BaseExamplesSuite.scala
- atlas-eval/src/main/scala/com/netflix/atlas/eval/graph/Grapher.scala
- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/ExprInterpreter.scala
- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/FinalExprEval.scala
- atlas-eval/src/test/scala/com/netflix/atlas/eval/stream/EvaluatorSuite.scala
- atlas-eval/src/test/scala/com/netflix/atlas/eval/util/HostRewriterSuite.scala
- atlas-lwcapi/src/test/scala/com/netflix/atlas/lwcapi/SubscribeApiSuite.scala
- atlas-webapi/src/main/scala/com/netflix/atlas/webapi/TagsApi.scala
- project/Dependencies.scala
A number of new warnings needed to be fixed. Most were
for exhaustivity checks. For cooperative equality checks
that impact SmallHashMap the new warnings are currently
just being suppressed.
> update to scala 2.13.4

- atlas-core/src/main/scala/com/netflix/atlas/core/index/QueryIndex.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/index/QueryIndexSuite.scala
- atlas-jmh/src/main/scala/com/netflix/atlas/core/index/QueryIndexMatching.scala
The two changes are:
1. Always use small map for subindexes to avoid allocation
of `Some` objects when performing a get.
2. If a `SmallHashMap` is used for the tags, then use the
entries iterator to avoid allocating the query list. This
avoids the allocation of the list nodes and short circuits
creation of `Query.Equal` in some cases.
On sample benchmark with index size of 100k the throughput
increased from ~1.8M ops/second to ~2.6M ops/second. Allocation
rate was reduced from ~624 B/op to ~24 B/op.
> reduce allocations for query index matching

- atlas-core/src/main/scala/com/netflix/atlas/core/index/QueryIndex.scala
There are some index rewrite use-cases that rely on the
generated copy method. It was switched to a regular class
in #1225.
> switch QueryIndex back to case class

- atlas-core/src/main/scala/com/netflix/atlas/core/util/SmallHashMap.scala
Before the `getOrNull` method would call `equals` twice
when a matching entry was found.
> avoid multiple calls to `equals` on matches

- atlas-core/src/main/scala/com/netflix/atlas/core/index/QueryIndex.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/index/QueryIndexSuite.scala
In #1225, we switched to using the EntriesIterator for
`SmallHashMap`s to avoid allocations. This works well for
compact maps. However, when there is free space in the map
it adds some computational overhead to search for the next
entry. Since the traversal occurs multiple times when
searching for matches this overhead can add up. In this
change we switch to a simple array with thread local so
we can iterate the tags map a single time and avoid the
allocations for most calls.
The benchmark doesn't show much improvement, but it
shows considerable improvement on a test cluster with
real data.
> QueryIndex: reduce iteration cost for tags map

- atlas-akka/src/main/scala/com/netflix/atlas/akka/ClusterOps.scala
- atlas-akka/src/main/scala/com/netflix/atlas/akka/OpportunisticEC.scala
- atlas-akka/src/main/scala/com/netflix/atlas/akka/StreamOps.scala
- atlas-akka/src/test/scala/com/netflix/atlas/akka/OpportunisticECSuite.scala
- atlas-akka/src/test/scala/com/netflix/atlas/akka/StreamOpsSuite.scala
- atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/StreamApi.scala
- atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/SubscribeApi.scala
In scala 2.13.4 the behavior of the default global execution
context changed. See:
https://github.com/scala/scala/releases/tag/v2.13.4
This change adds a helper class for accessing the opportunistic
context that was used before and switches some use-cases to
use that version as it is more well tested on our use-cases.
We can reevaluate in the future as needed.
/cc @jfz
> add helper for accessing opportunistic EC

- atlas-akka/src/main/scala/com/netflix/atlas/akka/OpportunisticEC.scala
Cleanup printStackTrace call that was used for some
debugging and shouldn't have gotten checked in.
> remove printStackTrace

- atlas-core/src/main/scala/com/netflix/atlas/core/index/QueryIndex.scala
This ensures the query objects that are created can be
cleaned up and will not get promoted.
> clear queries array after matching

- atlas-akka/src/main/scala/com/netflix/atlas/akka/ClusterOps.scala
Use passed in registry instead of `NoopRegistry`.
> Use passed in registry

- atlas-akka/src/main/scala/com/netflix/atlas/akka/RequestHandler.scala
Add a log message that can be enabled to get the exception
coming from failed requests. In some cases there are
failures that show in the access log that are not otherwise
logged. This ensures that any exception leading to a failed
response can easily be logged via the request handler.
> trace logging for request exceptions

- project/Dependencies.scala
There is a memory leak in 2.6.11 impacting some use-cases.
> akka 2.6.10

- atlas-core/src/main/scala/com/netflix/atlas/core/model/MathExpr.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/model/DataGroupBySuite.scala
Rather than silently fail with an empty result set, it will
now fail early with an error indicating that the groupings
do not match expectations.
> add sanity check for binary operations with group by

- atlas-eval/src/main/resources/reference.conf
- atlas-eval/src/main/scala/com/netflix/atlas/eval/graph/DefaultSettings.scala
- atlas-eval/src/main/scala/com/netflix/atlas/eval/graph/Grapher.scala
- atlas-eval/src/main/scala/com/netflix/atlas/eval/graph/SimpleLegends.scala
- atlas-eval/src/test/resources/application.conf
- atlas-eval/src/test/scala/com/netflix/atlas/eval/graph/SimpleLegendsSuite.scala
The default legends just summarize the expression and are
often hard to read and get truncated. This change adds a
helper that tries to generate a simplified legend if the
user has not set the legend explicitly. It will look at
the full set of expressions being rendered and try to
emphasize differences where possible.
Example:
```
Expr:
nf.cluster,www-main,:eq,
name,apache.http.request,:eq,:and,
:dist-stddev
Before:
sqrt(
(
(
(
(statistic=count) and (
(nf.cluster=www-main) and (name=apache.http.request)
)
*
(statistic=totalOfSquares) and (
(nf.cluster=www-main) and (name=apache.http.request)
)
)
-
(
(statistic in (totalAmount,totalTime)) and (
(nf.cluster=www-main) and (name=apache.http.request)
)
*
(statistic in (totalAmount,totalTime)) and (
(nf.cluster=www-main) and …
```
> add support for simplified legends

- atlas-core/src/main/scala/com/netflix/atlas/core/model/DataExpr.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/model/MathExpr.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/model/DataExprSuite.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/model/DataGroupBySuite.scala
This change add support for binary operations where both
sides are grouped and the keys for one side is a subset
of the other. Before the keys would have to match exactly.
When one side has a subset, the matching for entries will
be performed using the smaller set of keys.
For example, suppose that dimensions `a` and `b` each have
two values:
```
Expr: q1,(,a,b,),:by, q2,(,a,),:by, :add
Result Set:
q1:a1b1 + q2:a1
q1:a1b2 + q2:a1
q1:a2b1 + q2:a2
q1:a2b2 + q2:a2
```
> binary ops with a subset of group by keys

- atlas-core/src/main/scala/com/netflix/atlas/core/model/FilterExpr.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/model/FilterVocabulary.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/model/SummaryStats.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/util/BoundedPriorityBuffer.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/util/BoundedPriorityBufferSuite.scala
Add filtering operators to collect the top/bottom `K`
time series based on a summary statistic. This is the
first part of #1224. A follow up PR will add the
variant that aggregates the others category.
> add topk/bottomk operators

- atlas-akka/src/main/scala/com/netflix/atlas/akka/RequestHandler.scala
- atlas-akka/src/test/scala/com/netflix/atlas/akka/RequestHandlerNoCompressionSuite.scala
- atlas-akka/src/test/scala/com/netflix/atlas/akka/RequestHandlerSuite.scala
- atlas-akka/src/test/scala/com/netflix/atlas/akka/TestApi.scala
Handles the circuit breaker rejection so the client will
get 503 instead of 400. Many clients will retry when the
service is unavailable, but not for client failures.
/cc @rnz0
> handle circuit breaker rejection

- atlas-poller-cloudwatch/src/main/resources/rds.conf
> add mapping for 2 rds metrics

- atlas-core/src/main/scala/com/netflix/atlas/core/model/FilterVocabulary.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/stacklang/Context.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/stacklang/Interpreter.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/stacklang/Word.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/util/Features.java
- atlas-core/src/test/scala/com/netflix/atlas/core/stacklang/BaseExamplesSuite.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/stacklang/FreezeSuite.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/stacklang/InterpreterSuite.scala
- atlas-eval/src/main/scala/com/netflix/atlas/eval/graph/GraphConfig.scala
- atlas-eval/src/main/scala/com/netflix/atlas/eval/graph/Grapher.scala
- atlas-eval/src/test/scala/com/netflix/atlas/eval/graph/GrapherSuite.scala
The features flag can be used by early adopters to enable
experimental functionality. This reduces the risk on our
side of users becoming reliant on incubating features and
making it hard for us to change them before they have been
fully vetted.
For now, the recently added priority operators are the
only things enabled by selecting unstable features.
> add features flag to graph API

- atlas-eval/src/main/scala/com/netflix/atlas/eval/graph/Grapher.scala
- atlas-eval/src/test/scala/com/netflix/atlas/eval/graph/GrapherSuite.scala
If invalid stuff is left on the stack, then return a 400
that gives an indication of the problematic contents rather
than the default MatchError which results in the user getting
a 500 error.
> improve error for invalid stack

- atlas-poller-cloudwatch/src/main/resources/rds.conf
It looks like rds metric "VolumeBytesUsed" is published hourly. 
With default period count is 6, the look back period is 10m * 6 = 1h, plus the default 1 period offset, it seems reasonable.
> fix poll period for rds metric "VolumeBytesUsed"

- atlas-poller-cloudwatch/src/main/resources/rds.conf
Increase poll period for rds metric "VolumeBytesUsed" to avoid data point gaps.
> increase poll period for rds metric "VolumeBytesUsed" 

- atlas-core/src/main/scala/com/netflix/atlas/core/model/FilterExpr.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/model/FilterVocabulary.scala
- atlas-webapi/src/main/resources/reference.conf
Count was the only summary statistic for which there was
not a helper macro for use with filtering. This adds that
helper to improve consistency.
> add stat-count for consistency

- atlas-akka/src/main/scala/com/netflix/atlas/akka/ClusterOps.scala
- atlas-akka/src/main/scala/com/netflix/atlas/akka/StreamOps.scala
- atlas-akka/src/test/scala/com/netflix/atlas/akka/StreamOpsSuite.scala
There are some race conditions in the implementation of
the custom blocking queue source that result in:
- The source hanging after complete.
- An item in the queue not getting processed until another
item is offered if the source is pulled after the push
immediately check and before the poll call.
In recent versions of akka there is now a bounded source
queue that addresses the memory concerns we had. Rather
than track down the race conditions, this change switches
the internals of the `blockingQueue` helper to use the
BoundedSourceQueue in akka.
> switch blockingQueue to use BoundedSourceQueue

- atlas-core/src/main/scala/com/netflix/atlas/core/model/StyleExpr.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/model/StyleExprSuite.scala
When processing operators that modify colors the later
operations will override and win. The expression string
generated for StyleExpr was sorting which means that
`:alpha` would be output before `:palette` even if the
user did them in the reverse order. Since `:palette`
will override a previously set alpha this caused the
setting to get ignored. For now change the sort order
to be descending which should always preserve the user
intent with the current set of style operations.
> ensure alpha setting is not lost with toString

- atlas-poller-cloudwatch/src/main/resources/dx.conf
- atlas-poller-cloudwatch/src/main/resources/reference.conf
add cloudwatch mapping for dx connection metrics
> add cloudwatch mapping for dx connection metrics

- project/Dependencies.scala
Pull in security fix for CVE-2021-23339:
https://doc.akka.io/docs/akka-http/10.2/release-notes/10.2.x.html#10-2-4
> update to akka-http 10.2.4

- atlas-core/src/main/scala/com/netflix/atlas/core/model/CustomVocabulary.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/model/MathExpr.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/util/Shards.scala
- atlas-eval/src/main/scala/com/netflix/atlas/eval/model/TimeGroup.scala
- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/Evaluator.java
- atlas-eval/src/main/scala/com/netflix/atlas/eval/util/HostRewriter.scala
- atlas-eval/src/main/scala/com/netflix/atlas/eval/util/SmallHashMapDeserializer.scala
- atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/SubscriptionManager.scala
- atlas-module-akka/src/main/scala/com/netflix/atlas/akka/AkkaModule.scala
- atlas-module-eval/src/main/scala/com/netflix/atlas/eval/EvalModule.scala
- project/BuildSettings.scala
They were disabled due to a bug, but looks like it
has been fixed. Fixed a number of scaladoc errors
to get the build clean.
Error from publishing attempt without docs:
```
Failed: javadoc-staging, failureMessage:Missing: no javadoc
jar found in folder
'/com/netflix/atlas_v1/atlas-module-lwcapi_2.13/1.7.0-rc.14'
```
> re-enable doc artifacts

- atlas-core/src/main/scala/com/netflix/atlas/core/model/DataExpr.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/model/Query.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/model/DataExprSuite.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/model/QuerySuite.scala
Add api to extract all keys from Query and DataExpr. 
This is preparing for auto rollup, to check if any key has been dropped or rolled up for a given DataExpr.
> extract all keys from Query and DataExpr

- atlas-poller-cloudwatch/src/main/resources/rds.conf
Add cloudwatch mapping for RDS DBLoad metrics. 
Note that Performance Insights needs to enabled for a db instance for these metrics to be available: https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_PerfInsights.Enabling.html
> add cloudwatch mapping for RDS DBLoad metrics

- atlas-akka/src/main/resources/reference.conf
- atlas-akka/src/main/scala/com/netflix/atlas/akka/CustomDirectives.scala
- atlas-akka/src/main/scala/com/netflix/atlas/akka/RequestHandler.scala
- atlas-akka/src/test/scala/com/netflix/atlas/akka/CustomDirectivesSuite.scala
- atlas-akka/src/test/scala/com/netflix/atlas/akka/RequestHandlerNoCompressionSuite.scala
- atlas-akka/src/test/scala/com/netflix/atlas/akka/RequestHandlerSuite.scala
For load balancers that work at the TCP level there can
be an imbalance in traffic if clients reuse connections.
The `closeConnection` directive can be used to mitigate
this by adding an explicit `Connection: close` header to
the responses.
In order to allow some reuse, a probability can be set
to tune how frequently the header is applied. This also
avoids the need to track details like the number of
requests per connection for more complex policies.
> add directive to force connection close

- atlas-core/src/main/scala/com/netflix/atlas/core/util/Interner.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/util/InternerSuite.scala
- atlas-jmh/src/main/scala/com/netflix/atlas/core/util/StringIntern.scala
This can have less overhead than using the built in string
interner, though it does not guarantee that the values will
be deduped. For the most common use-case of reducing memory
overhead by avoiding duplicate values in the heap it should
be fine.
> add interner based on Caffeine cache

- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/Evaluator.java
- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/StreamContext.scala
- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/SyntheticDataSource.scala
Adds a helper that can be used to generate arbitrary
amounts of data for an expression by changing the scheme
to `synthetic`.
> lwc: helper for generating data

- atlas-core/src/main/scala/com/netflix/atlas/core/index/RoaringTagIndex.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/util/IntRefHashMap.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/index/RoaringTagIndexSuite.scala
Updates the RoaringTagIndex.findValues method to loop
over the set of values for a key rather than the set
of matching items in some cases. Depending on the number
of matches, this can often be much faster.
Performance difference was tested using the data from
one of the large prod clusters. The first is just dumping
all values for a given key with no query restriction.
This is the ideal case for this change as before it would
require analyzing all items in the index with that key.
The second test was to dump all values for a key in a
given region. For some values, like the region key it can
be close to the worst case for looping across the values
because keys like region, zone, asg, and node are specific
to a region. The worst case for `hasNonEmptyIntersection`
is when both bitmaps have …
> improve performance for findValues

- atlas-akka/src/main/resources/reference.conf
- atlas-akka/src/main/scala/com/netflix/atlas/akka/ConfigConnectionContextFactory.scala
- atlas-akka/src/main/scala/com/netflix/atlas/akka/ConnectionContextFactory.scala
- atlas-akka/src/main/scala/com/netflix/atlas/akka/WebServer.scala
- atlas-akka/src/test/scala/com/netflix/atlas/akka/ConnectionContextFactorySuite.scala
Updates the config for setting up the SSL config to allow
a custom implementation to be used. This gives more complete
control to tuning how it is setup. The default uses the same
approach as before.
> add base interface to customize SSLContext

- atlas-core/src/main/scala/com/netflix/atlas/core/limiter/CardinalityLimiter.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/limiter/LimiterConifg.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/util/BoundedPriorityBuffer.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/util/CardinalityEstimator.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/limiter/CardinalityLimiterSuite.scala
Automatically rollup or drop tags based on cardinality limit configuration, also provide an api to check if a query can be served based on the limiter stats. 
It tracks cardinality by a list of pre-defined keys and associated limits, and build out a tree structure level by level based on that, also tracks cardinality for other tag keys at leaf level.
Given below example configuration:
`atlas.auto-rollup = {
prefix = `[`
{
key = "app",
value-limit = 20,
total-limit = 1000,
},
{
key = "name",
value-limit = 30,
total-limit = 50,
}
],
tag-value-limit = 40
}`
- Level 1: track cardinality by "app", max number of apps allowed is 20, max number of tags across all apps is 1000; drop new apps if either limit is reached.
- Level 2: for a specific app, track cardinality by "name", max number of names …
> auto rollup or drop tags based on cardinality limits

- atlas-core/src/main/scala/com/netflix/atlas/core/norm/LastValueFunction.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/norm/MaxValueFunction.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/norm/RollingValueBuffer.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/norm/SumValueFunction.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/norm/LastValueFunctionSuite.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/norm/MaxValueFunctionSuite.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/norm/RollingValueBufferSuite.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/norm/SumValueFunctionSuite.scala
Updates the normalization functions for last, max, and sum
modes to allow out of order updates within a small window
of time. The use-case is inline aggregation where updates
can come from many nodes. If a node is shutting down, then
it will force data for the current interval to get sent out
earlier than it normally would. Without this change that
flush could cause data from an earlier interval on other
nodes to get dropped resulting in an incorrect aggregate.
> allow out of order updates for normalization

- atlas-core/src/main/scala/com/netflix/atlas/core/util/IdMap.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/validation/HasKeyRule.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/validation/MaxUserTagsRule.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/validation/Rule.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/validation/TagRule.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/util/IdMapSuite.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/validation/HasKeyRuleSuite.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/validation/MaxUserTagsRuleSuite.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/validation/NameValueLengthRuleSuite.scala
Updates the validation rules so that Spectator Id
objects can be validated directly. This can help
avoid conversions for some use-cases where validation
is on the hot path.
> support validating Id objects

- atlas-poller-cloudwatch/src/main/resources/reference.conf
Add alias for Cloudwatch dimension "DBClusterIdentifier".
The behavior of this dimension is inconsistent across AWS services, can be "DbClusterIdentifier" or "DBClusterIdentifier", and in some services its cases insensitive(like RDS uses either for different clusters), some are(like Neptune use the latter).
> add alias for cloudwatch dimension "DBClusterIdentifier"

- atlas-core/src/main/scala/com/netflix/atlas/core/db/BlockStore.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/db/MemoryBlockStoreSuite.scala
If it is updated, then it can cause some older blocks
to get rotated out earlier than expected if there is
another update with a value.
> do not update position for block store flush

- atlas-poller-cloudwatch/src/main/resources/alb.conf
ALB Cloudwatch metrics data for the recent minute can be incomplete and volatile depending on the timing of polling, increase offset to 2 min to avoid this issue.
> increase delay for alb cloudwatch metrics to avoid partial data

- atlas-poller-cloudwatch/src/main/resources/ec2.conf
Ensures that they will stop getting published after an
ASG goes away. Otherwise they will stick around until
the poller service is redeployed.
> add timeout for ec2 cloudwatch metrics

- Makefile
The plugin for SBT was removed a long time ago. Remove
the target from the makefile since it doesn't work.
> remove coverage target

- build.sbt
- project/BuildSettings.scala
Replace in with [slash syntax].
[slash syntax]: https://www.scala-sbt.org/1.x/docs/Migrating-from-sbt-013x.html#slash
> fix build deprecation warnings

- atlas-core/src/main/scala/com/netflix/atlas/core/model/Block.scala
Compute the hash code on the long value directly and
avoid boxing with a `java.lang.Long`.
> avoid boxing for computing hash code

- atlas-core/src/main/scala/com/netflix/atlas/core/index/RoaringTagIndex.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/util/ArrayHelper.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/util/IntRefHashMap.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/util/InternMap.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/util/ListHelper.scala
Manifest is not supported in scala 3. Removes the
usage of Manifest for everything but JSON type
detection.
> reduce usage of Manifest

- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/EvaluatorImpl.scala
- atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/SubscribeApi.scala
When there are many small strict messages the fold
step adds a significant overhead.
> avoid fold for strict messages

- atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/SubscribeApi.scala
Update the heartbeat timestamp to be one interval
behind the current time. This gives more time for
data flowing in from real systems to arrive when
using a small number of buffers on the eval client.
> delay heartbeat timestamp

- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/EvaluatorImpl.scala
Refactor so that the expressions passed in are only
processed once rather than once per server instance.
> eval: avoid redundant parsing of expressions

- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/EvaluatorImpl.scala
- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/LwcToAggrDatapoint.scala
- atlas-eval/src/test/scala/com/netflix/atlas/eval/stream/EvaluatorSuite.scala
- atlas-eval/src/test/scala/com/netflix/atlas/eval/stream/LwcToAggrDatapointSuite.scala
Moves the message parsing out of LwcToAggrDatapoint to
just after the data is received. This allows us to avoid
some intermediate conversions from String to ByteString.
> eval: move message parsing earlier

- atlas-eval/src/main/scala/com/netflix/atlas/eval/model/LwcDataExpr.scala
- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/LwcToAggrDatapoint.scala
Make the parsed expression a lazy val and reuse the first
instance for a given id to minimize the number of times
a data expression needs to be fully processed. Before it
occur for each expression from each server.
> eval: reduce parsing of data exprs

- .github/workflows/pr.yml
- .github/workflows/release.yml
- .github/workflows/snapshot.yml
- build.sbt
- project/Dependencies.scala
Jdk16 strongly encapsulates the internals by default
causing problems for older versions of Guice. When
running on a newer JDK, have the build use Guice 5.
For the published library still need to use 4.1.0
to avoid creating problems internally for other
users stuck on old versions.
> update CI builds to use jdk16

- atlas-core/src/main/scala/com/netflix/atlas/core/db/BlockStore.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/db/MemoryDatabase.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/model/Block.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/model/BlockStats.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/db/MemoryBlockStoreSuite.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/model/BlockSuite.scala
Adds a new block type that is mutable, allows random access,
and tries to compress data as it is coming in. This should
reduce the overhead for the data that is filling in and help
avoid issue for out of order updates since the historical
blocks will not be compressed to an immutable type.
> add compressed mutable block type

- atlas-core/src/main/scala/com/netflix/atlas/core/model/Block.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/model/BlockStats.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/model/BlockStatsSuite.scala
The compressed array block was always using buffer
member rather than the passed in array. This caused
resizes to be ignored since the delta would always
be 0.
> fix block size calculation

- atlas-core/src/main/scala/com/netflix/atlas/core/db/BlockStore.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/norm/RollingValueFunction.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/db/MemoryBlockStoreSuite.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/norm/MaxValueFunctionSuite.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/norm/NormalizationCacheSuite.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/norm/RollingValueFunctionSuite.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/norm/SumValueFunctionSuite.scala
In #1297, normalized values were buffered and would only
get output at the end. This led to some user complaints
that data was delayed. It was still within SLA, but it
wouldn't show up until a bit later than before if the end
time was set to now instead of offset by the SLA for data
to be actionable.
With the compressed mutable block type introduced in #1320,
it is possible to update the older blocks as they are not
immutable. In this change, the block store checks have been
updated so the previous block can be updated to account for
out of order values that may arrive. This should make the
data visible earlier as it was before.
> allow out of order updates for blocks

- atlas-poller-cloudwatch/src/main/resources/nlb.conf
https://docs.aws.amazon.com/elasticloadbalancing/latest/network/load-balancer-cloudwatch-metrics.html
* ProcessedPackets, statistic: sum
* PeakPacketsPerSecond, statistic: max
* PacketsPerSecondCapacity,  statistic: min
> add nlb cloudwatch metrics

- atlas-eval/src/main/scala/com/netflix/atlas/eval/model/LwcMessages.scala
- project/Dependencies.scala
Use `fromArrayUnsafe` to avoid copying the byte array used
by the ByteString object.
> reduce array allocations for encoding batch

- .github/workflows/release.yml
- .github/workflows/snapshot.yml
- .gitignore
Previously, when maintaining a fork of this repo, merging updates from
the upstream would trigger GitHub actions for the snapshot workflow,
which failed because the secrets are missing. We do not want forks to
run either the snapshot or the release actions.
> limit gh-actions to the main repo

- atlas-core/src/main/scala/com/netflix/atlas/core/util/SmallHashMap.scala
Updates the SmallHashMap implementation to override
the `isEmpty` method with an efficient check. The
default that is inherited will allocate an iterator.
> more efficient empty check for hash map

- atlas-core/src/main/scala/com/netflix/atlas/core/model/ItemIdCalculator.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/model/TaggedItemSuite.scala
Refactors the logic to create the complete id string
before feeding into the UTF-8 encoder and then message
digest. For the existing benchmark this change improves
the throughput by ~33%.
> improve performance for computing id

- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/EvaluatorImpl.scala
In cases where the message from the websocket was not
strict, the source from the parsed batch wasn't getting
flattend properly and the batch would get ignored later
because it wasn't a recognized message type.
> eval: properly handle non-strict messages

- atlas-core/src/main/scala/com/netflix/atlas/core/util/ArrayHelper.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/util/SortedTagMap.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/util/ArrayHelperSuite.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/util/SortedTagMapSuite.scala
For some of the storage experiments it is useful to be
able to receive and maintain the tags sorted by the keys.
This change adds an implementation of Map that is based
on a sorted string array. The memory overhead and general
performance is similar to SmallHashMap, though lookups for
an individual key can be slower, logarithmic rather than
typically constant, compared to a non-compact small hash
map instance.
> add SortedTagMap implementation

- atlas-akka/src/main/scala/com/netflix/atlas/akka/AccessLogger.scala
Adjust the log level for failed requests to warn instead
of the default of debug.
> update access log to use warn for failures

- atlas-akka/src/main/scala/com/netflix/atlas/akka/AccessLogger.scala
- project/Dependencies.scala
Record the request/response entity sizes to the ipc
logger when it is known.
> update access logger to record sizes

- atlas-akka/src/main/scala/com/netflix/atlas/akka/CustomRejection.scala
- atlas-akka/src/main/scala/com/netflix/atlas/akka/RequestHandler.scala
- atlas-akka/src/test/scala/com/netflix/atlas/akka/RequestHandlerSuite.scala
- atlas-akka/src/test/scala/com/netflix/atlas/akka/TestApi.scala
Update the default handler so it will use a 401 code
rather than 400. Also adds a custom rejection type
that can be used for custom directives to provide more
context into why the authorization failed.
> handle AuthorizationFailedRejection

- atlas-core/src/main/scala/com/netflix/atlas/core/util/SmallHashMap.scala
The Java Map view for SmallHashMap was using the default
implementation of `size` that calls `entrySet().size()`.
This change overrides the size to avoid creating the
entry set unnecessarily.
> avoid allocation for computing size

- atlas-core/src/main/scala/com/netflix/atlas/core/model/ItemIdCalculator.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/util/SortedTagMap.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/model/TaggedItemSuite.scala
- atlas-jmh/src/main/scala/com/netflix/atlas/core/model/ComputeId.scala
Avoid the duplicate sort and support a direct copy
into the buffer array.
> tune id calculation when using sorted map

- atlas-core/src/main/scala/com/netflix/atlas/core/index/RoaringTagIndex.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/index/TaggedItemIndex.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/index/package.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/index/TaggedItemIndexSuite.scala
Experiment for a more restrictive tag index that only
supports finding items overall and not projecting keys
or values. The index is also setup so that it doesn't
need to reference the items or tag maps to give more
flexibility to the database implementation over how that
data is stored and structured.
The implementation is heavily based on the corresponding
parts of the RoaringTagIndex implementation. If the overall
experiments go well, then this will replace the various
implementations of TagIndex.
> add simplified tag index

- atlas-core/src/main/scala/com/netflix/atlas/core/util/FastGzipOutputStream.scala
- atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/ExpressionApi.scala
- atlas-lwcapi/src/test/scala/com/netflix/atlas/lwcapi/ExpressionApiSuite.scala
Before it would compute the etag by computing a sha1 hash
of a string representation of the sorted expression list.
With 100k+ expressions that is quite expensive both in
terms of the memory use and CPU.
This change introduces a cache for the encoded entity so
it can be returned directly if there are frequent calls
within a short period. The ETag is computed over the
encoded and compressed response using CRC32. This reduces
the memory and CPU overhead considerably.
> reduce overhead of expressions etag check

- atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/EvaluateApi.scala
- atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/QueueHandler.scala
- atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/SubscribeApi.scala
- atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/WebSocketSessionManager.scala
- atlas-lwcapi/src/test/scala/com/netflix/atlas/lwcapi/ExpressionApiSuite.scala
- atlas-lwcapi/src/test/scala/com/netflix/atlas/lwcapi/SubscribeApiSuite.scala
- atlas-lwcapi/src/test/scala/com/netflix/atlas/lwcapi/WebSocketSessionManagerSuite.scala
There is some synchronization needed to offer an item
to the source queue. With a high throughput this can
add up to a lot of contention across threads. Batch
the incoming datapoints to reduce the number of items
that have to be offered to the queue.
> batch messages going to evaluation queue

- atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/SubscribeApi.scala
Doing it before results in a lot more message passing. By
moving it after fusing happens and it is fairly cheap.
> move flatMap to after the broadcast hub

- atlas-core/src/main/scala/com/netflix/atlas/core/util/ByteBufferInputStream.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/util/CharBufferReader.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/util/ByteBufferInputStreamSuite.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/util/CharBufferReaderSuite.scala
Add simple InputStream and Reader wrappers for use with
ByteBuffer and CharBuffer respectively. Useful for cases
where we have data in a NIO buffer, but need to pass it
to something that expects an InputStream or Reader.
> add stream wrappers for nio buffers

- atlas-core/src/main/scala/com/netflix/atlas/core/util/SmallHashMap.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/util/SortedTagMap.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/util/SmallHashMapSuite.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/util/SortedTagMapSuite.scala
Update SmallHashMap and SortedTagMap to override the
contains method and reduce the overhead.
> avoid option allocation for contains

- atlas-core/src/main/scala/com/netflix/atlas/core/validation/HasKeyRule.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/validation/MaxUserTagsRule.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/validation/NameValueLengthRule.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/validation/Rule.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/validation/TagRule.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/validation/HasKeyRuleSuite.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/validation/RuleSuite.scala
- atlas-jmh/src/main/scala/com/netflix/atlas/core/validation/TagRules.scala
Add validate variant that allows checking this type without
first converting to SmallHashMap.
Benchmark was updated and fixed so that validation would pass
which is the most common case in actual use. Before it would
fail due to the reserved key check. That made the benchmark
results misleading as the composite check seemed faster since
it was able to short-circuit earlier. For the successful case
it was actually slower. Also adds a flag that can be used to
choose whether or not to group simple tag rules into a
composite. By default it will not as that seems to generally
be faster.
> optimize validation when using SortedTagMap

- atlas-akka/src/main/scala/com/netflix/atlas/akka/CustomDirectives.scala
- atlas-akka/src/test/scala/com/netflix/atlas/akka/CustomDirectivesSuite.scala
Some clients send OPTIONS requests with an empty chunked
payload. This would result in warnings in the log because
the response was sent before consuming the request entity.
> ignore entity if present on pre-flight check

- atlas-core/src/main/scala/com/netflix/atlas/core/util/SortedTagMap.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/util/SortedTagMapSuite.scala
Update SortedTagMap to have helper methods for getting the
keys and values as an array. Avoids the overhead of using
the `keys` or `values` method on Map and creating the array
from the returned iterable.
> methods on SortedTagMap to get key/value arrays

- atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/SubscribeApi.scala
* Refactor the common code to drop connections using the same Id to its
own method
* Avoid creating new Ids and a doing counter lookups in the Registry
since the Ids are always the same for the eval and items counters
> Minor improvements to SubscribeApi

- atlas-core/src/main/scala/com/netflix/atlas/core/util/ArrayHelper.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/util/ArrayHelperSuite.scala
Update the ArrayHelper.merge method to indicate if the
source arrays have been fully consumed. The first position
of the source array will be set to null if it was fully
consumed and merged into the destination.
> indicate if input arrays were fully consumed

- atlas-core/src/main/scala/com/netflix/atlas/core/model/Datapoint.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/model/ItemId.scala
- atlas-jmh/src/main/scala/com/netflix/atlas/webapi/PublishPayloadsBench.scala
- atlas-webapi/src/main/scala/com/netflix/atlas/webapi/PublishApi.scala
- atlas-webapi/src/main/scala/com/netflix/atlas/webapi/PublishConsumer.scala
- atlas-webapi/src/main/scala/com/netflix/atlas/webapi/PublishPayloads.scala
- atlas-webapi/src/test/scala/com/netflix/atlas/webapi/PublishPayloadsSuite.scala
- build.sbt
Adds helper functions for a new publish format that is more
efficient to decode. In particular, it allows the id to be
sent along so it doesn't need to get recomputed and keeps the
strings up front so they are only interned once if there are
duplicate values.
This format is a bit more expensive to encode due to needing
to compute the string table. This change also Moves the helper
functions for encoding and decoding publish payloads to a
separate object.
> add codec for more efficient publish format

- atlas-core/src/main/scala/com/netflix/atlas/core/db/MemoryDatabase.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/model/Datapoint.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/model/DatapointTuple.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/norm/NormalizationCache.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/norm/package.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/db/MemoryDatabaseSuite.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/norm/NormalizationCacheSuite.scala
- atlas-jmh/src/main/scala/com/netflix/atlas/webapi/PublishPayloadsBench.scala
- atlas-webapi/src/main/scala/com/netflix/atlas/webapi/LocalPublishActor.scala
- atlas-webapi/src/main/scala/com/netflix/atlas/webapi/PublishApi.scala
- atlas-webapi/src/main/scala/com/netflix/atlas/webapi/PublishConsumer.scala
- atlas-webapi/src/main/scala/com/netflix/atlas/webapi/PublishPayloads.scala
- atlas-webapi/src/test/scala/com/netflix/atlas/webapi/PublishApiJsonSuite.scala
- atlas-webapi/src/test/scala/com/netflix/atlas/webapi/PublishApiSuite.scala
- atlas-webapi/src/test/scala/com/netflix/atlas/webapi/PublishPayloadsSuite.scala
Update the flow from parsing publish messages to storage
so that the id does not need to be recomputed.
> avoid recomputing id after parsing

- atlas-webapi/src/main/scala/com/netflix/atlas/webapi/PublishPayloads.scala
Encoder will now ensure the entries are sorted so the
decoding side can create the map without a local sort
step.
> improve performance for decoding tags

- atlas-core/src/main/scala/com/netflix/atlas/core/util/SortedTagMap.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/util/SortedTagMapSuite.scala
Copy pattern used in SmallHashMap to reduce allocations
while computing the cached hash code value.
> reduce alloc for hashCode

- atlas-core/src/main/scala/com/netflix/atlas/core/db/BlockStoreItem.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/db/MemoryDatabase.scala
Allow it to be set to avoid recomputing if it is already
available.
> avoid recomputing id on BlockStoreItem

- atlas-akka/src/main/scala/com/netflix/atlas/akka/CustomDirectives.scala
- atlas-akka/src/test/scala/com/netflix/atlas/akka/CustomDirectivesSuite.scala
Adds `jsonUnmarshaller` method for getting an unmarshaller
that can be used with the default `entity` directive.
> add unmarshaller for use with entity

- atlas-webapi/src/main/scala/com/netflix/atlas/webapi/ExprApi.scala
- atlas-webapi/src/test/scala/com/netflix/atlas/webapi/ExprApiSuite.scala
Adds an endpoint to the expr API that can be used to
strip query clauses that for specific keys. The main
use-case is for taking a specific sample query and
removing scoping clauses to get a base expression for
use in a template.
/cc @nathfisher
> add endpoint to strip query clauses

- atlas-core/src/main/scala/com/netflix/atlas/core/model/MathVocabulary.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/model/CustomVocabularySuite.scala
This makes expressions like the following work:
```
foo,a,:eq,$foo,:legend,(,bar,),:cg
name,cpu,:eq,(,node,),:by,80,:gt,15,:rolling-count,10,:gt,
$node,:legend,region,east,:eq,:cq,(,region,),:cg
```
Previously we would get a match error since we were only expecting math
expressions but since we want to have tools blindly add `:cg` to
arbitrary expressions, we need to handle expressions that include style words
> Handle :cg after style expressions

- atlas-chart/src/main/scala/com/netflix/atlas/chart/util/GraphAssertions.scala
When generating the HTML report for image tests, use the
absolute path for the golden image. This avoids missing
images in the report if the working directory for rendering
the page differs.
> use absolute path for golden image

- atlas-webapi/src/main/scala/com/netflix/atlas/webapi/PublishPayloads.scala
- atlas-webapi/src/test/scala/com/netflix/atlas/webapi/PublishPayloadsSuite.scala
Update PublishPayloads to have a helper to decode batches
direct to datapoints. This can be useful where the id is
not needed to avoid having to compute it.
> add method to decode direct to datapoints

- atlas-core/src/main/scala/com/netflix/atlas/core/util/InternMap.scala
Update ConcurrentInternMap to make intern call more
efficient. In particular, it will no longer use create
a lambda instance on each call.
> avoid lambda allocation for lock

- project/Dependencies.scala
Pull in latest version for fix to [CVE-2021-44228].
[CVE-2021-44228]: https://nvd.nist.gov/vuln/detail/CVE-2021-44228
> log4j 2.15.0

- atlas-webapi/src/main/scala/com/netflix/atlas/webapi/PublishPayloads.scala
- atlas-webapi/src/test/scala/com/netflix/atlas/webapi/PublishPayloadsSuite.scala
These are used for proxies and operations that do not require computing
a hash on the data point identity.
> Add encode methods to `PublishPayloads` for `List[Datapoint]`s.

- atlas-json/src/main/scala/com/netflix/atlas/json/JsonSupport.scala
Users should override `encode` to customize and can
get confusing results if only `toJson` is overridden.
Also updates the `toJson` to ensure the generator will
be cleaned up if `encode` throws an exception.
> make JsonSupport.toJson final

- atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/QueueHandler.scala
- atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/StreamMetadata.scala
- atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/StreamSubscriptionManager.scala
- atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/SubscriptionManager.scala
- atlas-lwcapi/src/test/scala/com/netflix/atlas/lwcapi/EvaluateApiSuite.scala
- atlas-lwcapi/src/test/scala/com/netflix/atlas/lwcapi/ExpressionApiSuite.scala
- atlas-lwcapi/src/test/scala/com/netflix/atlas/lwcapi/StreamMetadataSuite.scala
- atlas-lwcapi/src/test/scala/com/netflix/atlas/lwcapi/SubscribeApiSuite.scala
- atlas-lwcapi/src/test/scala/com/netflix/atlas/lwcapi/SubscriptionManagerSuite.scala
- atlas-module-lwcapi/src/main/scala/com/netflix/atlas/guice/LwcApiModule.scala
Updates the stream metadata to keep track of the number
of recently received and dropped messages rather than
the number overall. Currently this is done based on a
step interval. Adds a guage to show the number of streams
with a dimension indicating the state.
> track number of streams dropping data

- atlas-webapi/src/main/scala/com/netflix/atlas/webapi/PublishPayloads.scala
Update PublishPayloads helper to limit the visibility
for methods related to a single datapoint. These are
only needed internally or in some cases used as part
of the unit tests.
> limit visibility of methods for single datapoint

- atlas-core/src/main/scala/com/netflix/atlas/core/model/MathExpr.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/model/MathGroupBySuite.scala
if a subsequent key group was not a `slice` of the previous group but
was still a subset of that group. E.g.
`(,name,mode,value,),:by,(,name,value,),:by` would throw the error
despite `name` and `value` being present in the original group.
> Fix a bug regarding chained group by queries where an error was thrown

- .gitignore
- atlas-eval/src/main/resources/reference.conf
- atlas-eval/src/main/scala/com/netflix/atlas/eval/model/AggrDatapoint.scala
- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/EvaluatorImpl.scala
- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/FinalExprEval.scala
- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/StreamContext.scala
- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/TimeGrouped.scala
- atlas-eval/src/test/scala/com/netflix/atlas/eval/model/AggrDatapointSuite.scala
- atlas-eval/src/test/scala/com/netflix/atlas/eval/stream/EvaluatorSuite.scala
- atlas-eval/src/test/scala/com/netflix/atlas/eval/stream/FinalExprEvalSuite.scala
- atlas-eval/src/test/scala/com/netflix/atlas/eval/stream/TestContext.scala
- atlas-eval/src/test/scala/com/netflix/atlas/eval/stream/TimeGroupedSuite.scala
1. update eval library so it can be configured with explicit limits for expressions with config parameter - `atlas.eval.stream.expression-limit`
2. if any expression within the streamContext exceeds the limit, then emit an error to all the datasources using this expression.
3. stop adding additional `AggrDataPoint` to the Aggregator corresponding to an expression when the number of raw data points for that expression coming in exceed the expression limit.
4. drop all `AggrDataPoint` corresponding to the expression within the `TimeGroup` before flushing if raw data points exceeds the configured limit. This is to avoid any user confusion that could be caused by keeping the data points until the limit is exceeded that results in incorrect data.
5. add tests
#1355
1. …
> 1. update eval library so it can be configured with explicit limits for expressions

- atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/StreamSubscriptionManager.scala
- atlas-lwcapi/src/test/scala/com/netflix/atlas/lwcapi/StreamSubscriptionManagerSuite.scala
Updates the unregister to ensure the queue will be completed.
This can avoid issues with data being retained in memory for
the queue and associated stream source.
> lwcapi: ensure cleanup on unregister

- atlas-eval/src/main/scala/com/netflix/atlas/eval/model/AggrDatapoint.scala
- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/TimeGrouped.scala
- atlas-eval/src/test/scala/com/netflix/atlas/eval/stream/FinalExprEvalSuite.scala
For group by it was calling `datapoints.size` which is a
linear operation and maps the values resulting in a lot
of allocations. This changes the intermediate size check
to be a constant time operation.
> fix performance of limit check

- atlas-eval/src/main/scala/com/netflix/atlas/eval/model/AggrDatapoint.scala
- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/EvaluatorImpl.scala
- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/TimeGrouped.scala
- atlas-eval/src/test/scala/com/netflix/atlas/eval/model/AggrDatapointSuite.scala
- atlas-eval/src/test/scala/com/netflix/atlas/eval/stream/FinalExprEvalSuite.scala
Before the counter and associated id was being created
each time an aggregator instance was. Now it is part of
a settings object which can be reused. The aggregators
have also been refactored a bit to reduce code duplication.
> reduce allocations for datapoint aggregators

- atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/QueueHandler.scala
- atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/SubscribeApi.scala
The BroadcastHub doesn't complete if there are still items
pending. When the subscriber failed, the failure wasn't
propagated up since the BroadcastHub can have another
subscriber come along later. Change it to use a publisher
with no fanout, this will fail along with the connected
downstream.
> fix memory leak for failed streams

- atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/SubscribeApi.scala
In some cases there will be multiple subscriptions. If
a downstream fails it will still get propagated and
cleanup the resources that came into the queue.
> enable fanout on the publisher

- atlas-webapi/src/main/scala/com/netflix/atlas/webapi/ExprApi.scala
- atlas-webapi/src/test/scala/com/netflix/atlas/webapi/ExprApiSuite.scala
Updates the `/expr/strip` API to allow filtering operations
from the style and filter vocabularies. This can be useful
for some use-cases for ignoring presentation aspects and
trying to see if the underlying expression is the same. In
the future other operators maybe supported as well, but that
becomes more complex as it wouldn't necessarily be a single
expression.
/cc @vfilanovsky
> support stripping out style and filter operations

- project/Dependencies.scala
Pull in fix for [CVE-2020-36518].
[CVE-2020-36518]: https://nvd.nist.gov/vuln/detail/CVE-2020-36518
> jackson-databind 2.13.2.2

- project/BuildSettings.scala
Some tests rely on static state and can be flakey when
run concurrently.
> disable parallel execution for tests

- atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/StreamsApi.scala
Update the matching logic to list for the end of the path
or a single slash. Before it would try to use an empty string
as the id which can be confusing.
> lwcapi: list streams if path ends with `/`

- atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/SubscriptionManager.scala
- build.sbt
- project/Dependencies.scala
The spectator server group parser is more performant
and used with other observability tooling.
> use server group parser instead of frigga

- project/BuildSettings.scala
Min scala version is now 2.13 so they are no longer
necessary.
> remove build hacks for 2.11

- atlas-core/src/main/scala/com/netflix/atlas/core/db/MemoryDatabase.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/model/Query.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/model/StyleVocabulary.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/util/SmallHashMap.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/db/TimeSeriesBufferSuite.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/model/MathGroupBySuite.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/model/TimeSeriesExprSuite.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/stacklang/InterpreterSuite.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/util/RefIntHashMapSuite.scala
Fixes some minor issues that cause compile errors on
scala3 for atlas-core. The atlas-core project now
compiles and all tests pass except for AlgoStateSuite
due to issues with atlas-json.
> fix compile and test errors on scala3

- atlas-core/src/main/scala/com/netflix/atlas/core/validation/Rule.scala
- project/Dependencies.scala
Scala reflection libraries were removed in scala 3.
The only usage was for loading rule instances based on
a config entry. This can be done easily enough with the
normal java reflection.
> drop use of scala reflection for atlas-core

- atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/ExpressionSplitter.scala
- atlas-lwcapi/src/test/scala/com/netflix/atlas/lwcapi/ExpressionSplitterSuite.scala
- atlas-lwcapi/src/test/scala/com/netflix/atlas/lwcapi/SubscriptionManagerSuite.scala
Some expressions have an exact match for `nf.asg`, but do
not have conditions for `nf.app` or `nf.cluster`. This change
will parse the asg value based on the server group naming
rules and add a cluster restriction so that expressions for
a specific asg will only show when requesting data for the
cluster containing that asg.
> lwc: use asg for matching exprs to a cluster

- atlas-core/src/main/scala/com/netflix/atlas/core/model/CustomVocabulary.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/model/CustomVocabularySuite.scala
In the past this wasn't permitted because binary operations
had to have the same grouping on both sides. In #1244 that
was changed so that one side could have a subset of the other.
> allow mixed grouping for custom averages

- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/ExprInterpreter.scala
- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/StreamContext.scala
- atlas-eval/src/test/scala/com/netflix/atlas/eval/stream/EvaluatorSuite.scala
Exclude operators that are confusing when used in a
streaming context. Specifically:
- `integral`: accumulates the value over the life of
the evaluation. For a streaming evaluation the user
has no way to know the time window it has been
accumulating the value over.
- _Filters_: all filtering operators rely on statistics
from the evaluation context to select the results.
For streaming evaluation, that context is always a
single step interval. Filtering is best left to the
consumer of the data.
> lwc: update operator validation

- atlas-core/src/main/scala/com/netflix/atlas/core/util/SortedTagMap.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/util/SortedTagMapSuite.scala
- atlas-webapi/src/main/scala/com/netflix/atlas/webapi/PublishPayloads.scala
This is typically more efficient overall as it avoids
the need to sort multiple times later on. For example,
in publish the sort is needed for computing the ids
and then ends up getting performed again to encode
as a compact batch.
> use sorted map when decoding tags

- atlas-core/src/main/scala/com/netflix/atlas/core/util/SortedTagMap.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/util/SortedTagMapSuite.scala
Fixes SortedTagMap to address some update patterns
that could result in duplicate keys.
> ensure map keys are deduped

- atlas-webapi/src/main/scala/com/netflix/atlas/webapi/PublishPayloads.scala
- atlas-webapi/src/test/scala/com/netflix/atlas/webapi/PublishPayloadsSuite.scala
If the common tags were after the metric data in the batch
json payload, then the tags in the tuple would get updated,
but not the id. This change fixes it so that the id is
updated based on the final tags for a metric. Also updates
the behavior so the conflicts resolution is consistent for
both paths.
> fix id when common tags are after metric data

- atlas-core/src/main/scala/com/netflix/atlas/core/model/MathVocabulary.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/model/NamedRewriteSuite.scala
Updates the rewrite used for math functions that behave
like aggregation functions, e.g. `:avg`, so that the
rewrite works correctly when the display expression is
a `Query`. Before it would always apply the rewrite to
just the eval expression which could lead to a different
and sometimes broken expression if reinterpreted from
the display expression.
> fix common grouping for aggr helpers

- atlas-core/src/main/scala/com/netflix/atlas/core/model/MathExpr.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/model/MathVocabulary.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/model/NamedRewriteSuite.scala
The subset check for nested grouping would check all
data expressions. If the underlying expression was
combined with binary operations with the grouping for
one side being a subset of the other, then a subsequent
grouping operation could fail the check. Now it checks
based on the final grouping of the pre-aggregate.
> fix cg with custom averages

- atlas-json/src/main/scala/com/netflix/atlas/json/JsonParserHelper.scala
For special double values, e.g. `NaN`, use `parseDouble`
instead of `valueOf` to avoid allocating an instance of
the primitive wrapper type.
> avoid boxing when parsing special double values

- atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/QueueHandler.scala
- atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/SubscribeApi.scala
- atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/WebSocketSessionManager.scala
- atlas-lwcapi/src/test/scala/com/netflix/atlas/lwcapi/WebSocketSessionManagerSuite.scala
improperly terminated clients.
Also add a TODO about dealing with clients that connect and fail to send
a message wherein the queue shuts down after a timeout period and fails to
notify the rest of the flow.
> LWC API: Move the termination watch to the root flow in order to catch

- atlas-eval/src/main/resources/reference.conf
- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/EvaluatorImpl.scala
- atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/SubscribeApi.scala
- atlas-lwcapi/src/test/scala/com/netflix/atlas/lwcapi/SubscribeApiSuite.scala
This was an earlier version that relied used unbatched
text messages for passing the data and was much less
efficient. It is no longer in use internally.
> lwcapi: remove the /v1/subscribe endpoint

- atlas-core/src/main/scala/com/netflix/atlas/core/util/Shards.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/util/ShardsSuite.scala
Before it was relying on `abs` to get a non-negative value
for computing an index to the array. This breaks when the
int value of the id is `Integer.MIN_VALUE`. Update it to
explicitly clear the sign bit to ensure the value will
always be non-negative.
> fix shard lookup for Integer.MIN_VALUE

- .github/workflows/release.yml
- atlas-core/src/main/scala/com/netflix/atlas/core/model/CustomVocabulary.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/model/MathExpr.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/util/Shards.scala
- atlas-eval/src/main/scala/com/netflix/atlas/eval/model/TimeGroup.scala
- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/Evaluator.java
- atlas-eval/src/main/scala/com/netflix/atlas/eval/util/SmallHashMapDeserializer.scala
- atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/SubscriptionManager.scala
- atlas-module-akka/src/main/scala/com/netflix/atlas/akka/AkkaModule.scala
- atlas-module-eval/src/main/scala/com/netflix/atlas/eval/EvalModule.scala
- project/BuildSettings.scala
Back port of #1271.
They were disabled due to a bug, but looks like it
has been fixed. Fixed a number of scaladoc errors
to get the build clean.
Error from publishing attempt without docs:
```
Failed: javadoc-staging, failureMessage:Missing: no javadoc
jar found in folder
'/com/netflix/atlas_v1/atlas-module-lwcapi_2.13/1.7.0-rc.14'
```
> 1.6: re-enable doc artifacts

- atlas-core/src/main/scala/com/netflix/atlas/core/util/Shards.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/util/ShardsSuite.scala
Back port of #1452.
Before it was relying on `abs` to get a non-negative value
for computing an index to the array. This breaks when the
int value of the id is `Integer.MIN_VALUE`. Update it to
explicitly clear the sign bit to ensure the value will
always be non-negative.
> 1.6: fix shard lookup for Integer.MIN_VALUE

- atlas-core/src/main/scala/com/netflix/atlas/core/model/ItemId.scala
- atlas-jmh/src/main/scala/com/netflix/atlas/core/model/ItemIdToString.scala
Initialize capacity for the builder to avoid a resize while filling the buffer. Reduces allocations for the sample benchmark from 440 B/op to 216 B/op.
> reduce allocations for ItemId.toString

- atlas-core/src/main/scala/com/netflix/atlas/core/model/ItemIdCalculator.scala
When computing the id from a tag map, avoid making the sort call when a SortedTagMap is used. That type will already be sorted so it is not necessary.
> avoid calling sort for SortedTagMap

- atlas-core/src/main/scala/com/netflix/atlas/core/model/Query.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/model/QuerySuite.scala
If the inverted query has an exact match, then adding dimensions cannot change the result and it should be excluded.
> improve couldMatch check for not clauses

- atlas-core/src/main/scala/com/netflix/atlas/core/model/CollectorStats.scala
Return a reference to `this` from the builder methods so that they can be chained.
> update CollectorStatsBuilder to allow chaining

- atlas-core/src/main/scala/com/netflix/atlas/core/db/TimeSeriesBuffer.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/db/TimeSeriesBufferSuite.scala
Port an old internal fix to ensure we have consistent behavior. If the data source type is a rate, then treat NaN values as 0 as it means no activity measured for those intervals when consolidating. That means the avg will always be computed over the entire consolidated interval.
For gauges, the NaN values are ignored because to be consistent with values reported to the gauge. The
behavior of gauges is not impacted with this change.
> adjust consolidation behavior for rates

- atlas-core/src/main/scala/com/netflix/atlas/core/db/TimeSeriesBuffer.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/model/DsType.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/db/MemoryDatabaseSuite.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/db/TimeSeriesBufferSuite.scala
This change makes the default dstype consistently
rate for both apply methods of DsType as well as
matching the behavior for the publish path when
feeding data into the normalization cache.
> make default dstype consistent

- atlas-core/src/main/scala/com/netflix/atlas/core/db/AggregateCollector.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/db/MemoryDatabase.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/db/TimeSeriesBuffer.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/db/AggregateCollectorSuite.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/db/TimeSeriesBufferSuite.scala
A long time ago the tag set was made deterministic based on the query expression where it only includes tags with an exact match or that are listed in the group by. As a result, it isn't necessary to compute the intersection of dimensions while aggregating the matching time series.
> optimize result tags computation

- atlas-core/src/main/scala/com/netflix/atlas/core/model/FilterExpr.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/model/FilterVocabulary.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/model/FilterSuite.scala
- atlas-webapi/src/main/scala/com/netflix/atlas/webapi/ExprApi.scala
- atlas-webapi/src/test/scala/com/netflix/atlas/webapi/ExprApiSuite.scala
Updates the behavior of normalize to reflect preferences of the UI team. In particular:
- It will not try to extract common query aspects into a `:cq` clause.
- The helpers for filtering based on summary stats will be preserved rather than expanding.
/cc @nathfisher
> update normalize behavior for UI

- atlas-eval/src/main/scala/com/netflix/atlas/eval/graph/SimpleLegends.scala
- atlas-eval/src/test/scala/com/netflix/atlas/eval/graph/SimpleLegendsSuite.scala
Updates the simple legends generation to handle the case of custom averages used with nested grouping. Before the logic to remove the named rewrite would also remove the first grouping and break the rewrite of any later groupings.
> improve legend for custom avg with nested grouping

- atlas-chart/src/main/scala/com/netflix/atlas/chart/JsonCodec.scala
- atlas-chart/src/main/scala/com/netflix/atlas/chart/model/GraphDef.scala
- atlas-chart/src/test/scala/com/netflix/atlas/chart/JsonCodecSuite.scala
- atlas-eval/src/main/scala/com/netflix/atlas/eval/graph/GraphConfig.scala
- atlas-eval/src/main/scala/com/netflix/atlas/eval/graph/Grapher.scala
- atlas-eval/src/main/scala/com/netflix/atlas/eval/graph/ImageFlags.scala
- atlas-eval/src/test/scala/com/netflix/atlas/eval/graph/GraphUriSuite.scala
The image rendering can be computationally expensive and increase the size of the payload quite a bit. For some cases it is desirable to use the `v2.json` format since it is similar to fetch and LWC, but the image is not needed. Alert processing is one example.
This change adds a `hints` URI parameter that can be used to pass arbitrary hints back to the rendering engine that is used. The `v2.json` engine has been updated to omit the image if a `no-image` hint is passed. In the future we may want to only include the image if requested, but that would be backwards incompatible and break some current usage.
> allow image to be disabled for v2.json

- atlas-eval/src/main/scala/com/netflix/atlas/eval/model/ChunkData.scala
- atlas-eval/src/main/scala/com/netflix/atlas/eval/model/LwcDatapoint.scala
- atlas-eval/src/main/scala/com/netflix/atlas/eval/model/TimeSeriesMessage.scala
- atlas-json/src/main/scala/com/netflix/atlas/json/Json.scala
- atlas-json/src/main/scala/com/netflix/atlas/json/JsonSupport.scala
- atlas-json/src/main/scala/com/netflix/atlas/json/JsonSupportSerializer.scala
- atlas-json/src/main/scala/com/netflix/atlas/json/JsonSupportSerializerModifier.scala
- atlas-json/src/test/scala/com/netflix/atlas/json/JsonSuite.scala
- atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/StreamMetadata.scala
If a class extended JsonSupport and provided a custom encoding it would get used by the interited methods, but would get ignored when using `Json.encode`. This could create problems when an object is nested because the custom encode would not get used. The `Json.encode` could not directly call encode, because it would create a loop with the default implementation.
This change adds a method that can indicate if it is desirable for `Json.ecnode` to use the custom encoding.
> use custom JSON encoding if specified

- atlas-json/src/main/scala/com/netflix/atlas/json/JsonParserHelper.scala
- atlas-json/src/test/scala/com/netflix/atlas/json/JsonParserHelperSuite.scala
Before when using `JsonParserHelper.nextDouble` if the raw encoded value looked like an integer type it would try to access it as a long, then convert the long to a double. This causes problems for larger integers that cannot fit within the bounds of a Java long. Now it will access it as a double.
> json: fix double parsing for large integers

- atlas-chart/src/main/scala/com/netflix/atlas/chart/JsonCodec.scala
- atlas-chart/src/main/scala/com/netflix/atlas/chart/model/DataDef.scala
- atlas-chart/src/test/scala/com/netflix/atlas/chart/PngGraphEngineSuite.scala
- atlas-eval/src/main/scala/com/netflix/atlas/eval/graph/Grapher.scala
Update the `v2.json` format to include the query expression for the lines. This makes it more consistent with the time series messages used with fetch and LWC.
> add expression to v2.json output

- atlas-core/src/main/scala/com/netflix/atlas/core/db/SimpleStaticDatabase.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/index/BatchUpdateTagIndex.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/index/RoaringTagIndex.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/index/RoaringTagIndexSuite.scala
- atlas-jmh/src/main/scala/com/netflix/atlas/core/index/BatchRebuild.scala
- atlas-jmh/src/main/scala/com/netflix/atlas/core/index/RoaringTagIndexBench.scala
A lot of the time and allocations were being spent sorting the items passed to the index. Java uses TimSort internally when sorting object arrays and that uses a merge sort. It allocates a bunch of temporary arrays when performing the merges.
This change leverages the fact that the items that are already indexed will be sorted, so we can just sort the new items and merge the two sorted sets.
> improve performance of batch index update

- atlas-json/src/main/scala/com/netflix/atlas/json/Json.scala
- atlas-json/src/main/scala/com/netflix/atlas/json/JsonParserHelper.scala
Enable the fast double reading/writing that was added in jackson 2.14.0.
> json: enable fast double operations

- atlas-akka/src/main/scala/com/netflix/atlas/akka/ActorService.scala
- atlas-akka/src/main/scala/com/netflix/atlas/akka/HealthcheckApi.scala
- atlas-akka/src/main/scala/com/netflix/atlas/akka/WebServer.scala
- atlas-akka/src/test/scala/com/netflix/atlas/akka/HealthcheckApiSuite.scala
- atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/ExpressionApi.scala
- atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/StartupDelayService.scala
- atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/StreamSubscriptionManager.scala
- atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/StreamsApi.scala
- atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/SubscribeApi.scala
- atlas-spring-webapi/src/main/scala/com/netflix/atlas/webapi/WebApiConfiguration.scala
- atlas-webapi/src/main/scala/com/netflix/atlas/webapi/DatabaseSupplier.scala
- build.sbt
- project/Dependencies.scala
These have been moved to jakarta in later versions. With the way we are using Spring, the annotations are not necessary.
> remove usage of javax annotations

- atlas-akka/src/main/scala/com/netflix/atlas/akka/StreamOps.scala
- atlas-akka/src/test/scala/com/netflix/atlas/akka/StreamOpsSuite.scala
- atlas-jmh/src/main/scala/com/netflix/atlas/akka/MonitorFlowBench.scala
- build.sbt
- project/Dependencies.scala
Updates the monitor flow stage to batch the updates to the meters. This avoids some of the overhead for calling gettimeofday frequently for high volume streams.
> batch updates to meters when monitoring flows

- atlas-akka/src/main/scala/com/netflix/atlas/akka/StreamOps.scala
- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/TimeGrouped.scala
- project/Dependencies.scala
Use the spectator batch updaters in some of the key parts of the eval stream that were manually batched before.
> switch to spectator batch updaters

- atlas-eval/src/main/scala/com/netflix/atlas/eval/model/LwcMessages.scala
- atlas-eval/src/main/scala/com/netflix/atlas/eval/util/SortedTagMapDeserializer.scala
- atlas-eval/src/test/scala/com/netflix/atlas/eval/util/SortedTagMapDeserializerSuite.scala
- atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/EvaluateApi.scala
- atlas-lwcapi/src/test/scala/com/netflix/atlas/lwcapi/EvaluateApiSuite.scala
The main advantage is that for eval it can just quickly copy into an array without all the hashing and extra space in the hash array to avoid collisions.
Note, this change is safe to roll out as long as the lwcapi service is pushed first.
> lwc: use SortedTagMap for data points

- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/EvaluatorImpl.scala
- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/TimeGrouped.scala
- atlas-eval/src/test/scala/com/netflix/atlas/eval/stream/TimeGroupedSuite.scala
When processing data with a high input volume the
`ConnectionSources`, `InputLines`, and `LwcDatapoints` monitors would have a high throughput and the same number of elements flowing through. This change removes two of them so there is now just `InputLines`. This helps reduce overhead in the hot path.
> lwc: remove some monitorFlow steps

- atlas-eval/src/main/scala/com/netflix/atlas/eval/model/LwcMessages.scala
- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/EvaluatorImpl.scala
- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/LwcToAggrDatapoint.scala
- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/TimeGrouped.scala
- atlas-eval/src/test/scala/com/netflix/atlas/eval/stream/LwcToAggrDatapointSuite.scala
- atlas-eval/src/test/scala/com/netflix/atlas/eval/stream/TimeGroupedSuite.scala
Refactors the stream from parsing the messages from lwcapi to the TimeGrouped stage to keep the datapoints batched. This significantly reduces the number of messages passed between the stream stages and achieve a higher throughput.
Also creates a dedicated thread pool to use for parsing the messages as that is the most time consuming step.
> lwc: keep input to TimeGrouped batched

- atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/SubscriptionManager.scala
- atlas-lwcapi/src/test/scala/com/netflix/atlas/lwcapi/SubscriptionManagerSuite.scala
Creating the full list of of all subscriptions can be expensive when there are a lot of expressions. Update it to only be done when there are changes the same as the query index update.
> lwcapi: only update subscription list on changes

- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/TimeGrouped.scala
The heartbeat just ensures the stream keeps moving even if there is no data. It is expected to be delayed from the actual flow a bit.
> ignore heartbeat for dropped old

- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/TimeGrouped.scala
When TimeGrouped flushes a finalized time grouping also have it explicitly flush the batch meter updaters. This avoids the counts potentially showing up much later due to a low rate.
> flush meters when a time grouping is emitted

- atlas-akka/src/main/resources/reference.conf
- atlas-akka/src/main/scala/com/netflix/atlas/akka/RequestHandler.scala
- atlas-akka/src/test/scala/com/netflix/atlas/akka/RequestHandlerNoCompressionSuite.scala
- atlas-akka/src/test/scala/com/netflix/atlas/akka/RequestHandlerSuite.scala
If we are proxying to another server that already supports CORS, then having multiple layers adding the CORS headers can cause problems.
> add option to disable CORS

- atlas-core/src/main/scala/com/netflix/atlas/core/norm/DedupValueFunction.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/norm/NormalizeValueFunction.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/norm/RateValueFunction.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/norm/RollingValueFunction.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/norm/ValueFunction.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/norm/DedupValueFunctionSuite.scala
When pushing data to memory the blocks can easily overwrite when an update for a given datapoint is received. In other use-cases this can be quite expensive and undesirable. This change adds a value function that can be used to buffer the updates for a window of time and dedup the data.
> add value function to dedup inputs

- atlas-webapi/src/main/scala/com/netflix/atlas/webapi/ExprApi.scala
- atlas-webapi/src/test/scala/com/netflix/atlas/webapi/ExprApiSuite.scala
Update the normalization logic to deduplicate the same query clause within an conjunction. Also deduplicates terms within an IN clause and maps to an equals check if there is a single term.
> dedup query clauses during normalization

- atlas-webapi/src/main/scala/com/netflix/atlas/webapi/ExprApi.scala
- atlas-webapi/src/test/scala/com/netflix/atlas/webapi/ExprApiSuite.scala
When normalizing an expression that uses a filter, use one of the `:stat-$(aggr)` placeholders if possible. This avoids duplication of the input expression making them easier to read. It also helps if comparing expressions after normalization to see if they are equivalent.
> use stat placeholders for normalize

- atlas-webapi/src/main/scala/com/netflix/atlas/webapi/ExprApi.scala
- atlas-webapi/src/test/scala/com/netflix/atlas/webapi/ExprApiSuite.scala
Update the expression normalization to dedup OR clauses if the conditions are the same.
> dedup or clauses when normalizing

- atlas-webapi/src/main/scala/com/netflix/atlas/webapi/ExprApi.scala
- atlas-webapi/src/test/scala/com/netflix/atlas/webapi/ExprApiSuite.scala
In some cases with tooling a `:cq` can get applied multiple times. If the common query condition has an OR clause, then that will get expanded with the cross product when computing the DNF. As a result, the normalized query resulting from applying a `:cq` once would differ from applying the same `:cq` multiple times. This change removes redundant clauses from the normalized OR set to avoid the discrepancy. Redundant means that the removed clause will not change the result since another branch of the OR would have matched.
> remove redundant clauses when normalizing

- atlas-chart/src/main/scala/com/netflix/atlas/chart/model/Palette.scala
- atlas-chart/src/test/scala/com/netflix/atlas/chart/model/PaletteSuite.scala
Also add an equals override to palettes for unit testing.
> Add a unique colors list to the palettes for use by heatmaps.

- atlas-chart/src/main/scala/com/netflix/atlas/chart/util/Fonts.scala
- atlas-chart/src/test/scala/com/netflix/atlas/chart/graphics/TicksSuite.scala
There are some differences in image rendering and floating point on the ARM M1 processors that cause tests to fail. This will need some more work, but for now disable those tests when running on ARM. The CI will still catch any issues before merging.
> make tests pass when running on M1 Mac

- atlas-eval/src/main/scala/com/netflix/atlas/eval/graph/Grapher.scala
- atlas-eval/src/test/scala/com/netflix/atlas/eval/graph/GrapherSuite.scala
Before it would always set it to `default` when processing the URI and the caller would have to set it to another value later. To get better consistency, recognize the id parameter when present. The caller can still override with additional logic if desirable.
> grapher: use id parameter if present

- atlas-akka/src/main/resources/reference.conf
Helps to avoid timeout during logging initialization.
> adjust log settings for akka

- atlas-core/src/main/scala/com/netflix/atlas/core/util/SortedTagMap.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/util/SortedTagMapSuite.scala
For some use-cases the tag maps may not have the `name` that is required by Spectator. If that is desirable, then a default name can be used to still be able to leverage utilities like the query index.
> support default name when creating id

- atlas-akka/src/main/scala/com/netflix/atlas/akka/Cors.scala
- atlas-akka/src/main/scala/com/netflix/atlas/akka/CustomDirectives.scala
- atlas-akka/src/test/resources/application.conf
- atlas-akka/src/test/scala/com/netflix/atlas/akka/CorsSuite.scala
- atlas-eval/src/main/scala/com/netflix/atlas/eval/graph/Grapher.scala
- atlas-eval/src/test/scala/com/netflix/atlas/eval/graph/GraphUriSuite.scala
- build.sbt
For requests coming from UIs that have an allowed origin host, use the origin as the default id. If one is explicitly specified via the uri parameter, then that will still be used.
> use CORS origin as id

- atlas-akka/src/main/scala/com/netflix/atlas/akka/CustomDirectives.scala
Swaps the body for the condition so it matches expectations. Before it was doing the opposite, so setting to 0.1 would close ~90% of connections rather than ~10%.
> fix condition for close probability

- atlas-core/src/main/scala/com/netflix/atlas/core/util/RefDoubleHashMap.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/util/RefDoubleHashMapSuite.scala
Primary use-case is computing an aggregate double value based on a key.
> add specialized map for ref with double values

- atlas-eval/src/main/scala/com/netflix/atlas/eval/model/AggrDatapoint.scala
- atlas-eval/src/test/scala/com/netflix/atlas/eval/model/AggrDatapointSuite.scala
Adds a new datapoint aggregator implementation to handle sum/count of gauge values that come from an aggregation service where there can be duplicates. The aggregation service would add a tag `atlas.aggr` with a key to use for grouping and deduping the relevant values. Values within a group will use max aggregation to be consistent with the behavior if there was a single instance of the aggregation service.
> eval: sum aggregation for gauges

- atlas-lwc-events/src/main/scala/com/netflix/atlas/lwc/events/LwcEvent.scala
- atlas-lwc-events/src/test/scala/com/netflix/atlas/lwc/events/LwcEventSuite.scala
- build.sbt
Initial model object representing an arbitrary event to process with LWC. The raw event would typically be a log, span, or trace. The `LwcEvent` type would define how to extract data and encode the event without putting any restrictions on the structure so that LWC is agnostic to the event model and so we can avoid expensive conversions when processing.
> lwc: model object for event

- atlas-lwc-events/src/main/scala/com/netflix/atlas/lwc/events/LwcEvent.scala
When mapping to time series data points, we need to know the timestamp for an event. For events like spans that have a start and end, the end time is used. This is similar behvavior to a timer which would get updated at the end when the latency is known.
> lwc: add timestamp accessor

- atlas-core/src/main/scala/com/netflix/atlas/core/model/EventExpr.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/model/ModelExtractors.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/model/TraceQuery.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/model/TraceVocabulary.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/model/TraceVocabularySuite.scala
- atlas-lwc-events/src/main/scala/com/netflix/atlas/lwc/events/AbstractLwcEventClient.scala
- atlas-lwc-events/src/main/scala/com/netflix/atlas/lwc/events/DatapointEvent.scala
- atlas-lwc-events/src/main/scala/com/netflix/atlas/lwc/events/ExprUtils.scala
- atlas-lwc-events/src/main/scala/com/netflix/atlas/lwc/events/LwcEvent.scala
- atlas-lwc-events/src/main/scala/com/netflix/atlas/lwc/events/LwcEventClient.scala
- atlas-lwc-events/src/main/scala/com/netflix/atlas/lwc/events/Subscription.scala
- atlas-lwc-events/src/main/scala/com/netflix/atlas/lwc/events/Subscriptions.scala
- atlas-lwc-events/src/main/scala/com/netflix/atlas/lwc/events/TraceMatcher.scala
- atlas-lwc-events/src/main/scala/com/netflix/atlas/lwc/events/package.scala
- atlas-lwc-events/src/test/scala/com/netflix/atlas/lwc/events/ExprUtilsSuite.scala
- atlas-lwc-events/src/test/scala/com/netflix/atlas/lwc/events/LwcEventClientSuite.scala
- atlas-lwc-events/src/test/scala/com/netflix/atlas/lwc/events/LwcEventSuite.scala
- atlas-lwc-events/src/test/scala/com/netflix/atlas/lwc/events/TraceMatcherSuite.scala
- atlas-spring-lwc-events/src/main/resources/reference.conf
- atlas-spring-lwc-events/src/main/scala/com/netflix/atlas/lwc/events/LwcEventConfiguration.scala
- atlas-spring-lwc-events/src/test/scala/com/netflix/atlas/lwc/events/LwcEventConfigurationSuite.scala
- build.sbt
- project/Dependencies.scala
Adds `LwcEventClient` that can be used as part of an event ingestion workflow to make events available to an LWC stream. The current setup just supports a statically configured set of subscriptions for verifying the interface and testing the performance overhead.
> lwc: add client interface for processing events

- atlas-eval/src/main/scala/com/netflix/atlas/eval/model/AggrDatapoint.scala
- atlas-eval/src/test/scala/com/netflix/atlas/eval/model/AggrDatapointSuite.scala
The `atlas.aggr` key was included when grouping the datapoints which caused values for the same key to go to separate buckets.
> eval: fix aggr for group by with gauges

- atlas-eval/src/main/scala/com/netflix/atlas/eval/model/AggrDatapoint.scala
- atlas-eval/src/test/scala/com/netflix/atlas/eval/model/AggrDatapointSuite.scala
The `atlas.aggr` key was included when grouping the datapoints which caused values for the same key to go to separate buckets.
Backport of #1555
> 1.7.x: eval: fix aggr for group by with gauges

- atlas-akka/src/main/scala/com/netflix/atlas/akka/StreamOps.scala
- atlas-akka/src/test/scala/com/netflix/atlas/akka/StreamOpsSuite.scala
- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/EvaluatorImpl.scala
If the websocket to an lwcapi node fails and needs to reconnect, then the message with the set of expressions needs to be resent. Before this would only happen when there was a change in either the set of remote instances or the set of expressions. With this change, the set of expressions will get repeated every 5s so it will get resent on a reconnect.
Note, the websocket sub-flow already has some deduping if there is no change, so the additional overhead during normal operations is minimal. If there is a failure, then the sub-flow will get restarted and the state for the `unique` operator will get reset allowing the repeated expression message through.
> eval: ensure exprs are resent on reconnect

- atlas-akka/src/main/scala/com/netflix/atlas/akka/StreamOps.scala
- atlas-akka/src/test/scala/com/netflix/atlas/akka/StreamOpsSuite.scala
- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/EvaluatorImpl.scala
If the websocket to an lwcapi node fails and needs to reconnect, then the message with the set of expressions needs to be resent. Before this would only happen when there was a change in either the set of remote instances or the set of expressions. With this change, the set of expressions will get repeated every 5s so it will get resent on a reconnect.
Note, the websocket sub-flow already has some deduping if there is no change, so the additional overhead during normal operations is minimal. If there is a failure, then the sub-flow will get restarted and the state for the `unique` operator will get reset allowing the repeated expression message through.
Backport of #1557.
> 1.7 - eval: ensure exprs are resent on reconnect

- atlas-lwc-events/src/main/scala/com/netflix/atlas/lwc/events/LwcEvent.scala
- atlas-lwc-events/src/main/scala/com/netflix/atlas/lwc/events/LwcEventClient.scala
Provide a default implementation for the encode methods of an LWC event. They can be overridden for the less common case that a custom encoding is needed.
> lwc-events: default impl for encode methods

- atlas-eval/src/main/scala/com/netflix/atlas/eval/model/ExprType.java
- atlas-eval/src/main/scala/com/netflix/atlas/eval/model/LwcExpression.scala
- atlas-eval/src/main/scala/com/netflix/atlas/eval/model/LwcMessages.scala
- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/EvaluatorImpl.scala
- atlas-eval/src/test/scala/com/netflix/atlas/eval/model/LwcMessagesSuite.scala
- atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/ExpressionMetadata.scala
- atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/ExpressionSplitter.scala
- atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/SubscribeApi.scala
- atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/WebSocketSessionManager.scala
- atlas-lwcapi/src/test/scala/com/netflix/atlas/lwcapi/ExpressionApiSuite.scala
- atlas-lwcapi/src/test/scala/com/netflix/atlas/lwcapi/ExpressionMetadataSuite.scala
- atlas-lwcapi/src/test/scala/com/netflix/atlas/lwcapi/ExpressionSplitterSuite.scala
- atlas-lwcapi/src/test/scala/com/netflix/atlas/lwcapi/SubscribeApiJsonSuite.scala
- atlas-lwcapi/src/test/scala/com/netflix/atlas/lwcapi/SubscribeApiSuite.scala
- atlas-lwcapi/src/test/scala/com/netflix/atlas/lwcapi/SubscriptionManagerSuite.scala
- atlas-lwcapi/src/test/scala/com/netflix/atlas/lwcapi/WebSocketSessionManagerSuite.scala
In preparation for supporting event and trace data flowing through indicate an expression type on the messages to setup the subscription. For backwards compatiblity, the time series type will be used if there is not an explicit type set on the messages.
> lwc: indicate expr type for subscriptions

- atlas-eval/src/main/scala/com/netflix/atlas/eval/model/ExprType.java
- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/EurekaGroupsLookup.scala
- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/Evaluator.java
- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/EvaluatorImpl.scala
- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/ExprInterpreter.scala
- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/FinalExprEval.scala
- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/StreamContext.scala
- atlas-eval/src/test/scala/com/netflix/atlas/eval/stream/EurekaGroupsLookupSuite.scala
- atlas-eval/src/test/scala/com/netflix/atlas/eval/stream/EvaluatorSuite.scala
- atlas-eval/src/test/scala/com/netflix/atlas/eval/stream/FinalExprEvalSuite.scala
Update the model classes used with `Evalutor` to be records now that the baseline is java 17.
> eval: make model classes records

- atlas-eval/src/main/scala/com/netflix/atlas/eval/graph/Grapher.scala
- atlas-eval/src/main/scala/com/netflix/atlas/eval/util/IdParamSanitizer.scala
- atlas-eval/src/test/scala/com/netflix/atlas/eval/graph/GraphUriSuite.scala
- atlas-eval/src/test/scala/com/netflix/atlas/eval/util/IdParamSanitizerSuite.scala
Adds a utility to do some basic sanitization. First the it is normalized to lower case. Second it will be checked for some common patterns for arbitrary high cardinality values that should not be used, but sometimes are and maps those to the default bucket.
> sanitize id parameter on graph URIs

- atlas-pekko/src/main/scala/com/netflix/atlas/pekko/PekkoHttpClient.scala
- atlas-pekko/src/main/scala/com/netflix/atlas/pekko/StreamOps.scala
- atlas-spring-pekko/src/main/scala/com/netflix/atlas/pekko/PekkoConfiguration.scala
- atlas-spring-pekko/src/test/scala/com/netflix/atlas/pekko/PekkoConfigurationSuite.scala
Rename to use Pekko for better consistency and making it easier to automate the transition of other projects that pull in these classes. Allows for easier search and replace to migrate.
> rename classes with Akka in the name

- atlas-core/src/main/scala/com/netflix/atlas/core/model/MathExpr.scala
- atlas-eval/src/test/scala/com/netflix/atlas/eval/stream/FinalExprEvalSuite.scala
When executing an expression in a streaming context, stateful operators used as input to a second level grouping were not preserving the state.
> eval: preserve state with multi-level grouping

- atlas-core/src/main/scala/com/netflix/atlas/core/model/MathExpr.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/util/Strings.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/util/StringsSuite.scala
Allows references like `now` to be set to an explicit value for the purposes of tests. Can also be used to have custom reference points.
> core: support custom set of references for dates

- atlas-core/src/main/scala/com/netflix/atlas/core/stacklang/Context.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/stacklang/Interpreter.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/stacklang/LoopSuite.scala
If the `:call` operator is used recursively it can result in an infinite loop. This change adds some sanity checks for the call depth to quickly fail in these cases and indicate that a loop was detected.
> core: add check for infinite loops

- atlas-core/src/main/scala/com/netflix/atlas/core/model/StyleExpr.scala
- atlas-webapi/src/main/scala/com/netflix/atlas/webapi/ExprApi.scala
- atlas-webapi/src/test/scala/com/netflix/atlas/webapi/ExprApiSuite.scala
Updates the normalization behavior so that expressions that use the default line style or `:line` explicitly will be the same after normalization. For other line styles use the simple name rather than `:ls` as it is more familiar to users.
> consistent normalization of line styles

- atlas-core/src/main/scala/com/netflix/atlas/core/model/MathVocabulary.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/model/PercentilesSuite.scala
Adds a `sample-count` operation that can be used to estimate the number of samples received for a percentile approximation baed on a range of the distribution. This estimate is computed by adjusting the query to restrict the set of buckets used to model the distribution to those for the specified range.
One use-case for this is to be able to track number of requests that are not within an SLO based on latency. If more precise tracking is needed, then a bucket counter could be used with a bucket boundary that matches the SLO threshold. However, this operation can be used to get an estimate if an existing percentile timer exists.
For now this operation is marked as unstable to allow for some broader testing. There may still be some adjustments to the naming and behavior.
> core: add sample-count operation

- atlas-core/src/main/scala/com/netflix/atlas/core/stacklang/Interpreter.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/stacklang/StandardVocabulary.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/stacklang/InterpreterSuite.scala
- atlas-webapi/src/main/scala/com/netflix/atlas/webapi/ExprApi.scala
Updates the `/expr/*` APIs to support unstable operations. These are used for debugging and understaning expressions so failing for unstable operations just adds confusion and makes it harder for early adopters to experiment with unstable features.
> webapi: support unstable ops for expr manipulation

- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/ExprInterpreter.scala
- atlas-eval/src/test/scala/com/netflix/atlas/eval/stream/EvaluatorSuite.scala
Check each data expression to catch some uses of named rewrites where the offset is not available on the display expression.
> eval: improve offset validation

- atlas-eval/src/main/scala/com/netflix/atlas/eval/graph/DefaultSettings.scala
- atlas-eval/src/test/scala/com/netflix/atlas/eval/graph/GraphUriSuite.scala
If an invalid theme name was requested, it was returning a 500 with a confusing error message. It will now return a 400 and indicate the theme is invalid.
> improve error message for invalid theme

- atlas-standalone/src/main/resources/log4j2.xml
Set spectator to info to reduce log noise when running the demo app.
> standalone: adjust log levels

- atlas-postgres/src/main/scala/com/netflix/atlas/postgres/Interval.scala
- atlas-postgres/src/main/scala/com/netflix/atlas/postgres/PostgresDatabase.scala
- atlas-postgres/src/main/scala/com/netflix/atlas/postgres/PostgresService.scala
- atlas-postgres/src/main/scala/com/netflix/atlas/postgres/PostgresTagIndex.scala
- atlas-postgres/src/main/scala/com/netflix/atlas/postgres/SqlUtils.scala
- atlas-postgres/src/main/scala/com/netflix/atlas/postgres/TableDefinition.scala
- atlas-postgres/src/test/scala/com/netflix/atlas/postgres/IntervalSuite.scala
- atlas-postgres/src/test/scala/com/netflix/atlas/postgres/PostgresDatabaseSuite.scala
- atlas-postgres/src/test/scala/com/netflix/atlas/postgres/PostgresSuite.scala
- atlas-postgres/src/test/scala/com/netflix/atlas/postgres/PostgresTagIndexSuite.scala
- atlas-postgres/src/test/scala/com/netflix/atlas/postgres/SqlUtilsSuite.scala
- atlas-postgres/src/test/scala/com/netflix/atlas/postgres/TableDefinitionSuite.scala
- build.sbt
- project/Dependencies.scala
Metric database implementation delegating to postgres for querying tables with rows of block data. Some optimizations for aggregations pending: moving windows, consolidation, and potentially compressed arrays.
> postgres: db implementation

- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/LwcToAggrDatapoint.scala
This will get inremented when we get messages from the LWC API service and do not recognize the id.
> eval: add counter for unknown messages

- atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/SubscribeApi.scala
When setting up a new subscription, batch the subscription metadata messages sent to the queue. Otherwise if there is a large set it they could get written quickly enough to exceed the queue size.
> lwcapi: batch sub messages

- atlas-eval/src/main/resources/reference.conf
- atlas-eval/src/main/scala/com/netflix/atlas/eval/graph/SimpleLegends.scala
- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/ExprInterpreter.scala
- atlas-eval/src/test/resources/application.conf
- atlas-eval/src/test/scala/com/netflix/atlas/eval/stream/TestContext.scala
To make streaming data more consistent with the backends allow simple legends to be used. Defaults to true, but can be disabled if needed.
> eval: support simple legends for streaming data

- atlas-chart/src/main/scala/com/netflix/atlas/chart/JsonCodec.scala
- atlas-eval/src/main/scala/com/netflix/atlas/eval/graph/Grapher.scala
- atlas-eval/src/main/scala/com/netflix/atlas/eval/model/TimeSeriesMessage.scala
- atlas-eval/src/test/scala/com/netflix/atlas/eval/stream/EvaluatorSuite.scala
Update v2.json output to include the id for a time series. This can be useful when matching without output from other sources such as streaming data. For consistency also updates the LWC/fetch output to include the offset dimension.
> add time series id to v2.json output

- atlas-core/src/main/scala/com/netflix/atlas/core/model/MathExpr.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/model/TimeSeriesExprSuite.scala
- atlas-eval/src/test/scala/com/netflix/atlas/eval/stream/FinalExprEvalSuite.scala
Make the behavior of using an aggregate on an empty group by result consistent with aggregate on an empty query result.
> core: no data for aggr of empty group by

- atlas-jmh/src/main/scala/com/netflix/atlas/webapi/PublishPayloadsBench.scala
when decoding batches of datapoints.
> atlas JMH: Quantify skipping decoding of the time series ID

- atlas-chart/src/main/scala/com/netflix/atlas/chart/JsonCodec.scala
- atlas-eval/src/main/scala/com/netflix/atlas/eval/graph/Grapher.scala
- atlas-eval/src/main/scala/com/netflix/atlas/eval/graph/ImageFlags.scala
- atlas-eval/src/main/scala/com/netflix/atlas/eval/model/LineStyleMetadata.scala
- atlas-eval/src/main/scala/com/netflix/atlas/eval/model/TimeSeriesMessage.scala
- atlas-eval/src/test/scala/com/netflix/atlas/eval/model/TimeSeriesMessageSuite.scala
- atlas-webapi/src/main/scala/com/netflix/atlas/webapi/FetchRequestSource.scala
Adds initial support for presentation metadata when using fetch API. It will force hashed palette selection as not all data is known in advance. It is off by default to keep data sizes smaller. To enable the user would need to specify a hint of `presentation-metadata`.
> support presentation metadata for fetch

- atlas-core/src/main/scala/com/netflix/atlas/core/model/CustomVocabulary.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/model/TraceQuery.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/model/TraceVocabulary.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/model/TraceVocabularySuite.scala
- atlas-eval/src/main/scala/com/netflix/atlas/eval/model/ExprType.java
- atlas-lwc-events/src/main/scala/com/netflix/atlas/lwc/events/AbstractLwcEventClient.scala
- atlas-lwc-events/src/main/scala/com/netflix/atlas/lwc/events/ExprUtils.scala
- atlas-lwc-events/src/test/scala/com/netflix/atlas/lwc/events/ExprUtilsSuite.scala
- atlas-lwc-events/src/test/scala/com/netflix/atlas/lwc/events/TraceMatcherSuite.scala
Just using span-filter for both pass-through and time series use-cases on traces creates some ambiguity for some use-cases in particular with implicit conversions.
> add span-time-series operator

- atlas-core/src/main/scala/com/netflix/atlas/core/model/ModelExtractors.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/model/ModelExtractorsSuite.scala
Add some model extractors for getting trace filters and time series queries with expected implicit conversions.
> core: add extractors for trace queries

- atlas-core/src/main/scala/com/netflix/atlas/core/model/EventExpr.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/model/TraceQuery.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/model/EventVocabularySuite.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/model/TraceVocabularySuite.scala
Update toString to output an expression that conforms to the model. This makes them consistent with other expr types.
> core: fix toString for event and trace exprs

- .github/workflows/pr.yml
- .github/workflows/release.yml
- .github/workflows/snapshot.yml
- atlas-eval/src/main/scala/com/netflix/atlas/eval/model/TimeSeriesMessage.scala
- atlas-eval/src/test/scala/com/netflix/atlas/eval/stream/FinalExprEvalSuite.scala
- project/BuildSettings.scala
- project/Dependencies.scala
Help ensure code stays compatible with 3 going forward.
> enable cross-building for scala 3

- .github/workflows/release.yml
- .github/workflows/snapshot.yml
The `+` on publishSigned will handle the publishing of all scala versions.
> avoid double publishing of artifacts

- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/EvaluatorImpl.scala
- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/ExprInterpreter.scala
- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/FinalExprEval.scala
- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/StreamContext.scala
- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/SyntheticDataSource.scala
- atlas-eval/src/test/scala/com/netflix/atlas/eval/stream/EvaluatorSuite.scala
- atlas-eval/src/test/scala/com/netflix/atlas/eval/stream/FinalExprEvalSuite.scala
- atlas-eval/src/test/scala/com/netflix/atlas/eval/stream/TestContext.scala
Honor `presentation-metadata` hint for time series messages emitted by the stream. This allows it to be blended with the backend with consistent presentation.
> eval: support presentation metadata for stream

- atlas-eval/src/main/resources/reference.conf
- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/ExprInterpreter.scala
- atlas-eval/src/test/scala/com/netflix/atlas/eval/stream/EvaluatorSuite.scala
- atlas-eval/src/test/scala/com/netflix/atlas/eval/stream/TestContext.scala
Add setting to limit the maximum step size permitted for streaming. Large step sizes require accumulating state for a long time and can complicate deployments. There are no current uses.
> eval: add max step size setting

- atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/ExpressionSplitter.scala
- atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/SubscriptionManager.scala
- atlas-lwcapi/src/test/scala/com/netflix/atlas/lwcapi/SubscriptionManagerSuite.scala
Update cluster matching logic to consider the nf.shard1 and nf.shard2 dimensions. Helps ensure more precise matching with clusters using these newer aspects.
> lwcapi: support shard dimensions for cluster scoping

- atlas-core/src/main/scala/com/netflix/atlas/core/model/MathVocabulary.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/model/PercentilesSuite.scala
Update `:sample-count` operator to be considered stable. It has been around for a few months and usage seems to match user expectations.
> core: sample-count is now stable

- atlas-core/src/main/scala/com/netflix/atlas/core/validation/ReservedKeyRule.scala
Some testing shows HashSet performs a little bit better (~5%) for the contains check under high load for the keys we have.
> core: use HashSet for reserved key rule

- atlas-eval/src/main/scala/com/netflix/atlas/eval/model/AggrDatapoint.scala
- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/LwcToAggrDatapoint.scala
- atlas-eval/src/test/scala/com/netflix/atlas/eval/model/AggrDatapointSuite.scala
This was originally intended for some deduping, but was never utilized. The only function right now is to indicate a synthetic data point generated from a heartbeat. This change removes some of the deduping overhead based on the source that won't actually dedup anything.
> eval: simplify data point source

- atlas-core/src/main/scala/com/netflix/atlas/core/model/TraceVocabulary.scala
- atlas-lwc-events/src/test/scala/com/netflix/atlas/lwc/events/TraceMatcherSuite.scala
Update matcher to make it more convenient to chain together child queries to indicate a path.
> core: support chaining child queries

- atlas-eval/src/main/scala/com/netflix/atlas/eval/model/EventMessage.scala
- atlas-eval/src/main/scala/com/netflix/atlas/eval/model/LwcEvent.scala
- atlas-eval/src/main/scala/com/netflix/atlas/eval/model/LwcMessages.scala
- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/LwcToAggrDatapoint.scala
- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/StreamContext.scala
- atlas-eval/src/test/scala/com/netflix/atlas/eval/model/LwcMessagesSuite.scala
- atlas-eval/src/test/scala/com/netflix/atlas/eval/stream/EvaluatorSuite.scala
Update messages parsing to handle simple pass-through events. They get logged out just like diagnostic
messages.
> eval: add event message type

- atlas-lwc-events/src/main/scala/com/netflix/atlas/lwc/events/AbstractLwcEventClient.scala
- atlas-lwc-events/src/main/scala/com/netflix/atlas/lwc/events/DatapointConverter.scala
- atlas-lwc-events/src/main/scala/com/netflix/atlas/lwc/events/LwcEvent.scala
- atlas-lwc-events/src/main/scala/com/netflix/atlas/lwc/events/LwcEventClient.scala
- atlas-lwc-events/src/test/scala/com/netflix/atlas/lwc/events/DatapointConverterSuite.scala
- atlas-lwc-events/src/test/scala/com/netflix/atlas/lwc/events/LwcEventClientSuite.scala
Updates to support common statistics for timer and dist summary. Aggregates the values locally to reduce number of messages.
> lwc-events: improve data point conversion

- atlas-core/src/main/scala/com/netflix/atlas/core/util/Strings.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/util/StringsSuite.scala
Update `Strings.parseDuration` to support sub-second durations.
> core: support sub-second durations

- atlas-eval/src/main/scala/com/netflix/atlas/eval/model/DatapointsTuple.scala
- atlas-eval/src/main/scala/com/netflix/atlas/eval/model/ExprType.java
- atlas-eval/src/main/scala/com/netflix/atlas/eval/model/TimeGroupsTuple.scala
- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/EvaluatorImpl.scala
- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/ExprInterpreter.scala
- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/FinalExprEval.scala
- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/LwcToAggrDatapoint.scala
- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/StreamContext.scala
- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/SyntheticDataSource.scala
- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/TimeGrouped.scala
- atlas-eval/src/test/scala/com/netflix/atlas/eval/stream/EvaluatorSuite.scala
- atlas-eval/src/test/scala/com/netflix/atlas/eval/stream/ExprInterpreterSuite.scala
- atlas-eval/src/test/scala/com/netflix/atlas/eval/stream/LwcToAggrDatapointSuite.scala
- atlas-eval/src/test/scala/com/netflix/atlas/eval/stream/TimeGroupedSuite.scala
Diagnostic messages and events were using the ds logger that has a separate queue. This made them prone to getting dropped if the throughput was high. Refactor to pass these messages over the same path as the data points.
> eval: fix message drops for higher throughput

- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/ExprInterpreter.scala
- atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/ExpressionMetadata.scala
- atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/ExpressionSplitter.scala
- atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/SubscribeApi.scala
- atlas-lwcapi/src/test/scala/com/netflix/atlas/lwcapi/ExpressionApiSuite.scala
- atlas-lwcapi/src/test/scala/com/netflix/atlas/lwcapi/ExpressionMetadataSuite.scala
- atlas-lwcapi/src/test/scala/com/netflix/atlas/lwcapi/ExpressionSplitterSuite.scala
- atlas-lwcapi/src/test/scala/com/netflix/atlas/lwcapi/SubscribeApiSuite.scala
Update the subscribe API to send back the subscription V2 message when using event types other than time series. Time series can be converted once all clients are updated.
> lwcapi: use subv2 type for events

- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/FinalExprEval.scala
- atlas-eval/src/test/scala/com/netflix/atlas/eval/stream/FinalExprEvalSuite.scala
FinalExprEval stage would emit spurious warnings for event expressions. Ignore the non time series expressions for the eval processing as events are just passed through.
> eval: fix spurious warnings for event expressions

- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/ExprInterpreter.scala
- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/FinalExprEval.scala
- atlas-eval/src/test/scala/com/netflix/atlas/eval/stream/EvaluatorSuite.scala
- atlas-eval/src/test/scala/com/netflix/atlas/eval/stream/FinalExprEvalSuite.scala
Map back to normal graph URI and generate the config to support consistent presentation metadata behavior.
> eval: preserve presentation meta for trace graph

- atlas-eval/src/test/scala/com/netflix/atlas/eval/stream/LwcToAggrDatapointSuite.scala
- atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/ExpressionSplitter.scala
- atlas-lwcapi/src/test/scala/com/netflix/atlas/lwcapi/ExpressionSplitterSuite.scala
Ensure trace time series query will get split up into representative data expressions correctly.
> lwcapi: add test for splitting trace query

- atlas-lwc-events/src/main/scala/com/netflix/atlas/lwc/events/AbstractLwcEventClient.scala
- atlas-lwc-events/src/main/scala/com/netflix/atlas/lwc/events/ExprUtils.scala
- atlas-lwc-events/src/main/scala/com/netflix/atlas/lwc/events/Subscription.scala
- atlas-lwc-events/src/main/scala/com/netflix/atlas/lwc/events/Subscriptions.scala
- atlas-lwc-events/src/test/scala/com/netflix/atlas/lwc/events/LwcEventClientSuite.scala
- atlas-lwc-events/src/test/scala/com/netflix/atlas/lwc/events/LwcEventSuite.scala
- atlas-spring-lwc-events/src/main/resources/reference.conf
- atlas-spring-lwc-events/src/main/scala/com/netflix/atlas/lwc/events/LwcEventConfiguration.scala
Update the sync logic to reuse the existing handlers rather than completely replace them. For data point converters this helps avoid losing state during the sync.
Also changes some of the naming to be more consistent with the expressions response.
> lwc-events: reuse handlers when syncing expressions

- atlas-lwc-events/src/main/resources/reference.conf
- atlas-lwc-events/src/main/scala/com/netflix/atlas/lwc/events/AbstractLwcEventClient.scala
- atlas-lwc-events/src/main/scala/com/netflix/atlas/lwc/events/RemoteLwcEventClient.scala
- atlas-lwc-events/src/main/scala/com/netflix/atlas/lwc/events/Subscription.scala
- atlas-spring-lwc-events/src/main/resources/reference.conf
- atlas-spring-lwc-events/src/main/scala/com/netflix/atlas/lwc/events/LwcEventConfiguration.scala
Update config so when disabled it will still use local client to allow for debugging. Remote client that talks to lwcapi service will be used when enabled.
> lwc-events: add remote client

- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/LwcToAggrDatapoint.scala
- atlas-eval/src/test/scala/com/netflix/atlas/eval/stream/LwcToAggrDatapointSuite.scala
Update test case to have the correct expression for a trace time series subscription response.
> eval: fix test case for trace time series

- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/StreamContext.scala
- atlas-eval/src/test/scala/com/netflix/atlas/eval/stream/EvaluatorSuite.scala
For some backends, such as event queries, the expensive query check may not make sense as there may not be a name field. Allow it to be disabled for specific backends.
> eval: add flag to check for expensive queries

- atlas-lwc-events/src/main/scala/com/netflix/atlas/lwc/events/AbstractLwcEventClient.scala
- atlas-lwc-events/src/test/scala/com/netflix/atlas/lwc/events/LwcEventClientSuite.scala
Ensure that unchanged handlers are added to the set that will get flushed based on the heartbeat.
> lwc-events: fix sync for time series

- atlas-lwc-events/src/main/scala/com/netflix/atlas/lwc/events/AbstractLwcEventClient.scala
- atlas-lwc-events/src/main/scala/com/netflix/atlas/lwc/events/ExprUtils.scala
- atlas-lwc-events/src/test/scala/com/netflix/atlas/lwc/events/LwcEventClientSuite.scala
Update trace time series to support extracting a particular value from the event the same as event time series.
> lwc-events: support value extraction for traces

- atlas-eval/src/main/scala/com/netflix/atlas/eval/model/LwcEvent.scala
- atlas-lwcapi/src/test/scala/com/netflix/atlas/lwcapi/EvaluateApiSuite.scala
If an event is sent to `/evaluate` without an id, respond with a 400 error instead of 500.
> lwcapi: fix status code for event without id

- atlas-lwc-events/src/main/scala/com/netflix/atlas/lwc/events/LwcEvent.scala
- atlas-lwc-events/src/test/scala/com/netflix/atlas/lwc/events/LwcEventSuite.scala
Add support for mapping Java Enum types to tag string values.
> lwc-events: support enums as tag values

- project/Dependencies.scala
Switch back to older version as there is a known performance regression in 2.17.0 ([#672]).
[#672]: https://github.com/FasterXML/jackson-module-scala/issues/672
> jackson 2.16.2

- atlas-json/src/main/scala/com/netflix/atlas/json/Json.scala
- atlas-json/src/test/scala/com/netflix/atlas/json/JsonSuite.scala
Provide method that can be used to customize the mapper. This should be used carefully as it will impact all uses of `Json` and could break other aspects that rely on the default behavior.
> json: allow mapper to be customized

- atlas-eval/src/main/scala/com/netflix/atlas/eval/graph/SimpleLegends.scala
- atlas-eval/src/test/scala/com/netflix/atlas/eval/graph/SimpleLegendsSuite.scala
When generating a simple legend with variable substitutions use the `$(var)` for instead of `$var`. This avoid issues in some cases where the data source is using invalid key characters.
> eval: use parens for simple legends

- atlas-lwc-events/src/main/resources/reference.conf
- atlas-lwc-events/src/main/scala/com/netflix/atlas/lwc/events/RemoteLwcEventClient.scala
Add config setting for the config refresh frequency.
> lwc-events: make refresh frequency configurable

- atlas-lwc-events/src/main/scala/com/netflix/atlas/lwc/events/AbstractLwcEventClient.scala
- atlas-lwc-events/src/main/scala/com/netflix/atlas/lwc/events/RemoteLwcEventClient.scala
- atlas-lwc-events/src/test/scala/com/netflix/atlas/lwc/events/RemoveLwcEventClientSuite.scala
Explicitly flush data for the heartbeat to ensure data doesn't get buffered for an excessive length of time.
> lwc-events: explicitly flush on heartbeat

- atlas-lwc-events/src/main/scala/com/netflix/atlas/lwc/events/DatapointConverter.scala
- atlas-lwc-events/src/main/scala/com/netflix/atlas/lwc/events/DatapointEvent.scala
- atlas-lwc-events/src/main/scala/com/netflix/atlas/lwc/events/LwcEvent.scala
- atlas-lwc-events/src/test/scala/com/netflix/atlas/lwc/events/DatapointConverterSuite.scala
Allow the default value to be specified for an event if an explicit value key is not part of the query. It will default to 1.0. Also support negative values with min/max aggregates.
> lwc-events: default value for event

- atlas-lwc-events/src/main/scala/com/netflix/atlas/lwc/events/DatapointConverter.scala
- atlas-lwc-events/src/test/scala/com/netflix/atlas/lwc/events/DatapointConverterSuite.scala
Map duration type to seconds when converting to a data point.
> lwc-events: support duration type

- atlas-lwc-events/src/main/scala/com/netflix/atlas/lwc/events/DatapointConverter.scala
- atlas-lwc-events/src/test/scala/com/netflix/atlas/lwc/events/DatapointConverterSuite.scala
The `:percentiles` operator internally will group by `percentile`. Updates the datapoint converter to map the value to the appropriate bucket dimension so that percentile approximations can be used. For timers, the raw value type should be a `Duration` to allow for accurate unit conversion.
> lwc-events: support percentile grouping

- atlas-lwc-events/src/main/scala/com/netflix/atlas/lwc/events/DatapointConverter.scala
- atlas-lwc-events/src/test/scala/com/netflix/atlas/lwc/events/LwcEventClientSuite.scala
Update group by data converter to remove simple aggregate converters when flushing if they have no data. Otherwise the set of groups can grow unbounded.
> lwcevents: cleanup groups with no data

- atlas-lwc-events/src/main/scala/com/netflix/atlas/lwc/events/DatapointConverter.scala
- atlas-lwc-events/src/main/scala/com/netflix/atlas/lwc/events/LwcEvent.scala
- atlas-lwc-events/src/test/scala/com/netflix/atlas/lwc/events/DatapointConverterSuite.scala
- atlas-lwc-events/src/test/scala/com/netflix/atlas/lwc/events/LwcEventDurationSuite.scala
When wrapping timer events it can be useful for the default value to be a duration for mapping to percentile timer type.
> lwc-events: support duration for default value

- atlas-core/src/main/scala/com/netflix/atlas/core/model/CustomVocabulary.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/model/MathExpr.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/model/MathVocabulary.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/model/CustomVocabularySuite.scala
- atlas-eval/src/main/scala/com/netflix/atlas/eval/graph/SimpleLegends.scala
- atlas-webapi/src/test/scala/com/netflix/atlas/webapi/ExprApiSuite.scala
Before it was getting expanded exposing the underlying details and showing the user a more complex query that is hard to for them to understand. Use named rewrite to preserve the operator when doing the normalization.
> webapi: improve normalize behavior for sample-count

- atlas-lwc-events/src/main/scala/com/netflix/atlas/lwc/events/AbstractLwcEventClient.scala
- atlas-lwc-events/src/main/scala/com/netflix/atlas/lwc/events/LwcEventClient.scala
- project/Dependencies.scala
Add `couldMatch` method to the client to allow for filtering our some data early if it requires an expensive transform to generate the final event.
> lwc-events: add pre-filter method for events

- atlas-core/src/main/scala/com/netflix/atlas/core/util/Strings.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/util/StringsSuite.scala
Updates the data parsing to allow for epoch timestamps in seconds, millis, micros, or nanos. Before it only supported seconds and millis. This does reduce the range of times a bit, but in practice the transition point is in the 1970s well before times we encounter or a few hundred years in the future.
> core: parse epoch in micros or nanos

- atlas-pekko/src/main/resources/reference.conf
- atlas-pekko/src/main/scala/com/netflix/atlas/pekko/StreamOps.scala
- atlas-pekko/src/test/scala/com/netflix/atlas/pekko/StreamOpsSuite.scala
Add helper to create a source that is based on a Java BlockingQueue implementation. This can be used as an alternative to Pekko's BoundedSourceQueue when more control of the queue is desirable. If the queue is full it can be set to either drop newly arriving values or older values that are already in the queue.
> pekko: source based on BlockingQueue

- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/EvaluatorImpl.scala
- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/StreamContext.scala
- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/package.scala
- atlas-eval/src/test/scala/com/netflix/atlas/eval/stream/EddaGroupsLookupSuite.scala
- atlas-eval/src/test/scala/com/netflix/atlas/eval/stream/EddaSourceSuite.scala
- atlas-eval/src/test/scala/com/netflix/atlas/eval/stream/LwcToAggrDatapointSuite.scala
- atlas-eval/src/test/scala/com/netflix/atlas/eval/stream/TestContext.scala
- atlas-pekko/src/main/scala/com/netflix/atlas/pekko/AccessLogger.scala
- atlas-pekko/src/main/scala/com/netflix/atlas/pekko/PekkoHttpClient.scala
- atlas-pekko/src/test/scala/com/netflix/atlas/pekko/PekkoHttpClientSuite.scala
Update PekkoHttpClient to support `superPool` more commonly used with streams. Also hooks in retry logic to make it work with the logger consistently and support throttling. Pekko's internal pool retries only happen if the request fails with an exception. This also provides some more flexiblity with the retry decision so it may be used for requests that are not clearly idempotent based on the HTTP spec, but maybe ok to retry for a given use-case.
> pekko: update client helper to support flow API

- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/DataSourceLogger.scala
- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/EvaluatorImpl.scala
- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/StreamContext.scala
- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/package.scala
- atlas-eval/src/test/scala/com/netflix/atlas/eval/stream/LwcToAggrDatapointSuite.scala
Create context earlier to allow for performing validation or logging related to the data sources in the firts parts of the stream.
> eval: refactor flow to create context earlier

- atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/QueueHandler.scala
- atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/SubscribeApi.scala
- atlas-lwcapi/src/test/scala/com/netflix/atlas/lwcapi/ExpressionApiSuite.scala
- atlas-lwcapi/src/test/scala/com/netflix/atlas/lwcapi/StreamSubscriptionManagerSuite.scala
Update queue for incoming data to drop old data rather than new data. For use-cases like logs pass-through it is preferable to bias for new data.
> lwcapi: drop old data if queue is full

- atlas-pekko/src/main/scala/com/netflix/atlas/pekko/PekkoHttpClient.scala
Simplify to just the client flow if no retries are specified. The retry flow may not allow concurrent requests on the flow.
> pekko: just use client flow if no retries

- atlas-lwcapi/src/main/resources/reference.conf
- atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/SubscribeApi.scala
Whether the queue drops old or new data can now be configured. Defaults to drop new which wa the previous behavior.
> lwcapi: add config option for drop policy

- atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/WebSocketSessionManager.scala
If subs change after the data source has been pushed, then it wouldn't push the high priority messages until the next pull. Now it will go ahead and push if messages are ready.
> lwcapi: fix push for new subs

- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/DataSourceRewriter.scala
- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/EvaluatorImpl.scala
- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/HostSource.scala
- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/package.scala
- atlas-eval/src/test/scala/com/netflix/atlas/eval/stream/DataSourceRewriterSuite.scala
- atlas-eval/src/test/scala/com/netflix/atlas/eval/stream/EvaluatorSuite.scala
- build.sbt
DataSource URIs are sent via HTTP (with retries) and if they incorporate namespace predicates, the service will rewrite them to route to the proper host, removing the namespace predicate.
> eval: add a rewrite module to handle queries with namespaces.

- atlas-core/src/main/scala/com/netflix/atlas/core/util/Strings.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/util/StringsSuite.scala
Add helper to encode designated special characters in a string using the unicode escape sequence (\uXXXX).
> core: add helper for escaping unicode chars

- atlas-core/src/main/scala/com/netflix/atlas/core/model/EventExpr.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/model/FilterExpr.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/model/MathExpr.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/model/Query.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/model/StatefulExpr.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/stacklang/Interpreter.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/model/QueryVocabularySuite.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/stacklang/InterpreterSuite.scala
Update stacklang parsing to allow comma and whitespace to be preserved by using unicode escape sequences.
> core: allow comma to be escaped for exprs

- atlas-pekko/src/main/resources/reference.conf
- atlas-pekko/src/main/scala/com/netflix/atlas/pekko/AccessLogger.scala
Update access logger so that settings for IPC logger can be managed via typesafe config.
> pekko: config settings for access logger

- atlas-core/src/main/scala/com/netflix/atlas/core/util/Step.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/util/StepSuite.scala
Update step rounding logic to allow for sub-second step sizes.
> core: support sub-second step sizes

- atlas-chart/src/main/scala/com/netflix/atlas/chart/JsonCodec.scala
- atlas-chart/src/test/scala/com/netflix/atlas/chart/JsonCodecSuite.scala
The old scala 2.12 code did not serialize the theme in the v2.json graph metadata. For Core, they're using Spark to emit data in V2 then parsing it with the latest Atlas code. This will fix the issue for them.
> chart: add default theme to JsonCodec parsing.

- atlas-core/src/main/scala/com/netflix/atlas/core/model/ItemId.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/model/ItemIdSuite.scala
- atlas-jmh/src/main/scala/com/netflix/atlas/core/model/ItemIdHashCode.scala
The id is generated from a hash function, typically SHA1 so we can just use a part of that for the hash code of the id object. Since data is sometimes partitioned and routed based on the most and least significant bits, we pick one of the middle bytes to reduce the liklihood of collisions.
Benchmarks show it is about 25% slower to access the hash code this way, but it does provide some memory savings and compute savings when creating an id instance since the murmur hash doesn't need to be computed.
> core: remove cached hash code for ItemId

- atlas-core/src/main/scala/com/netflix/atlas/core/model/MathExpr.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/db/TimeSeriesBufferSuite.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/model/PerStepSuite.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/model/TrendSuite.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/norm/RateValueFunctionSuite.scala
Add some tests and put in some patches to address minor issues with using sub-second step sizes. There is a known issue with percentiles operator that will be addressed in a follow up PR after some updates to spectator utility classes.
> core: fixes for sub-second step size

- atlas-core/src/main/scala/com/netflix/atlas/core/model/MathExpr.scala
Update percentiles operator to use double values directly rather than coverting to long.
> core: avoid long conversion for percentiles

- atlas-core/src/main/scala/com/netflix/atlas/core/model/DataExpr.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/model/EventExpr.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/model/Expr.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/model/FilterExpr.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/model/MathExpr.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/model/Query.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/model/StatefulExpr.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/model/StyleExpr.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/model/TraceQuery.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/stacklang/Interpreter.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/stacklang/StackItem.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/util/Strings.scala
- atlas-jmh/src/main/scala/com/netflix/atlas/core/stacklang/InterpreterEscape.scala
Creating a string from the expression can be a common operation when creating messages. This change reduces the overhead by allowing it to be written to an existing builder instance and reduce the amount of internal resizing and copies.
**Before**
```
Benchmark           Mode  Cnt         Score       Error  Units
withEscapes        thrpt   10    581,213.514 ± 4708.897  ops/s
withNoEscapes      thrpt   10    643,706.596 ± 9144.301  ops/s
```
**After**
```
Benchmark           Mode  Cnt         Score       Error  Units
withEscapes        thrpt   10    956,439.595 ±  5243.582  ops/s
withNoEscapes      thrpt   10  1,031,542.340 ± 25261.261  ops/s
```
> core: improve expr.toString performance

- atlas-eval/src/main/scala/com/netflix/atlas/eval/model/TimeSeriesMessage.scala
- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/FinalExprEval.scala
for large group by expressions it can be expensive to recompute the expression string for every output message. Precompute for all messages from a given expression.
> eval: precompute expression string

- atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/SubscriptionManager.scala
- atlas-lwcapi/src/test/scala/com/netflix/atlas/lwcapi/ExpressionApiSuite.scala
- atlas-lwcapi/src/test/scala/com/netflix/atlas/lwcapi/SubscriptionManagerSuite.scala
Now that we are off the legacy query index, refactor the update to modify the index with changes rather than recreate each time the subscription set changes.
> lwcapi: improve performance for index updates

- atlas-eval/src/main/resources/reference.conf
- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/EvaluatorImpl.scala
- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/FinalExprEval.scala
- atlas-eval/src/test/scala/com/netflix/atlas/eval/stream/FinalExprEvalSuite.scala
When running in streaming support disabling the no data messages for the expression. Some legacy use-cases may not account for them and fail.
> eval: add flag to disable no data messages

- atlas-core/src/main/scala/com/netflix/atlas/core/db/MemoryDatabase.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/index/BatchUpdateTagIndex.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/db/MemoryDatabaseSuite.scala
Support a filter that can be used to ensure only data matching the filter remains loaded. Can be useful to quickly respond if problematic data is reported.
> core: add filter to MemoryDatabase

- atlas-core/src/main/scala/com/netflix/atlas/core/db/BlockStoreItem.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/db/MemoryDatabase.scala
The block store included would not match the equality check so it wouldn't work as intended. The items will get deduped as part of the index update.
> core: remove interning for BlockStoreItem

- atlas-core/src/main/scala/com/netflix/atlas/core/model/MathExpr.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/model/PercentilesSuite.scala
In #1704 the approximation was updated to use doubles instead of longs. As part of that non-finite values were ignored. Before they would be treated as 0. By ignoring them a bad value could potentially be carried forward if it only occurred for a single interval.
> core: fix percentile approximation

- atlas-core/src/main/scala/com/netflix/atlas/core/model/MathExpr.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/model/PercentilesSuite.scala
The changes in #1706 have a bug for percentiles used after a group by where the query clause would get duplicated.
> core: fix expr string for :percentiles

- atlas-pekko/src/main/scala/com/netflix/atlas/pekko/ByteStringInputStream.scala
- atlas-pekko/src/main/scala/com/netflix/atlas/pekko/CustomDirectives.scala
- atlas-pekko/src/test/scala/com/netflix/atlas/pekko/ByteStringInputStreamSuite.scala
Update the ByteStringInputStream to add a helper method for creating the stream that automatically wraps with a GZIP input stream if the data is compressed.
> pekko: helper to decompress while streaming ByteString

- atlas-eval/src/main/scala/com/netflix/atlas/eval/model/LwcMessages.scala
- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/EvaluatorImpl.scala
- atlas-lwcapi/src/test/scala/com/netflix/atlas/lwcapi/SubscribeApiSuite.scala
There is a often quite a bit of redundancy. For a sample set of 40k expressions it reduced the message size from ~14MB to ~1MB.
> eval: compress subscription message

- atlas-core/src/main/scala/com/netflix/atlas/core/model/EventVocabulary.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/model/EventExamplesSuite.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/model/TraceExamplesSuite.scala
The example stack was not valid. Fix it and add tests for the examples on event and trace vocabularies.
> core: fix example for :table

- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/StreamContext.scala
- atlas-eval/src/test/scala/com/netflix/atlas/eval/stream/TestContext.scala
Uses have migrated to edda-uri.
> eval: remove legacy eureka-uri property

- atlas-lwc-events/src/main/scala/com/netflix/atlas/lwc/events/RemoteLwcEventClient.scala
- atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/EvaluateApi.scala
- atlas-lwcapi/src/test/scala/com/netflix/atlas/lwcapi/EvaluateApiSuite.scala
Update remote client to encode the samples and lwcapi to read them.
> lwc-events: encode samples associated with datapoint

- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/FinalExprEval.scala
For the value associated with sampled events, use the rate per step, i.e. raw count for that step interval, rather than the rate per second. This is more intuitive for users.
> eval: use rate per step for sample messages

- atlas-core/src/main/scala/com/netflix/atlas/core/util/Strings.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/util/StringsSuite.scala
Updates the date and range parsing to allow a unix timestamp value to be an absolute time anchor for the time parameters. This is mostly a convenience if generating the parameters via substitution, but there is a need to have some offset.
For now the ISO date time patterns do not support the offset behavior. The parsing is trickier because they already use `-` for the year-month-day as well as for time zone offsets.
> core: allow unix timestamp to be anchor time parameters

- atlas-lwc-events/src/main/scala/com/netflix/atlas/lwc/events/RemoteLwcEventClient.scala
In some cases we see serialization fail. Add a trace level log to help debug those that will output the toString value for the payload.
> lwc-events: add trace log for bad events payload

- atlas-json/src/main/scala/com/netflix/atlas/json/Json.scala
- atlas-json/src/test/scala/com/netflix/atlas/json/JsonSuite.scala
When using smile enable lenient UTF encoding. In some cases log strings can have invalid UTF characters that work for encoding as JSON, but fail surrogate checks with smile. The lenient encoding allows these to go through, but replaces the invalid characters with `\uFFFD`.
> json: enabled lenient UTF encoding

- atlas-core/src/main/scala/com/netflix/atlas/core/model/Query.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/model/QuerySuite.scala
- atlas-lwc-events/src/test/scala/com/netflix/atlas/lwc/events/LwcEventClientSuite.scala
Add `Query.matches` overload that takes a function to supply the tags. This can be used for cases like `LwcEvent` to do matching where the data structure for the tags may not be known.
> core: support query matching using tags function

- atlas-lwc-events/src/main/scala/com/netflix/atlas/lwc/events/AbstractLwcEventClient.scala
- atlas-lwc-events/src/main/scala/com/netflix/atlas/lwc/events/DatapointConverter.scala
- atlas-lwc-events/src/main/scala/com/netflix/atlas/lwc/events/DatapointEvent.scala
- atlas-lwc-events/src/main/scala/com/netflix/atlas/lwc/events/LwcEvent.scala
- atlas-lwc-events/src/test/scala/com/netflix/atlas/lwc/events/LwcEventDurationSuite.scala
- atlas-lwc-events/src/test/scala/com/netflix/atlas/lwc/events/LwcEventSuite.scala
Ensure that if the extractValue implementation for an event throws an exception, it will not impact processing other events. If the extract fails, then it will treat the value as `null`.
> lwc-events: guard against exception from extractValue

- atlas-eval/src/main/resources/reference.conf
- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/EvaluatorImpl.scala
Allow the pattern to be customized so secure option can be used for use-cases other than local testing.
> eval: make backend ws pattern configurable

- atlas-core/src/main/scala/com/netflix/atlas/core/index/RoaringTagIndex.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/index/RoaringTagIndexSuite.scala
For the roaring tag index there were some bugs resulting in incorrect matching if the value being compared was larger than the last element for a given tag. The offset position was for the last tag and so it would return an empty match set since the tag key didn't match.
> core: fix corner cases with less than comparison

- atlas-core/src/main/resources/reference.conf
Update reference config to permit the `nf.ns` dimension to be used on the denominator for custom averages. This ensures a consistent view when used on namespaced queries internally.
> core: allow nf.ns on custom average denominator

- atlas-core/src/main/scala/com/netflix/atlas/core/algorithm/OnlineRollingMean.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/algorithm/OnlineRollingSum.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/algorithm/RollingSumBuffer.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/algorithm/OnlineRollingMeanSuite.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/algorithm/OnlineRollingSumSuite.scala
Update rolling-sum and rolling-mean to better handle cases where there is a large value. Before a really large value compared to others would skew the sum and it would never fully recover since the sum is maintained incrementally. Now it will check if there is a big difference in the exponent and recompute from the buffer to recover.
> core: improve handling of large spikes for rolling-sum

- atlas-core/src/main/scala/com/netflix/atlas/core/index/LazyOrBitmap.java
- atlas-core/src/main/scala/com/netflix/atlas/core/index/RoaringTagIndex.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/index/TagIndexSuite.scala
Update RoaringTagIndex implementation to fix pagination of findItems for range and pattern clauses. Before the offset was being ignored for these query clauses. In common usage it often wouldn't be noticed because AND with an equal clause would result in the offset gettng applied via the conjunction.
Also updates range queries and patterns to use a lazy OR operation on the bitmap. In some of our benchmarks this improves the throughput by about 30%.
> core: fix pagination and lazily compute OR

- atlas-core/src/main/scala/com/netflix/atlas/core/model/StyleExpr.scala
When the legend is explicitly set, avoid computing the default label. In most cases we enable the simple legends option so there will be an explicit legend set on the expressions.
> eval: avoid computing default label

- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/TimeGrouped.scala
Access the wall time once for the batch pushed to the time group rather than accessing for each entry in the batch.
> eval: reuse wall time

- atlas-eval/src/main/scala/com/netflix/atlas/eval/model/AggrDatapoint.scala
For the GroupByAggregator optimize computing the datapoints. Use a List builder to avoid creation of iterators and the intermediate collections when doing flatMap and then converting back to a List. Since all aggregators that are part of a group should have a single element in the list, special case that path to avoid the need for a separate iterator.
> eval: optimize computing list of datapoints

- atlas-core/src/main/scala/com/netflix/atlas/core/algorithm/RollingSumBuffer.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/algorithm/OnlineRollingSumSuite.scala
In some cases when it falls back to summing the buffer, the sum will be set to NaN. In this case it will not recover until there is another fall back. Update it to use addNaN so that it will recover correctly when values start coming in again.
> core: fix rolling-sum with NaN data

- Makefile
JCenter is no longer around. Update to latest version and point to Maven Central.
> update URL for iep-launcher

- atlas-core/src/main/scala/com/netflix/atlas/core/model/EventExpr.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/model/FilterExpr.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/model/MathExpr.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/model/Query.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/model/StatefulExpr.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/model/TraceQuery.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/stacklang/Interpreter.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/model/QueryVocabularySuite.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/stacklang/InterpreterSuite.scala
Updates the escaping to support the beginning colon used for operations and the parenthesis used to indicate lists.
> core: support escaping colon and parenthesis

- atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/ExpressionApi.scala
Avoid creating byte array from ByteArrayOutputStream multiple times.
> lwcapi: reduce allocation overhead

- atlas-eval/src/main/scala/com/netflix/atlas/eval/model/LwcMessages.scala
- atlas-json/src/main/scala/com/netflix/atlas/json/Json.scala
Update to add a `newMapperBuilder` to get a builder for the caller to modify. Helps to phase out deprecation warnings when modifying the ObjectMapper.
> json: create builder instead of mapper

- atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/ExpressionApi.scala
Add timer to track the time taken to encode the expressions for the overall set and for clusters.
> lwcapi: track encoding time for expressions

- atlas-eval/src/main/scala/com/netflix/atlas/eval/graph/SimpleLegends.scala
- atlas-eval/src/test/scala/com/netflix/atlas/eval/graph/SimpleLegendsSuite.scala
Before it was the regex string which would escape characters that are special in regex like `.`. This was confusing to some users. Now it will handle prefix and contains matchers and just use the literal without escaping when constructing the legend.
> eval: update default legend for starts/contains

- atlas-core/src/main/scala/com/netflix/atlas/core/model/EvalContext.scala
- atlas-eval/src/main/scala/com/netflix/atlas/eval/graph/GraphConfig.scala
- atlas-eval/src/test/resources/graph-config-test.conf
- atlas-eval/src/test/scala/com/netflix/atlas/eval/graph/GraphConfigSuite.scala
- atlas-webapi/src/main/scala/com/netflix/atlas/webapi/FetchRequestSource.scala
- atlas-webapi/src/main/scala/com/netflix/atlas/webapi/GraphApi.scala
- atlas-webapi/src/main/scala/com/netflix/atlas/webapi/GraphRequestActor.scala
- atlas-webapi/src/main/scala/com/netflix/atlas/webapi/LocalDatabaseActor.scala
Updates the data response to provide a step size. This makes it possible for the data actor to indicate that the step size was changed from what was requested. This is useful in some contexts where the primary step may vary across the data sources.
> webapi: allow data actor to modify the step

- atlas-core/src/main/scala/com/netflix/atlas/core/model/MathVocabulary.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/model/MathAcrossStyleSuite.scala
With this change binary math operations can be used even if both sides have presentation settings. To avoid ambiguity the presentation settings will be stripped from both sides for the resulting expression.
> core: support binary ops with presentations settings

- atlas-core/src/main/scala/com/netflix/atlas/core/model/StyleVocabulary.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/model/MathAcrossStyleSuite.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/model/ModelExtractorsSuite.scala
Adds an operator that can be used to explicitly remove any presentation settings for a time series expression. This can be useful for taking an existing expression and resetting the style before reusing in other operations.
> core: add strip-style operator

- atlas-core/src/main/scala/com/netflix/atlas/core/model/StyleExpr.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/model/StyleExprSuite.scala
Updates the sed expressions for the legend to fallback to the tags if the variable is not present on the regex matcher. Since the substitution is outside the matcher, escape before appending to avoid spurious exceptions if using a `$` or `\` in the replacement value.
> core: update sed exprs to support tag vars

- atlas-lwcapi/src/main/resources/reference.conf
- atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/ExpressionApi.scala
- atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/SubscriptionManager.scala
- atlas-lwcapi/src/test/scala/com/netflix/atlas/lwcapi/ExpressionApiSuite.scala
When listing expressions for a cluster, the client will often ignore the publish step because it is covered by a bridge cluster. Add an option so we can disable listing those for a cluster to reduce the payload sizes.
Also fixes updates so that refreshing will not update the access time for the cache entry.
> lwcapi: add option to ignore publish step

- atlas-core/src/main/scala/com/netflix/atlas/core/model/DataVocabulary.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/model/StyleVocabularySuite.scala
This makes it behave more similarly to other unary operators.
> core: allow offset to be applied across style

- atlas-core/src/main/scala/com/netflix/atlas/core/model/MathVocabulary.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/model/StyleVocabularySuite.scala
Update the math aggr functions to behave consistently with unary math operators.
> core: allow math aggr across style

- atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/SubscribeApi.scala
- atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/SubscriptionManager.scala
- atlas-lwcapi/src/test/scala/com/netflix/atlas/lwcapi/SubscriptionManagerSuite.scala
Before it would happen after each update meaning the index update might happen more often than necessary.
> lwcapi: update query change flag after batch

- atlas-core/src/main/scala/com/netflix/atlas/core/util/Step.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/util/StepSuite.scala
- atlas-eval/src/main/resources/reference.conf
- atlas-eval/src/main/scala/com/netflix/atlas/eval/graph/DefaultSettings.scala
- atlas-eval/src/main/scala/com/netflix/atlas/eval/graph/GraphConfig.scala
- atlas-eval/src/test/resources/graph-config-test.conf
- atlas-eval/src/test/scala/com/netflix/atlas/eval/stream/TestContext.scala
When consolidating data, limit the set of allowed step sizes to those that evenly divide the underlying blocks or are even multiples of the block. Push down doesn't work correctly for step sizes that do not evenly divide the blocks.
> eval: choose allowed steps based on block size

- atlas-eval/src/main/resources/reference.conf
- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/DataSourceRewriter.scala
- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/EvaluatorImpl.scala
- atlas-eval/src/test/resources/application.conf
- atlas-eval/src/test/scala/com/netflix/atlas/eval/stream/DataSourceRewriterSuite.scala
- atlas-eval/src/test/scala/com/netflix/atlas/eval/stream/EvaluatorSuite.scala
- project/BuildSettings.scala
Add support for a simple config based mapping to allow for a generic namespace query layer with `ns` query param to rewrite to supported hosts. This replaces the http approach since it is a simple rewrite to avoid the risk of problems with that service impacting streaming execution of data.
> eval: support config based rewrite

- atlas-core/src/main/scala/com/netflix/atlas/core/util/Strings.scala
- atlas-lwc-events/src/main/scala/com/netflix/atlas/lwc/events/AbstractLwcEventClient.scala
- atlas-lwc-events/src/main/scala/com/netflix/atlas/lwc/events/DatapointConverter.scala
- atlas-lwc-events/src/main/scala/com/netflix/atlas/lwc/events/LwcEventClient.scala
- atlas-lwc-events/src/main/scala/com/netflix/atlas/lwc/events/LwcEventFilter.scala
- atlas-lwc-events/src/main/scala/com/netflix/atlas/lwc/events/RemoteLwcEventClient.scala
- atlas-lwc-events/src/main/scala/com/netflix/atlas/lwc/events/TypedLwcEventFilter.scala
- atlas-lwc-events/src/test/scala/com/netflix/atlas/lwc/events/DatapointConverterSuite.scala
- atlas-lwc-events/src/test/scala/com/netflix/atlas/lwc/events/LwcEventClientSuite.scala
- atlas-lwc-events/src/test/scala/com/netflix/atlas/lwc/events/RemoteLwcEventClientSuite.scala
- atlas-lwc-events/src/test/scala/com/netflix/atlas/lwc/events/TypedLwcEventFilterSuite.scala
- atlas-spring-lwc-events/src/main/scala/com/netflix/atlas/lwc/events/LwcEventConfiguration.scala
This can be used for some cases such as typed matching on some fields in the event. Helpers are provided for matching on durations, instants, long, and double.
> lwc-events: support post filter for matching events

- atlas-lwc-events/src/main/scala/com/netflix/atlas/lwc/events/DatapointConverter.scala
- atlas-lwc-events/src/main/scala/com/netflix/atlas/lwc/events/DatapointEvent.scala
- atlas-lwc-events/src/main/scala/com/netflix/atlas/lwc/events/LwcEvent.scala
- atlas-lwc-events/src/test/scala/com/netflix/atlas/lwc/events/DatapointConverterSuite.scala
- atlas-lwc-events/src/test/scala/com/netflix/atlas/lwc/events/LwcEventDurationSuite.scala
Always use a default value of 1 and avoid boxing the value to a `java.lang.Double`.
> lwc-events: avoid boxing for default value
