atlas-chart/src/main/scala/com/netflix/atlas/chart/Colors.scala
atlas-chart/src/test/scala/com/netflix/atlas/chart/GraphAssertions.scala
atlas-chart/src/test/scala/com/netflix/atlas/chart/PngImageSuite.scala
atlas-core/src/main/scala/com/netflix/atlas/core/db/TimeSeriesBuffer.scala
atlas-core/src/test/scala/com/netflix/atlas/core/db/TimeSeriesBufferSuite.scala
atlas-webapi/src/test/scala/com/netflix/atlas/webapi/GraphAssertions.scala
project/Build.scala
project/Dependencies.scala

Removes some of the simple uses of guava.
Not sure why, but something about the
TimeSeriesBuffer class triggers a
ClassNotFoundException with the
equalsverifier library:
```
[info]   Cause: java.lang.NoClassDefFoundError: nl/jqno/equalsverifier/internal/cglib/proxy/Factory
[info]   at java.lang.ClassLoader.defineClass1(Native Method)
[info]   at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
[info]   at sun.reflect.GeneratedMethodAccessor7.invoke(Unknown Source)
[info]   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[info]   at java.lang.reflect.Method.invoke(Method.java:483)
[info]   at nl.jqno.equalsverifier.internal.cglib.core.ReflectUtils.defineClass(ReflectUtils.java:384)
[info]   at …
```

reduce use of guava

---

atlas-chart/src/main/scala/com/netflix/atlas/chart/Rrd4jGraphEngine.scala
atlas-core/src/main/scala/com/netflix/atlas/core/model/TaggedItem.scala
atlas-core/src/main/scala/com/netflix/atlas/core/model/TimeSeries.scala
atlas-core/src/test/scala/com/netflix/atlas/core/model/TimeSeriesExprSuite.scala
atlas-webapi/src/main/scala/com/netflix/atlas/webapi/PublishApi.scala
atlas-webapi/src/test/scala/com/netflix/atlas/webapi/PublishApiSuite.scala

Supports legacy formats and field labels that are
still needed internally. It will likely be a long time
before we can fully deprecate and simplify those
paths.
Also has some to make it more efficient when working
with SmallHashMap values.

json codec for publish payload

---

atlas-chart/src/main/scala/com/netflix/atlas/chart/CommaSepGraphEngine.scala
atlas-chart/src/main/scala/com/netflix/atlas/chart/CsvGraphEngine.scala
atlas-chart/src/main/scala/com/netflix/atlas/chart/GraphEngine.scala
atlas-chart/src/main/scala/com/netflix/atlas/chart/JsonGraphEngine.scala
atlas-chart/src/main/scala/com/netflix/atlas/chart/Rrd4jGraphEngine.scala
atlas-chart/src/main/scala/com/netflix/atlas/chart/StatsJsonGraphEngine.scala
atlas-chart/src/main/scala/com/netflix/atlas/chart/TabSepGraphEngine.scala
atlas-webapi/src/main/resources/reference.conf
atlas-webapi/src/main/scala/com/netflix/atlas/webapi/ApiSettings.scala
atlas-webapi/src/main/scala/com/netflix/atlas/webapi/GraphApi.scala

For some legacy backward compatibility use-cases
internally we need to support a number of additional
formats. This can potentially be useful for others
that might want to provide a custom output format.
This change adds a config setting:
`atlas.webapi.graph.engines`
The value is a list of class names that implement the
GraphEngine trait. Another consideration we will
table for now is source compatibility between versions.
Internally we only try to maintain compatibility of the
webapi and make no guarantees about compatibility of
source built against the app.

allow formats for graph api to be configured

---

atlas-core/src/main/scala/com/netflix/atlas/core/model/FilterExpr.scala
atlas-core/src/main/scala/com/netflix/atlas/core/model/FilterVocabulary.scala
atlas-core/src/main/scala/com/netflix/atlas/core/model/StyleVocabulary.scala
atlas-core/src/test/scala/com/netflix/atlas/core/model/FilterExamplesSuite.scala
atlas-core/src/test/scala/com/netflix/atlas/core/model/TimeSeriesExprSuite.scala

Moving filter expressions from internal to OSS. This
also generalizes them a bit to work using an arbitrary
line.

filtering group by results

---

atlas-akka/src/main/scala/com/netflix/atlas/akka/ConfigApi.scala
atlas-akka/src/main/scala/com/netflix/atlas/akka/Paths.scala
atlas-akka/src/main/scala/com/netflix/atlas/akka/RequestHandlerActor.scala
atlas-akka/src/test/scala/com/netflix/atlas/akka/ConfigApiSuite.scala
atlas-aws/src/main/scala/com/netflix/atlas/aws/AwsClientFactory.scala
atlas-aws/src/test/scala/com/netflix/atlas/aws/AwsClientFactorySuite.scala
atlas-aws/src/test/scala/com/netflix/atlas/aws/DefaultAwsClientFactorySuite.scala
atlas-config/src/main/scala/com/netflix/atlas/config/ConfigManager.scala
atlas-config/src/test/scala/com/netflix/atlas/config/ConfigManagerSuite.scala
atlas-core/src/main/scala/com/netflix/atlas/core/db/Limits.scala
atlas-core/src/main/scala/com/netflix/atlas/core/db/MemoryDatabase.scala
atlas-core/src/main/scala/com/netflix/atlas/core/model/DefaultSettings.scala
atlas-webapi/src/main/scala/com/netflix/atlas/webapi/ApiSettings.scala
atlas-webapi/src/main/scala/com/netflix/atlas/webapi/Main.scala
atlas-webapi/src/main/scala/com/netflix/atlas/webapi/RequestId.scala
project/Build.scala

To make it easier to run the standalone jar in different
modes, this change allows additional config files to be
specified as command line arguments. Example:
```
$ java -jar atlas-standalone.jar c1.conf c2.conf
```

allow additional config files on command line

---

atlas-config/src/main/scala/com/netflix/atlas/config/ConfigManager.scala
atlas-config/src/test/scala/com/netflix/atlas/config/ConfigManagerSuite.scala
atlas-core/src/main/resources/reference.conf
atlas-core/src/main/scala/com/netflix/atlas/core/db/DataSet.scala
atlas-core/src/main/scala/com/netflix/atlas/core/db/MemoryDatabase.scala
atlas-core/src/main/scala/com/netflix/atlas/core/db/StaticDatabase.scala
atlas-webapi/src/main/resources/reference.conf
atlas-webapi/src/main/scala/com/netflix/atlas/webapi/ApiSettings.scala

Primary change is to re-resolve the config on
subsequent updates so vars can be updated. Note
that the reference conf files are resolved on
load so configs applied via update cannot change
a var in the reference conf.
Also removes duplicate step settings.

re-resolve config on update

---

atlas-akka/src/main/scala/com/netflix/atlas/akka/DiagnosticMessage.scala
atlas-core/src/main/resources/reference.conf
atlas-core/src/main/scala/com/netflix/atlas/core/db/MemoryDatabase.scala
atlas-webapi/src/main/resources/reference.conf
atlas-webapi/src/main/scala/com/netflix/atlas/webapi/LocalPublishActor.scala
atlas-webapi/src/main/scala/com/netflix/atlas/webapi/Main.scala
atlas-webapi/src/main/scala/com/netflix/atlas/webapi/PublishApi.scala
atlas-webapi/src/test/scala/com/netflix/atlas/webapi/PublishApiJsonSuite.scala
atlas-webapi/src/test/scala/com/netflix/atlas/webapi/PublishApiSuite.scala
conf/memory.conf
scripts/publish-test.sh

Includes sample conf and a test script to show
and example of how to send data. To try it:
```
$ cd $REPO_DIR
$ sbt one-jar
$ java -jar atlas-webapi/target/atlas-webapi-1.4.2-SNAPSHOT-one-jar.jar conf/memory.conf
```
From another terminal:
```
$ scripts/publish-test.sh
```

initial import of publish webapi

---

atlas-config/src/test/scala/com/netflix/atlas/config/ConfigManagerSuite.scala

```
[warn] /scratch/atlas/atlas-config/src/test/scala/com/netflix/atlas/config/ConfigManagerSuite.scala:46: possible missing interpolator: detected an interpolated expression
[warn]     ConfigManager.update(ConfigFactory.parseString("foo = ${user.home}"))
[warn]                                                    ^
[warn] /scratch/atlas/atlas-config/src/test/scala/com/netflix/atlas/config/ConfigManagerSuite.scala:56: possible missing interpolator: detected an interpolated expression
[warn]     ConfigManager.update(ConfigFactory.parseString("""
[warn]                                                    ^
[warn] two warnings found
```

fix warnings: possible missing interpolator

---

atlas-chart/src/main/scala/com/netflix/atlas/chart/CsvGraphEngine.scala

Previously it was using the default associated with
the ZonedDateTime.toString call:
```
2015-01-16T23:40:59-08:00[US/Pacific]   562916.031424
2015-01-16T23:41-08:00[US/Pacific]      575008.038403
2015-01-16T23:41:01-08:00[US/Pacific]   569944.697917
```
This change removes the zone ID from the output and
always includes the seconds in the timestamp.
```
2015-01-16T23:40:59-08:00   562916.031424
2015-01-16T23:41:00-08:00   575008.038403
2015-01-16T23:41:01-08:00   569944.697917
```
UTC will show a Z:
```
2015-01-17T07:40:59Z   562916.031424
2015-01-17T07:41:00Z   575008.038403
2015-01-17T07:41:01Z   569944.697917
```

more script friendly time format for txt output

---

atlas-webapi/src/main/resources/reference.conf
atlas-webapi/src/main/scala/com/netflix/atlas/webapi/ApiSettings.scala
atlas-webapi/src/main/scala/com/netflix/atlas/webapi/Main.scala
project/Build.scala
project/Dependencies.scala

When running on AWS instances it is convenient to
be able to open up a single port on the security group
to allow for JMX access. The option is disabled by
default since it tries to access the on instance
metadata service.

add option to restrict jmx port

---

atlas-akka/src/main/resources/reference.conf
atlas-akka/src/main/scala/com/netflix/atlas/akka/CustomDirectives.scala
atlas-akka/src/main/scala/com/netflix/atlas/akka/RequestHandlerActor.scala
atlas-akka/src/test/scala/com/netflix/atlas/akka/CustomDirectivesSuite.scala
project/Build.scala

When using the Netflix baseami we often rely on the
apache access.log and reporting. This change adds a
basic directive to generate an access log with basic
metrics when running standalone.

simple access log when running standalone

---

atlas-akka/src/test/scala/com/netflix/atlas/akka/ConfigApiSuite.scala
atlas-webapi/src/test/scala/com/netflix/atlas/webapi/TagsApiSuite.scala

There have been a few spurious failures due to
default 1s timeout being exceeded. Changing to 5s.

explicit timeout for tags suite

---

atlas-standalone/src/main/scala/com/netflix/atlas/standalone/Main.scala
atlas-webapi/src/main/resources/reference.conf
project/Build.scala
project/Dependencies.scala

Uses helper to manage a set of modules with governator. This
allows us to package with eureka, archaius, and karyon admin
for use internally.
It seems governator (guice probably) doesn't play well with
one-jar. When running standalone single jar we get:
```
WARNING: Could not load Finalizer in its own class loader. Loading Finalizer in the current class loader instead. As a result, you will not be able to garbage collect this class loader. To support reclaiming this class loader, either resolve the underlying issue, or move Google Collections to your system class path.
```
Need to look into the best option there. One-jar is also known
to prevent the ServiceLoader from finding providers.

support initializing a set of modules on startup

---

atlas-wiki/src/main/scala/com/netflix/atlas/wiki/GraphHelper.scala

When showing the uri for graphs in the wiki, the
stack operators now link to the reference.

docs: add links to reference page

---

Makefile
atlas-standalone/src/main/resources/META-INF/services/com.netflix.spectator.api.Registry
atlas-standalone/src/main/scala/com/netflix/atlas/standalone/Main.scala
project/Build.scala
project/Dependencies.scala
project/plugins.sbt

One-JAR's class loader is causing a problems with
other libraries.
```
WARNING: Could not load Finalizer in its own class loader. Loading Finalizer in the current class loader instead. As a result, you will not be able to garbage collect this class loader. To support reclaiming this class loader, either resolve the underlying issue, or move Google Collections to your system class path.
```
Might be related to: http://sourceforge.net/p/one-jar/bugs/74/
We mainly want a simple way to package so the end-user
can just run `java -jar atlas.jar ...`, so using a simple
launcher that creates a self-extracting jar. After
extracting it uses the built-in URLClassLoader for the
set of jars and invokes a specfied main class.
So far this seems to be working well. The standalone jar
is built with a …

remove one-jar usage

---

project/Build.scala
project/BuildSettings.scala

Nebula builds use jcenter by default. These are sync'd with
maven central, but that can take some time. This changes the
default resolver order to be:
1. local
2. jcenter
3. maven
4. jfrog snapshot repo
5. hack for custom rrd4j
We should try to remove the need for 5 in the future.

update resolver list

---

atlas-core/src/main/scala/com/netflix/atlas/core/model/DataVocabulary.scala
atlas-core/src/main/scala/com/netflix/atlas/core/model/FilterVocabulary.scala
atlas-core/src/main/scala/com/netflix/atlas/core/model/MathVocabulary.scala
atlas-core/src/main/scala/com/netflix/atlas/core/model/ModelExtractors.scala
atlas-core/src/main/scala/com/netflix/atlas/core/model/QueryVocabulary.scala
atlas-core/src/main/scala/com/netflix/atlas/core/model/StatefulVocabulary.scala
atlas-core/src/main/scala/com/netflix/atlas/core/model/StyleExpr.scala
atlas-core/src/main/scala/com/netflix/atlas/core/model/StyleVocabulary.scala
atlas-core/src/main/scala/com/netflix/atlas/core/stacklang/Extractors.scala
atlas-core/src/main/scala/com/netflix/atlas/core/stacklang/StandardVocabulary.scala
atlas-core/src/test/scala/com/netflix/atlas/core/model/TimeSeriesExprSuite.scala
atlas-core/src/test/scala/com/netflix/atlas/core/stacklang/NDropSuite.scala
atlas-core/src/test/scala/com/netflix/atlas/core/stacklang/NListSuite.scala
atlas-core/src/test/scala/com/netflix/atlas/core/stacklang/PickSuite.scala
atlas-core/src/test/scala/com/netflix/atlas/core/stacklang/RollSuite.scala
atlas-webapi/src/main/scala/com/netflix/atlas/webapi/GraphApi.scala
atlas-wiki/src/main/scala/com/netflix/atlas/wiki/Main.scala

Adds depth, pick, roll, nip, and tuck to make the
standard set more complete for those used to languages
like forth.
For convenience adds ndrop and nlist to select a subset
of the stack for those operations.

additional stack manipulation operators

---

atlas-wiki/src/main/scala/com/netflix/atlas/wiki/Main.scala

Also changes index to start at 0 to better match the
behavior of the index for pick and roll operations.

docs: arrange table so top of stack is top row

---

atlas-wiki/src/main/scala/com/netflix/atlas/wiki/GraphHelper.scala
atlas-wiki/src/main/scala/com/netflix/atlas/wiki/Main.scala

Pins the end time of the charts generated for the
stack language reference examples so we don't change
all images on every run.

pin the end time of ref charts

---

atlas-webapi/src/main/resources/reference.conf
atlas-webapi/src/main/scala/com/netflix/atlas/webapi/ApiSettings.scala
atlas-webapi/src/main/scala/com/netflix/atlas/webapi/GraphApi.scala
atlas-webapi/src/main/scala/com/netflix/atlas/webapi/GraphRequestActor.scala
atlas-webapi/src/main/scala/com/netflix/atlas/webapi/TagsApi.scala
atlas-webapi/src/main/scala/com/netflix/atlas/webapi/TagsRequestActor.scala
atlas-webapi/src/test/scala/com/netflix/atlas/webapi/ApiSettingsSuite.scala

There are a number of use-cases where it is convenient
to be able to change the vocabulary used by the graph
api via configuration. Main uses:
1. Experiments such as current work looking at better
support for percentiles. This could be true of other
extensions that likely will never be part of core.
2. Internal extensions that only make sense with our
infrastructure.
This change allows the vocabulary to get set with:
```
atlas.webapi.graph.vocabulary = "com.foo.CustomVocabulary"
```

add setting to customize vocabulary for graph api

---

atlas-aws/src/test/scala/com/netflix/atlas/aws/DefaultAwsClientFactorySuite.scala

These can take a while to run (~30s) and we don't update
the list all that often. They can be reenabled when the list
is changed or if it becomes a problem.

set the aws host resolve tests to ignore

---

atlas-core/src/main/scala/com/netflix/atlas/core/model/MathVocabulary.scala

Several users have suggested it would be easier for these
to appear just like a normal aggregate function. So they
will not work like:
```
name,foo,:eq,:dist-avg
```
Rather than:
```
:dist-avg,name,foo,:eq,:cq
```

change dist-avg and dist-stddev to work like aggr

---

atlas-core/src/main/scala/com/netflix/atlas/core/model/MathExpr.scala
atlas-core/src/main/scala/com/netflix/atlas/core/model/MathVocabulary.scala
atlas-core/src/test/scala/com/netflix/atlas/core/model/TimeSeriesExprSuite.scala

A common case for timers is to divide a `totalTime` stat
by the `count` stat. For intervals where there is no activity
both will have a value of 0. The previous behavior was to
treat this as NaN but we have frequently seen users confuse
that for a failure to report data since it leads to a spotty
chart with a lot of gaps. Now if both the numerator and
denominator are 0, then the value will be 0 to make it more
clear that 0 was explicitly reported and there was no activity
rather than a failure to report.
For uses that need the typical floating point behavior the
`:fdiv` operator can be used instead. It has also been fixed
os that it doesn't special case div by zero to be NaN instead
of Infinity.

report 0 for 0/0 on graph

---

atlas-webapi/src/main/scala/com/netflix/atlas/webapi/LocalPublishActor.scala

```
[warn] atlas-webapi/src/main/scala/com/netflix/atlas/webapi/LocalPublishActor.scala:71: match may not be exhaustive.
[warn] It would fail on the following input: Pass
[warn]     failures.foreach { case ValidationResult.Fail(error, _) =>
[warn]                      ^
[warn] one warning found
```

fix warning

---

atlas-chart/src/main/scala/com/netflix/atlas/chart/JsonGraphEngine.scala
atlas-chart/src/main/scala/com/netflix/atlas/chart/StdJsonGraphEngine.scala
atlas-chart/src/test/scala/com/netflix/atlas/chart/JsonGraphEngineSuite.scala
atlas-webapi/src/main/resources/reference.conf

The default json output of `/api/v1/graph` will output values
`NaN`, `Infinity`, and `-Infinity` as literals which is not
standard json and can cause issues with some parsers. To avoid
breaking backwards compatibility a new output format option,
`std.json`, is provided so a user can choose to get compatible
json. The use of non-standard json features will be avoided in
future APIs.

add output format for compatible json

---

scripts/publish-test.sh

At least on Ubuntu 14, /bin/sh doesn't appear to provide `$RANDOM`

Use bash for publish test

---

atlas-core/src/main/scala/com/netflix/atlas/core/model/DataVocabulary.scala
atlas-core/src/main/scala/com/netflix/atlas/core/model/FilterVocabulary.scala
atlas-core/src/main/scala/com/netflix/atlas/core/model/MathVocabulary.scala
atlas-core/src/main/scala/com/netflix/atlas/core/model/QueryVocabulary.scala
atlas-core/src/main/scala/com/netflix/atlas/core/model/StatefulVocabulary.scala
atlas-core/src/main/scala/com/netflix/atlas/core/stacklang/Interpreter.scala
atlas-core/src/main/scala/com/netflix/atlas/core/stacklang/StandardVocabulary.scala
atlas-core/src/main/scala/com/netflix/atlas/core/stacklang/Vocabulary.scala
atlas-core/src/test/scala/com/netflix/atlas/core/model/VocabularySuite.scala
atlas-wiki/src/main/resources/stacklang/Stack-Language-Reference.md
atlas-wiki/src/main/scala/com/netflix/atlas/wiki/GraphHelper.scala
atlas-wiki/src/main/scala/com/netflix/atlas/wiki/Main.scala
atlas-wiki/src/main/scala/com/netflix/atlas/wiki/Utils.scala

Updates the word links for graph expressions to point
to the actual page. See [examples](https://github.com/Netflix/atlas/wiki/Single-Line).
The make it easier to generate a link with just the name
the [reference page](https://github.com/Netflix/atlas/wiki/Stack-Language-Reference)
was updated with an alphabetical list showing the variants.
Not addressed in this PR, but updating the jmh plugin to
0.1.15 breaks the publish-wiki task in the makefile. The
first problem is the working directory changes to be the
atlas-wiki project dir. Fixing that leads to strange exception
when trying to run:
```
info] [init] error: error while loading Object, Missing dependency 'object scala in compiler mirror', required by /Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre/lib/rt.jar(java/l …
```

fix links for expressions in wiki

---

atlas-akka/src/main/scala/com/netflix/atlas/akka/WebServer.scala
atlas-standalone/src/main/scala/com/netflix/atlas/standalone/Main.scala

When there was a bind failure the process would stay
up in a bad state. This change blocks on the service
start to ensure better integration with eureka status
and exits if there is a failure with the guice
initialization. The bouncing process can then easily
be tracked with the process restart counter in the
daemontools run script.
Tested bind failure with address already in use:
```
$ /usr/bin/nc -6 -v -l ::0 7101
```

ensure server shutsdown on bind failure

---

Makefile

Use ssh for publish-wiki task to make it easier with
2FA enabled.

fix #107, use ssh for publish-wiki

---

atlas-core/src/main/scala/com/netflix/atlas/core/db/MemoryDatabase.scala
atlas-core/src/main/scala/com/netflix/atlas/core/model/DataExpr.scala
atlas-core/src/main/scala/com/netflix/atlas/core/model/Query.scala
atlas-core/src/test/scala/com/netflix/atlas/core/db/MemoryDatabaseSuite.scala
atlas-webapi/src/main/scala/com/netflix/atlas/webapi/GraphRequestActor.scala

In the past this wasn't always true, but we will now
handle this in the query aggregation layer.
This change also adds some additional test-cases to
boost confidence for refactoring/merging a few more
internal components.
The tag generated labels don't wind up being empty
very often in practice, but it does happen. For
aggregates this change also defaults to just using
an expression summary on the labels. Bigger win will
be if we can finally stop aggregating tag maps. Looks
like that still breaks a few uses, but may be able
to clean up in one of the upcoming deprecation cycles.

require query step is >= db step

---

atlas-akka/src/main/resources/reference.conf
atlas-akka/src/main/scala/com/netflix/atlas/akka/WebServer.scala

In some cases during app startup we'll see a GC pause
or other behavior during warmup that can cause the
1s value specified before to cause problems.

allow bind timeout to be configured

---

atlas-core/src/main/scala/com/netflix/atlas/core/db/MemoryDatabase.scala
atlas-core/src/main/scala/com/netflix/atlas/core/model/DataExpr.scala
atlas-core/src/main/scala/com/netflix/atlas/core/model/Query.scala
atlas-core/src/test/scala/com/netflix/atlas/core/db/MemoryDatabaseSuite.scala
atlas-webapi/src/main/scala/com/netflix/atlas/webapi/GraphRequestActor.scala

The query was getting re-evaluated against the aggregated
tags causing false no data responses. The no data response
was happening for queries that had multiple matches for a
query clause and thus the aggregated tag map would be missing
a value for that key.
This was inadvertantly fixed in commit 8ce42d29 for the
master branch along with some other cleanup. This patch
is back porting that change to the v1.4.x branch.

fix #157, queries reevaluated on aggregate

---

atlas-core/src/main/scala/com/netflix/atlas/core/model/DataExpr.scala
atlas-core/src/test/scala/com/netflix/atlas/core/db/MemoryDatabaseSuite.scala

Fixes a regression introduced in the previous
commit. The offset if non-zero should be included
in the default label.
Conflicts:
atlas-core/src/main/scala/com/netflix/atlas/core/model/DataExpr.scala
atlas-core/src/test/scala/com/netflix/atlas/core/db/MemoryDatabaseSuite.scala

missing offset on default label

---

atlas-core/src/main/scala/com/netflix/atlas/core/stacklang/Interpreter.scala
atlas-webapi/src/main/scala/com/netflix/atlas/webapi/ExprApi.scala
atlas-webapi/src/test/scala/com/netflix/atlas/webapi/ExprApiSuite.scala

Moving in from internal extensions. For now the
values just get mapped to strings to avoid the
legacy codec classes.

api to debug/validate expressions

---

atlas-core/src/main/scala/com/netflix/atlas/core/model/StatefulExpr.scala
atlas-core/src/test/scala/com/netflix/atlas/core/model/DerivativeSuite.scala
atlas-core/src/test/scala/com/netflix/atlas/core/model/IntegralSuite.scala
atlas-core/src/test/scala/com/netflix/atlas/core/model/TimeSeriesExprSuite.scala

For lines that started reporting in the middle of a
chart the integral would report NaN all the way through.
The NaN values will now get treated as 0 if an actual
value is encountered.

use addNaN for integral

---

atlas-core/src/main/scala/com/netflix/atlas/core/model/DataExpr.scala
atlas-core/src/main/scala/com/netflix/atlas/core/util/Strings.scala
atlas-jmh/src/main/scala/com/netflix/atlas/core/util/StringSub.scala

Tuning to reduce the number of allocations for batch
operations with many large group by. Main source was
the buffer resizes generating the key and additional
copies getting created to trim for the default label.
Also replaces the regex used for variable substition
since it was the second biggest contributor.

reduce allocations for group by and substitutions

---

atlas-core/src/main/scala/com/netflix/atlas/core/model/MathVocabulary.scala

There were some questions about what the `f` meant.
Updated the docs to better describe the behavior and
make it clear they provide floating point behavior
where some of the others special case some operations
to be more appropriate for visualization.

update docs for f* operators

---

atlas-chart/src/main/resources/reference.conf
atlas-chart/src/main/scala/com/netflix/atlas/chart/DefaultGraphEngine.scala

Adds a block in the chart config to allow for rendering hints
such as antialiasing to be specified.

allow renderning hints to be setup in config

---

atlas-core/src/main/scala/com/netflix/atlas/core/model/StyleVocabulary.scala

```
[warn] ./atlas-core/src/main/scala/com/netflix/atlas/core/model/StyleVocabulary.scala:115: possible missing interpolator: detected interpolated identifier `$name`
[warn]     override def examples: List[String] = List("name,sps,:eq,:sum,(,name,),:by,$name")
[warn]                                                ^
[warn] one warning found
```

fix warning about possible interpolation error

---

atlas-webapi/src/main/scala/com/netflix/atlas/webapi/GraphApi.scala
atlas-webapi/src/test/scala/com/netflix/atlas/webapi/GraphUriSuite.scala

If the URI contains title or ylabel values that are set
to an empty string it is currently returning an error during
rendering:
```
IllegalArgumentException: Can't add attribute to 0-length text.
```
With this change an empty string for those values will be
the same as not having them set.

treat empty title and ylabel params as not set

---

atlas-core/src/main/scala/com/netflix/atlas/core/model/StyleVocabulary.scala
atlas-core/src/test/scala/com/netflix/atlas/core/model/StyleVocabularySuite.scala

Before `:alpha` would only modify the alpha setting for
colors selected from the palette. If an explicit color
was used the alpha setting from the color would always
get chosen. Now an alpha setting that comes after a color
in the expression will override the alpha setting for
that color.

allow alpha to modify explicit color

---

atlas-core/src/main/scala/com/netflix/atlas/core/model/TagKey.scala
atlas-core/src/test/scala/com/netflix/atlas/core/validation/NonStandardKeyRuleSuite.scala

There is increasing interest in have a more common tagging
scheme for hadoop, spark, mantis, etc. All of these have
a notion of a job which gets broken down into a set of tasks.

add nf.job and nf.task keys

---

atlas-core/src/main/scala/com/netflix/atlas/core/model/ModelExtractors.scala
atlas-core/src/test/scala/com/netflix/atlas/core/model/ModelExtractorsSuite.scala

If the string was an invalid duration the `DurationType` matcher
was throwing:
```
java.lang.IllegalArgumentException: invalid period sps
at com.netflix.atlas.core.util.Strings$.parseDuration(Strings.scala:397)
at com.netflix.atlas.core.model.ModelExtractors$DurationType$.unapply(ModelExtractors.scala:29)
```

fix invalid period exception for duration match

---

atlas-wiki/src/main/resources/Graph.md
atlas-wiki/src/main/resources/Time-Parameters.md
atlas-wiki/src/main/scala/com/netflix/atlas/wiki/Main.scala
atlas-wiki/src/main/scala/com/netflix/atlas/wiki/pages/TimeZones.scala

Provides a more detailed overview of the options allowed
on time parameters. Also adds a simple reference page on
the time zones mainly to provide a clear reference showing
how the the short display name used for the label on multi
timezone graphs correspond to ids. There doesn't seem to
be a widely agreed on format for the short names. Still
need to find the source the jdk uses.

add more docs around time parameters

---

atlas-core/src/main/scala/com/netflix/atlas/core/db/MemoryDatabase.scala
atlas-webapi/src/test/scala/com/netflix/atlas/webapi/GraphApiMemDbSuite.scala

For simple aggregates where nothing matches the query.
This ensures that binary operations that combine results
will work as expected when one side of the expression
does not have data for a given window.

use no data line for aggregates

---

atlas-core/src/main/scala/com/netflix/atlas/core/model/MathVocabulary.scala

When using a constant on the stack it will get automatically
converted to a TimeSeriesExpr when the graph is rendered. So
if I have something like:
```
name,sps,:eq,:sum,$name,:legend,42
```
It will work for graph rendering. However, if using `:cq` to
append a query restriction with `:each`, e.g.:
```
name,sps,:eq,:sum,$name,:legend,42,:list,(,app,foo,:eq,:cq,),:each
```
It will fail because 42 is not an Expr. Having `:cq` coerce
to an expression is not desirable because it would change
the type and could break existing queries that apply
additional operations.
With this change `:cq` will ignore values it doesn't understand
and leave them on the stack unmodified.

update cq to ignore values that are not understood

---

atlas-core/src/main/scala/com/netflix/atlas/core/model/DataExpr.scala
atlas-core/src/test/scala/com/netflix/atlas/core/model/TimeSeriesExprSuite.scala

Avoids getting entries with NaN values for data
that doesn't match the query. In most cases this
wouldn't be an issue since the data was pre-filtered
based on the query before evaluation. This change
makes it more convenient when doing an eval with
an arbitrary data set.

filter before grouping with eval helper

---

atlas-core/src/main/scala/com/netflix/atlas/core/model/StatefulExpr.scala

If an expression is used across multiple threads, then
the state for the OnlineDes operation would get corrupted.
This change limits the scope to the method.

limit scope of des state

---

atlas-core/src/main/scala/com/netflix/atlas/core/model/Expr.scala
atlas-core/src/test/scala/com/netflix/atlas/core/model/ExprRewriteSuite.scala

If the productArity is 0 we cannot change instance so
return the existing class. A common case where the arity
is 0 are case objects. If they go through the product
case it causes duplicate instances of the objects to get
created leading to strange failures in other places.

rewrite can cause duplicate case objects

---

atlas-core/src/main/scala/com/netflix/atlas/core/model/StatefulExpr.scala
atlas-core/src/main/scala/com/netflix/atlas/core/model/StatefulVocabulary.scala

The base operator was called `:sliding-des` and all
other variants were `:sdes-*`. With this change `:sdes`
is used consistently for sliding DES operations.
The shorter form was generally preferred because it
makes it much easier to switch between `:des` and `:sdes`
by just changing a single character. When experimenting
and comparing the results of both this is quite handy.

make naming of sdes operations consistent

---

atlas-akka/src/main/resources/reference.conf
atlas-akka/src/main/scala/com/netflix/atlas/akka/StaticPages.scala
atlas-akka/src/test/scala/com/netflix/atlas/akka/StaticPagesSuite.scala

Adds two configuration options for the StaticPages webapi:
1. `atlas.akka.static.default-page`: configures the default
page to redirect to when the user accesses `/` on the
server.
2. `atlas.akka.static.single-page-prefixes`: configures zero
or more prefixes that map to a single resource. This is for
single page apps where the javascript should interpret the
rest of the path.

configure prefixes for single page apps

---

atlas-wiki/src/main/resources/Presentations.md
atlas-wiki/src/main/resources/_Sidebar.md

Adds a page to the wiki with links to various presentations
on Atlas or related tooling used at Netflix.

docs: add links to presentations

---

atlas-akka/src/main/scala/com/netflix/atlas/akka/RequestHandlerActor.scala
atlas-akka/src/test/scala/com/netflix/atlas/akka/TestApi.scala

Adds a default exception handler for the routes added
with webapi. Helps to avoid confusing issues if an api
didn't add in a custom handler.

add default exception handler

---

atlas-akka/src/main/scala/com/netflix/atlas/akka/DiagnosticMessage.scala

JsonProcessingException is more generic and covers the
current JsonParseException as well as the fairly common
JsonMappingException that occurs when databind is used
to read the data.

default JsonProcessingException to BadRequest

---

atlas-core/src/main/scala/com/netflix/atlas/core/model/DataVocabulary.scala
atlas-core/src/main/scala/com/netflix/atlas/core/model/StatefulVocabulary.scala
atlas-core/src/main/scala/com/netflix/atlas/core/stacklang/StandardVocabulary.scala

For some of the new operations indicate the version they
were added in to reduce confusion.

docs: indicate version for new operations

---

atlas-core/src/main/scala/com/netflix/atlas/core/index/QueryIndex.scala
atlas-core/src/test/scala/com/netflix/atlas/core/index/QueryIndexSuite.scala
atlas-jmh/src/main/scala/com/netflix/atlas/core/index/QueryIndexMatching.scala

The current indexes allow us to quickly check a query
against many tag sets. For some use-cases, in particular,
stream processing, we need to check a tag set against
many queries.
The specific use-case is inline alert processing. Currently
in the main environment there are around 17k alert expressions
used for alerts. Decomposing those into individual queries
we get around 33k queries. With a quick test of comparing
a real payload of 5000 datapoints to find matches within the
alert query set takes around 6.2s using a naive loop. This
query index takes around 6ms.
We'll likely need to do some further optimization to reduce
the number of allocations when doing the match, but current
testing shows it to be good enough to include in a snapshot
for more experimentation.

index for efficiently matching many queries

---

project/Bintray.scala
project/BuildSettings.scala

Due to some historical baggage, it is a pain to get the
artifacts into jcenter with the current com.netflix.atlas
groupId. This changes the id to add a version as I couldn't
come up with something better. This may also be useful in
the future to allow side by side import of a v2 version.

update maven groupId

---

atlas-core/src/main/scala/com/netflix/atlas/core/model/DataExpr.scala
atlas-core/src/main/scala/com/netflix/atlas/core/model/MathExpr.scala
atlas-core/src/main/scala/com/netflix/atlas/core/model/MathVocabulary.scala
atlas-core/src/test/scala/com/netflix/atlas/core/model/MathGroupBySuite.scala

Supports multi-level group by operation. Main use-case
is different aggregates, e.g., the maximum average
cpu for an asg within a cluster:
```
name,ssCpuUser,:eq,:avg,(,nf.cluster,nf.asg,),:by,
:max,(,nf.cluster,),:by
```

multi-level group by

---

atlas-akka/src/main/scala/com/netflix/atlas/akka/RequestHandlerActor.scala
atlas-akka/src/test/scala/com/netflix/atlas/akka/RequestHandlerActorSuite.scala

Now shows the 404 NotFound rather than an exception about
route rejection in the logs.

fixes #266 server log is confusing for 404s

---

atlas-chart/src/main/scala/com/netflix/atlas/chart/model/GraphDef.scala
atlas-webapi/src/main/scala/com/netflix/atlas/webapi/GraphApi.scala

The `font_size` param is a legacy setting that hasn't
worked in years. It isn't really appropriate now as
several different font sizes are used and dynamic sizing
would need to be thoughout to ensure it still works well
with the layouts.

remove unused query param

---

atlas-wiki/src/main/resources/Graph.md
atlas-wiki/src/main/resources/Home.md
atlas-wiki/src/main/resources/examples/Graph-Layout.md
atlas-wiki/src/main/scala/com/netflix/atlas/wiki/GraphHelper.scala

Several users complained that anchor links were
unreliable. This seems to mostly be chrome scrolling
before images have completed loading. This changes
all auto-generated images to have exact sizes as
well as manually updating some of the static images.
A quick test shows the github wiki will restrict
the max-width so there is no horizontal scrolling
if the actual width is wider than the wiki.
So far in my tests the anchor links work reliably
now.

docs: use exact sizes for images

---

Makefile
atlas-standalone/src/main/scala/com/netflix/atlas/standalone/ImageDiff.scala

Makes the image diff utility used for tests available
as a command line tool. Mainly for scripting some
comparisons.

add command line tool for image diff

---

atlas-core/src/main/scala/com/netflix/atlas/core/model/MathExpr.scala
atlas-core/src/main/scala/com/netflix/atlas/core/model/MathVocabulary.scala
atlas-core/src/main/scala/com/netflix/atlas/core/model/ModelExtractors.scala
atlas-core/src/main/scala/com/netflix/atlas/core/model/TagKey.scala
atlas-core/src/test/scala/com/netflix/atlas/core/model/PercentilesSuite.scala
project/Dependencies.scala

Adds a `:percentiles` helper to compute estimated percentiles
for spectator PercentileTimer and PercentileDistributionSummary.
These use a precomputed set of buckets that partition the range
of non-negative long values to allow for arbitrary slicing and
dicing based on the dimensions and still get a reasonable
approximation of percentiles.
This approach is less accurate than alternatives like t-Digest,
but more efficent and practical for our use-cases.
It is used just after the data function which should be a sum
or group by:
```
name,requestLatency,:eq,(,50,90,),:percentiles
name,requestLatency,:eq,(,nf.cluster,),:by,(,50,90,),:percentiles
```
The output will be one line per input per requested percentile.
There is also a helper, `:median` that is just short hand for …

add :percentiles and :median

---

atlas-core/src/main/scala/com/netflix/atlas/core/index/QueryIndex.scala
atlas-core/src/test/scala/com/netflix/atlas/core/index/QueryIndexSuite.scala

Allow the entry type to vary so it is easier to create the index
for any entry rather than just those with a value type of Query.

make QueryIndex.create more generic

---

atlas-chart/src/main/scala/com/netflix/atlas/chart/CsvGraphEngine.scala
atlas-chart/src/main/scala/com/netflix/atlas/chart/JsonCodec.scala
atlas-chart/src/main/scala/com/netflix/atlas/chart/JsonGraphEngine.scala
atlas-chart/src/main/scala/com/netflix/atlas/chart/PngGraphEngine.scala
atlas-chart/src/main/scala/com/netflix/atlas/chart/StatsJsonGraphEngine.scala
atlas-chart/src/main/scala/com/netflix/atlas/chart/V2JsonGraphEngine.scala
atlas-chart/src/main/scala/com/netflix/atlas/chart/model/GraphDef.scala
atlas-chart/src/main/scala/com/netflix/atlas/chart/model/PlotBound.scala
atlas-chart/src/test/scala/com/netflix/atlas/chart/JsonGraphEngineSuite.scala
atlas-chart/src/test/scala/com/netflix/atlas/chart/PngGraphEngineSuite.scala
atlas-json/src/main/scala/com/netflix/atlas/json/Json.scala
atlas-json/src/main/scala/com/netflix/atlas/json/JsonParserHelper.scala
atlas-json/src/main/scala/com/netflix/atlas/json/JsonSupport.scala
atlas-webapi/src/main/resources/reference.conf

**The format is not final yet and may still change in
incompatible ways.**
Adds an experimental JSON output format that includes all
metadata so we can precisely detect presentation settings
if using external rendering. This is becoming more common
with various javascript libraries and there is a desire
to accurately capture user-intent for palettes, stack vs
area, etc.
It was a bit difficult to shoehorn this into existing
formats and there are a number of short comings so we'll
keep this to the side for now to get more experience with
the new format.

add experimental output format with all metadata

---

project/Dependencies.scala

Adds support for g2.8xlarge type.

update to aws-java-sdk 1.10.50

---

atlas-core/src/main/scala/com/netflix/atlas/core/model/MathExpr.scala
atlas-core/src/test/scala/com/netflix/atlas/core/model/TimeSeriesExprSuite.scala

When using the math aggregate on an empty group by result
it an exception was being thrown:
```
requirement failed: must have 1 or more time series to perform
aggregation
```
Example: `:false,(,name,),:by,4,:div,:sum`
It will now return an empty result in the same way that
`:false,(,name,),:by` does.

fix aggregation failure for empty by

---

atlas-core/src/main/scala/com/netflix/atlas/core/util/PngImage.scala
atlas-core/src/test/scala/com/netflix/atlas/core/util/PngImageSuite.scala

For some use-cases we may have unicode characters in the text
fields. This change switches the metadata fields to get encoded
as iTXt fields instead of tEXt. For more information see:
http://www.libpng.org/pub/png/spec/1.2/PNG-Chunks.html#C.iTXt

use internationalized text fields for png metadata

---

atlas-chart/src/main/scala/com/netflix/atlas/chart/PngGraphEngine.scala
atlas-chart/src/main/scala/com/netflix/atlas/chart/model/GraphDef.scala
atlas-webapi/src/main/resources/reference.conf
atlas-webapi/src/main/scala/com/netflix/atlas/webapi/ApiSettings.scala
atlas-webapi/src/main/scala/com/netflix/atlas/webapi/GraphApi.scala

Adds an option to have the image url encoded as part of the text
metadata on the image. This can be useful for debugging and in
some cases tooling that needs to figure out how the image was
derived.

encode graph url as part of image metadata

---

atlas-wiki/src/main/resources/Getting-Started.md

Some internal users found the getting started page confusing
as they don't need to run Atlas, just use it. We need to do
some further cleanup of how the docs flow, but for now this
adds a quick note at the top with some links to other common
references.

docs: add note on getting started page

---

atlas-webapi/src/main/resources/reference.conf
atlas-webapi/src/main/scala/com/netflix/atlas/webapi/ApiSettings.scala
atlas-webapi/src/main/scala/com/netflix/atlas/webapi/ExprApi.scala
atlas-webapi/src/test/scala/com/netflix/atlas/webapi/ExprApiSuite.scala

This adds some additional API endpoints for manipulating the
expressions. Some of these need some further work, but are
minimally usable now and merging should make it easier to
get additional feedback form ui team.
* `/api/v1/expr` is still works and is an alias for the
`/api/v1/expr/debug` endpoint.
* `/api/v1/expr/debug` executes an expression step by step and
is frequently used for helping to debug problems with an
expression.
* `/api/v1/expr/normalize` simplifies an expression and expands
all stack manipulation operations.
* `api/v1/expr/complete` provides a list of possible commands
given a current expression.

initial merge of additional expr utilities

---

atlas-core/src/main/scala/com/netflix/atlas/core/model/StatefulVocabulary.scala
atlas-wiki/src/main/resources/examples/Anonymization.md
atlas-wiki/src/main/resources/examples/Axis-Bounds.md
atlas-wiki/src/main/resources/examples/Axis-Scale.md
atlas-wiki/src/main/resources/examples/Basics.md
atlas-wiki/src/main/resources/examples/Color-Palettes.md
atlas-wiki/src/main/resources/examples/Examples.md
atlas-wiki/src/main/resources/examples/Graph-Layout.md
atlas-wiki/src/main/resources/examples/Legends.md
atlas-wiki/src/main/resources/examples/Line-Attributes.md
atlas-wiki/src/main/resources/examples/Line-Colors.md
atlas-wiki/src/main/resources/examples/Line-Styles.md
atlas-wiki/src/main/resources/examples/Multi-Y.md
atlas-wiki/src/main/resources/examples/Output-Formats.md
atlas-wiki/src/main/resources/examples/Stack.md
atlas-wiki/src/main/resources/examples/Time-Shift.md
atlas-wiki/src/main/resources/examples/Time-Zone.md
atlas-wiki/src/main/resources/examples/Vision.md
atlas-wiki/src/main/resources/examples/_Sidebar.md
atlas-wiki/src/main/scala/com/netflix/atlas/wiki/Main.scala
atlas-wiki/src/main/scala/com/netflix/atlas/wiki/pages/StackLanguageReference.scala

Breaks out the sidebar for each vocabulary to
make the sidebar shorter and only show the expanded
list for that category.

docs: simplify sidebar for reference page

---

atlas-json/src/test/scala/com/netflix/atlas/json/JsonSuite.scala
atlas-json/src/test/scala/com/netflix/atlas/json/ObjWithLambda.java
project/Dependencies.scala

When using the Json helper for classes that contain a
lambda there was an ArrayIndexOutOfBoundsException
coming from paranamer shadowed into jackson. See test
case for more details on the error.
This bumps to jackson 2.7.2 which uses a newer shaded
version of paranamer.

fix out of bounds exception for java8 classes

---

atlas-chart/src/test/scala/com/netflix/atlas/chart/PngGraphEngineSuite.scala
atlas-test/src/main/scala/com/netflix/atlas/test/SrcPath.scala
atlas-webapi/src/test/scala/com/netflix/atlas/webapi/GraphApiSuite.scala

The working directory changes to the sub-project when the
tests are forked. For the image tests this is used to
determine the source path so that if the flag is enabled
the diffs can be blessed to update the golden files.

fix path when test are run with being forked

---

atlas-core/src/test/scala/com/netflix/atlas/core/db/TimeSeriesBufferSuite.scala
project/Build.scala

Tests are no longer forked by default. That was done
as a workaround for an issue with equalsverifier, but
more recently there is another workaround using prefab
values:
https://groups.google.com/forum/#!topic/equalsverifier/R5MWUGVx-C8
The hope is that this will avoid some transient failures
with travis builds. See #322 for more details.

disable forking tests

---

atlas-core/src/main/scala/com/netflix/atlas/core/util/Strings.scala
atlas-core/src/test/scala/com/netflix/atlas/core/util/StringsSuite.scala

Allow start/end time params to parse ISO timestamps
with millis. Examples:
```
2012-02-01T04:05:06.123
2012-02-01T04:05:06.123Z
2012-02-01T04:05:06.123-03:00
```

allow iso timestamps with millis

---

atlas-json/src/main/scala/com/netflix/atlas/json/Json.scala

Allow the cached decoder to be used for cases where we
already have the parser instance.

make decode(JsonParser) public

---

atlas-akka/src/main/resources/reference.conf
atlas-akka/src/main/scala/com/netflix/atlas/akka/HealthcheckApi.scala
atlas-akka/src/main/scala/com/netflix/atlas/akka/RequestHandlerActor.scala
atlas-akka/src/main/scala/com/netflix/atlas/akka/WebServer.scala
atlas-akka/src/test/scala/com/netflix/atlas/akka/HealthcheckApiSuite.scala
atlas-akka/src/test/scala/com/netflix/atlas/akka/RequestHandlerActorSuite.scala
atlas-standalone/src/main/scala/com/netflix/atlas/standalone/Main.scala
atlas-standalone/src/main/scala/com/netflix/atlas/standalone/WebServerProvider.scala
atlas-standalone/src/test/scala/com/netflix/atlas/standalone/MainSuite.scala
project/Build.scala
project/Dependencies.scala

Previously the `/healthcheck` endpoint provided here always
returned 200 and was mostly used for debugging. This is now
`/ok`. The `/healthcheck` endpoint now indicates the service
health based on the ServiceManager so it should be usable
as a load balancer healthcheck endpoint.
With this change we shouldn't need a separate internal
healthcheck endpoint registered for use with the load
balancers and monitoring.

default /healthcheck based on ServiceManager

---

atlas-akka/src/main/scala/com/netflix/atlas/akka/HealthcheckApi.scala
atlas-akka/src/test/scala/com/netflix/atlas/akka/HealthcheckApiSuite.scala

The status was being chosen when the route was created
instead of when the healthcheck endpoint was being
called.

fix bug with status when the route is created

---

atlas-json/src/main/scala/com/netflix/atlas/json/Json.scala

Allow additional modules to be registered with the default
ObjectMappers used by the Json utility.
cc @codyrioux

additional modules for ObjectMapper

---

atlas-core/src/main/scala/com/netflix/atlas/core/model/StyleVocabulary.scala
atlas-core/src/test/scala/com/netflix/atlas/core/model/TimeSeriesExprSuite.scala

For some tooling it is often convenient to be able
to append a filter after a legend or other presentation
settings have been applied to an expression with a
group by.

add override to allow filter after legend

---

atlas-wiki/src/main/resources/application.conf

Limit the endpoints used on the wiki script to
just the tags and graph endpoints that are needed.

limit endpoints for wiki script

---

atlas-wiki/src/main/scala/com/netflix/atlas/wiki/Main.scala
atlas-wiki/src/main/scala/com/netflix/atlas/wiki/Page.scala

Generate search index json file for the wiki
that can be consumed easily with lunr. Format
is similar to index created by mkdocs, e.g.:
https://netflix.github.io/spectator/en/latest/mkdocs/search_index.json

docs: create search index for wiki

---

project/Dependencies.scala

Fixes issue with 0 values being counted as
part of the negative_latency bucket and tagging
of serviceName on AWS metric collector.

spectator 0.37.0

---

atlas-core/src/main/scala/com/netflix/atlas/core/model/MathVocabulary.scala

Short-term change to minimize confusion (see #345). Also
adds links to javadocs for the spectator classes and updates
the wiki link.

docs: add since 1.5 note to :percentile ref

---

atlas-webapi/src/main/scala/com/netflix/atlas/webapi/ExprApi.scala
atlas-webapi/src/test/scala/com/netflix/atlas/webapi/ExprApiSuite.scala

Adds an expr endpoint for extracting the queries [1] from a stack expression. This can be useful for UIs that need to further explore the tag space associated with a graph expression. Output is a list of all distinct queries used.
Example, suppose I have a graph of requests and errors:
```
nf.app,www,:eq,name,http.req.complete,:eq,:and,(,statusCode,),:by
```
And I want to expand it to get one graph per zone or node for the application. Send a request:
```
GET /api/v1/expr/queries?q=nf.app,www,:eq,name,http.req.complete,:eq,:and,(,statusCode,),:by
```
The response is:
```json
[
"nf.app,www,:eq,name,http.req.complete,:eq,:and"
]
```
This data can then be used with the [tags API](https://github.com/Netflix/atlas/wiki/Tags) to get all of the matching zones, nodes, etc.
[1] …

extract the queries from a stack expression.

---

atlas-chart/src/main/scala/com/netflix/atlas/chart/graphics/Constants.scala
atlas-config/src/main/scala/com/netflix/atlas/config/ConfigManager.scala

In some cases we are seeing:
```
Thread.currentThread().getContextClassLoader() == null
```
With this change we'll log a warning and try the
classloader for a given class.
/cc @fangji

work-around for null context classloader

---

atlas-core/src/main/scala/com/netflix/atlas/core/index/LazyTagIndex.scala
atlas-core/src/main/scala/com/netflix/atlas/core/model/Block.scala
atlas-core/src/main/scala/com/netflix/atlas/core/util/DoubleIntHashMap.scala
atlas-core/src/main/scala/com/netflix/atlas/core/util/IntHashSet.scala
atlas-core/src/main/scala/com/netflix/atlas/core/util/IntIntHashMap.scala
atlas-core/src/main/scala/com/netflix/atlas/core/util/LongIntHashMap.scala
atlas-core/src/main/scala/com/netflix/atlas/core/util/RefIntHashMap.scala
atlas-core/src/test/scala/com/netflix/atlas/core/util/DoubleIntHashMapSuite.scala
atlas-core/src/test/scala/com/netflix/atlas/core/util/IntHashSetSuite.scala
atlas-core/src/test/scala/com/netflix/atlas/core/util/IntIntHashMapSuite.scala
atlas-core/src/test/scala/com/netflix/atlas/core/util/LongIntHashMapSuite.scala
atlas-core/src/test/scala/com/netflix/atlas/core/util/RefIntHashMapSuite.scala
atlas-jmh/src/main/scala/com/netflix/atlas/core/util/IntSet.scala
project/Build.scala
project/Dependencies.scala

There are two main reasons:
1. Desire not to have LGPL licensed lib as transitive.
2. Minimize dependencies for core lib.

remove dependency on trove4j

---

conf/log4j2.xml

Add helper logging configuration that writes the data
to files instead of stdout and splits out the access
log to separate files.

logging config to split out access log

---

atlas-core/src/main/scala/com/netflix/atlas/core/model/StatefulVocabulary.scala
atlas-wiki/src/main/resources/Concepts.md
atlas-wiki/src/main/resources/Getting-Started.md
atlas-wiki/src/main/scala/com/netflix/atlas/wiki/pages/DistStddev.scala

Spectator docs moved off of github wiki. Fix links
that were broken with that change.

docs: fix links to spectator wiki

---

atlas-core/src/main/scala/com/netflix/atlas/core/model/StatefulExpr.scala
atlas-core/src/test/scala/com/netflix/atlas/core/model/DesSuite.scala

Incremental DES evaluation should match a global
evaluation with all data available in advance. The
pos was being updated such that values after the
first datapoint were getting ignored.
There is still a problem with `:sdes`, but for now
this change just adds a test to illustrate it.
We'll look at fixing `:sdes` later.

fix incremental des evaluation

---

atlas-json/src/main/scala/com/netflix/atlas/json/Json.scala
atlas-json/src/test/scala/com/netflix/atlas/json/JsonSuite.scala
project/Dependencies.scala

Note, scala Option now behaves more like java 8
Optional. The include setting has been changed
from NON_NULL to NON_ABSENT.

jackson 2.7.4

---

atlas-chart/src/main/scala/com/netflix/atlas/chart/JsonCodec.scala
atlas-chart/src/main/scala/com/netflix/atlas/chart/V2JsonGraphEngine.scala

For the experimental v2.json format this changes the
output so that all plot metadata will be emitted first
and then the lines will explicitly refer to the axis.
Before the metadata for a plot would be emitted followed
by all lines on that plot. That would be repeated for
each plot. The problem with this is that format becomes
cumbersome for a streaming evaluation where we only have
data for a single time interval at a time. With this
change the same format can be used for the normal
evaluation or a streaming evaluation.

lines should explicitly refer to axis

---

atlas-chart/src/main/scala/com/netflix/atlas/chart/JsonCodec.scala
atlas-chart/src/main/scala/com/netflix/atlas/chart/model/GraphDef.scala
atlas-chart/src/main/scala/com/netflix/atlas/chart/model/PlotDef.scala
atlas-chart/src/test/scala/com/netflix/atlas/chart/PngGraphEngineSuite.scala

For the v2.json format always be explicit about
the axis color. Before it was optional, but this
makes it easier for dynamic rendering without having
to worry about the rules the backend uses to
assign the color based on the lines.

always add the axis color

---

atlas-core/src/main/scala/com/netflix/atlas/core/model/StyleExpr.scala
atlas-core/src/main/scala/com/netflix/atlas/core/model/StyleVocabulary.scala
atlas-core/src/main/scala/com/netflix/atlas/core/util/Strings.scala
atlas-core/src/test/scala/com/netflix/atlas/core/util/StringsSuite.scala

Provides a style operator, `:decode`, that can be
used to perform hex decoding of the legend text.
Background: internally we restrict input to simple
alpha-numeric characters, `.`, `-`, and `_`. if
characters are used the data will get dropped as
invalid. If using the servo-atlas module, then it
will convert invalid characters to `_`. Most
commonly that was done for spaces.
The restriction is to ensure that it is easy and
safe to craft the query expressions and include
them as part of the URI in a variety of contexts.
Precise linkability is extremely important and
should not be compromised.
Some users do their own url encoding and the `%`
then gets converted to an `_`. This allows them
to undo the restriction and get the original
characters back. With this change that decoding
can now be …

hex decoding for legend values (bug 1271)

---

atlas-core/src/main/scala/com/netflix/atlas/core/algorithm/OnlineDes.scala
atlas-core/src/main/scala/com/netflix/atlas/core/algorithm/OnlineSlidingDes.scala
atlas-core/src/main/scala/com/netflix/atlas/core/model/StatefulExpr.scala

For future work, we will want to render the internal state to JSON or similar.  This change set adds a side object for OnlineDes and OnlineSlidingDes which is a simple case class, easily rendered to JSON.  This state class is used in the :des and :sdes operators to store and restore internal state, which allows this to be rendered to JSON as well.
Additionally, the state passed into StatefulExpression eval() methods is not modified in any expression.

Export state

---

atlas-core/src/main/scala/com/netflix/atlas/core/util/IntIntHashMap.scala
atlas-core/src/main/scala/com/netflix/atlas/core/util/LongIntHashMap.scala
atlas-core/src/main/scala/com/netflix/atlas/core/util/RefIntHashMap.scala
atlas-jmh/src/main/scala/com/netflix/atlas/core/util/IntIntMap.scala

Changes the primitive maps to resize at 50% full
rather than 70%. The 70% factor was originally
chosen to keep the memory use lower and for the
primary use-cases we didn't see much performance
degradation at the time. Rolling it out to more
systems though we have started seeing cases where
it performs quite badly and 50% does an order of
magnitude better.
JMH test with a simple example included.
```
0.7
[info] Benchmark                        Mode  Cnt      Score     Error  Units
[info] IntIntMap.testIntIntHashMap800  thrpt   10  10374.640 ± 782.568  ops/s
[info] IntIntMap.testIntIntHashMap8k   thrpt   10    589.537 ±   8.124  ops/s
[info] IntIntMap.testJavaHashMap800    thrpt   10   4051.768 ± 499.362  ops/s
[info] IntIntMap.testJavaHashMap8k     thrpt   10   2846.103 ±  14.858  ops/s …
```

adjust load factor for primitive maps

---

atlas-akka/src/main/resources/reference.conf
atlas-akka/src/main/scala/com/netflix/atlas/akka/ActorService.scala
atlas-akka/src/main/scala/com/netflix/atlas/akka/ActorSystemProvider.scala
atlas-akka/src/main/scala/com/netflix/atlas/akka/ConfigApi.scala
atlas-akka/src/main/scala/com/netflix/atlas/akka/DeadLetterStatsActor.scala
atlas-akka/src/main/scala/com/netflix/atlas/akka/Paths.scala
atlas-akka/src/main/scala/com/netflix/atlas/akka/StaticPages.scala
atlas-akka/src/main/scala/com/netflix/atlas/akka/UnboundedMeteredMailbox.scala
atlas-akka/src/main/scala/com/netflix/atlas/akka/WebServer.scala
atlas-akka/src/test/scala/com/netflix/atlas/akka/ConfigApiSuite.scala
atlas-akka/src/test/scala/com/netflix/atlas/akka/DeadLetterStatsActorSuite.scala
atlas-akka/src/test/scala/com/netflix/atlas/akka/StaticPagesSuite.scala
atlas-core/src/main/scala/com/netflix/atlas/core/db/MemoryDatabase.scala
atlas-core/src/main/scala/com/netflix/atlas/core/db/SimpleStaticDatabase.scala
atlas-core/src/main/scala/com/netflix/atlas/core/db/StaticDatabase.scala
atlas-core/src/test/scala/com/netflix/atlas/core/db/MemoryDatabaseSuite.scala
atlas-standalone/src/main/scala/com/netflix/atlas/standalone/Main.scala
atlas-standalone/src/main/scala/com/netflix/atlas/standalone/WebServerProvider.scala
atlas-standalone/src/test/resources/application.conf
atlas-webapi/src/main/resources/reference.conf
atlas-webapi/src/main/scala/com/netflix/atlas/webapi/DatabaseProvider.scala
atlas-webapi/src/main/scala/com/netflix/atlas/webapi/LocalPublishActor.scala
atlas-webapi/src/test/scala/com/netflix/atlas/webapi/GraphApiMemDbSuite.scala
conf/memory.conf
project/Build.scala

Updates the akka helpers to be more DI friendly. In
particular, it removes the dependency on `atlas-config`
and injects the `Config` as well as the `ActorSystem`.
A helper setting `atlas.akka.actors` is now available
in the config to configure an actor to load into the
system.

inject config and actor system

---

atlas-akka/src/main/scala/com/netflix/atlas/akka/ActorService.scala
atlas-akka/src/main/scala/com/netflix/atlas/akka/WebServer.scala
atlas-module-akka/src/main/resources/META-INF/services/com.google.inject.Module
atlas-module-akka/src/main/scala/com/netflix/atlas/akka/AkkaModule.scala
atlas-module-akka/src/test/scala/com/netflix/atlas/akka/AkkaModuleSuite.scala
atlas-module-webapi/src/main/resources/META-INF/services/com.google.inject.Module
atlas-module-webapi/src/main/scala/com/netflix/atlas/guice/WebApiModule.scala
atlas-module-webapi/src/test/scala/com/netflix/atlas/guice/WebApiModuleSuite.scala
atlas-standalone/src/main/scala/com/netflix/atlas/standalone/Main.scala
project/Build.scala
project/Dependencies.scala

Pulls the setup logic in standalone into modules that
we can just include in other projects. We don't use
the standalone jar internally it is just for simple
testing. This change allows us to further reduce
deviation from oss and internal.

create module packages for akka/webapi

---

atlas-standalone/src/main/resources/log4j2.xml
atlas-standalone/src/main/scala/com/netflix/atlas/standalone/Main.scala

For more details see:
http://netflix.github.io/spectator/en/latest/ext/log4j2/
Which is a bit out of date, with the change below the
ordering issues are no longer a problem when using the
appender via the config:
https://github.com/Netflix/spectator/commit/33825db0b96e3337f68b85e9ecbc78567071aecc#diff-9bc272482ec3aa21411ff595a1f4225f

move appender setup to log4j config

---

atlas-akka/src/main/scala/com/netflix/atlas/akka/AccessLogger.scala
atlas-akka/src/main/scala/com/netflix/atlas/akka/CustomDirectives.scala

Splits out a helper class for doing the access logging
based on the spray http classes. Makes it easier to
reuse in other contexts, in particular, for use with
clients.

make it easier to reuse access logging

---

atlas-webapi/src/main/scala/com/netflix/atlas/webapi/GraphRequestActor.scala

If the input set has many equal values it was possible to
get an exception:
```
IllegalArgumentException: Comparison method violates its general contract!
```
This is because the descending order was simply inverting
the ascending order comparator. With this change we sort
in ascending order and simply reverse the list if it should
be descending.

fix #405 possible contract error using desc order

---

atlas-core/src/main/scala/com/netflix/atlas/core/model/TaggedItem.scala
atlas-core/src/test/scala/com/netflix/atlas/core/model/TaggedItemSuite.scala
atlas-jmh/src/main/scala/com/netflix/atlas/core/model/ComputeId.scala

Computing the id for a tag map is in the hot path when publishing metrics. It is currently the biggest chunk of allocations on that path and it looks like there are a few simple changes that would reduce it significantly.

reduce allocations for computing ids

---

atlas-json/src/main/scala/com/netflix/atlas/json/Json.scala

The thread local buffer recycling in jackson seems to
cause corruption in some cases. It is hard to reproduce
in a controlled setting, but we see it pretty reliably
on a big cluster. After disabling, the corruption is
no longer being seen. First observed in jackson 2.7.x.
Current tests do not show much performance impact for
our use-cases.

disable jackson buffer recycling

---

atlas-webapi/src/main/scala/com/netflix/atlas/webapi/LocalPublishActor.scala
atlas-webapi/src/main/scala/com/netflix/atlas/webapi/PublishApi.scala

Fixes a bug where the failure message was getting encoded as
a json string inside the message of the json response. Also
changes the behavior on failures to have the error count
explicitly in the response and limit the number of specific
failure messages to the first 5. This significantly reduces
allocations and response sizes for payloads with many failures.

reduce size of publish failure response

---

atlas-core/src/main/resources/reference.conf
atlas-core/src/main/scala/com/netflix/atlas/core/db/MemoryDatabase.scala
atlas-core/src/main/scala/com/netflix/atlas/core/index/BatchUpdateTagIndex.scala
atlas-core/src/main/scala/com/netflix/atlas/core/index/LazyTagIndex.scala
atlas-core/src/test/scala/com/netflix/atlas/core/db/MemoryDatabaseSuite.scala
atlas-webapi/src/test/scala/com/netflix/atlas/webapi/GraphApiMemDbSuite.scala

Adds an option to support turning off string interning while
building the index. In many cases the strings will already
have been interned while parsing the incoming payload and this
additional step is redundant.

turn off interning while building the index

---

atlas-core/src/main/scala/com/netflix/atlas/core/util/SmallHashMap.scala
atlas-jmh/src/main/scala/com/netflix/atlas/core/util/SmallHashMapHashCode.scala

Switches the hashCode implementation for SmallHashMap
to call `MurmurHash3.arrayHash` instead of relying on
the implementation from the super class which calls
`MurmurHash3.mapHash`. The array variant is much faster
(3-4x) and greatly reduces allocations.

switch to MurmurHash3.arrayHash

---

atlas-core/src/main/scala/com/netflix/atlas/core/util/SmallHashMap.scala
atlas-core/src/test/scala/com/netflix/atlas/core/util/SmallHashMapSuite.scala
atlas-jmh/src/main/scala/com/netflix/atlas/core/util/SmallHashMapEquals.scala
atlas-jmh/src/main/scala/com/netflix/atlas/core/util/SmallHashMapHashCode.scala

Overrides equals for SmallHashMap to improve the performance.
The two main changes are to use the cache hash code as a filter
and simply compare the elements of the array. This does much
better than the default inherited from GenMapLike that more or
less does:
```scala
this.forall { t => other.get(t._1) == Some(t._2) }
```
If the elements are not inserted in the same order, then they
may be in a different order in the array due to collisions.
However, others will be in the correct position and we can
limit the lookups to ones where there is a mismatch.
**Equal Maps**
Checking where the maps being compared are equal:
```
Benchmark                     Mode  Cnt          Score          Error  Units
currentEquals                thrpt   10   47004215.059 ±  2291847.719  ops/s
inheritedEquals …
```

improve performance of SmallHashMap equality check

---

atlas-core/src/main/scala/com/netflix/atlas/core/util/SmallHashMap.scala
atlas-core/src/test/scala/com/netflix/atlas/core/util/SmallHashMapSuite.scala

Changes the hash code function to be more similar
to the MurmurHash3.unorderedHash. This is mostly
paranoia that the simple additive method will be
terrible for some data sets. There is an added
test case that demonstrates a fairly bad case.

more robust hash code function

---

atlas-akka/src/main/resources/reference.conf

Updates the default path pattern to make the ending
slash optional. If it is a simple actor path it is
usually not present. Makes it match the setting we
are typically using internally.

make ending '/' optional in path pattern

---

atlas-akka/src/main/scala/com/netflix/atlas/akka/ActorService.scala

Without this change, automatically generated paths are made (such as ```akka://atlas/user/$a```) rather than what we specified in our config.  This change calls the explicit-name version of ```actorOf()``` to fix this.
As a side note, in travis, we should probably fire up the server once and verify we can post something to it.  All the tests pass without this change, but the stand-alone server could not find actors as the names were wrong.

Set actor name rather than using a generated one.

---

atlas-poller/src/main/resources/reference.conf
atlas-poller/src/main/scala/com/netflix/atlas/poller/ClientActor.scala
atlas-poller/src/main/scala/com/netflix/atlas/poller/Messages.scala
atlas-poller/src/main/scala/com/netflix/atlas/poller/PollerManager.scala
atlas-poller/src/test/resources/application.conf
atlas-poller/src/test/scala/com/netflix/atlas/poller/ClientActorSuite.scala
atlas-poller/src/test/scala/com/netflix/atlas/poller/DataRef.scala
atlas-poller/src/test/scala/com/netflix/atlas/poller/PollerManagerSuite.scala
atlas-poller/src/test/scala/com/netflix/atlas/poller/TestActor.scala
build.sbt

Adds in the base manager that supervises a set of poller
actors. This is used for collecting metrics data from
various other services such as edda, healthcheck service,
cloudwatch, etc.

manager for polling data

---

atlas-poller/src/main/scala/com/netflix/atlas/poller/ClientActor.scala

Updates the content-type to be smile to match the
payload. This was mistakenly set as the accept header
earlier.

fix content type for client actor

---

atlas-poller-cloudwatch/src/main/scala/com/netflix/atlas/cloudwatch/CloudWatchPoller.scala

Use the immutable copy rather than the mutable
list for the batch that has already been cleared.

fix batch that is written back

---

atlas-poller-cloudwatch/src/main/resources/reference.conf

The conf file is already there, but it got left out
of the main list.

add lambda to default list of categories

---

atlas-poller/src/test/scala/com/netflix/atlas/poller/ClientActorSuite.scala

Fixes a compiler warning in ClientActorSuite:
```
Warning:(173, 15) non-variable type argument spray.http.HttpResponse in type pattern scala.util.Try[spray.http.HttpResponse] is unchecked since it is eliminated by erasure
case t: Try[HttpResponse] => response = t.asInstanceOf[Try[HttpResponse]]
```

fix warning in test case

---

atlas-akka/src/test/scala/com/netflix/atlas/akka/ActorServiceSuite.scala

Verifies that the actor is created on the expected
path. See #417 for more details.

add test case for ActorService

---

atlas-webapi/src/main/resources/reference.conf

Updates the allowed `nf.` keys to include vpc and subnet.

add vpc and subnet to default allowed-keys

---

atlas-core/src/main/scala/com/netflix/atlas/core/model/DataExpr.scala
atlas-core/src/test/scala/com/netflix/atlas/core/model/DataGroupBySuite.scala

If a subset of the time series passed to `GroupBy.eval` are
missing keys, then a NullPointerException will result when
sorting the groups. This change filters out the entries with
missing keys and adds some additional test cases for group by.

fix NPE if keyString is null for subset of values

---

atlas-core/src/main/scala/com/netflix/atlas/core/index/QueryIndex.scala
atlas-core/src/main/scala/com/netflix/atlas/core/model/MathExpr.scala
atlas-core/src/main/scala/com/netflix/atlas/core/model/MathVocabulary.scala
atlas-core/src/main/scala/com/netflix/atlas/core/model/Query.scala
atlas-core/src/main/scala/com/netflix/atlas/core/model/QueryVocabulary.scala
atlas-core/src/main/scala/com/netflix/atlas/core/model/StatefulVocabulary.scala
atlas-core/src/main/scala/com/netflix/atlas/core/model/StyleExpr.scala
atlas-core/src/test/scala/com/netflix/atlas/core/model/QuerySuite.scala
atlas-webapi/src/main/scala/com/netflix/atlas/webapi/ExprApi.scala
atlas-webapi/src/test/scala/com/netflix/atlas/webapi/ExprApiSuite.scala

Update the `/api/v1/expr/normalize` endpoint to be
less repetitive. In particular, the macros like `:avg`
and `:dist-stddev` should not get expanded.

less repetitive expression normalization

---

project/Dependencies.scala

This version fixes a bug with `Option[Trait]` getting
encoded as an empty object.

jackson 2.8.2

---

atlas-core/src/main/scala/com/netflix/atlas/core/index/QueryIndex.scala
atlas-core/src/test/scala/com/netflix/atlas/core/index/QueryIndexSuite.scala
atlas-jmh/src/main/scala/com/netflix/atlas/core/index/QueryIndexMatching.scala

Once there was a match at a given level it would
check the sub-tree, but never check for matches
among siblings. Adds the test case from the issue
and a second that demonstrates the issue for the
`matches` function as well. The original test case
would pass for `matches` because both sub-trees
in the index would match.

fix #436, QueryIndex misses some entries

---

atlas-json/src/main/scala/com/netflix/atlas/json/AtlasModule.scala
atlas-json/src/main/scala/com/netflix/atlas/json/CaseClassDeserializer.scala
atlas-json/src/main/scala/com/netflix/atlas/json/CaseClassDeserializers.scala
atlas-json/src/main/scala/com/netflix/atlas/json/Json.scala
atlas-json/src/main/scala/com/netflix/atlas/json/Reflection.scala
atlas-json/src/test/scala/com/netflix/atlas/json/JsonSuite.scala
atlas-json/src/test/scala/com/netflix/atlas/json/ReflectionSuite.scala

Adds a custom case class deserializer to the json
helper that supports default values used in the
case class constructor.
This is the more intuitive behavior most users
expect and avoids the need for wrapping in Option
or having custom deserializers for a given type
to fill in the defaults.

add custom case class deserializer

---

atlas-json/src/main/scala/com/netflix/atlas/json/CaseClassDeserializer.scala
atlas-json/src/main/scala/com/netflix/atlas/json/Reflection.scala
atlas-json/src/test/scala/com/netflix/atlas/json/CaseClassDeserializerSuite.scala
atlas-json/src/test/scala/com/netflix/atlas/json/JsonSuite.scala
atlas-json/src/test/scala/com/netflix/atlas/json/ReflectionSuite.scala

This change fixes two issues with the case class
deserializer added in #439:
1. We now check the initial token type to verify
it is an object.
2. Avoids creating the object before parsing the
fields. That was done before to avoid the
allocating the argument array for the constructor.
However, it prevents users from being able to
have additional validation as part of the
constructor logic. Now the object will be
created after the fields have all been processed
and placed in the arguments array.

fix minor issues with case class deserializer

---

atlas-json/src/main/scala/com/netflix/atlas/json/CaseClassDeserializer.scala
atlas-json/src/test/scala/com/netflix/atlas/json/CaseClassDeserializerSuite.scala

If the current token for the parser is `VALUE_NULL`,
then use the default rather than call readValue. The
readValue call can throw which will cause it to incorrectly
fail to parse the object. Exceptions like:
```
com.fasterxml.jackson.databind.JsonMappingException: Can not
deserialize instance of scala.collection.immutable.List out
of VALUE_NULL token
```

do not call readValue if current token is null

---

atlas-json/src/main/scala/com/netflix/atlas/json/CaseClassDeserializer.scala
atlas-json/src/main/scala/com/netflix/atlas/json/Json.scala
atlas-json/src/main/scala/com/netflix/atlas/json/Reflection.scala
atlas-json/src/test/scala/com/netflix/atlas/json/CaseClassDeserializerSuite.scala

Uses the type information from the bean description
when available so we have more context as to the requested
types for generic parameters.
The `generics 2` test case would fail before this change
because it would decode to a `Map` instead of `Inner`.

improve generic type detection

---

project/Dependencies.scala

This version fixes a security vulerability for directory
traversals on Windows:
https://groups.google.com/forum/#!topic/spray-user/4V3F_oLm_TA
We aren't using that method directly and do not run on
Windows, but that might not be true downstream.

update to spray 1.3.4

---

conf/memory.conf

Port setting in sample memory.conf was not updated to
reflect changes introduced in #396.

fix #451: port setting in sample memory.conf

---

atlas-core/src/main/scala/com/netflix/atlas/core/util/StringMatcher.scala
atlas-core/src/test/scala/com/netflix/atlas/core/model/QuerySuite.scala
atlas-core/src/test/scala/com/netflix/atlas/core/util/StringMatcherSuite.scala

For simple patterns the `StringMatcher` will convert
them to basic string operations that perform better
than using regular expressions.
If a simple pattern had an explicit end anchor, then it
was incorrectly choosing the `IndexOf` matcher rather
than falling back to using `Regex`. This change fixes
the `IndexOf` pattern and also adds an `Equals` matcher
to cover the simple case using `String.equals`.

some patterns incorrectly interpretted as indexOf

---

atlas-jmh/src/main/scala/com/netflix/atlas/json/CaseClasses.scala
atlas-json/src/main/scala/com/netflix/atlas/json/CaseClassDeserializer.scala
build.sbt

Comparing our custom deserializer for case classes to
the default from jackson module scala:
```
Benchmark       Mode  Cnt      Score     Error  Units
default        thrpt   10  39889.677 ± 483.340  ops/s
custom         thrpt   10  12219.647 ± 479.135  ops/s
```
There is a big slow down. Most of that was for trying
to find the contextual deserializer for the field types.
Adding something to cache that:
```
custom         thrpt   10  36432.024 ±  867.252  ops/s
```

improve performance for accessing deserializer

---

atlas-chart/src/main/scala/com/netflix/atlas/chart/JsonCodec.scala
atlas-chart/src/main/scala/com/netflix/atlas/chart/JsonGraphEngine.scala
atlas-chart/src/test/scala/com/netflix/atlas/chart/JsonGraphEngineSuite.scala
atlas-core/src/main/scala/com/netflix/atlas/core/index/SimpleTagIndex.scala
atlas-core/src/main/scala/com/netflix/atlas/core/model/TaggedItem.scala
atlas-core/src/main/scala/com/netflix/atlas/core/util/Strings.scala
atlas-core/src/test/scala/com/netflix/atlas/core/util/StringsSuite.scala
atlas-jmh/src/main/scala/com/netflix/atlas/chart/GraphEngines.scala
atlas-jmh/src/main/scala/com/netflix/atlas/core/util/ZeroPad.scala
atlas-webapi/src/main/scala/com/netflix/atlas/webapi/GraphApi.scala
atlas-webapi/src/test/scala/com/netflix/atlas/webapi/GraphApiSuite.scala
atlas-wiki/src/main/resources/Graph.md
atlas-wiki/src/main/scala/com/netflix/atlas/wiki/GraphHelper.scala
build.sbt

String.format uses regex internally to parse the format
string. This makes it quite expensive and removing the
usage is an easy win.

avoid using String.format in hot code paths

---

atlas-wiki/src/main/resources/Getting-Started.md

Looks like it was added to help guide internal users
that might go to this wiki. Other links should suffice
and we'll revisit if it becomes a problem. Fixes #471.

docs: remove internal link from wiki

---

atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/SSEActor.scala
atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/StreamApi.scala
atlas-lwcapi/src/test/scala/com/netflix/atlas/lwcapi/SSEActorSuite.scala
atlas-lwcapi/src/test/scala/com/netflix/atlas/lwcapi/StreamApiSuite.scala

This patch changes limiting outstanding messages to limiting outstanding bytes for slower readers.  The limit is set to 10 megabytes per stream.
Also, individual metrics are combined into a single HTTP write request every 100 ms (hard coded) or 100 k of buffered data (hard coded)

track bytes sent, not messages sent, for limiting resource usage

---

atlas-core/src/main/scala/com/netflix/atlas/core/index/RoaringTagIndex.scala
atlas-core/src/test/scala/com/netflix/atlas/core/index/RoaringTagIndexSuite.scala
build.sbt
project/Dependencies.scala

Adds an implementation of the `TagIndex` that uses
roaring bitmaps as the underlying integer sets. Will
follow up with some benchmarks and then see how it
does on real world data sets.

impl of TagIndex using roaring bitmaps

---

atlas-core/src/main/scala/com/netflix/atlas/core/util/SmallHashMap.scala
atlas-core/src/test/scala/com/netflix/atlas/core/util/SmallHashMapSuite.scala

For maps with the same length and hashCodes the equality
check would fall back to `dataEquals`. That method had
a bug where if different keys were in the same position
of the underlying data array, then the values would not
get checked and the entry would get skipped. This could
cause some maps to incorrectly get treated as being equal
even though they are not.

fix bug with equality check on SmallHashMap

---

atlas-poller-cloudwatch/src/main/resources/ec2.conf
atlas-poller-cloudwatch/src/main/resources/reference.conf

This makes it easier to query for just the t2 credit
metrics rather than all ec2 metrics.

move ec2 credit to separate block

---

atlas-poller-cloudwatch/src/main/resources/sqs.conf

The filter for testing was left in the config. As it is
not generally applicable it should not be in the base
config files.

remove test sqs filter from config

---

atlas-json/src/main/scala/com/netflix/atlas/json/Reflection.scala
atlas-json/src/test/scala/com/netflix/atlas/json/CaseClassDeserializerSuite.scala
atlas-lwcapi/src/test/scala/com/netflix/atlas/lwcapi/ExpressionWithFrequencySuite.scala

The json decoder will now unwrap the `InvocationTargetException`
and throw the cause. This avoids a bunch of reflection non-sense
the user does not care about and make it easier to see the root
issue for why decoding failed.

propagate exception if thrown in constructor

---

atlas-akka/src/main/scala/com/netflix/atlas/akka/CustomDirectives.scala
atlas-akka/src/main/scala/com/netflix/atlas/akka/WebApi.scala
atlas-akka/src/test/scala/com/netflix/atlas/akka/CustomDirectivesSuite.scala
atlas-akka/src/test/scala/com/netflix/atlas/akka/TestApi.scala
atlas-webapi/src/main/scala/com/netflix/atlas/webapi/PublishApi.scala
atlas-webapi/src/main/scala/com/netflix/atlas/webapi/RenderApi.scala

Replaces the old `getJsonParser` helper with a
directive `jsonParser`. The directive will work
for all entity types rather than just strict
entities that have a single `ByteString`.

remove WebApi.getJsonParser

---

atlas-akka/src/main/resources/reference.conf

Updates our reference.conf to use the settings from
akka-http rather than spray.

update reference.conf to use akka-http settings

---

atlas-akka/src/main/scala/com/netflix/atlas/akka/RequestHandler.scala
atlas-akka/src/test/scala/com/netflix/atlas/akka/CustomDirectivesSuite.scala
atlas-akka/src/test/scala/com/netflix/atlas/akka/RequestHandlerSuite.scala

When switching to akka-http there was a regression
in the routes. The CORS headers were no longer
getting added to the OPTIONS preflight request.
For the original issue see #259. This passes the
test case in that commit comment using chrome. Also
adds local unit test that verifies the headers are
present.

fix CORS headers on preflight request

---

atlas-akka/src/main/resources/reference.conf
atlas-akka/src/main/scala/com/netflix/atlas/akka/AccessLogger.scala
atlas-akka/src/test/scala/com/netflix/atlas/akka/TestApi.scala
atlas-akka/src/test/scala/com/netflix/atlas/akka/TestApiSuite.scala
atlas-akka/src/test/scala/com/netflix/atlas/akka/UriParsingSuite.scala
project/Dependencies.scala

The access logger would create a URI instance and the
`java.net.URI` class is strict when parsing. This has
been changed to just pass in the string. It appears
that the `toString` for the spray/akka-http Uri class
changed in akka-http to be more consistent with what
the user actually used.

fix internal server error due to access logging

---

atlas-webapi/src/main/scala/com/netflix/atlas/webapi/GraphEval.scala

Adds a helper method for creating the graph definition
without actually rendering it. Useful for some cases
where we want to do a standalone eval and then manipulate
the results rather than output to the user.

split out helper method for creating the graph

---

atlas-core/src/main/scala/com/netflix/atlas/core/norm/NormalizationCache.scala
atlas-core/src/test/scala/com/netflix/atlas/core/norm/NormalizationCacheSuite.scala

If a heartbeat interval larger than the step is applied to
rates, then it can artificially inflate the overall count.
This can happen on occasion with the expiration pattern
used by spectator and servo when reporting counters if
the counter gets an update exactly one interval after it
expired.
Counters should be fine because they will compute the
delta and average over the missed interval. The heartbeat
is retained for this use-case as poller using a fixed
delay may have a reporting interval that is slightly
larger than the specified step.
Fixes #497.

do not apply heartbeat interval to rates

---

atlas-json/src/main/scala/com/netflix/atlas/json/JsonParserHelper.scala
atlas-json/src/test/scala/com/netflix/atlas/json/JsonParserHelperSuite.scala

If the function `f` has a bug and consumes the `END_ARRAY`
token, then before it would result in an endless loop. With
this change it will fail quickly.

check for null token in foreachItem helper

---

atlas-core/src/main/scala/com/netflix/atlas/core/index/BatchUpdateTagIndex.scala
atlas-core/src/main/scala/com/netflix/atlas/core/index/RoaringTagIndex.scala
project/Dependencies.scala

Updates the `RoaringTagIndex` to short-circuit AND queries
just like `LazyTagIndex`. The second query will not only
be performed if the first query has a non-empty result set.
In the test environment this was the main cause of slower
results when using `RoaringTagIndex` instead of `LazyTagIndex`.
Also updates the version to 0.6.36.

short circuit AND queries in roaring index

---

atlas-core/src/main/scala/com/netflix/atlas/core/util/StringMatcher.scala
atlas-core/src/test/scala/com/netflix/atlas/core/util/StringMatcherSuite.scala
atlas-jmh/src/main/scala/com/netflix/atlas/core/util/StringMatchingOr.scala

Changes simple regex OR queries to use a set of
basic `StringMatcher`s. This significantly improves
performance for the most common cases we see in
practice.

rewrite simple regex OR queries

---

atlas-akka/src/main/scala/com/netflix/atlas/akka/CustomDirectives.scala
atlas-akka/src/test/scala/com/netflix/atlas/akka/CustomDirectivesSuite.scala
atlas-webapi/src/main/scala/com/netflix/atlas/webapi/PublishApi.scala
atlas-webapi/src/main/scala/com/netflix/atlas/webapi/RenderApi.scala

The `jsonParser` directive could potentially result in
the created parser being created in one thread and then
used in another. Jackson uses some thread local buffers
for keeping track of state and this behavior means multiple
threads could be updating those buffers.
This change removes that directive and adds a `customJson`
that allows the decoding to use the parser directly to
create an object, but keeps it all local to one block that
should all be run on a single thread.

avoid passing JsonParser across threads

---

atlas-core/src/main/scala/com/netflix/atlas/core/model/MathVocabulary.scala
atlas-core/src/test/scala/com/netflix/atlas/core/model/TimeSeriesExprSuite.scala
atlas-wiki/src/main/scala/com/netflix/atlas/wiki/Main.scala
atlas-wiki/src/main/scala/com/netflix/atlas/wiki/pages/Stddev.scala

Helper function for computing the stddev over the
results of a group by operation. Sometimes useful
as an offset for outlier detection.

add macro for stddev of group by

---

atlas-core/src/main/scala/com/netflix/atlas/core/validation/ValidCharactersRule.scala
atlas-core/src/test/scala/com/netflix/atlas/core/validation/ValidCharactersRuleSuite.scala
project/Dependencies.scala

It now allows the set of valid characters to be set
via a pattern in the config and for overrides to be
set for given tag values.
This is mostly to support an internal decision to relax
group names so that they allow `^` and `~`. Others values
should not be relaxed as it could result in backwards
compatibility issues for names that were already being
converted to `_` when published.

make ValidCharactersRule more flexible

---

atlas-core/src/main/scala/com/netflix/atlas/core/db/BlockStore.scala
atlas-core/src/main/scala/com/netflix/atlas/core/db/MemoryDatabase.scala
atlas-core/src/test/scala/com/netflix/atlas/core/db/MemoryBlockStoreSuite.scala
atlas-core/src/test/scala/com/netflix/atlas/core/db/MemoryDatabaseSuite.scala

Adds a method to the block store to explicitly
rotate and compress the blocks. Before it would
only happen when there was data written for a given
time series. So if no data comes in after the time
boundary it would not get automatically rotated.

add method to explicitly rotate blocks

---

atlas-core/src/main/scala/com/netflix/atlas/core/util/Hash.scala
atlas-core/src/main/scala/com/netflix/atlas/core/util/IntHashSet.scala
atlas-core/src/main/scala/com/netflix/atlas/core/util/IntIntHashMap.scala
atlas-core/src/main/scala/com/netflix/atlas/core/util/LongIntHashMap.scala
atlas-core/src/main/scala/com/netflix/atlas/core/util/RefIntHashMap.scala
atlas-core/src/main/scala/com/netflix/atlas/core/util/SmallHashMap.scala
atlas-core/src/test/scala/com/netflix/atlas/core/util/DoubleIntHashMapSuite.scala
atlas-core/src/test/scala/com/netflix/atlas/core/util/IntHashSetSuite.scala
atlas-core/src/test/scala/com/netflix/atlas/core/util/IntIntHashMapSuite.scala
atlas-core/src/test/scala/com/netflix/atlas/core/util/LongIntHashMapSuite.scala
atlas-core/src/test/scala/com/netflix/atlas/core/util/RefIntHashMapSuite.scala

If an object hashes to `Integer.MIN_VALUE`, then the
absolute value will be `Integer.MIN_VALUE` and a negative
values was used for looking up data in the underlying
array. This change will map those to be `0` instead.

fix bounds exception for Integer.MIN_VALUE hash

---

atlas-akka/src/main/scala/com/netflix/atlas/akka/CustomDirectives.scala
atlas-akka/src/test/scala/com/netflix/atlas/akka/CustomDirectivesSuite.scala
atlas-akka/src/test/scala/com/netflix/atlas/akka/RequestHandlerSuite.scala

Avoids confusing errors due to requests being
cached with the wrong origin.

add vary origin to cors responses

---

atlas-akka/src/main/scala/com/netflix/atlas/akka/CustomDirectives.scala
atlas-akka/src/main/scala/com/netflix/atlas/akka/RequestHandler.scala
atlas-akka/src/test/scala/com/netflix/atlas/akka/RequestHandlerSuite.scala

Adds the `Access-Control-Max-Age` to the CORS
preflight response. Age is set to 10 minutes
as that seems to be a common max allowed by
various browsers.

enable caching of CORS preflight

---

atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/SSEActor.scala
atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/StreamApi.scala
atlas-lwcapi/src/test/scala/com/netflix/atlas/lwcapi/SSEActorSuite.scala

Cleanup a TODO in the code from when we switched to
akka-http. The subscriptions objects are passed into
the stream source actor.
Also fixes a bug where we would only write the chunks
on receive, but not when we had messages and available
room based on `totalDemand`.

emit subscriptions back in the sse response

---

atlas-poller-cloudwatch/src/main/resources/ec2.conf
atlas-poller-cloudwatch/src/main/resources/efs.conf
atlas-poller-cloudwatch/src/main/resources/elasticache.conf
atlas-poller-cloudwatch/src/main/resources/kinesis.conf
atlas-poller-cloudwatch/src/main/resources/rds.conf
atlas-poller-cloudwatch/src/main/resources/redshift.conf
atlas-poller-cloudwatch/src/main/resources/reference.conf

Adds mapping for cloudwatch EFS metrics and adjust
some of the ids to be more consistent with casing.
Some users found it annoying and hard to remember
which ones had a starting capital. This change makes
them more consistent.

add efs metrics

---

atlas-poller/src/main/scala/com/netflix/atlas/poller/ClientActor.scala

The poller client was not properly discarding the
entity bytes for success or unexpected status codes.

fix poller client to discard entity bytes

---

atlas-core/src/main/scala/com/netflix/atlas/core/db/BlockStore.scala
atlas-core/src/main/scala/com/netflix/atlas/core/db/MemoryDatabase.scala
atlas-core/src/main/scala/com/netflix/atlas/core/model/Block.scala
atlas-core/src/main/scala/com/netflix/atlas/core/model/TagKey.scala
atlas-core/src/main/scala/com/netflix/atlas/core/norm/NormalizationCache.scala
atlas-core/src/test/scala/com/netflix/atlas/core/db/MemoryDatabaseSuite.scala
atlas-webapi/src/main/scala/com/netflix/atlas/webapi/LocalPublishActor.scala
atlas-webapi/src/main/scala/com/netflix/atlas/webapi/PublishApi.scala
atlas-webapi/src/test/scala/com/netflix/atlas/webapi/LocalPublishActorSuite.scala
atlas-webapi/src/test/scala/com/netflix/atlas/webapi/PublishApiSuite.scala

This change allows datapoints to be rolled up as they
are flowing into the in memory storage. Typically this
has been done later as part of offline processing using
EMR or via a separate aggregator cluster that would
perform the aggregations prior to being sent to the
in memory storage.
To be eligible for the rollup the data must have already
been normalized to the step boundary and rate conversion
for counters should have already been performed.
The inline rollup will create a rollup block so it will
have more overhead in terms of memory use unless the
reduction multiple is over 4. Data will only go through
the rollup path if it is tagged with `atlas.rollup=true`.
The publish payload can now take an `id` field which will
get used to dedup messages. If used, then it should avoid
over …

support inline rollup of datapoints

---

atlas-core/src/main/scala/com/netflix/atlas/core/util/SmallHashMap.scala
atlas-core/src/test/scala/com/netflix/atlas/core/util/SmallHashMapSuite.scala
atlas-jmh/src/main/scala/com/netflix/atlas/core/util/SmallHashMapModify.scala

Changes the small hash map implementation of `+`
and `-` to retain the type. This is primarily to
avoid using a less memory efficient map type if
the map is modified somewhere along the way. A
side benefit is better performance and reduced
allocations.
**Before**
```
Benchmark        Mode  Cnt       Score       Error  Units
addPair         thrpt   10  781344.330 ± 25173.790  ops/s
removePair      thrpt   10  738796.252 ± 44849.997  ops/s
```
**After**
```
Benchmark        Mode  Cnt        Score       Error  Units
addPair         thrpt   10  1637470.772 ± 29948.315  ops/s
removePair      thrpt   10  2520939.662 ± 32320.759  ops/s
```

improve performance of SmallHashMap.{+,-}

---

project/BuildSettings.scala

Add the build date and number to the jar manifest
to aid in debugging.

add additional build metadata to jar

---

atlas-webapi/src/main/resources/reference.conf

Updates the default allowed keys list for `atlas.`
prefix to include `atlas.rollup`.

add `atlas.rollup` to allowed keys

---

atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/ExpressionApi.scala
atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/ExpressionDatabase.scala
atlas-lwcapi/src/test/scala/com/netflix/atlas/lwcapi/ExpressionApiSuite.scala

Modifies the `/lwc/api/v1/expressions` endpoint
to support listing all expressions. Before it would
only list out expresssions for a particular cluster.

add support for listing all expressions

---

atlas-webapi/src/main/scala/com/netflix/atlas/webapi/GraphApi.scala
atlas-webapi/src/test/scala/com/netflix/atlas/webapi/GraphApiMemDbSuite.scala

For some use-cases we access `GraphApi.Request.exprs`
many times, there is no reason to interpret it each
time.

store the interpreted expression in the Request

---

atlas-poller-cloudwatch/src/main/resources/sqs.conf

It was incorrectly specified as `s3`.

fix prefix for cloudwatch sqs metrics

---

atlas-core/src/main/scala/com/netflix/atlas/core/model/Block.scala
atlas-core/src/test/scala/com/netflix/atlas/core/model/BlockSuite.scala

With inline rollups the the blocks from a single
mirror can contain a rollup. For now it follows
a simple strategy of just merging the individual
blocks for the rollup.

support merging rollup blocks

---

atlas-standalone/src/main/resources/application.conf
atlas-standalone/src/main/resources/static.conf
atlas-standalone/src/main/scala/com/netflix/atlas/standalone/Main.scala
conf/lwcapi.conf
conf/memory.conf

Fixes the standalone example to only run the lwc api
and services when using the lwcapi config. The webapi
portions have been restricted in a similar way. This
avoids the need for having redis to run the basic
standalone example.

only run lwc when using the lwcapi.conf

---

atlas-standalone/src/main/resources/log4j2.xml

Updates the default logging config for standalone so
that it disables the log4j shutdown hook. This is to
avoid missing log messages for the app shutdown:
https://github.com/Netflix/iep/tree/master/iep-guice#shutdown

disable log4j shutdown hook on default config

---

atlas-standalone/src/main/resources/application.conf
atlas-standalone/src/main/scala/com/netflix/atlas/standalone/Main.scala
build.sbt
conf/lwcapi.conf
conf/memory.conf
project/Dependencies.scala

The standalone example will not report data to itself
when running with the sample `memory.conf`. A similar
thing can be done with the `lwcapi.conf` by uncommenting
the enabled flag. It is disabled by default since there
are some ordering issues on startup that cause exceptions
in the log.

enable self-reporting for standalone example

---

atlas-eval/README.md
atlas-eval/src/main/scala/com/netflix/atlas/eval/model/AggrDatapoint.scala
atlas-eval/src/main/scala/com/netflix/atlas/eval/model/ChunkData.scala
atlas-eval/src/main/scala/com/netflix/atlas/eval/model/LwcDatapoint.scala
atlas-eval/src/main/scala/com/netflix/atlas/eval/model/LwcSubscription.scala
atlas-eval/src/main/scala/com/netflix/atlas/eval/model/ServoMessage.scala
atlas-eval/src/main/scala/com/netflix/atlas/eval/model/TimeGroup.scala
atlas-eval/src/main/scala/com/netflix/atlas/eval/model/TimeSeriesMessage.scala
atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/DataExprEval.scala
atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/DatapointEval.scala
atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/EurekaSourceActor.scala
atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/Evaluator.scala
atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/HostSource.scala
atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/LwcToAggrDatapoint.scala
atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/StreamRef.scala
atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/TimeGrouped.scala
atlas-eval/src/test/resources/application.conf
atlas-eval/src/test/scala/com/netflix/atlas/eval/model/AggrDatapointSuite.scala
atlas-eval/src/test/scala/com/netflix/atlas/eval/model/ChunkDataSuite.scala
atlas-eval/src/test/scala/com/netflix/atlas/eval/model/LwcDataExprSuite.scala
atlas-eval/src/test/scala/com/netflix/atlas/eval/stream/DataExprEvalSuite.scala
atlas-eval/src/test/scala/com/netflix/atlas/eval/stream/DatapointEvalSuite.scala
atlas-eval/src/test/scala/com/netflix/atlas/eval/stream/HostSourceSuite.scala
atlas-eval/src/test/scala/com/netflix/atlas/eval/stream/LwcToAggrDatapointSuite.scala
atlas-eval/src/test/scala/com/netflix/atlas/eval/stream/TimeGroupedSuite.scala
build.sbt

This isn't yet fully baked or hardened, but is a good
enough check point. This is an initial version of a
library to evaluate expressions using the LWC service
as a source.
Still left to do:
1. Expose simple and stable java API for accessing
the stream for a corresponding graph uri. This is
to make it really easy to transition between the
backend graph and a streaming source.
2. Source identification in LWC so we can reliably
dedup messages.
3. Improving test coverage of Eureka source and
evaluator helpers. This is really sparse right
now.
4. Refactor Datapoint so that the step size is provided
rather than coming from a static config.
5. Performance testing and tuning.
These follow up items will be addressed in later PRs.

initial streaming eval library

---

atlas-core/src/main/scala/com/netflix/atlas/core/model/MathExpr.scala
atlas-core/src/main/scala/com/netflix/atlas/core/model/MathVocabulary.scala
atlas-core/src/test/scala/com/netflix/atlas/core/model/MathExamplesSuite.scala
atlas-core/src/test/scala/com/netflix/atlas/core/stacklang/BaseExamplesSuite.scala
atlas-webapi/src/main/scala/com/netflix/atlas/webapi/ExprApi.scala

Fixes a bug with the expression string for named rewrites
that contain offsets. If the rewrite is being used similar
to an aggregate function and the display expression is a
query, then the offset was getting lost because that is an
attribute of the aggregate functions that are only present
in the expanded evaluation expression.
Now the named rewrite will extract the offset and group by
information if the display type is a query. For others the
rewrite will be re-evaluated using the same interpreter.

named rewrite expr string now preserves offset

---

atlas-eval/src/main/scala/com/netflix/atlas/eval/model/ServoMessage.scala
atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/Evaluator.scala
atlas-eval/src/main/scala/com/netflix/atlas/eval/util/SmallHashMapDeserializer.scala
atlas-jmh/src/main/scala/com/netflix/atlas/eval/ServoMessageToDatapoint.scala
atlas-json/src/main/scala/com/netflix/atlas/json/Json.scala
atlas-json/src/main/scala/com/netflix/atlas/json/Reflection.scala
build.sbt

Some initial performance checks on the streaming
evaluation show a lot of allocations. The biggest
contributor was converting from ByteString to
a form that jackson could parse. This has been
reduced by reusing buffers. Some other minor
changes have been made to reduce allocations for
fields and to go direct to SmallHashMap for the
tag data.
Biggest bottlenecks right now are parsing the
json messages from the SSE stream followed by
the materialization speed. The materialization
speed should be less of an issue in practice
because the streams will be longer lived and is
supposed to be improved in akka 2.5.0.

reduce allocations for processing messages

---

atlas-jmh/src/main/scala/com/netflix/atlas/eval/ServoMessageToDatapoint.scala
build.sbt
project/Dependencies.scala

Switch to akka 2.5.0 to get improved materialization
performance for streams. Throughput for the simple
benchmark in #541 improved by 26%.

update to akka 2.5.0

---

atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/Evaluator.scala
atlas-eval/src/main/scala/com/netflix/atlas/eval/util/ByteStringInputStream.scala
atlas-eval/src/test/scala/com/netflix/atlas/eval/util/ByteStringInputStreamSuite.scala

This makes it easier to quickly pass the ByteString to
jackson and keep the number of additional allocations
minimal.

add util for wrapping ByteString as InputStream

---

atlas-core/src/main/scala/com/netflix/atlas/core/model/MathExpr.scala
atlas-core/src/test/scala/com/netflix/atlas/core/model/MathExamplesSuite.scala
atlas-core/src/test/scala/com/netflix/atlas/core/model/StatefulExamplesSuite.scala
atlas-core/src/test/scala/com/netflix/atlas/core/stacklang/BaseExamplesSuite.scala

Fixes a regression introduced in #540. The non-query
case was re-evaluating the rewrite command on the
original query rather than the new rewritten display
expression.

fix rewrite to use new display expr

---

atlas-eval/src/main/resources/reference.conf
atlas-module-eval/src/test/scala/com/netflix/atlas/eval/EvalModuleSuite.scala

This was accidentally left out of a previous commit.

add reference config for eval lib

---

atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/SourceRef.scala
build.sbt

It wasn't getting published to jfrog/jcenter
since it wasn't part of the root.

add eval lib to root project

---

project/build.properties

This version seems to fix `formatLicenseHeaders` so it
will work when run from the root. In #553 it was noticed
that it worked when running for a particular subproject,
but not when run for the root project.

update to sbt 0.13.15

---

atlas-core/src/main/scala/com/netflix/atlas/core/util/Streams.scala

They avoid finalize making them a bit more GC
friendly.
https://www.cloudbees.com/blog/fileinputstream-fileoutputstream-considered-harmful

switch to Files.new{Input,Output}Stream

---

project/Dependencies.scala

Adds support for `~` in the detail for group
names (Netflix/frigga#20).

update to frigga 0.18.0

---

atlas-chart/src/main/scala/com/netflix/atlas/chart/JsonCodec.scala
atlas-core/src/main/scala/com/netflix/atlas/core/util/PngImage.scala

Fixes #564. We may move this behind a flag before 1.6 final,
but for now it is enabled by default. By including in the
v2.json format the UI/dashboard can use the static image
and switch to a dynamic rendering without making another
request.
The message has a type of `graph-image` with a data field
that is a data uri of the image without the legend.
Sample usage:
```html
<html>
<body>
<div id="content"></div>
<script>
var content = document.getElementById('content');
fetch('http://localhost:7101/api/v1/graph?q=name,sps,:eq,(,nf.cluster,),:by&format=v2.json')
.then(function(response) {
return response.json();
})
.then(function(json) {
var html = '';
json.forEach(function(msg) {
if (msg.type === 'graph-image') {
html += '<div><img src="' + msg.data + '"/></div>';
} else if (msg.type === …
```

included rendered image in v2.json response

---

atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/EvaluationFlows.scala
atlas-eval/src/test/scala/com/netflix/atlas/eval/stream/EvaluatorSuite.scala

Provides a simple example of usage and verifies some
of the basic functionality with the file based uri.

add test case for createStreamsProcessor()

---

atlas-core/src/main/scala/com/netflix/atlas/core/index/RoaringTagIndex.scala

Avoids boxing the values to Integer.

use int iterator for bitmaps

---

atlas-core/src/main/scala/com/netflix/atlas/core/model/StyleExpr.scala
atlas-core/src/main/scala/com/netflix/atlas/core/model/StyleVocabulary.scala
atlas-core/src/main/scala/com/netflix/atlas/core/util/Strings.scala
atlas-core/src/test/scala/com/netflix/atlas/core/model/StyleExprSuite.scala

This allows some simple manipulation of the legend
text using a sed like search and replace. The main
use-case is for massaging the results of a group by
to be more presentable.
/cc @vfilanovsky @tregoning

search and replace over legend text

---

atlas-core/src/main/scala/com/netflix/atlas/core/model/StyleVocabulary.scala
atlas-core/src/main/scala/com/netflix/atlas/core/stacklang/StandardVocabulary.scala

Looks like github no longer accepts the a line break
between the display text and href for the link.

fix #578, incorrect formatting for links

---

atlas-core/src/main/scala/com/netflix/atlas/core/model/Datapoint.scala
atlas-eval/src/main/scala/com/netflix/atlas/eval/model/AggrDatapoint.scala
atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/DataExprEval.scala
atlas-eval/src/test/scala/com/netflix/atlas/eval/stream/DatapointEvalSuite.scala

Before the step would always come from the global config
setting. This made it impossible to use the datapoint class
with multiple step sizes in play.

allow step size for datapoint to be set explicitly

---

atlas-webapi/src/main/scala/com/netflix/atlas/webapi/FetchRequestActor.scala
atlas-webapi/src/main/scala/com/netflix/atlas/webapi/GraphApi.scala
build.sbt

Starting work on #547. This adds an endpoint compatible
with the internal fetch API to the oss repo. There are
still a number of things left to do, but this should
unblock some other efforts.
To be addressed in later PRs:
- Test coverage, there are some basic test cases but I
still need to debug some issues with one of them and
clean them up a bit to remove use of some test data
that was dumped from internal sources.
- The throttling/limiter logic still needs to be moved
over, but is a bit more intertwined.
- In general need to move the actors away from the
actor publisher that was deprecated in akka 2.5.
/cc @skandragon

initial port of fetch api

---

atlas-core/src/main/scala/com/netflix/atlas/core/model/EvalContext.scala
atlas-core/src/test/scala/com/netflix/atlas/core/model/EvalContextSuite.scala

The context was ignoring the unit parameter passed into
partition. This would result in an IAE under some situations.
See test case for more details.

fix unit used when partitioning a context

---

atlas-core/src/test/scala/com/netflix/atlas/core/model/EvalContextSuite.scala
atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/DataSourceManager.scala
atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/EvaluationFlows.scala
atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/Evaluator.java
atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/EvaluatorImpl.scala
atlas-eval/src/test/scala/com/netflix/atlas/eval/stream/EvaluatorSuite.scala

Updates the high level processor to pass JsonSupport
messages instead of TimeSeriesMessage specifically. This
gives a lot of flexibility to send through other types
like DiagnosticMessage or other helpful information when
processing the stream.
Addresses issue #575.

update flow types to allow DiagnosticMessages

---

atlas-module-akka/src/main/scala/com/netflix/atlas/akka/AkkaModule.scala
atlas-module-cloudwatch/src/main/scala/com/netflix/atlas/guice/CloudWatchModule.scala
atlas-module-eval/src/main/scala/com/netflix/atlas/eval/EvalModule.scala
atlas-module-lwcapi/src/main/scala/com/netflix/atlas/guice/LwcApiModule.scala

Since scala 2.12 the private provider methods in the
module cause warnings about unused methods. Unfortunately
scala doesn't provide a way to suppress these on individual
methods (SI-1781). For now the work around is to mark them
as protected rather than private. Note the module class is
final so there will not be any subclasses.

avoid unused method warnings in guice modules

---

.travis.yml
project/Dependencies.scala

We have been running on 2.12 for a while now
and internal builds and deployments are mostly
on 2.12 now. The few stragglers are using the
1.5.x Atlas builds which is 2.11.x only and that
will not change.

drop cross build for 2.11

---

atlas-core/src/main/resources/reference.conf
atlas-core/src/main/scala/com/netflix/atlas/core/db/MemoryDatabase.scala
atlas-core/src/main/scala/com/netflix/atlas/core/index/RoaringTagIndex.scala
atlas-core/src/main/scala/com/netflix/atlas/core/index/SimpleTagIndex.scala
atlas-core/src/main/scala/com/netflix/atlas/core/index/TagQuery.scala
atlas-core/src/main/scala/com/netflix/atlas/core/util/ArrayHelper.scala
atlas-core/src/main/scala/com/netflix/atlas/core/util/IntRefHashMap.scala
atlas-core/src/main/scala/com/netflix/atlas/core/util/LongHashSet.scala
atlas-core/src/main/scala/com/netflix/atlas/core/util/RefIntHashMap.scala
atlas-core/src/test/scala/com/netflix/atlas/core/index/TagIndexSuite.scala
atlas-core/src/test/scala/com/netflix/atlas/core/util/DoubleIntHashMapSuite.scala
atlas-core/src/test/scala/com/netflix/atlas/core/util/IntRefHashMapSuite.scala
atlas-core/src/test/scala/com/netflix/atlas/core/util/LongHashSetSuite.scala
atlas-jmh/src/main/scala/com/netflix/atlas/core/index/RoaringTagIndexBench.scala
atlas-webapi/src/test/scala/com/netflix/atlas/webapi/TagsApiSuite.scala

Drops support for counts in the index and does some
initial work to simplify and improve performance. For
a lot of the common use-cases we see a 2-3x improvement:
**Before**
```
Benchmark                                Mode  Cnt     Score     Error  Units
create             thrpt   10    13.210 ±   1.041  ops/s
findKeysAll        thrpt   10  4646.344 ± 176.685  ops/s
findKeysQuery      thrpt   10   450.728 ±  39.296  ops/s
findValuesAllMany  thrpt   10   739.919 ±  41.530  ops/s
findValuesAllOne   thrpt   10  2194.050 ± 248.351  ops/s
```
**After**
```
Benchmark                                Mode  Cnt        Score        Error  Units
create             thrpt   10       20.270 ±      0.798  ops/s
findKeysAll        thrpt   10  6382544.499 ± 353321.426  ops/s
findKeysQuery      thrpt   10 …
```

improve tag query performance

---

atlas-core/src/main/scala/com/netflix/atlas/core/index/BatchUpdateTagIndex.scala
atlas-core/src/main/scala/com/netflix/atlas/core/index/CachingTagIndex.scala
atlas-core/src/main/scala/com/netflix/atlas/core/index/RoaringTagIndex.scala
atlas-core/src/main/scala/com/netflix/atlas/core/index/SimpleTagIndex.scala
atlas-core/src/main/scala/com/netflix/atlas/core/index/TagIndex.scala
atlas-core/src/test/scala/com/netflix/atlas/core/index/TagIndexSuite.scala
atlas-webapi/src/main/scala/com/netflix/atlas/webapi/LocalDatabaseActor.scala

Before it was wrapping the string in a TagKey type that
could also provide counts for each key. Since this isn't
supported or used anymore we can avoid the additional
allocations. Also most use-cases were just mapping it
back to strings after getting the response.

update findKeys to just return the strings

---

atlas-core/src/main/scala/com/netflix/atlas/core/util/IntRefHashMap.scala
atlas-core/src/main/scala/com/netflix/atlas/core/util/LongHashSet.scala
atlas-core/src/main/scala/com/netflix/atlas/core/util/LongIntHashMap.scala

Several use-cases of the primitive collections assume
multi-threaded read-only access is safe after the collection
is built and effectively immutable. That is nothing will
ever write to it again. The variants with a Long key type
use an internal buffer to avoid allocations when passing
the long value to `MurmurHash3.bytesHash`. The multi-threaded
access could result in errors such as BufferOverflowException
on the buffer.
This changes those collections to use a ThreadLocal for keeping
track of the buffers.

fix multi-threaded reads from long set/map

---

atlas-core/src/main/scala/com/netflix/atlas/core/index/RoaringTagIndex.scala
atlas-core/src/test/scala/com/netflix/atlas/core/index/TagIndexSuite.scala

When searching for the prefix it was looking for the postion
of the first match that was strictly greater than the prefix.
For cases where the prefix is an exact match to the full value
they would not match. The search now checks for the first
match that is greater than or equal to the prefix.
/cc @svachalek

fix regex matching when prefix is an exact match

---

atlas-core/src/main/scala/com/netflix/atlas/core/index/BatchUpdateTagIndex.scala
atlas-core/src/main/scala/com/netflix/atlas/core/index/RoaringTagIndex.scala
atlas-core/src/main/scala/com/netflix/atlas/core/index/SimpleTagIndex.scala
atlas-core/src/main/scala/com/netflix/atlas/core/model/Datapoint.scala
atlas-core/src/main/scala/com/netflix/atlas/core/model/ItemId.scala
atlas-core/src/main/scala/com/netflix/atlas/core/model/StatefulExpr.scala
atlas-core/src/main/scala/com/netflix/atlas/core/model/TaggedItem.scala
atlas-core/src/main/scala/com/netflix/atlas/core/model/TimeSeries.scala
atlas-core/src/main/scala/com/netflix/atlas/core/util/Hash.scala
atlas-core/src/test/scala/com/netflix/atlas/core/model/ItemIdSuite.scala
atlas-core/src/test/scala/com/netflix/atlas/core/model/TaggedItemSuite.scala
atlas-eval/src/main/scala/com/netflix/atlas/eval/model/TimeSeriesMessage.scala

Before the ids were just a BigInteger. This was mostly
for convenience and it was an easy starting point for
some modifications.
Flame graphs of stateful clusters for some stacks are
showing a significant about of time being spent computing
the hash code for the ids when looking up the blocks. The
custom class in this change uses a precomputed hash code
so that it will be constant time.

change ids to custom class

---

atlas-webapi/src/main/scala/com/netflix/atlas/webapi/PublishApi.scala
atlas-webapi/src/test/scala/com/netflix/atlas/webapi/PublishApiJsonSuite.scala

If an unknown object field was used in a datapoint it
would result in a NullPointerException by prematurely
closing hitting the end of object.

skip value associated with unknown fields

---

atlas-core/src/main/scala/com/netflix/atlas/core/model/ItemId.scala
atlas-core/src/main/scala/com/netflix/atlas/core/util/RefIntHashMap.scala

Since the hash code is precomputed it can be a cheap
way to short circuit the equality check on the array.

use hash code to short-circuit equals check

---

atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/StreamApi.scala
atlas-webapi/src/main/scala/com/netflix/atlas/webapi/ExprApi.scala

The usage of the parameters directive was giving warnings
like:
```
Warning:(48, 17) Adapting argument list by creating a 3-tuple: this may not be what you want.
signature: ParameterDirectives.parameters(pdm: akka.http.scaladsl.server.directives.ParameterDirectives.ParamMagnet): pdm.Out
given arguments: scala.Symbol("name").$qmark, scala.Symbol("expression").$qmark, scala.Symbol("frequency").$qmark
after adaptation: ParameterDirectives.parameters((scala.Symbol("name").$qmark, scala.Symbol("expression").$qmark, scala.Symbol("frequency").$qmark): akka.http.scaladsl.server.directives.ParameterDirectives.ParamMagnet{type Out = akka.http.scaladsl.server.Directive[(Option[String], Option[String], Option[String])]})
parameters('name.?, 'expression.?, 'frequency.?) { (name, expr, frequency) => …
```

fix warnings about adapting argument list to tuple

---

atlas-akka/src/main/scala/com/netflix/atlas/akka/HealthcheckApi.scala

The healthcheck api was accessing the service manager
from a provider when the routes were fetched. There
doesn't appear to be any reason for this and it was
removed already in 1.6 branch as part of #490.
This was usually harmless, but on some systems threads
would get scheduled in such a way that all of the actor
threads were blocked with traces like:
```
"atlas-akka.actor.default-dispatcher-9" #18 prio=5 os_prio=0 tid=0x00007fb914010000 nid=0x6410 waiting on condition [0x00007fb9235f7000]
java.lang.Thread.State: WAITING (parking)
at sun.misc.Unsafe.park(Native Method)
- parking to wait for  <0x00000000838ae498> (a java.util.concurrent.locks.ReentrantLock$NonfairSync)
at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
at …
```

fix possible deadlock during startup

---

atlas-akka/src/main/scala/com/netflix/atlas/akka/RequestHandler.scala
atlas-akka/src/test/scala/com/netflix/atlas/akka/CustomDirectivesSuite.scala

Add some test cases for cors on error responses. There was
a report CORS headers were not added to errors. That does
not seem to be the case. Most likely they did not handle
the rejections and the filter was not applied to the error.

add more test cases for cors

---

atlas-core/src/main/scala/com/netflix/atlas/core/model/DataExpr.scala
atlas-core/src/test/scala/com/netflix/atlas/core/model/DataExprSuite.scala
atlas-core/src/test/scala/com/netflix/atlas/core/model/DataGroupBySuite.scala
atlas-core/src/test/scala/com/netflix/atlas/core/model/TimeSeriesExprSuite.scala

Illegal conversion when trying to access the group by
key for a data expression.
```
java.util.IllegalFormatConversionException: x != com.netflix.atlas.core.model.ItemId
at java.util.Formatter$FormatSpecifier.failConversion(Formatter.java:4302)
at java.util.Formatter$FormatSpecifier.printInteger(Formatter.java:2793)
at java.util.Formatter$FormatSpecifier.print(Formatter.java:2747)
at java.util.Formatter.format(Formatter.java:2520)
at java.util.Formatter.format(Formatter.java:2455)
at java.lang.String.format(String.java:2940)
at scala.collection.immutable.StringLike.format(StringLike.scala:351)
at scala.collection.immutable.StringLike.format$(StringLike.scala:350)
at scala.collection.immutable.StringOps.format(StringOps.scala:29)
at …
```

fix IllegalFormatConversionException

---

atlas-poller-cloudwatch/src/main/resources/sqs.conf

New SQS metric that was added a while back:
https://aws.amazon.com/about-aws/whats-new/2016/08/new-amazon-cloudwatch-metric-for-amazon-sqs-monitors-the-age-of-the-oldest-message/

add mapping for ApproximateAgeOfOldestMessage

---

atlas-poller-cloudwatch/src/main/resources/reference.conf
atlas-poller-cloudwatch/src/main/scala/com/netflix/atlas/cloudwatch/CloudWatchPoller.scala

In some cases if there are a lot of cloudwatch metrics,
then the polling can start to get throttled and cannot
keep up at the desired rate. This can cause spotty reporting
until the limit can get raised or the poller config is
changed to be less aggressive. To minimize the visibility
pf the problem for a user consuming the metric the last
datapoint is now cached and the reported value comes
from the local cache.
This does mean that when such a problem is happening the wrong
value might be propagated for several minutes. From recent
testing though in the more typical case it avoids confusion
more often until there is a better way to access cloudwatch
data. If it is a big concern the ttl can be configured to a
smaller value.

cache most recent datapoints from cloudwatch

---

atlas-core/src/main/scala/com/netflix/atlas/core/model/MathExpr.scala
atlas-core/src/main/scala/com/netflix/atlas/core/model/MathVocabulary.scala
atlas-core/src/test/scala/com/netflix/atlas/core/model/ClampSuite.scala

Allows the user to restrict the min and max values of
the input respectively. The most common use-case motivating
this is to be able to support a bounded auto-scaling for
data on an axis. The axis lower and upper limits are either
explicit or automatic. These operators give more flexiblity
and can be set for a given line to tune its behavior.
Name was chosen to match the same operators in Promoetheus.

add :clamp-min and :clamp-max

---

atlas-core/src/main/scala/com/netflix/atlas/core/util/ListHelper.scala
atlas-core/src/test/scala/com/netflix/atlas/core/util/ListHelperSuite.scala
atlas-jmh/src/main/scala/com/netflix/atlas/core/util/ListMerge.scala

Broken off from larger effort that is still in-progress.
Basic helper utility for merging a collection of sorted
lists. One such use-case is merging tag list results
coming back from many shards.

helper for merging sorted lists

---

atlas-core/src/main/scala/com/netflix/atlas/core/util/ListHelper.scala
atlas-core/src/test/scala/com/netflix/atlas/core/util/ListHelperSuite.scala

For the use-cases we care about the input list will
already be sorted and uniqued. This fixes the merge
to also remove duplicate values across the lists.

update merge to also dedup the list

---

atlas-poller-cloudwatch/src/main/resources/s3-request.conf

The latency is in milliseconds and we were treating it
as seconds.

fix unit for s3 request timers

---

atlas-poller/src/main/resources/reference.conf
atlas-poller/src/main/scala/com/netflix/atlas/poller/ClientActor.scala

When using an alias with a lambda it will get encoded
as a `:alias` suffix on the resource dimension. Before
those stats were getting dropped as invalid.
Changes were tested manually. Will follow up with some
refactoring to make the testing for this client easier in
general.

convert invalid characters for polled metrics

---

atlas-poller-cloudwatch/src/main/resources/alb.conf
atlas-poller-cloudwatch/src/main/resources/reference.conf

Adds basic mappings for the ApplicationELB metrics in
CloudWatch. There was a bit of debate on whether the
LoadBalancer and TargetGroup dimensions should be kept
as is or extract the name and only show that. The ids
are rarely useful to the end user and add quite a bit
of noise when selecting in the UI. For now though we
just map the values in as they are provided in CloudWatch.

add mappings for application load balancer stats

---

atlas-core/src/main/scala/com/netflix/atlas/core/util/Shards.scala
atlas-core/src/test/scala/com/netflix/atlas/core/util/ShardsSuite.scala

Move over the internal helper utility for mapping data
to a set of instances. This is typically used with a
service like edda that maintains stable slotting for
instances within auto-scaling groups. These simple
schemes are preferred for the core monitoring system
to avoid dependencies on complex infrastructure like
zookeeper that are prone to having correlated failure
with the key systems we need to monitor.

add helper for simple shard mapping

---

atlas-poller-cloudwatch/src/main/resources/dynamodb.conf

The key in the configuration was singular instead of
plural. Need to think about a better way to validate
this in the future.

fix key for adding tags to dynamodb errors

---

atlas-akka/src/main/resources/reference.conf
atlas-akka/src/test/scala/com/netflix/atlas/akka/PathsSuite.scala

We sometimes see paths for the stream supervisor that look
like:
```
akka://test/user/StreamSupervisor-99961
```
This creates a lot of ids which aren't that useful. This
change updates the default pattern to just extract the
prefix and ignore the counter at the end. So activity for
all stream supervisors will show up as a single metric.

update default path pattern for StreamSupervisor

---

atlas-core/src/main/scala/com/netflix/atlas/core/util/Shards.scala
atlas-core/src/test/scala/com/netflix/atlas/core/util/ShardsSuite.scala

The local mapper doesn't actually need the full group
details just the size. Originally it took the group,
but there are a number of uses now that just create a
fake group with the right size.

allow the local mapper with just group size

---

project/BuildSettings.scala

Trying to clean up some of the noise in the build
logs. No one is paying attention to these warnings
and if there is a real compatibility problem it
should be caught in tests or the integration
environment.

disable eviction warnings for update task

---

atlas-eval/src/main/scala/com/netflix/atlas/eval/model/AggrDatapoint.scala
atlas-eval/src/test/scala/com/netflix/atlas/eval/model/AggrDatapointSuite.scala

There is a bigger discussion on whether we should
remove `:all`, but for now all DataExpr types should
be supported.

handle :all expressions with streaming eval

---

atlas-akka/src/main/scala/com/netflix/atlas/akka/CustomMediaTypes.scala
atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/HostSource.scala
atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/StreamApi.scala
atlas-webapi/src/main/scala/com/netflix/atlas/webapi/FetchRequestActor.scala

As of 10.0.8 akka-http supports the `text/event-stream`
media type. We no longer need it as a custom one.

use built in text/event-stream media type

---

project/Dependencies.scala

Fixes issues when running on jdk9:
```
Cause: java.lang.IllegalAccessException: access to public member failed: com.netflix.spectator.api.RegistryConfig.gaugePollingFrequency()Duration/invokeSpecial, from com.netflix.spectator.api.RegistryConfig/2 (unnamed module @7d3cb5af)
at java.base/java.lang.invoke.MemberName.makeAccessException(MemberName.java:914)
at java.base/java.lang.invoke.MethodHandles$Lookup.checkAccess(MethodHandles.java:2193)
at java.base/java.lang.invoke.MethodHandles$Lookup.checkMethod(MethodHandles.java:2133)
at java.base/java.lang.invoke.MethodHandles$Lookup.getDirectMethodCommon(MethodHandles.java:2282)
at java.base/java.lang.invoke.MethodHandles$Lookup.getDirectMethodNoSecurityManager(MethodHandles.java:2276)
at …
```

update to spectator 0.57.1

---

atlas-core/src/main/scala/com/netflix/atlas/core/util/SmallHashMap.scala
atlas-core/src/test/scala/com/netflix/atlas/core/util/SmallHashMapSuite.scala

This method was incorrectly using the data length rather
than the capacity when looping over the array. If a key
had a collision and was hashed to a position that was
larger than the data length, then it would be an endless
loop because the key entry would never be found.

fix endless loop for numProbesPerKey

---

atlas-core/src/main/scala/com/netflix/atlas/core/util/SmallHashMap.scala
atlas-core/src/test/scala/com/netflix/atlas/core/util/SmallHashMapSuite.scala

Updates the return types for `add` and `addAll` to
return the Builder so they can be chained.

support chaining with SmallHashMap.Builder

---

atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/ExpressionWithFrequency.scala
atlas-lwcapi/src/test/scala/com/netflix/atlas/lwcapi/ExpressionApiSuite.scala
atlas-lwcapi/src/test/scala/com/netflix/atlas/lwcapi/ExpressionDatabaseSuite.scala
atlas-lwcapi/src/test/scala/com/netflix/atlas/lwcapi/ExpressionWithFrequencySuite.scala

Changes the id strings used for lwc expressions to be
more consistent with how metric ids are generated.

update ids for lwc to be consistent with metrics

---

atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/EurekaSource.scala
atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/HostSource.scala
atlas-eval/src/test/scala/com/netflix/atlas/eval/stream/HostSourceSuite.scala

The LWC HostSource was not recovering if there was
a failure on the entity source from the response. This
would cause the overall stream to fail and stop producing
data. With this change the error will get logged and it
will get retried like any other failure.

recover from errors on response source

---

atlas-core/src/test/scala/com/netflix/atlas/core/util/ShardsSuite.scala

Updates the checks for uniform distribution of the ids to
compare the average with the min and the max rather than
comparing the min to the max. In rare cases we were seeing
the min being over the 10% threshold to the max.
Fixes #660.

make ShardsSuite more resilient to false positives

---

atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/HostSource.scala
atlas-eval/src/test/scala/com/netflix/atlas/eval/stream/HostSourceSuite.scala

Since these are meant to be long lived, there should
not be a bound on the max size of the stream.
/cc @ruchirj

disable size limit on stream response

---

atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/StreamContext.scala

There are multiple paths that will get used now
and the components already know the correct path
for what they are doing. Currently this causes
a problem for the SubscriptionManager because
it is posting to `/stream/$id/subscribe` instead
of `/subscribe`.

do not assume stream path for backend

---

atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/Evaluator.java

The constructor was widened to take a Collection instead
of a Set, but this causes binary compatibility issues.

change DataSources constructor to take a Set

---

atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/FinalExprEval.scala
atlas-eval/src/test/scala/com/netflix/atlas/eval/stream/FinalExprEvalSuite.scala

Addresses three problems with the final eval step:
1. Errors parsing the expression will now get sent to back
as a diagnostic message on the stream.
2. Any errors that occur when running the evaluation on
a set of data will now get sent to the user as a
diagnostic message.
3. Fixes the no data behavior to match the backend. Before
it would result in an exception during evaluation instead
of a no data line.

improve error handling for final eval step

---

project/plugins.sbt

Fixes the warnings like:
```
Warning: Unknown Scalafmt version 1.2.0; using 1.0 interface
```

neo-sbt-scalafmt 1.12

---

atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/EvaluatorImpl.scala

The client is retrieved from the context now so
nothing is using this client.

cleanup unused client param

---

atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/ConnectionManager.scala
atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/EurekaGroupsLookup.scala
atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/EurekaSource.scala
atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/HostSource.scala
atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/StreamContext.scala
atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/SubscriptionManager.scala
atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/package.scala
atlas-eval/src/test/scala/com/netflix/atlas/eval/stream/EurekaGroupsLookupSuite.scala
atlas-eval/src/test/scala/com/netflix/atlas/eval/stream/EurekaSourceSuite.scala
atlas-eval/src/test/scala/com/netflix/atlas/eval/stream/HostSourceSuite.scala
atlas-eval/src/test/scala/com/netflix/atlas/eval/stream/SubscriptionManagerSuite.scala

Use access logger for all client requests made
during the eval.

more consistent use of access logger

---

atlas-akka/src/main/resources/reference.conf
atlas-akka/src/main/scala/com/netflix/atlas/akka/CustomDirectives.scala
atlas-akka/src/main/scala/com/netflix/atlas/akka/RequestHandler.scala
atlas-akka/src/test/scala/com/netflix/atlas/akka/CustomDirectivesSuite.scala
atlas-akka/src/test/scala/com/netflix/atlas/akka/RequestHandlerSuite.scala

Adds the `atlas.akka.cors-host-patterns` setting that can
be used to set an eplicit whitelist of origins that are
allowed to receive CORS headers.
Also adds `Access-Control-Allow-Credentials` for use-cases
that need to work with cookies.

add configuration option for allowed cors origins

---

atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/SubscribeApi.scala
atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/SubscriptionManager.scala

When creating a subscription with many expressions, the
`updateSubHandlers()` method in the subscription manager
is quite expensive. Before, the subscribe api would end
up calling this once per expression, now it will only
call it once.
/cc @ruchirj

improve performance for bulk subscribe

---

atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/SubscriptionManager.scala
atlas-lwcapi/src/test/scala/com/netflix/atlas/lwcapi/ExpressionApiSuite.scala

Refactors the subscription manager to make the updates
cheaper and minimize the synchronization that is needed.
Now the only synchronization is to ensure the that the
cleanup for the sub handlers map will not have a race
condition with adding new handlers.
This change also avoids the more costly computation of
the subscription handlers from the registration map. On
a test node with real traffic it significantly reduced
the CPU and thread contention observed.
/cc @ruchirj

reduce thread contention in SubscriptionManager

---

atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/EvaluatorImpl.scala
atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/LwcToAggrDatapoint.scala
atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/StreamContext.scala

Tracks the number of events seen during various phases
of the evaluation pipeline. The phase id is prefixed
so the group by will be ordered in the same manner as
they occur in the flow.

add counters tracking the number of events

---

atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/ExprInterpreter.scala
atlas-eval/src/test/scala/com/netflix/atlas/eval/stream/EvaluatorSuite.scala
atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/ExpressionSplitter.scala
atlas-lwcapi/src/test/scala/com/netflix/atlas/lwcapi/ExpressionSplitterSuite.scala

Some operations like `:offset` are not supported when
performing a streaming evaluaton. These will now result
in an error for that expression being propagated back
to the user.
/cc @ruchirj

explicit error for unsupported expressions

---

atlas-core/src/main/scala/com/netflix/atlas/core/util/SmallHashMap.scala
atlas-jmh/src/main/scala/com/netflix/atlas/core/util/SmallHashMapJavaGet.scala

For some use-cases when feeding into streaming evaluator
there are a lot of get calls on the underlying tag maps
for the datapoints. This change adds a custom map wrapper
that maps the `get(key)` call on the java map to the
`getOrNull(key)` on the SmallHashMap. This avoids the
allocation of the Option when using the default scala
wrapper.

custom map wrapper to improve get performance

---

atlas-json/src/main/scala/com/netflix/atlas/json/CaseClassDeserializer.scala
atlas-json/src/main/scala/com/netflix/atlas/json/Reflection.scala
project/Dependencies.scala

The constructor for AnnotatedParameter now takes another
parameter. Also the PropertyMetadata for a BeanProperty
needs to be set or we get NPE in the test cases. A few
other changes were made to clear up deprecation warnings.

fix #646, make compatible with jackson 2.9

---

atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/SSEActor.scala

This needs a bit more work and consideration, but the
change here resolves the most common and easy to reproduce
problem. When a new connection comes in with an id that
is already in use, it will replace the previous connection
and that stream is unregistered before setting up the
registration for the new connection stream. This creates
a race condition:
1. GET /stream/id
1. unregister(id), noop nothing present for id
2. register(id)
2. GET /stream/id
1. unregister(id), removes the previous and shutsdown
the connection
2. register(id), sets up new registration
3. SSEActor.postStop -> unregister(id), unregisters the
newly created actor
With this change the postStop method for SSEActor will not
attempt to unregister again because we know it has already
been unregistered.

fix propagation of needsUnregister for shutdown

---

atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/SSEActor.scala
atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/SubscriptionManager.scala
atlas-lwcapi/src/test/scala/com/netflix/atlas/lwcapi/SubscriptionManagerSuite.scala

Before when the stream went away the map for the subscription
to the handler was not getting cleaned up.

remove handlers when a stream is unregistered

---

atlas-core/src/main/scala/com/netflix/atlas/core/util/RollingInterval.scala
atlas-core/src/test/scala/com/netflix/atlas/core/util/RollingIntervalSuite.scala

This is being moved over from internal use. It is used for
keeping track of the set of data that should be loaded on
the historical clusters that read from s3.

add RollingInterval utility

---

atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/EurekaGroupsLookup.scala
atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/EvaluationFlows.scala
atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/EvaluatorImpl.scala

The EurekaGroupsLookup stage creates a source to regularly
refresh the set of Eureka vips that are needed based on the
requested data sources. When a new set of data sources comes
in, it will stop the old source and create a new one.
The problem is when a new set of data sources comes in quickly
it could stop the source refreshing Eureka groups after the
request was made and before the response was processed. In
this scenario the `max-open-requests` limit would eventually
be reached and all subsequent requests would fail.
There are two changes included here:
1. Before the source was stopped using a `takeWhile` operator
at a later stage. Now it is stopped by changing the source
to indicate it is done and no longer has data. This means
that the subsequent stages of the flow should go ahead …

fix possible buffer overflow for refreshing groups

---

atlas-akka/src/main/scala/com/netflix/atlas/akka/UnboundedMeteredMailbox.scala
atlas-core/src/main/scala/com/netflix/atlas/core/db/BlockStore.scala
atlas-core/src/main/scala/com/netflix/atlas/core/index/BatchUpdateTagIndex.scala
atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/SSEActor.scala
atlas-poller-cloudwatch/src/main/scala/com/netflix/atlas/cloudwatch/CloudWatchPoller.scala
atlas-poller/src/main/scala/com/netflix/atlas/poller/PollerManager.scala
atlas-webapi/src/main/scala/com/netflix/atlas/webapi/LocalPublishActor.scala
project/Dependencies.scala

Updates the version and fixes the new deprecation
warnings for gauges.

update to spectator 0.58.1

---

build.sbt
project/Dependencies.scala

In jdk9 the PostConstruct and PreDestroy annotations have
been moved to a deprecated module that has to be explicitly
enabled. Adding explicit dependency so that those classes
can be found and the start/stop methods on services will
be called correctly.

add dependency on jsr250

---

atlas-core/src/main/scala/com/netflix/atlas/core/util/ListHelper.scala
atlas-core/src/test/scala/com/netflix/atlas/core/util/ListHelperSuite.scala

Fixes the case when one of the lists is empty to check
the limit.

fix #711, restrict limit when one list is empty

---

atlas-jmh/src/main/scala/com/netflix/atlas/core/util/ListMergeCommonPrefix.scala

When merging across many shards with some data sets the
merge takes a long time due to increased cost of the
comparisons.

add jmh test for merge with long common prefix

---

atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/EvaluatorImpl.scala
atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/TimeGrouped.scala
atlas-eval/src/test/scala/com/netflix/atlas/eval/stream/EurekaGroupsLookupSuite.scala
atlas-eval/src/test/scala/com/netflix/atlas/eval/stream/EurekaSourceSuite.scala
atlas-eval/src/test/scala/com/netflix/atlas/eval/stream/SubscriptionManagerSuite.scala
atlas-eval/src/test/scala/com/netflix/atlas/eval/stream/TestContext.scala
atlas-eval/src/test/scala/com/netflix/atlas/eval/stream/TimeGroupedSuite.scala

Add counters to track how many datapoints are getting
dropped and buffered when going through the time grouped
stage.

add datapoint counters for TimeGrouped operator

---

atlas-jmh/src/main/scala/com/netflix/atlas/json/SeqDeser.scala

Compares performance of deserializing a sequence of strings
using json/smile and into an array and list. As expected,
smile with array is clear winner. The benchmark only shows
speed, but the allocation rate is also much better with using
an array.

add jmh test for seq deserialization

---

atlas-core/src/main/scala/com/netflix/atlas/core/util/ArrayHelper.scala
atlas-core/src/main/scala/com/netflix/atlas/core/util/ListHelper.scala
atlas-core/src/test/scala/com/netflix/atlas/core/util/ArrayHelperSuite.scala
atlas-jmh/src/main/scala/com/netflix/atlas/core/util/ListMerge.scala
atlas-jmh/src/main/scala/com/netflix/atlas/core/util/ListMergeCommonPrefix.scala

Changes the implementation of merging many sorted lists
to use arrays internally to store the intermediate results.
This eliminates the allocations when performing a merge
operation. Before it was construction many `::` objects
to create the merged list. This shows a nice improvement
on the JMH benchmarks as well.
**Before**
```
ListMerge.merge                thrpt   10  23.064 ± 5.711  ops/s
ListMergeCommonPrefix.merge    thrpt   10   6.606 ± 0.534  ops/s
```
**After**
```
ListMerge.merge                thrpt   10  42.918 ± 2.044  ops/s
ListMergeCommonPrefix.merge    thrpt   10   8.700 ± 0.160  ops/s
```

reduce allocations for merging many sorted lists

---

CONTRIBUTING.md

The header was changed and the corresponding link
did not get updated.

fix link to reporting issues section

---

atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/EurekaGroupsLookup.scala
atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/EvaluationFlows.scala
atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/EvaluatorImpl.scala

In #704, there was a change to fix how the Eureka refresh
source was stopped. That change has a bug in that the function
passed to `repeatWhile` has a reference to the member variable.
So it is almost always true, unless it happens to get checked
in the brief period between when the previous instance was set
to false and the new instance is created.
As a result, none of the sources are actually stopped and the
old DataSources instances get pushed out repeated. Depending
on how the expressions have changed, this can cause the
subscriptions for various expression to come and go.
This change avoids the problem on the actual instance. Still
need to come up with a way to test, but will do that as a new
PR so I can unblock some downstream users that need the fix.
/cc @zimmermatt

fix stop for Eureka refresh source

---

atlas-core/src/main/scala/com/netflix/atlas/core/stacklang/Interpreter.scala
atlas-core/src/test/scala/com/netflix/atlas/core/stacklang/InterpreterSuite.scala
atlas-jmh/src/main/scala/com/netflix/atlas/core/stacklang/StringSplit.scala

For some use-cases like lwcapi where many expressions
get processed a significant amount of time was being
spent compiling the regex used by `String.split`. This
change avoids the regex and significantly improves
the parsing performance.

improve performance for splitting expressions

---

atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/ExpressionSplitter.scala
atlas-lwcapi/src/test/scala/com/netflix/atlas/lwcapi/ExpressionSplitterSuite.scala

A substantial chunk of the CPU usage (~40%) on the lwcapi
clusters is being spent processing the subscription updates.
In most cases these are the same expressions each time. This
changes the splitter to cache the processed result to eliminate
most of the overhead.
/cc @zimmermatt

cache the split expressions

---

atlas-core/src/main/scala/com/netflix/atlas/core/stacklang/Context.scala
atlas-core/src/main/scala/com/netflix/atlas/core/stacklang/Interpreter.scala
atlas-core/src/main/scala/com/netflix/atlas/core/stacklang/StandardVocabulary.scala
atlas-core/src/test/scala/com/netflix/atlas/core/stacklang/FreezeSuite.scala
atlas-webapi/src/main/resources/reference.conf

Adds `:freeze` operator to allow freezing a portion
of the stack so it is isolated from further modification.
This is useful for query overlay and some other use-cases
where we essentially need to combine multiple expressions
and still be able to use operations like `:clear` or `:list`
without worrying about exactly how far back to go on the
stack.

fix #733, add :freeze operator

---

atlas-core/src/main/scala/com/netflix/atlas/core/model/DataVocabulary.scala

In #692, the simple static db was updated to check the
limits which resulted in the example for `:all` failing.
This changes the example to reduce the match set.

docs: update example for all to avoid limit

---

atlas-core/src/main/scala/com/netflix/atlas/core/stacklang/Interpreter.scala
atlas-core/src/main/scala/com/netflix/atlas/core/stacklang/StandardVocabulary.scala
atlas-core/src/test/scala/com/netflix/atlas/core/model/NamedRewriteSuite.scala
atlas-core/src/test/scala/com/netflix/atlas/core/stacklang/FreezeSuite.scala

The macros like `:avg` on a graph are executed using the
same context as the overall expression. When completed they
were unfreezing the stack to get the final result stack. This
should not be done for internal executions, only once the
overall expression evaluation is completed.

fix use of :freeze with macros

---

atlas-core/src/main/scala/com/netflix/atlas/core/stacklang/StandardVocabulary.scala
atlas-core/src/test/scala/com/netflix/atlas/core/stacklang/FreezeSuite.scala

Before the `:set` operation was creating a new context
which is losing other information such as the frozen
stack. This changes it to copy and just update the
parts that are being modified by the operator.

copy context in :set

---

atlas-core/src/main/scala/com/netflix/atlas/core/model/MathExpr.scala
atlas-core/src/test/scala/com/netflix/atlas/core/model/PercentilesSuite.scala

Use the default double to string conversion so the value
more closely reflects what the user entered. The previous
approach of using the formatter would cause rounding if
there were too many significant digits.

fix #746, avoid rounding for percentile labels

---

atlas-json/src/main/scala/com/netflix/atlas/json/Reflection.scala
atlas-json/src/test/scala/com/netflix/atlas/json/JsonSuite.scala

The name can have encoded characters such as `.`. For
example `a.b` will be encoded as `a$u002Eb`. The decoded
name is now used as an alias if there is not an explict
alias set with an annotation.

use the decoded name as field alias

---

project/Dependencies.scala

Not sure that we have any impacted use-cases, but this
version fixes a memory leak with async callbacks:
https://akka.io/blog/news/2017/12/08/akka-2.5.8-released

akka 2.5.8

---

atlas-poller-cloudwatch/src/main/resources/reference.conf
atlas-poller-cloudwatch/src/main/resources/trustedadvisor.conf
atlas-poller-cloudwatch/src/main/scala/com/netflix/atlas/cloudwatch/Conversions.scala
atlas-poller-cloudwatch/src/test/scala/com/netflix/atlas/cloudwatch/ConversionsSuite.scala

For now it is only the service limit usage metrics that
give us an idea of how close we are to limits. This can
be a simple alternative to many of the uses of howlermonkey.
The update frequency for the trusted advisor metrics is
fairly low so it will take an hour or so to detect a
problem. For slow growth it is adequate.

add mapping for TrustedAdvisor metrics

---

atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/FinalExprEval.scala
atlas-eval/src/test/scala/com/netflix/atlas/eval/stream/FinalExprEvalSuite.scala

Before it was ignoring the pattern specified using
`:legend` and always using the default.

fix #762, use proper legend in streaming eval

---

atlas-core/src/test/scala/com/netflix/atlas/core/db/MemoryBlockStoreSuite.scala

Fixes the warnings due to the ambiguity between a parameter
list to the function and the creation of a tuple. For this
test case it doesn't matter so just switch it to a list to
clear up the warnings.

fix #747, use List instead of Tuple

---

atlas-core/src/main/scala/com/netflix/atlas/core/model/Query.scala
atlas-core/src/test/scala/com/netflix/atlas/core/model/QuerySuite.scala

A number of internal libraries have the use-case to
perform rewrites and then simplify the query expression.
This change adds it as a common helper function to the
Query object. In the case of rewrites it is often useful
to ignore terms so it has the option to use special
handling of the not true case so it will get elided rather
than making the overall expression false.

add helper function for simplifying a query

---

atlas-json/src/test/scala/com/netflix/atlas/json/JsonSuite.scala
project/Dependencies.scala

Fixes the issue for empty arrays brought up in #710.
The relevant jackson issue is FasterXML/jackson-module-scala#346.
/cc @skandragon

jackson 2.9.4

---

atlas-wiki/src/main/scala/com/netflix/atlas/wiki/Main.scala
atlas-wiki/src/main/scala/com/netflix/atlas/wiki/pages/DistAvg.scala
atlas-wiki/src/main/scala/com/netflix/atlas/wiki/pages/DistMax.scala

The generated defaults are not very helpful to users since they just
output the expanded rewrite syntax.

Provide a more useful description for `:dist-avg` and `:dist-max`.

---

atlas-core/src/main/scala/com/netflix/atlas/core/index/QueryIndex.scala
atlas-core/src/test/scala/com/netflix/atlas/core/index/QueryIndexSuite.scala

When building the query index we expand `:in` clauses
so we get a set of simpler queries with `:eq` clauses.
This allows us to greatly reduce the number of queries
that wind up in the fallback set that have to be checked
linearly.
However, if there are many `:in` clauses and some of them
match a large set, then there is a combinatorial explosion
and the number of queries we need to index becomes too
large. This changes restricts the expansion to `:in` clauses
with 5 or less values.

limit size of in clause for expansion

---

atlas-poller-cloudwatch/src/main/scala/com/netflix/atlas/cloudwatch/CloudWatchPoller.scala
atlas-poller-cloudwatch/src/main/scala/com/netflix/atlas/cloudwatch/GetMetricActor.scala
atlas-poller-cloudwatch/src/main/scala/com/netflix/atlas/cloudwatch/MetricDefinition.scala
atlas-poller-cloudwatch/src/test/scala/com/netflix/atlas/cloudwatch/ConversionsSuite.scala
atlas-poller-cloudwatch/src/test/scala/com/netflix/atlas/cloudwatch/MetricDataSuite.scala

Some values in cloudwatch may be reported as monotonic
counters. This change allows a `monotonic` flag to be
set on the metric definition to convert those to deltas
based on the previous value.

support converting monotonic cw values to delta

---

atlas-core/src/main/scala/com/netflix/atlas/core/model/FilterVocabulary.scala
atlas-core/src/main/scala/com/netflix/atlas/core/model/MathVocabulary.scala
atlas-core/src/main/scala/com/netflix/atlas/core/model/StatefulVocabulary.scala
atlas-core/src/test/scala/com/netflix/atlas/core/model/MathAcrossStyleSuite.scala

This change relaxes the language restrictions a bit
so that basic math operations can can be applied to
a time series expression after style attributes have
been applied. The main use-case is to allow for some
UI operations that need to perform operations on an
arbitrary graph in a similar manner to using `:cq`
to restrict the scope.
For binary operations, only one side can be a StyleExpr.
This prevents mutually exclusive presentation attributes
from the two sides.

fix #761, allow basic math ops on StyleExpr

---

atlas-core/src/main/resources/reference.conf
atlas-core/src/main/scala/com/netflix/atlas/core/model/CustomVocabulary.scala
atlas-core/src/main/scala/com/netflix/atlas/core/model/MathExpr.scala
atlas-core/src/main/scala/com/netflix/atlas/core/model/MathVocabulary.scala
atlas-core/src/main/scala/com/netflix/atlas/core/stacklang/Interpreter.scala
atlas-core/src/test/scala/com/netflix/atlas/core/model/CustomVocabularySuite.scala
atlas-webapi/src/main/scala/com/netflix/atlas/webapi/ApiSettings.scala
atlas-webapi/src/main/scala/com/netflix/atlas/webapi/ExprApi.scala
atlas-webapi/src/test/scala/com/netflix/atlas/webapi/ApiSettingsSuite.scala

Merges internal vocabulary that allows us to specify
custom words or averages via the configuration. See
comments in `reference.conf` for more information about
how to set these up.
This will further reduce the difference between what
we run internally and OSS version. It should also make
it easier to keep LWC and backend operations consistent.

add support for custom words

---

atlas-core/src/main/scala/com/netflix/atlas/core/model/MathExpr.scala
atlas-core/src/test/scala/com/netflix/atlas/core/model/CustomVocabularySuite.scala
atlas-core/src/test/scala/com/netflix/atlas/core/model/NamedRewriteSuite.scala

If a `:cq` operation was used to restrict a query
by a tag that was not available on the denominator,
then it would result in a no data line because the
query would get applied to both sides. This change
simplifies the rewrite so it will always re-run
the operation after modifying the display expression.
In this case that means the `extractCommonQuery`
step will get executed on the new query formed by
applying the `:cq` operation.

fix :cq with custom averages

---

atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/EvaluatorImpl.scala
atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/ExprInterpreter.scala
atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/FinalExprEval.scala
atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/StreamContext.scala
atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/SubscriptionManager.scala
atlas-eval/src/test/scala/com/netflix/atlas/eval/stream/FinalExprEvalSuite.scala
atlas-eval/src/test/scala/com/netflix/atlas/eval/stream/TestContext.scala

Updates the eval lib to use the same vocabulary
that would get used with the graph api after #776.

use custom vocabulary from eval lib

---

atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/ExpressionSplitter.scala
atlas-lwcapi/src/test/scala/com/netflix/atlas/lwcapi/ExpressionApiSuite.scala
atlas-lwcapi/src/test/scala/com/netflix/atlas/lwcapi/ExpressionSplitterSuite.scala
atlas-lwcapi/src/test/scala/com/netflix/atlas/lwcapi/SubscribeApiSuite.scala
atlas-lwcapi/src/test/scala/com/netflix/atlas/lwcapi/SubscriptionManagerSuite.scala
atlas-module-lwcapi/src/main/scala/com/netflix/atlas/guice/LwcApiModule.scala

Updates the lwcapi expression splitter to use the
same vocabulary that would get used with the graph
api after #776.

use custom vocabulary from lwcapi

---

atlas-core/src/main/scala/com/netflix/atlas/core/model/FilterExpr.scala
atlas-core/src/main/scala/com/netflix/atlas/core/model/MathExpr.scala
atlas-core/src/test/scala/com/netflix/atlas/core/model/FilterSuite.scala

Fixes #781. Before if a filter was applied to a non-grouped
expression, then it could result in a confusing error being
propagated to the user. The cause was that the binary
operations did not expect for an empty result set unless
the underlying expression was grouped.

empty filtered result should be transitive

---

atlas-core/src/main/scala/com/netflix/atlas/core/model/DataExpr.scala
atlas-core/src/main/scala/com/netflix/atlas/core/model/FilterExpr.scala
atlas-core/src/main/scala/com/netflix/atlas/core/model/MathExpr.scala
atlas-core/src/main/scala/com/netflix/atlas/core/model/StatefulExpr.scala
atlas-core/src/main/scala/com/netflix/atlas/core/model/TimeSeriesExpr.scala
atlas-core/src/test/scala/com/netflix/atlas/core/model/FinalGroupingSuite.scala
atlas-core/src/test/scala/com/netflix/atlas/core/model/MathGroupBySuite.scala
atlas-core/src/test/scala/com/netflix/atlas/core/stacklang/BaseExamplesSuite.scala
atlas-eval/src/main/scala/com/netflix/atlas/eval/model/TimeSeriesMessage.scala
atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/FinalExprEval.scala
atlas-eval/src/test/scala/com/netflix/atlas/eval/model/TimeSeriesMessageSuite.scala
atlas-webapi/src/main/scala/com/netflix/atlas/webapi/FetchRequestActor.scala

Fixes #754. Exposes the set of keys that were used
explicitly as part of a group by in the time series
messages emitted by fetch and streaming evaluation.
This is useful for things like canary analysis that
generate a set of lines for multiple clusters and
need a reliable way to find the correlated entries
from the baseline and canary. Since the tags will
contain exact matches from the query as well as
keys used in the group by, this change will allow
the user to extract just the keys from the group by
and ignore other exact match tags coming from the
scope used on the query.

add group by keys to time series message

---

atlas-core/src/main/scala/com/netflix/atlas/core/model/MathExpr.scala
atlas-core/src/main/scala/com/netflix/atlas/core/model/MathVocabulary.scala
atlas-core/src/test/scala/com/netflix/atlas/core/model/MathGroupBySuite.scala

Fixes #584. Before this would result in errors if the
rewrite resulted in a non-grouped time series expression.

fix use of multi-level group by with rewrites

---

Makefile

Adds a format target to the makefile to make it easier
to run both the license formatting and scala format.

add format target

---

.travis.yml
atlas-eval/src/test/scala/com/netflix/atlas/eval/stream/EurekaGroupsLookupSuite.scala
atlas-eval/src/test/scala/com/netflix/atlas/eval/stream/FinalExprEvalSuite.scala
atlas-eval/src/test/scala/com/netflix/atlas/eval/stream/SubscriptionManagerSuite.scala
project/Dependencies.scala

It was dropped in #600. There are some use-cases
where it would be helpful to use the latest version
from Spark which does not yet support 2.12. We'll
revisit for Atlas 1.7.

re-enable scala 2.11 build

---

atlas-core/src/main/scala/com/netflix/atlas/core/model/TimeSeriesExpr.scala
atlas-core/src/test/scala/com/netflix/atlas/core/model/NamedRewriteSuite.scala

Before if the display expression for a rewrite was a
Query type it would not correctly get the offset applied.
Fixes #788.

fix offset for aggregate function rewrites

---

atlas-core/src/main/scala/com/netflix/atlas/core/model/MathExpr.scala
atlas-core/src/test/scala/com/netflix/atlas/core/model/NamedRewriteSuite.scala

The group by operation could lose the offset if it was
not encoded as part of the display expression.

fix additional case of losing offset

---

atlas-core/src/main/scala/com/netflix/atlas/core/model/MathExpr.scala
atlas-core/src/test/scala/com/netflix/atlas/core/model/MathGroupBySuite.scala
atlas-core/src/test/scala/com/netflix/atlas/core/model/NamedRewriteSuite.scala

If the final grouping for display varies from the final
grouping of the eval, then the rewrite is applying a
secondary grouping. Otherwise just apply the rewrite
operator.
Fixes #791.

simplify string mapping for NamedRewrite

---

atlas-wiki/src/main/scala/com/netflix/atlas/wiki/Page.scala

docs: fix end tag for example tables

---

atlas-core/src/main/scala/com/netflix/atlas/core/util/SmallHashMap.scala
atlas-core/src/test/scala/com/netflix/atlas/core/util/SmallHashMapSuite.scala

Before it would fail with:
```
requirement failed: data array is full
```

fix removal of key that is not in SmallHashMap

---

atlas-poller-cloudwatch/src/main/resources/dynamodb.conf

These appear to only be available at the table level. The
error for request throttled would be needed to see how it
impacts particular operations.

add mapping for dynamo-db throttle events

---

atlas-standalone/src/main/resources/static.conf

The RenderApi never really worked and was removed as
part of #797.

remove bad api from static config

---

atlas-core/src/main/scala/com/netflix/atlas/core/db/DataSet.scala

This is used for generating fake data for the purposes
of testing or creating documentation examples. The config
load is causing problems due to classloader issues when
running as part of build plugin. Not sure why, but for this
use-case it can be avoided.

avoid config loading for demo dataset

---

atlas-eval/src/main/scala/com/netflix/atlas/eval/graph/Grapher.scala
atlas-eval/src/main/scala/com/netflix/atlas/eval/graph/package.scala
atlas-eval/src/test/scala/com/netflix/atlas/eval/graph/GrapherSuite.scala
atlas-webapi/src/main/scala/com/netflix/atlas/webapi/GraphRequestActor.scala
atlas-wiki/src/main/scala/com/netflix/atlas/wiki/GraphHelper.scala

Updates the Grapher lib so it can be used to render data
that has already been evaluated. The previous methods that
accept the input data or data expr map have been renamed
to evalAndRender.

support rendering pre-evaluated data

---

atlas-core/src/main/scala/com/netflix/atlas/core/model/MathExpr.scala
atlas-core/src/test/scala/com/netflix/atlas/core/model/NamedRewriteSuite.scala

Before it was getting lost if the percentile expression was
written back out to a string. Fixes #809.

preserve offset information for :percentiles

---

atlas-core/src/main/scala/com/netflix/atlas/core/model/MathExpr.scala
atlas-core/src/main/scala/com/netflix/atlas/core/model/MathVocabulary.scala
atlas-core/src/test/scala/com/netflix/atlas/core/model/ModelExtractorsSuite.scala
atlas-core/src/test/scala/com/netflix/atlas/core/model/TimeSeriesExprSuite.scala

Allows the user to use `math.pow` on time series expressions.
`a,b,:pow` will return a new time series where the values are `a` taken
to the power of `b`.

Add :pow operator

---

atlas-core/src/main/scala/com/netflix/atlas/core/db/MemoryDatabase.scala
atlas-core/src/main/scala/com/netflix/atlas/core/db/SimpleStaticDatabase.scala
atlas-core/src/main/scala/com/netflix/atlas/core/index/BatchUpdateTagIndex.scala
atlas-core/src/main/scala/com/netflix/atlas/core/index/IndexStats.scala
atlas-core/src/main/scala/com/netflix/atlas/core/index/RoaringTagIndex.scala
atlas-core/src/test/scala/com/netflix/atlas/core/index/BatchUpdateTagIndexSuite.scala
atlas-core/src/test/scala/com/netflix/atlas/core/index/IndexStatsSuite.scala
atlas-core/src/test/scala/com/netflix/atlas/core/index/RoaringTagIndexSuite.scala
atlas-jmh/src/main/scala/com/netflix/atlas/core/index/RoaringTagIndexBench.scala

This provides a quick summary of some key stats for
the index to see what is contributing the most to the
number of distinct strings. In most cases we just use
hive queries for digging into this, but these stats
can be used before data is in hive and are always scoped
to the specific index. In some cases where we already
have rollup policies the hive data is raw from before
the additional policies are enabled.

add helper for tracking index stats

---

build.sbt
project/Dependencies.scala

In jdk9 the PostConstruct and PreDestroy annotations have
been moved to a deprecated module that has to be explicitly
enabled. Adding explicit dependency so that those classes
can be found and the start/stop methods on services will
be called correctly.

1.5.x backport: add dependency on jsr250 (#708)

---

atlas-poller-cloudwatch/src/main/scala/com/netflix/atlas/cloudwatch/Conversions.scala
atlas-poller-cloudwatch/src/main/scala/com/netflix/atlas/cloudwatch/MetricDefinition.scala
atlas-poller-cloudwatch/src/test/scala/com/netflix/atlas/cloudwatch/ConversionsSuite.scala
atlas-poller-cloudwatch/src/test/scala/com/netflix/atlas/cloudwatch/MetricDefinitionSuite.scala

It was not set before so all would get treated as rate.
This led to some confusion for some of the S3 metrics
where it appeared there was a massive drop in the amount
of data stored in s3 after a brief gap. This drop was
because the consolidation averaged with 0 for the NaN
values since the values were considered rates.

set dstype for polled cloudwatch metrics

---

atlas-chart/src/main/scala/com/netflix/atlas/chart/JsonCodec.scala

See #564 and #568 for more context. The included image would
suppress the image. For some use-cases it is desirable to
include it. The previous output can still be achieved by
explicitly using `no_legend=1`.
Main use-case right now is an explode view that shows the
images, but has some dynamic filtering for outliers or missing
data. This avoids the need to make multiple requests for the
same data if the user requests to see the legends.
/cc @nathfisher @tregoning

honor legend flag for v2.json format image

---

atlas-core/src/main/scala/com/netflix/atlas/core/model/EvalContext.scala
atlas-core/src/main/scala/com/netflix/atlas/core/model/ResultSet.scala
atlas-core/src/main/scala/com/netflix/atlas/core/util/IdentityMap.scala
atlas-core/src/test/scala/com/netflix/atlas/core/model/DerivativeSuite.scala
atlas-core/src/test/scala/com/netflix/atlas/core/util/IdentityMapSuite.scala
atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/FinalExprEval.scala
atlas-eval/src/test/scala/com/netflix/atlas/eval/stream/FinalExprEvalSuite.scala

If an expression has multiple equivalent stateful
sub-expressions, then the they would store the state
to the same place since the key is the stateful expr
instance. This changes the map used to look at the
identity when performing the state lookup, so separate
instances will have isolated state.
We'll probably need to refactor this more thoroughly
long term and either memoize equivalent sub-expressions
during the evaluation or lookup based on position.

fix state isolation for streaming execution

---

.travis.yml
atlas-akka/src/test/scala/com/netflix/atlas/akka/ConfigApiSuite.scala

Dropping jdk9 as there is no reason to use it over
jdk10 at this point.

update travis to build on jdk10

---

atlas-chart/src/main/scala/com/netflix/atlas/chart/graphics/ValueAxis.scala

The return value is never checked.

remove useless call

---

atlas-akka/src/main/resources/metered-mailbox.conf
atlas-akka/src/main/resources/reference.conf

Makes it easier for us to do comparison performance tests
with other implementations. It can be included with the
application config when needed.

move metered queue config out of reference.conf

---

atlas-core/src/test/scala/com/netflix/atlas/core/util/StringMatcherSuite.scala

There was some inconsistency between the UI validation
which uses the javascript regex library and the backend.
Originally we suspected this was a bug and it was getting
mapped to an IndexOf query, but that is not the case. The
java regex engine has a slightly different interpretation.
Fixes #841

add test case for `^*` behavior with matcher

---

atlas-poller-cloudwatch/src/main/resources/rds.conf

AWS is inconsistent in the casing for BinLog between the
disk usage and replica lag metrics.

fix name for AuroraBinlogReplicaLag

---

atlas-core/src/main/scala/com/netflix/atlas/core/index/IndexStats.scala
atlas-core/src/main/scala/com/netflix/atlas/core/index/RoaringTagIndex.scala
atlas-core/src/test/scala/com/netflix/atlas/core/index/IndexStatsSuite.scala

The total number of unique metrics is derived 
from the index size.  This is recorded as a gauge
by the memory database during a rebuild operation,
ensuring that Atomic variables are not read 
unnecessarily.
I initially attempted to record this within the memory
database itself, but the index stats seemed more appropriate.
See #848

Record the total number of unique metrics

---

atlas-poller-cloudwatch/src/main/scala/com/netflix/atlas/cloudwatch/CloudWatchPoller.scala
atlas-poller-cloudwatch/src/test/scala/com/netflix/atlas/cloudwatch/MetricDataSuite.scala

For cloudwatch if a monotonic value gets multiple samples
within an interval it will cause a spike when looking at
the sum. Use the max to see the largest sample within a
given interval. Example metrics with this issue are the HSM
network stats (InterfaceEth2OctetsInput).
https://docs.aws.amazon.com/cloudhsm/latest/userguide/hsm-metrics-cw.html

handle monotonic values with multiple samples

---

atlas-core/src/main/scala/com/netflix/atlas/core/util/Hash.scala
atlas-core/src/main/scala/com/netflix/atlas/core/util/LongHashSet.scala
atlas-core/src/main/scala/com/netflix/atlas/core/util/LongIntHashMap.scala
atlas-core/src/test/scala/com/netflix/atlas/core/util/DoubleIntHashMapSuite.scala
atlas-core/src/test/scala/com/netflix/atlas/core/util/LongHashSetSuite.scala
atlas-core/src/test/scala/com/netflix/atlas/core/util/LongIntHashMapSuite.scala

Before it was computing the murmur3 hash and then ignoring
the result and using `Long.hashCode`. This change moves
the computation of the murmur3 hash to a helper function
and now LongIntHashMap uses that value.

fix hash code for LongIntHashMap

---

atlas-webapi/src/main/scala/com/netflix/atlas/webapi/PublishApi.scala

Occasionally it is useful to sample this if the client
is ignoring the response.

additional logging for rejected datapoints

---

atlas-core/src/main/scala/com/netflix/atlas/core/util/StringMatcher.scala
atlas-core/src/test/scala/com/netflix/atlas/core/util/StringMatcherSuite.scala
atlas-jmh/src/main/scala/com/netflix/atlas/core/util/StringMatching.scala
atlas-jmh/src/main/scala/com/netflix/atlas/core/util/StringMatchingOr.scala
atlas-jmh/src/main/scala/com/netflix/atlas/core/util/StringMatchingPrefix.scala

In the streaming execution, up to 25% of the CPU usage is
checking regular expressions. This change improves the
chances that checks will be able to quickly fail without
needing regex by always checking the fixed prefix when
known in the matches function. This wasn't done before
because when evaluating with the index we already know
the prefix matches before checking.

short circuit pattern matching with prefix check

---

atlas-core/src/main/scala/com/netflix/atlas/core/util/Strings.scala
atlas-core/src/test/scala/com/netflix/atlas/core/util/StringsSuite.scala
atlas-eval/src/main/scala/com/netflix/atlas/eval/graph/GraphConfig.scala

There are a number of internal libs that have this same
logic of computing a time range based on parsed start and
end times that can be relative to each other. Move to a
helper function of Strings so it is easier to reuse.

add timeRange helper function

---

atlas-core/src/main/scala/com/netflix/atlas/core/model/MathExpr.scala
atlas-core/src/main/scala/com/netflix/atlas/core/model/MathVocabulary.scala

The `:random` operator is mostly used for generating sample
data that has some noise. However, in its current form the
values will change every time it runs. When experimenting with
expressions this makes it hard to reason about because the
input is always changing.
Now it will be based on a hash of the timestamp so it is
reproducible. There is also now a seeded variant, `:srandom`
that can be used if multiple sample lines are needed with
different noise.
Fixes #847.

make random operator deterministic

---

atlas-webapi/src/main/scala/com/netflix/atlas/webapi/ExprApi.scala
atlas-webapi/src/test/scala/com/netflix/atlas/webapi/ExprApiSuite.scala

The normalize endpoint will now ensure that variable in
the legend pattern consistently used parenthesis.
Fixes #863.

normalize variable style for legends

---

atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/Evaluator.java
atlas-eval/src/test/scala/com/netflix/atlas/eval/stream/EvaluatorSuite.scala

Verify the equals/hashCode contracts are satisfied. Also
check that DataSource and DataSources can be encoded and
decoded from JSON correctly. Needed to consume for replay
logging.

add test cases for Evaluator model objects

---

atlas-core/src/main/scala/com/netflix/atlas/core/util/StringMatcher.scala
atlas-core/src/test/scala/com/netflix/atlas/core/util/StringMatcherSuite.scala

When running on Spark it needs to be able to serialize
the matchers if regex is used in an expression.

fix serialization issues with StringMatcher

---

atlas-akka/src/main/scala/com/netflix/atlas/akka/StreamOps.scala
atlas-akka/src/test/scala/com/netflix/atlas/akka/StreamOpsSuite.scala
atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/EvaluatorImpl.scala
atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/StreamContext.scala

Adds a StreamOps helper class with utilities to monitor
source queue behavior and delays at a particular stage
in a flow. The flow monitoring can be used to understand
whether the producer or consumer is faster and where we
are getting backpressure delays.

 improve monitoring of eval flow

---

atlas-akka/src/test/scala/com/netflix/atlas/akka/StreamOpsSuite.scala
atlas-eval/src/test/scala/com/netflix/atlas/eval/stream/EurekaGroupsLookupSuite.scala
atlas-eval/src/test/scala/com/netflix/atlas/eval/stream/EvaluatorSuite.scala
atlas-eval/src/test/scala/com/netflix/atlas/eval/stream/FinalExprEvalSuite.scala
atlas-eval/src/test/scala/com/netflix/atlas/eval/stream/SubscriptionManagerSuite.scala

In #865, a new DataSource constructor was added to allow
the frequency to be specified and the previous constructor
was deprecated. The deprecated constructor was being used
in some of the test cases causing a lot of warnings.

fix deprecation warnings for DataSource ctor

---

atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/StreamApi.scala
atlas-lwcapi/src/test/scala/com/netflix/atlas/lwcapi/StreamApiSuite.scala

The old mechanism of pushing the stats messages was lost
inadvertantly as part of #871. Changed to a simple heartbeat
message since the stats are now checked as part of the queue
for the stream.

add heartbeat messages back to StreamApi

---

atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/QueueHandler.scala
atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/StreamApi.scala
atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/StreamSubscriptionManager.scala
atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/SubscriptionManager.scala
atlas-lwcapi/src/test/scala/com/netflix/atlas/lwcapi/ExpressionApiSuite.scala
atlas-lwcapi/src/test/scala/com/netflix/atlas/lwcapi/SubscribeApiSuite.scala

Adds some debug logging for all of the modification
operations on the subscription manager. Also enables
trace logging for the messages going to each stream.

additional logging for SubscriptionManager

---

atlas-akka/src/main/scala/com/netflix/atlas/akka/ActorService.scala
atlas-akka/src/main/scala/com/netflix/atlas/akka/WebServer.scala
atlas-module-akka/src/main/scala/com/netflix/atlas/akka/AkkaModule.scala

It was being shutdown by ActorService and WebServer. Also
since it could be used by other classes that do not inject
those, the ActorSystem could be shutdown in the wrong order.
This change moves it to a dedicated provider so it will be
shutdown in the correct order.

fix shutdown for ActorSystem

---

atlas-json/src/main/scala/com/netflix/atlas/json/Json.scala
atlas-json/src/test/scala/com/netflix/atlas/json/JsonSuite.scala

Can be useful for cases where there is a need to do some
basic structural inspection before mapping into an internal
value type.

add Json.decode that takes a JsonNode object

---

atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/SubscriptionManager.scala
atlas-lwcapi/src/test/scala/com/netflix/atlas/lwcapi/SubscriptionManagerSuite.scala

Before the short circuit behavior meant that only the first
new handler would get added.

fix subscribe for streams with multiple subs

---

atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/StreamApi.scala
atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/SubscriptionManager.scala
atlas-lwcapi/src/test/scala/com/netflix/atlas/lwcapi/SubscriptionManagerSuite.scala

There is a race condition on reconnects where the new
connection can come in before the stream for the old
connection is closed. The cleanup for the old connection
will then unregister the stream id. This is a short-term
work around to ensure running streams have a registered
handler and track the number of events that we see.

re-register handler if needed on heartbeat

---

atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/StreamApi.scala
atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/SubscriptionManager.scala
atlas-lwcapi/src/test/scala/com/netflix/atlas/lwcapi/SubscriptionManagerSuite.scala

Helps to reduce the amount of churn we see for changes
when looking at the logs.

ensure subs are maintained for re-register check

---

atlas-poller-cloudwatch/src/main/resources/reference.conf
atlas-poller-cloudwatch/src/main/scala/com/netflix/atlas/cloudwatch/DefaultTagger.scala
atlas-poller-cloudwatch/src/test/scala/com/netflix/atlas/cloudwatch/DefaultTaggerSuite.scala
atlas-poller-cloudwatch/src/test/scala/com/netflix/atlas/cloudwatch/NetflixTaggerSuite.scala

Some dimension values are decorated with information that reduces
readability without providing value (e.g., ALBs and NLBs). This commit
introduces a new `extractors` configuration within the `tagger` that
enables specifying a regex to capture the relevant portion of the name.

extract the name portion of the target group dimension

---

atlas-poller-cloudwatch/src/main/resources/reference.conf

The `LoadBalancer` dimension is specified as the final portion of the
load balancer ARN. For example:
`app/load-balancer-name/1234567890123456`

 extract the name from the load balancer dimension

---

atlas-poller-cloudwatch/src/main/resources/reference.conf
atlas-poller-cloudwatch/src/test/scala/com/netflix/atlas/cloudwatch/DefaultTaggerSuite.scala

Configure the app|net matching as a non-capturing group, so the correct
portion is extracted.
As I was thinking about the addition of NLB metrics, I realized the
previous commits don't handle conditional mapping of `LoadBalancer`
which will need to set `aws.alb` or `aws.nlb` depending on the context.
In the course of writing a passing case for `aws.alb` and a failing one
for `aws.nlb`, this bug was uncovered. I'll fix the ALB vs NLB handling
in a separate commit.

fix `LoadBalancer` extractor pattern

---

atlas-poller-cloudwatch/src/main/resources/reference.conf
atlas-poller-cloudwatch/src/main/scala/com/netflix/atlas/cloudwatch/DefaultTagger.scala
atlas-poller-cloudwatch/src/test/scala/com/netflix/atlas/cloudwatch/DefaultTaggerSuite.scala

CloudWatch uses the `LoadBalancer` dimension for both application and
network load balancers. This commit adds the ability to set an alias per
extractor pattern, enabling us to set it to `aws.alb` or `aws.nlb` as
appropriate depending on the context.

conditionally apply an alias per pattern

---

atlas-akka/src/main/scala/com/netflix/atlas/akka/AccessLogger.scala
atlas-akka/src/main/scala/com/netflix/atlas/akka/CustomDirectives.scala
atlas-akka/src/test/scala/com/netflix/atlas/akka/CustomDirectivesSuite.scala
build.sbt
project/Dependencies.scala

Makes Atlas consistent with other Netflix apps following
the common-ipc pattern internally.

switch to spectator-ext-ipc for request metrics

---

atlas-akka/src/main/scala/com/netflix/atlas/akka/ConfigApi.scala
atlas-akka/src/main/scala/com/netflix/atlas/akka/CustomDirectives.scala
atlas-akka/src/main/scala/com/netflix/atlas/akka/HealthcheckApi.scala
atlas-akka/src/test/scala/com/netflix/atlas/akka/CustomDirectivesSuite.scala
atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/EvaluateApi.scala
atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/ExpressionApi.scala
atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/StreamApi.scala
atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/SubscribeApi.scala
atlas-webapi/src/main/scala/com/netflix/atlas/webapi/ExprApi.scala
atlas-webapi/src/main/scala/com/netflix/atlas/webapi/GraphApi.scala
atlas-webapi/src/main/scala/com/netflix/atlas/webapi/PublishApi.scala
atlas-webapi/src/main/scala/com/netflix/atlas/webapi/TagsApi.scala

To improve the quality of metrics it is useful to be able
to see what path is being used. However, it shouldn't match
the full path that might have ids or other elements that
would make the cardinality explode. This change adds path
directives that will capture specified static portions and
map those to the `Netflix-Endpoint` header.
Note, when nested with other usages of the standard path
directives it will capture extracted portions from those
directives and include it in the header. While not ideal,
it isn't a common case and since the IPC logger has limiting
it will mostly impact the user with the broad matching.

add directives for setting Netflix-Endpoint header

---

atlas-akka/src/main/resources/reference.conf
atlas-akka/src/main/scala/com/netflix/atlas/akka/CustomDirectives.scala
atlas-akka/src/main/scala/com/netflix/atlas/akka/RequestHandler.scala
atlas-akka/src/test/scala/com/netflix/atlas/akka/CustomDirectivesSuite.scala
atlas-akka/src/test/scala/com/netflix/atlas/akka/RequestHandlerSuite.scala
atlas-akka/src/test/scala/com/netflix/atlas/akka/TestApi.scala

This can be used to add headers such as `Netflix-ASG`
or `Netflix-Zone` that are used by common IPC to provide
additional context.

add support for configurable diagnostic headers

---

atlas-lwcapi/src/main/resources/reference.conf
atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/StartupDelayService.scala
atlas-lwcapi/src/test/scala/com/netflix/atlas/lwcapi/StartupDelayServiceSuite.scala
atlas-module-lwcapi/src/main/scala/com/netflix/atlas/guice/LwcApiModule.scala

This delay is used to keep the service in an unhealthy
state for a specified window. Clients that publish data
use the load balancer and will not start publishing until
it is healthy. The eval library that does the subscriptions
will attemtp to connect once it detects the new instance.
This delay means that subscriptions should be in place
before data starts flowing.

add hook to control startup delay for lwcapi

---

atlas-poller-cloudwatch/src/main/resources/nlb.conf
atlas-poller-cloudwatch/src/main/resources/reference.conf

`ConsumedLCUs` is available only on the `LoadBalancer` dimension, not
`LoadBalancer` and `AvailabilityZone`.

Fix reporting of AWS/NetworkELB ConsumedLCUs

---

atlas-eval/src/main/scala/com/netflix/atlas/eval/model/AggrDatapoint.scala
atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/EvaluatorImpl.scala
atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/TimeGrouped.scala
atlas-eval/src/test/scala/com/netflix/atlas/eval/stream/TimeGroupedSuite.scala

This helps reduce the amount of memory required when
evaluating an expression. If a 1k node cluster is
sending data for a single sum expression, then it will
now result in a single value being maintained in the
time grouping stage rather than keeping one per node
until the final evaluation.

aggregate datapoints while grouping

---

atlas-eval/src/main/scala/com/netflix/atlas/eval/model/AggrDatapoint.scala
atlas-eval/src/main/scala/com/netflix/atlas/eval/model/TimeGroup.scala
atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/EvaluatorImpl.scala
atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/FinalExprEval.scala
atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/TimeGrouped.scala
atlas-eval/src/test/scala/com/netflix/atlas/eval/stream/FinalExprEvalSuite.scala
atlas-eval/src/test/scala/com/netflix/atlas/eval/stream/TimeGroupedSuite.scala

The TimeGrouped stage needs to group by the DataExpr
to aggregate the values as they arrive. It was then
flattening these out to keep the stage output the
same. Since the only consumer is FinalExprEval and
it needs them grouped by DataExpr, this change
maintains the grouping and passes it along.

maintain grouping by DataExpr

---

atlas-core/src/main/scala/com/netflix/atlas/core/algorithm/OnlineAlgorithm.scala
atlas-core/src/main/scala/com/netflix/atlas/core/algorithm/OnlineRollingMax.scala
atlas-core/src/main/scala/com/netflix/atlas/core/algorithm/OnlineRollingMin.scala
atlas-core/src/main/scala/com/netflix/atlas/core/algorithm/RollingBuffer.scala
atlas-core/src/test/scala/com/netflix/atlas/core/algorithm/BaseOnlineAlgorithmSuite.scala
atlas-core/src/test/scala/com/netflix/atlas/core/algorithm/OnlineAlgorithmSuite.scala
atlas-core/src/test/scala/com/netflix/atlas/core/algorithm/OnlineRollingMaxSuite.scala
atlas-core/src/test/scala/com/netflix/atlas/core/algorithm/OnlineRollingMinSuite.scala
atlas-core/src/test/scala/com/netflix/atlas/core/algorithm/RollingBufferSuite.scala

Also sets up a base OnlineAlgorithm trait that can be
used to get better reuse consuming the operations. The
state can be captured as a Config object to make it easy
to save the previous state and restore if needed.
Will refactor DES helpers to use the same pattern in a
follow up PR.

add helpers for rolling min/max

---

atlas-poller-cloudwatch/src/main/resources/rds.conf
atlas-poller-cloudwatch/src/main/scala/com/netflix/atlas/cloudwatch/CloudWatchPoller.scala
atlas-poller-cloudwatch/src/main/scala/com/netflix/atlas/cloudwatch/GetMetricActor.scala
atlas-poller-cloudwatch/src/main/scala/com/netflix/atlas/cloudwatch/MetricCategory.scala
atlas-poller-cloudwatch/src/test/scala/com/netflix/atlas/cloudwatch/ConversionsSuite.scala
atlas-poller-cloudwatch/src/test/scala/com/netflix/atlas/cloudwatch/MetricCategorySuite.scala
atlas-poller-cloudwatch/src/test/scala/com/netflix/atlas/cloudwatch/MetricDataSuite.scala
atlas-poller-cloudwatch/src/test/scala/com/netflix/atlas/cloudwatch/MetricDefinitionSuite.scala

This commit adds a mechanism to specify how long the system should
smooth out unreported CloudWatch metrics before ceasing to send them.
CloudWatch will return 0 metrics in at least two cases:
1. No metrics were recorded.
2. The resource has been removed, but metrics for it still fall within
the retention window.
I've made this optional and configurable at the metric category level to
tactically address the issue for RDS reported by a user and to minimize
visual clutter in the config. Depending on usage in practice, we may
want to require it to be specified for every category or lift the scope
to make it consistent at the global level.

Add optional CloudWatch metric timeout

---

atlas-poller-cloudwatch/src/main/scala/com/netflix/atlas/cloudwatch/MetricCategory.scala

Improves the wording of the `timeout` parameter doc vs previous commit:
CloudWatch will return 0 metrics for at least two cases:
- No metrics were recorded.
- The resource has been removed, metrics still show up when listing
metrics due to the retention window, but the specified time interval
for the metric statistics request is after the removal.

Minor improvement to `MetricCategory` doc

---

atlas-eval/src/main/scala/com/netflix/atlas/eval/model/AggrDatapoint.scala
atlas-eval/src/test/scala/com/netflix/atlas/eval/stream/TimeGroupedSuite.scala

The aggregate datapoint will already have been converted
from a raw value to a base count at the source. So when
it is received here it should behave just like a simple
sum. Before it was converting the datapoint to a 1 or 0
when aggregating as well which can lead to drastically
smaller count than expected if the source has many time
series for the query.

fix behavior for aggregating count

---

atlas-core/src/main/scala/com/netflix/atlas/core/algorithm/OnlineAlgorithm.scala
atlas-core/src/main/scala/com/netflix/atlas/core/algorithm/OnlineIgnoreN.scala
atlas-core/src/main/scala/com/netflix/atlas/core/algorithm/Pipeline.scala
atlas-core/src/test/scala/com/netflix/atlas/core/algorithm/OnlineIgnoreNSuite.scala
atlas-core/src/test/scala/com/netflix/atlas/core/algorithm/PipelineSuite.scala

Adds an online algorithm to ignore the first N values. This
can be used with sliding DES to align to a step boundary
before starting the DES computation.
Also adds a pipeline that can be used to chain together a
sequence of online algorithms while conforming to the same
interface.

add ignore and pipeline helpers for step alignment

---

atlas-core/src/main/scala/com/netflix/atlas/core/model/StatefulExpr.scala
atlas-core/src/main/scala/com/netflix/atlas/core/model/StatefulVocabulary.scala

Add operators requested for alerting use-cases:
- `delay`: can be used as an alternative to `:offset` for
use-cases short offsets that need to run in the streaming
path. Also it can be applied to any time series instead of
just data expressions.
- `rolling-min`: track the minimum value seen within a
window. For data that is mostly smooth, but has some noise
this can be a useful way to get a reasonable lower bound
with little tuning required.
- `rolling-max`: similar to `rolling-min` only using the max
to get an upper bound.
Also refactors DES operators to use a new common base trait
that works for any implementation of OnlineAlgorithm.

add :delay, :rolling-min, and :rolling-max

---

atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/EvaluatorImpl.scala
atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/LwcToAggrDatapoint.scala
atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/ReplayLogging.scala
atlas-eval/src/test/scala/com/netflix/atlas/eval/stream/LwcToAggrDatapointSuite.scala
atlas-jmh/src/main/scala/com/netflix/atlas/eval/stream/ByteStringDecode.scala

Refactor stream to avoid decoding into a String as an
intermediate step before parsing the JSON payloads. This
yields about a 16% reduction in bytes allocated per message
for the sample data tested.

avoid unnecessary string allocations

---

atlas-eval/src/main/scala/com/netflix/atlas/eval/model/LwcDataExpr.scala
atlas-eval/src/main/scala/com/netflix/atlas/eval/model/LwcDatapoint.scala
atlas-eval/src/main/scala/com/netflix/atlas/eval/model/LwcExpression.scala
atlas-eval/src/main/scala/com/netflix/atlas/eval/model/LwcMessages.scala
atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/LwcToAggrDatapoint.scala
atlas-eval/src/test/scala/com/netflix/atlas/eval/model/LwcMessagesSuite.scala
atlas-eval/src/test/scala/com/netflix/atlas/eval/stream/HostSourceSuite.scala
atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/StreamApi.scala
atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/SubscribeApi.scala
atlas-lwcapi/src/test/scala/com/netflix/atlas/lwcapi/SubscribeApiSuite.scala
build.sbt

Adds a websocket endpoint `/api/v1/subscribe` that can be
used for both updating the set of subscriptions and receiving
the stream of data. This also begins some changes to help
improve consistency with other Atlas APIs, namely the messages
rename `frequency` to `step` and the `/lwc` prefix is removed
from the endpoint path. For now there is an alias so the eval
client will still work with the messages coming from older
lwcapi services running.
This change also use the model objects from the eval client
on the server side for the websocket endpoint to help ensure
better consistency of the messages in the future. The old
endpoints have not been changed to preserve compatibility
during the transition.
Current plan:
1) Deploy updated lwcapi service with the new endpoint. The
client will …

initial websocket support for lwcapi

---

atlas-eval/src/main/scala/com/netflix/atlas/eval/model/LwcDiagnosticMessage.scala
atlas-eval/src/main/scala/com/netflix/atlas/eval/model/LwcMessages.scala
atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/EvaluatorImpl.scala
atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/ExprInterpreter.scala
atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/LwcToAggrDatapoint.scala
atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/StreamContext.scala
atlas-eval/src/test/scala/com/netflix/atlas/eval/model/LwcMessagesSuite.scala
atlas-eval/src/test/scala/com/netflix/atlas/eval/stream/LwcToAggrDatapointSuite.scala
atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/EvaluateApi.scala
atlas-lwcapi/src/test/scala/com/netflix/atlas/lwcapi/EvaluateApiSuite.scala

Adds support for diagnostic messages to be sent to the
evaluate api along with the data values. This can be used
for the publisher to send diagnostic messages that will
be received by a particular subscriber. An example use-case
is to reject an expression due to the amount of load already
on the publisher.

diagnostic messages from publisher to subscriber

---

atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/LwcToAggrDatapoint.scala
atlas-eval/src/test/scala/com/netflix/atlas/eval/stream/LwcToAggrDatapointSuite.scala

Since the diagnostic message is not being pushed to the
stream it should always pull. Test case has been updated
to catch the problem where before processing would stop
after the first diagnostic message.

fix pull for diagnostic messages

---

atlas-eval/src/main/scala/com/netflix/atlas/eval/model/AggrDatapoint.scala
atlas-eval/src/main/scala/com/netflix/atlas/eval/model/LwcHeartbeat.scala
atlas-eval/src/main/scala/com/netflix/atlas/eval/model/LwcMessages.scala
atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/LwcToAggrDatapoint.scala
atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/TimeGrouped.scala
atlas-eval/src/test/scala/com/netflix/atlas/eval/model/LwcMessagesSuite.scala
atlas-eval/src/test/scala/com/netflix/atlas/eval/stream/LwcToAggrDatapointSuite.scala
atlas-eval/src/test/scala/com/netflix/atlas/eval/stream/TimeGroupedSuite.scala
atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/StreamApi.scala
atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/SubscribeApi.scala
atlas-lwcapi/src/test/scala/com/netflix/atlas/lwcapi/SubscribeApiSuite.scala

The eval client for consuming LWC data uses the timestamps
in the messages so it can be used to run on live or captured
data that may have old timestamps. If there is a subscription
to an expression that doesn't match any data, then no messages
will go through and thus the time grouping will not be flushed
for a given interval.
This change allows the server to send heartbeats with the
timestamp and step so it can ensure there will always be at
least one message coming though for a given stream. When
running on previously captured data it will also include the
heartbeat messages and exhibit the same behavior.

lwc: server to client time notifications

---

atlas-eval/src/main/scala/com/netflix/atlas/eval/model/TimeGroup.scala
atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/TimeGrouped.scala
atlas-eval/src/test/scala/com/netflix/atlas/eval/stream/FinalExprEvalSuite.scala
atlas-eval/src/test/scala/com/netflix/atlas/eval/stream/TimeGroupedSuite.scala

If it is flushed via a heartbeat instead of data, then it
could be empty and the step size cannot be extracted from
the data.

store step size for TimeGroup

---

atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/ExpressionSplitter.scala
atlas-lwcapi/src/test/scala/com/netflix/atlas/lwcapi/ExpressionSplitterSuite.scala

Before the style variant of offset would not get expanded
and the expression would appear to work.

expand style offset for lwcapi

---

atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/EvaluatorImpl.scala
atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/StreamContext.scala
atlas-eval/src/test/scala/com/netflix/atlas/eval/stream/LwcToAggrDatapointSuite.scala

Computes the data expr map when the data sources are updated
instead of when doing a lookup for logging. Reduces the
overhead later in the stream if there are a lot of diagnostic
messages.

pre-compute data expr map

---

atlas-eval/src/main/resources/reference.conf
atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/ExprInterpreter.scala
atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/StreamContext.scala
atlas-eval/src/test/scala/com/netflix/atlas/eval/stream/EvaluatorSuite.scala
atlas-eval/src/test/scala/com/netflix/atlas/eval/stream/TestContext.scala

Adds sanity checks that the query can be efficiently
indexed with at least one exact match clause. Overly
broad tag keys that would apply to almost all datapoints
can be excluded via the configuration.

improve early expr validation for eval lib

---

atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/HostSource.scala

Current testing indicates the largest chunk of CPU time
server side is in the GZIP compression. The akka directive
doesn't easily allow for configuring it with `BEST_SPEED`
instead of `BEST_COMPRESSION`. Further on the client side,
the largest chunk of allocations is for the decompression.
Overall it seems preferable right now to use more bandwidth
and avoid the compression. Will revisit after web-socket
change and switching to binary encoding for stream.

do not request gzip for /stream call

---

atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/SubscribeApi.scala
atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/SubscriptionManager.scala
atlas-lwcapi/src/test/scala/com/netflix/atlas/lwcapi/SubscriptionManagerSuite.scala

When running for a lot of expressions this can be a
significant number of messages. In most cases the set
of subscriptions do not change that often.

only send LwcSubscription for new subscriptions

---

atlas-lwcapi/src/main/resources/reference.conf
atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/StreamApi.scala
atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/SubscribeApi.scala
atlas-lwcapi/src/test/scala/com/netflix/atlas/lwcapi/SubscribeApiSuite.scala

Add `atlas.lwcapi.queue-size` setting for controlling the
max number of items to queue up per stream before dropping.

make queue size configurable

---

atlas-akka/src/main/scala/com/netflix/atlas/akka/StreamOps.scala
atlas-akka/src/test/scala/com/netflix/atlas/akka/StreamOpsSuite.scala
atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/EvaluatorImpl.scala
atlas-jmh/src/main/scala/com/netflix/atlas/akka/SourceQueueBench.scala
atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/QueueHandler.scala
atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/StreamApi.scala
atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/SubscribeApi.scala
atlas-lwcapi/src/test/scala/com/netflix/atlas/lwcapi/ExpressionApiSuite.scala
atlas-lwcapi/src/test/scala/com/netflix/atlas/lwcapi/SubscribeApiSuite.scala

The default `Source.queue` has quite a bit of overhead and
the input must be throttled based on the future to bound the
memory use. `Source.actorRef` has a bit less overhead, but
has the same unbounded memory use if it cannot keep up and
does not provide a reasonable way to throttle the input.
This change uses a custom source stage based on the java
ArrayBlockingQueue. There is significantly less overhead and
the memory usage is bounded even with an offer and forget
usage style.

switch to source based on BlockingQueue

---

atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/Evaluator.java
atlas-eval/src/test/scala/com/netflix/atlas/eval/stream/EvaluatorSuite.scala

If a step size is not explicitly supplied as part of the
data source, then try to extract it based on the step param
of the uri before falling back to the default of 1m. This
allows `Evaluator.createPublisher` to work with a custom
step size.

extract the step size from the uri

---

atlas-core/src/main/scala/com/netflix/atlas/core/util/Strings.scala
atlas-core/src/test/scala/com/netflix/atlas/core/util/HashSuite.scala
atlas-core/src/test/scala/com/netflix/atlas/core/util/StringsSuite.scala
atlas-eval/src/test/scala/com/netflix/atlas/eval/graph/GrapherSuite.scala
atlas-jmh/src/main/scala/com/netflix/atlas/core/util/ZeroPad.scala
atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/ExpressionApi.scala
atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/ExpressionMetadata.scala
atlas-webapi/src/test/scala/com/netflix/atlas/webapi/GraphApiSuite.scala
atlas-wiki/src/main/scala/com/netflix/atlas/wiki/GraphHelper.scala

Avoids creating a BigInteger object from the hash array
just for the purposes of creating the hex string.

reduce overhead for creating hash strings

---

atlas-eval/src/main/scala/com/netflix/atlas/eval/model/LwcDatapoint.scala
atlas-eval/src/test/scala/com/netflix/atlas/eval/model/LwcMessagesSuite.scala
atlas-jmh/src/main/scala/com/netflix/atlas/eval/model/LwcDatapointEncode.scala

Avoid using databind to automatically encode as this is
a hot path that is called many times on lwcapi for sending
the datapoints to the user.

optimize json encoding for lwc datapoint

---

atlas-core/src/main/scala/com/netflix/atlas/core/util/PngImage.scala

Should avoid tmp files that get created by default when
rendering images. Also helps avoid problems on shared
clusters when /tmp fills up.

disable use of cache for ImageIO

---

atlas-webapi/src/main/resources/reference.conf
atlas-webapi/src/main/scala/com/netflix/atlas/webapi/ApiSettings.scala
atlas-webapi/src/main/scala/com/netflix/atlas/webapi/PublishApi.scala

For general use it is not recommended to change this, but
making it configurable to facilitate experimentation and
testing.

add config setting for max tags permitted

---

atlas-core/src/main/scala/com/netflix/atlas/core/index/RoaringTagIndex.scala
atlas-jmh/src/main/scala/com/netflix/atlas/core/index/RoaringTagIndexBench.scala

For tags that are repeated across many metrics, this change
prunes the item set by doing a lookup for that key value. The
`andNot` is quite a bit faster than iterating the matches.
It mostly impacts queries that are projecting all values for
a common tag without other restrictions.
For the sample benchmark, findValuesAllOne is the only one
to show a noticeable change as expected. Before it was about
4864.472 ops/s and after 357671.851 ops/s.
Trying it on real data, it is mostly faster, but there are a
handful of cases where it is a bit slower. The table below
shows mean time per operation in milliseconds for a handful
of common queries:
| *URI*                | *Before*  | *After*   |
|----------------------|-----------|-----------|
| `/nf.app`            | 115.5     | 26.9      |
| …

improve performance of findValues for common tags

---

atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/LwcToAggrDatapoint.scala
atlas-eval/src/test/scala/com/netflix/atlas/eval/stream/LwcToAggrDatapointSuite.scala

This will prevent the stream from failing and just log
the invalid message that was received to help with debugging.
If this does occur it isn't clear that the stream will
recover, but there is a metric to detect that bad messsages
were received.

add check for invalid messages in the stream

---

atlas-core/src/main/scala/com/netflix/atlas/core/model/Query.scala
atlas-core/src/test/scala/com/netflix/atlas/core/model/QuerySuite.scala
atlas-jmh/src/main/scala/com/netflix/atlas/core/model/KeyValueQuery.scala

For the LWC bridge flame graphs show a lot of time being
spent on accessing the values. Futher allocation profiles
show a lot of allocations for the temporary Option that
isn't needed. This change adds a special case that uses
`SmallHashMap.getOrNull` when possible to avoid the extra
overhead.

avoid Option allocation for queries

---

atlas-eval/src/main/resources/reference.conf
atlas-eval/src/main/scala/com/netflix/atlas/eval/graph/DefaultSettings.scala
atlas-eval/src/main/scala/com/netflix/atlas/eval/graph/Grapher.scala
atlas-webapi/src/main/scala/com/netflix/atlas/webapi/GraphApi.scala
atlas-webapi/src/main/scala/com/netflix/atlas/webapi/GraphRequestActor.scala
atlas-webapi/src/test/scala/com/netflix/atlas/webapi/GraphApiMemDbSuite.scala
atlas-webapi/src/test/scala/com/netflix/atlas/webapi/GraphApiSuite.scala

There are some programmatic use-cases for accessing images
such as alerting emails and bots for including in chat apps.
The current behavior makes it hard to detect errors with the
images because it is embedded within the image text and has
a 200 response code. This changes the graph api behavior to
only use error images when the access appears to be coming
from a web browser.

only use error images for browsers

---

atlas-core/src/main/scala/com/netflix/atlas/core/util/IntRefHashMap.scala
atlas-core/src/test/scala/com/netflix/atlas/core/util/IntRefHashMapSuite.scala

Updates IntRefHashMap to just use the int value as the hash
code just like IntIntMap and Integer.hashCode. This makes them
more consistent. In tests on real data the overhead of computing
the murmur hash outweighs the benefits it provides.

use same hash for IntRefHashMap and IntIntMap

---

atlas-chart/src/main/scala/com/netflix/atlas/chart/graphics/Ticks.scala
atlas-chart/src/test/scala/com/netflix/atlas/chart/graphics/TicksSuite.scala

If the upper bound exactly matched `10 * factor` for the
selected unit prefix, then it would use a different selection
to avoid large numbers for the tick labels. However, for an
exact match it is better to use the default prefix to avoid
getting zeros due to rounding with the larger prefix.

fix #948, all zeros shown on y-axis

---

atlas-core/src/main/scala/com/netflix/atlas/core/model/DataVocabulary.scala
atlas-core/src/test/scala/com/netflix/atlas/core/model/NamedRewriteSuite.scala

The rewrites that look like aggregation functions will now
work with custom consolidations. If used the rewrite will
not be preserved in the model. So the output of converting
the parsed expression model to a string will be the expanded
expression and not indicate the rewrite was used.

fix #763, custom consolidation with rewrites

---

atlas-core/src/main/scala/com/netflix/atlas/core/model/MathVocabulary.scala
atlas-core/src/test/scala/com/netflix/atlas/core/model/MathGroupBySuite.scala

Before, attempting a group by on non-grouped expressions
without a math aggregate function would behave differently
than a non-grouped expression with a math aggregate. Now
they have the same behavior and the group by will be ignored
for expression trees that do not support it.

fix #852, inconsistent group by behavior

---

atlas-chart/src/main/scala/com/netflix/atlas/chart/util/PngImage.scala
atlas-chart/src/test/scala/com/netflix/atlas/chart/util/PngImageSuite.scala

When using the `-release 8` option the internal `PNGMetadata`
class is not found in the classpath. Update the usage to rely
on the public APIs.

use standard IIOMetadata classes for PNG

---

.travis.yml

This is no longer needed for the Atlas build.

remove redis from travis config

---

project/BuildSettings.scala

After switching to use jdk11 for the build, the java classes
were getting compiled to class version 55 instead of 52.

set --release for javac

---

atlas-core/src/main/scala/com/netflix/atlas/core/algorithm/OnlineAlgorithm.scala

In the docs site it is getting config 1.2 in the sbt
classpath. There isn't an obvious way to force it to
a newer version. The older version will fail if trying
to convert a ConfigValue to a ConfigValue. For now we
can workaround the problem by special casing that to
avoid the unnecessary conversion.

avoid conversion if already a ConfigValue

---

atlas-core/src/main/scala/com/netflix/atlas/core/algorithm/AlgoState.scala
atlas-core/src/main/scala/com/netflix/atlas/core/algorithm/OnlineAlgorithm.scala
atlas-core/src/main/scala/com/netflix/atlas/core/algorithm/OnlineDelay.scala
atlas-core/src/main/scala/com/netflix/atlas/core/algorithm/OnlineDes.scala
atlas-core/src/main/scala/com/netflix/atlas/core/algorithm/OnlineIgnoreN.scala
atlas-core/src/main/scala/com/netflix/atlas/core/algorithm/OnlineRollingMax.scala
atlas-core/src/main/scala/com/netflix/atlas/core/algorithm/OnlineRollingMin.scala
atlas-core/src/main/scala/com/netflix/atlas/core/algorithm/OnlineSlidingDes.scala
atlas-core/src/main/scala/com/netflix/atlas/core/algorithm/Pipeline.scala
atlas-core/src/main/scala/com/netflix/atlas/core/algorithm/RollingBuffer.scala
atlas-core/src/main/scala/com/netflix/atlas/core/model/StatefulExpr.scala
atlas-core/src/test/scala/com/netflix/atlas/core/algorithm/AlgoStateSuite.scala
atlas-core/src/test/scala/com/netflix/atlas/core/algorithm/OnlineAlgorithmSuite.scala
atlas-core/src/test/scala/com/netflix/atlas/core/algorithm/RollingBufferSuite.scala
build.sbt

Before it was using a Config object for convenience. This
switches it to a dedicated object that can be easily used
with `Json.encode/decode` or other similar tools. This should
also be more efficient for the more common use-cases because
we can avoid creation of the needless config objects.

use dedicated object for algo state

---

atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/Evaluator.java
atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/EvaluatorImpl.scala
atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/StreamContext.scala
atlas-eval/src/test/scala/com/netflix/atlas/eval/stream/EvaluatorSuite.scala

This can be used as an upfront check to filter out bad
data sources rather than getting the failure via the
stream.

add helper function to validation a datasource

---

atlas-core/src/main/scala/com/netflix/atlas/core/model/StyleExpr.scala
atlas-eval/src/main/scala/com/netflix/atlas/eval/graph/Grapher.scala
atlas-eval/src/test/scala/com/netflix/atlas/eval/graph/GrapherSuite.scala

The stat vars are desired for substitutions (#878), but should
not be included in the tag maps for the output. The output tags
should be stable over time if evaluated incrementally. Including
the stats breaks this because the values are dependent on the
data for that time slice.

remove stat vars from output tags

---

.travis.yml

Since 2.11 doesn't support the `--release` option, building
on a newer version can lead to errors when running on jdk8.
Specifically the return type of some methods changed in jdk9+.
This should fix errors like:
```
Cause: java.lang.NoSuchMethodError: java.nio.CharBuffer.clear()Ljava/nio/CharBuffer;
at com.netflix.atlas.core.model.TaggedItem$.writePair(TaggedItem.scala:59)
at com.netflix.atlas.core.model.TaggedItem$.computeId(TaggedItem.scala:105)
```

use jdk8 for building the scala 2.11 artifacts

---

atlas-poller-cloudwatch/src/main/resources/reference.conf
atlas-poller-cloudwatch/src/main/scala/com/netflix/atlas/cloudwatch/CloudWatchPoller.scala

We're hitting CloudWatch rate limits on a regular basis. However, the
AWS limits should be sufficient for our overall per second call rate in
the majority of cases. The current pattern of calls has bursts when the
`Tick` message kicks off a collection, which causes the call rate to
spike above the per second limit. This commit introduces call rate
limiting to smooth out the request pattern.
The Akka documentation for throttling request/response actor
communication is incomplete. Through iteration playing around in a local
toy app, I arrived at the implementation herein and confirmed that it
works as expected.

Throttle calls to CloudWatch

---

atlas-json/src/main/scala/com/netflix/atlas/json/Reflection.scala

This class was renamed in scala 2.13 (scala/scala@870131b).

refactor to avoid AssignOrNamedArg

---

atlas-core/src/main/scala/com/netflix/atlas/core/index/QueryIndex.scala
atlas-lwcapi/src/test/scala/com/netflix/atlas/lwcapi/ExpressionApiSuite.scala

Flame graphs on the prod clusters show a bit of overhead
for filter and exists calls on the list of entries. This
change converts it to a simple array and avoids using the
collections framework methods. For the existing JMH test
this resulted in about a 12% improvement.

QueryIndex: reduce overhead for checking entries

---

atlas-core/src/main/scala/com/netflix/atlas/core/util/SmallHashMap.scala
atlas-jmh/src/main/scala/com/netflix/atlas/core/util/BoxesRuntime.scala
atlas-jmh/src/main/scala/com/netflix/atlas/core/util/SmallHashMapJavaGet.scala

For the QueryIndex on the streaming clusters a hot spot
is `SmallHashMap.get`. Flame graphs show a significant
and unnecessary overhead being `BoxesRunTime.equals`.
This change updates 7 places in the code to avoid that
call:
**Before**
```
$ javap -verbose ./atlas-core/target/scala-2.12/classes/com/netflix/atlas/core/util/SmallHashMap.class | grep Boxes
46: invokestatic  #1101               // Method scala/runtime/BoxesRunTime.equals:(Ljava/lang/Object;Ljava/lang/Object;)Z
79: invokestatic  #1101               // Method scala/runtime/BoxesRunTime.equals:(Ljava/lang/Object;Ljava/lang/Object;)Z
105: invokestatic  #1101               // Method scala/runtime/BoxesRunTime.equals:(Ljava/lang/Object;Ljava/lang/Object;)Z
40: invokestatic  #1155               // Method …
```

avoid BoxesRunTime.equals for SmallHashMap

---

project/Dependencies.scala

Fixes a number of security vulnerabilities. Most of these
are [serialization gadgets].
[serialization gadgets]: https://medium.com/@cowtowncoder/on-jackson-cves-dont-panic-here-is-what-you-need-to-know-54cd0d6e8062

1.5: update to latest jackson 2.8.x

---

atlas-eval/README.md

Reference to reactive streams publisher didn't match.

fix link on eval lib readme

---

atlas-poller-cloudwatch/src/main/resources/nlb.conf

See
* https://aws.amazon.com/about-aws/whats-new/2019/01/network-load-balancer-now-supports-tls-termination/
* https://docs.aws.amazon.com/elasticloadbalancing/latest/network/load-balancer-cloudwatch-metrics.html

Add NetworkELB TLS metrics

---

atlas-poller-cloudwatch/src/main/resources/billing.conf
atlas-poller-cloudwatch/src/main/resources/dynamodb.conf
atlas-poller-cloudwatch/src/main/resources/ec2.conf
atlas-poller-cloudwatch/src/main/resources/es.conf
atlas-poller-cloudwatch/src/main/resources/s3.conf
atlas-poller-cloudwatch/src/main/resources/sns.conf
atlas-poller-cloudwatch/src/main/resources/sqs.conf
atlas-poller-cloudwatch/src/main/resources/trustedadvisor.conf
atlas-poller-cloudwatch/src/main/scala/com/netflix/atlas/cloudwatch/CloudWatchPoller.scala
atlas-poller-cloudwatch/src/main/scala/com/netflix/atlas/cloudwatch/GetMetricActor.scala
atlas-poller-cloudwatch/src/main/scala/com/netflix/atlas/cloudwatch/MetricCategory.scala
atlas-poller-cloudwatch/src/test/scala/com/netflix/atlas/cloudwatch/ConversionsSuite.scala
atlas-poller-cloudwatch/src/test/scala/com/netflix/atlas/cloudwatch/MetricDataSuite.scala
atlas-poller-cloudwatch/src/test/scala/com/netflix/atlas/cloudwatch/MetricDefinitionSuite.scala

This is the first of potentially multiple commits to improve handling
of CloudWatch metric lag. This first commit makes the time range of
the query configurable and adds a metric to track the age (in
CloudWatch periods) of the latest datapoint returned. This will enable
assessing the distribution of ages across the namespaces and metrics
collected. Those data will influence the approach for datapoints that
are older than Atlas will accept.

Improve CloudWatch metric lag handling

---

atlas-poller/src/main/scala/com/netflix/atlas/poller/PollerManager.scala

Clearly log the initialization failure as an error for the
poller manager. Avoids this getting overlooked if the detailed
actor logging is not enabled.

improve logging for poller actor failures

---

atlas-poller-cloudwatch/src/main/resources/lambda.conf
atlas-poller-cloudwatch/src/main/scala/com/netflix/atlas/cloudwatch/CloudWatchPoller.scala
atlas-poller-cloudwatch/src/test/scala/com/netflix/atlas/cloudwatch/MetricCategorySuite.scala
atlas-poller-cloudwatch/src/test/scala/com/netflix/atlas/cloudwatch/NetflixTaggerSuite.scala
atlas-poller/src/main/scala/com/netflix/atlas/poller/PollerManager.scala

The code that loads `MetricCategory` instances from the config expects
the `dimension` field, even if it's empty. This was causing the service
to silently fail.
In addition to fixing the `lambda` config, I've added tests that load
the production config to improve the chances we'll catch this at build
time. I've also added logging, so the problem will be evident in the
logs.

Fix lambda config

---

Makefile

`git fetch --unshallow` was being used to get tags to set the artifact
version. This has started failing on one of the builds. This commit
switches to explicitly fetching tags via `git fetch --tags`.

Ensure git tags are available for build

---

Makefile

This did not have the desired affect and seems to have caused the 2.11
build to no longer work.
This reverts commit 7f30c26.

Revert "Ensure git tags are available for build"

---

.travis.yml

Switch to linux/trusty for 2.12 build to match the 2.11 build. This is
to observe whether the issue determining the version to use for
publication has an OS component.

Switch to linux/trusty for 2.12 build

---

.travis.yml
Makefile

Expermient showed that the 2.12 build with linux/trusty _does_ result in
the correct version.

Switch 2.12 build back to `osx`

---

atlas-core/src/main/scala/com/netflix/atlas/core/model/MathExpr.scala
atlas-core/src/test/scala/com/netflix/atlas/core/model/NamedRewriteSuite.scala

In some cases when the rewrite was not being used like
an aggregate function, the offset would get lost.
Fixes #1021.

preserve offset for named rewrites

---

atlas-core/src/main/scala/com/netflix/atlas/core/model/StatefulVocabulary.scala

fix typo in rolling-{min,max} descriptions

---

atlas-core/src/main/scala/com/netflix/atlas/core/algorithm/OnlineAlgorithm.scala
atlas-core/src/main/scala/com/netflix/atlas/core/algorithm/OnlineRollingSum.scala
atlas-core/src/main/scala/com/netflix/atlas/core/model/StatefulExpr.scala
atlas-core/src/main/scala/com/netflix/atlas/core/model/StatefulVocabulary.scala
atlas-core/src/test/scala/com/netflix/atlas/core/algorithm/OnlineRollingSumSuite.scala

Sum of the values within a specified window. The sum will only be emitted
if there are at least a minimum number of actual values (not `NaN`) within
the window. Otherwise `NaN` will be emitted for that time period.

Add rolling-sum stateful operator

---

atlas-core/src/main/scala/com/netflix/atlas/core/model/MathExpr.scala
atlas-core/src/test/scala/com/netflix/atlas/core/model/PercentilesSuite.scala

The spectator-js client had a bug (Netflix/spectator-js#22)
leading to duplicate values for a given count. This change
updates the error message so it is easier to understand what
is happening. Before it would just say `assertion failed`.

improve error message for invalid percentile data

---

atlas-core/src/main/scala/com/netflix/atlas/core/db/MemoryDatabase.scala
atlas-core/src/test/scala/com/netflix/atlas/core/db/MemoryDatabaseSuite.scala

Backport of #1031 to 1.5.x.
The set of tags for the aggregated lines should be limited
to the set that are exact matches in the query or are a part
of a group by. Otherwise the grouping can have incorrect
duplicates in the result set.
Fixes #629.

1.5: fix tag results on MemoryDatabase.execute

---

atlas-core/src/main/scala/com/netflix/atlas/core/algorithm/OnlineAlgorithm.scala
atlas-core/src/main/scala/com/netflix/atlas/core/algorithm/OnlineDelay.scala
atlas-core/src/main/scala/com/netflix/atlas/core/algorithm/OnlineDerivative.scala
atlas-core/src/main/scala/com/netflix/atlas/core/algorithm/OnlineDes.scala
atlas-core/src/main/scala/com/netflix/atlas/core/algorithm/OnlineIgnoreN.scala
atlas-core/src/main/scala/com/netflix/atlas/core/algorithm/OnlineIntegral.scala
atlas-core/src/main/scala/com/netflix/atlas/core/algorithm/OnlineRollingCount.scala
atlas-core/src/main/scala/com/netflix/atlas/core/algorithm/OnlineRollingMax.scala
atlas-core/src/main/scala/com/netflix/atlas/core/algorithm/OnlineRollingMean.scala
atlas-core/src/main/scala/com/netflix/atlas/core/algorithm/OnlineRollingMin.scala
atlas-core/src/main/scala/com/netflix/atlas/core/algorithm/OnlineRollingSum.scala
atlas-core/src/main/scala/com/netflix/atlas/core/algorithm/OnlineSlidingDes.scala
atlas-core/src/main/scala/com/netflix/atlas/core/algorithm/OnlineTrend.scala
atlas-core/src/main/scala/com/netflix/atlas/core/algorithm/Pipeline.scala
atlas-core/src/main/scala/com/netflix/atlas/core/algorithm/RollingBuffer.scala
atlas-core/src/main/scala/com/netflix/atlas/core/model/StatefulExpr.scala
atlas-core/src/test/scala/com/netflix/atlas/core/algorithm/OnlineDelaySuite.scala
atlas-core/src/test/scala/com/netflix/atlas/core/algorithm/OnlineDerivativeSuite.scala
atlas-core/src/test/scala/com/netflix/atlas/core/algorithm/OnlineDesSuite.scala
atlas-core/src/test/scala/com/netflix/atlas/core/algorithm/OnlineRollingCountSuite.scala
atlas-core/src/test/scala/com/netflix/atlas/core/algorithm/OnlineRollingMaxSuite.scala
atlas-core/src/test/scala/com/netflix/atlas/core/algorithm/OnlineRollingMeanSuite.scala
atlas-core/src/test/scala/com/netflix/atlas/core/algorithm/OnlineRollingMinSuite.scala
atlas-core/src/test/scala/com/netflix/atlas/core/algorithm/OnlineRollingSumSuite.scala
atlas-core/src/test/scala/com/netflix/atlas/core/algorithm/OnlineTrendSuite.scala
atlas-core/src/test/scala/com/netflix/atlas/core/model/DerivativeSuite.scala

Updates the online algorithms used with stateful operators
to detect if the state is effectively empty. In that case
the state will be dropped from the state map maintained
during evaluation. This is useful to avoid leaking memory
for tracking the state during long running streaming
evaluations.
There are currently three exceptions that have an unbounded
window and never become empty: ignore-N, sdes, and integral.
Integral is generally not very useful in a streaming context
so we may just prohibit that operation. For sdes (and ignore-N
which is typically only used to align sdes), the current uses
do not involve group by operations, so it shouldn't be an
issue for now. We'll revisit in the future when there are
concrete use-cases that are problematic for that operation.

detect empty state and stop tracking it

---

atlas-core/src/main/scala/com/netflix/atlas/core/model/StatefulExpr.scala
atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/FinalExprEval.scala
atlas-eval/src/test/scala/com/netflix/atlas/eval/stream/FinalExprEvalSuite.scala

Before, if a line was sparse, for example an error counter
that has a lot of gaps, the state would be handled incorrectly.
There would be one state item per matching grouping when data
was present and they would only get moved forward if there was
data for that key in a given interval. For intervals with no
data, a no data line would get pushed through and have its own
independent state.
With this change, an empty group by result will push an empty
data set through eval and it will now move the state buffers
to allow for expiration and correct handling of subsequent
intervals with data. If there is no resulting data lines from
the overall expression, then a no data line for the overall
expression will be emitted to the user.

fix eval state for sparse lines with group by
