- .travis.yml
http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/
> enable container based build

- atlas-core/src/main/scala/com/netflix/atlas/core/db/MemoryDatabase.scala
- project/BuildSettings.scala
With java 8 the ConcurrentHashMap has a built in
method, computeIfAbsent, for just this use-case.
> simplify getOrCreateBlockStore

- atlas-wiki/src/main/resources/_Sidebar.md
- atlas-wiki/src/main/resources/examples/Bounds.md
- atlas-wiki/src/main/resources/examples/Group-By-Percentage.md
- atlas-wiki/src/main/resources/examples/Legends.md
- atlas-wiki/src/main/resources/examples/Line-Colors.md
- atlas-wiki/src/main/resources/examples/Line-on-Area.md
- atlas-wiki/src/main/resources/examples/Logarithmic-Axis.md
- atlas-wiki/src/main/resources/examples/Multiple-Lines.md
- atlas-wiki/src/main/resources/examples/Single-Line.md
- atlas-wiki/src/main/resources/examples/Stack.md
- atlas-wiki/src/main/resources/examples/Time-Shift.md
- atlas-wiki/src/main/resources/examples/Time-Zone.md
- atlas-wiki/src/main/resources/examples/Title.md
- atlas-wiki/src/main/resources/examples/Transparency.md
- atlas-wiki/src/main/resources/examples/_Sidebar.md
Split out the examples to individual pages with
a separate sidebar to aid in quick navigation.
> break out examples

- project/Dependencies.scala
This version fixes occasional NPE on startup:
```
WARN  com.netflix.spectator.gc.GcLogger - exception thrown by event listener
java.lang.NullPointerException
at com.netflix.spectator.http.RxHttp.getServersForVip(RxHttp.java:561) ~[spectator-nflx-plugin-0.18.jar:?]
at com.netflix.spectator.http.RxHttp.getServers(RxHttp.java:542) ~[spectator-nflx-plugin-0.18.jar:?]
at com.netflix.spectator.http.RxHttp.post(RxHttp.java:171) ~[spectator-nflx-plugin-0.18.jar:?]
at com.netflix.spectator.http.RxHttp.postJson(RxHttp.java:188) ~[spectator-nflx-plugin-0.18.jar:?]
at com.netflix.spectator.nflx.ChronosGcEventListener.sendToChronos(ChronosGcEventListener.java:109) ~[spectator-nflx-plugin-0.18.jar:?]
at com.netflix.spectator.nflx.ChronosGcEventListener.onComplete(ChronosGcEventListener.java:161) …
```
> spectator-0.19

- atlas-aws/src/main/resources/reference.conf
- project/Dependencies.scala
Update version of aws-java-sdk and update the aws
reference conf to include kinesis and security token
endpoints.
> aws-java-sdk-1.9.23

- atlas-core/src/main/scala/com/netflix/atlas/core/util/SmallHashMap.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/validation/HasKeyRule.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/validation/KeyLengthRule.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/validation/KeyPatternRule.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/validation/MaxUserTagsRule.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/validation/NonStandardKeyRule.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/validation/Rule.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/validation/TagRule.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/validation/ValidCharactersRule.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/validation/ValidationResult.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/validation/ValueLengthRule.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/validation/ValuePatternRule.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/validation/HasKeyRuleSuite.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/validation/KeyLengthRuleSuite.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/validation/KeyPatternRuleSuite.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/validation/MaxUserTagsRuleSuite.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/validation/NonStandardKeyRuleSuite.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/validation/RuleSuite.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/validation/ValidCharactersRuleSuite.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/validation/ValueLengthRuleSuite.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/validation/ValuePatternRuleSuite.scala
- atlas-webapi/src/main/resources/reference.conf
- atlas-webapi/src/main/scala/com/netflix/atlas/webapi/ApiSettings.scala
- atlas-webapi/src/main/scala/com/netflix/atlas/webapi/LocalPublishActor.scala
- atlas-webapi/src/main/scala/com/netflix/atlas/webapi/PublishApi.scala
- atlas-webapi/src/test/scala/com/netflix/atlas/webapi/ApiSettingsSuite.scala
- atlas-webapi/src/test/scala/com/netflix/atlas/webapi/PublishApiSuite.scala
Merging in some of the internal validation rules we
use to sanity check the data flowing in.
> validation rules for published data

- project/Dependencies.scala
Fixes an issue with non-numeric values like NaN and Infinity
that occur on buffer boundaries.
> jackson 2.5.2

- project/Dependencies.scala
Updating to match other jackson libs.
> jackson-module-scala-2.5.2

- atlas-akka/src/main/scala/com/netflix/atlas/akka/ServerStats.scala
the parameter names added for greater readability
> initializing case class Stats with parameter names for gaining better readability

- atlas-core/src/main/scala/com/netflix/atlas/core/model/StatefulVocabulary.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/model/StyleVocabulary.scala
- atlas-wiki/src/main/resources/DES.md
* adds visualization helper
* update DES wiki page to discuss the epic helpers
* change signal helper to allow the upper/lower bound
to be disabled by specifying the percentage as NaN
> add helper for visualizing des-epic-signal

- atlas-standalone/src/main/scala/com/netflix/atlas/standalone/Main.scala
- project/Dependencies.scala
Bump dependency versions, mainly to get updated iep with
name change for guice helper.
> iep 0.1.22

- atlas-akka/src/main/scala/com/netflix/atlas/akka/RequestHandlerActor.scala
- atlas-akka/src/test/scala/com/netflix/atlas/akka/RequestHandlerActorSuite.scala
- atlas-akka/src/test/scala/com/netflix/atlas/akka/TestApi.scala
Back port change to automatically handle compressed data.
> add directive to automatically decompress entity

- atlas-chart/src/main/resources/reference.conf
- atlas-chart/src/main/scala/com/netflix/atlas/chart/graphics/Constants.scala
Will likely get refactored out of constants at some
point in the future, but for now making it configurable
at startup.
> setting to control the fonts used

- atlas-core/src/main/scala/com/netflix/atlas/core/util/SmallHashMap.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/validation/HasKeyRule.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/validation/KeyLengthRule.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/validation/KeyPatternRule.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/validation/MaxUserTagsRule.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/validation/NonStandardKeyRule.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/validation/Rule.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/validation/TagRule.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/validation/ValidCharactersRule.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/validation/ValidationResult.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/validation/ValueLengthRule.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/validation/ValuePatternRule.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/validation/HasKeyRuleSuite.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/validation/KeyLengthRuleSuite.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/validation/KeyPatternRuleSuite.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/validation/MaxUserTagsRuleSuite.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/validation/NonStandardKeyRuleSuite.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/validation/RuleSuite.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/validation/ValidCharactersRuleSuite.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/validation/ValueLengthRuleSuite.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/validation/ValuePatternRuleSuite.scala
- atlas-webapi/src/main/resources/reference.conf
- atlas-webapi/src/main/scala/com/netflix/atlas/webapi/ApiSettings.scala
- atlas-webapi/src/main/scala/com/netflix/atlas/webapi/LocalPublishActor.scala
- atlas-webapi/src/main/scala/com/netflix/atlas/webapi/PublishApi.scala
- atlas-webapi/src/test/scala/com/netflix/atlas/webapi/ApiSettingsSuite.scala
- atlas-webapi/src/test/scala/com/netflix/atlas/webapi/PublishApiSuite.scala
- project/Dependencies.scala
Backport validation rules, in particular support for `publish.max-age` setting.
> fixes #175, backport validation rules

- atlas-core/src/main/scala/com/netflix/atlas/core/index/LazyTagIndex.scala
A large number of allocations were for creating a
string representation of the id. The original reason
was to allow specifying the offset as a simple prefix
of the id hash. In practice we don't rely on that
and all uses seem to be of the full id. By doing the
lookup using the `BigInteger` and not creating the
string copies we significantly reduce the allocation
rate.
For a simple test application the average allocation
rate for a 5m sample window went from 29 MB/s to
20 MB/s.
> reduce allocations for reindexing

- atlas-akka/src/main/scala/com/netflix/atlas/akka/RequestHandlerActor.scala
Updates the routes so that the OPTIONS pre-flight
request will include the CORS headers. This is needed
by at least chrome if certain conditions apply, in
particular, adding various headers.
Example for testing with XMLHttpRequest and the newer
fetch call:
```html
<html>
<head>
<script>
// https://developers.google.com/web/updates/2015/03/introduction-to-fetch?hl=en
var url = 'http://localhost:7101/api/v1/tags/nf.region';
function reqListener() {
var data = JSON.parse(this.responseText);
console.log('info xmlhttprequest: ' + data);
}
function reqError(err) {
console.log('error xmlhttprequest: ', err);
}
var oReq = new XMLHttpRequest();
oReq.onload = reqListener;
oReq.onerror = reqError;
oReq.open('get', url, true);
oReq.setRequestHeader('X-Netflix.client.appid', 'foo');
oReq.send(); …
```
> add cors headers on pre-flight request

- atlas-core/src/main/scala/com/netflix/atlas/core/model/StatefulVocabulary.scala
* Discuss area under line so it is more likely to come up
in search results.
* Describe when to use with per-step for counters.
* Add example table and clarify NaN behavior.
> docs: update summary description for integral

- atlas-wiki/src/main/resources/Concepts.md
- atlas-wiki/src/main/resources/_Sidebar.md
Expands on time series, tagging, and how measured samples
get mapped to stored values. Still need to add more information
for aggregation and consolidation, but that can be a later
update.
> docs: add more details to concepts page

- atlas-akka/src/main/scala/com/netflix/atlas/akka/HealthcheckApi.scala
- atlas-akka/src/main/scala/com/netflix/atlas/akka/RequestHandlerActor.scala
- atlas-akka/src/main/scala/com/netflix/atlas/akka/WebServer.scala
- atlas-akka/src/test/scala/com/netflix/atlas/akka/HealthcheckApiSuite.scala
- project/Dependencies.scala
To aid in debugging summarize the service state in the
response.
> add status for each service in response

- project/Dependencies.scala
Fixes bug with ArrayIndexOutOfBoundsException.
> spectator 0.38.1

- .travis.yml
https://docs.travis-ci.com/user/trusty-ci-environment/
> use trusty build environment

- atlas-core/src/main/scala/com/netflix/atlas/core/model/StatefulExpr.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/model/DesSuite.scala
Fix :sdes to return identical values if passed as a single batch or incrementally.
> Sdes streaming

- atlas-core/src/main/scala/com/netflix/atlas/core/util/IntHashSet.scala
See #390 for further details. Deployments with the map
changes look good overnight. Changing set to be consistent.
> make set load factor consistent with map

- project/plugins.sbt
Newer version has convenient option for profiling
with flight recorder: `-prof jmh.extras.JFR`.
> update jmh plugin

- project/Build.scala
- project/Dependencies.scala
Makes it easier to automatically detect for tools
that want to index scala libraries.
> fix #401, add scala version to artifact id

- atlas-core/src/main/scala/com/netflix/atlas/core/db/MemoryDatabase.scala
The datapoint passed in computes the id on demand which
can be slow. The tag map is immutable and has a cached
hash code and is thus much cheaper for the initial lookup.
> use tag map for block store lookup

- atlas-akka/src/main/resources/reference.conf
- atlas-akka/src/main/scala/com/netflix/atlas/akka/ActorService.scala
- atlas-akka/src/main/scala/com/netflix/atlas/akka/WebServer.scala
Looks for routing config on routed actors including the
request-handler.
> look for routing config on loaded actors

- atlas-module-akka/src/main/scala/com/netflix/atlas/akka/AkkaModule.scala
- atlas-module-akka/src/test/scala/com/netflix/atlas/akka/AkkaModuleSuite.scala
- atlas-module-cloudwatch/src/main/scala/com/netflix/atlas/guice/CloudWatchModule.scala
- atlas-module-cloudwatch/src/test/scala/com/netflix/atlas/guice/CloudWatchModuleSuite.scala
- atlas-module-webapi/src/main/scala/com/netflix/atlas/guice/WebApiModule.scala
- atlas-module-webapi/src/test/scala/com/netflix/atlas/guice/WebApiModuleSuite.scala
Changes the guice modules to be final and implement
equals and hashCode so that guice will dedup if it
is installed multiple times.
> update modules to dedup

- atlas-poller-cloudwatch/src/main/scala/com/netflix/atlas/cloudwatch/CloudWatchPoller.scala
CloudWatch graphs will frequently show gaps if there is
low activity and if the reporting frequency is much larger
than the step size used with Atlas. With this change we'll
use an explicit zero value.
> fill with zero for periods of inactivity

- atlas-webapi/src/main/scala/com/netflix/atlas/webapi/LocalPublishActor.scala
The counter was not getting incremented.
> fix update of invalid datapoints metric

- atlas-json/src/main/scala/com/netflix/atlas/json/CaseClassDeserializer.scala
- atlas-json/src/main/scala/com/netflix/atlas/json/Reflection.scala
- atlas-json/src/test/scala/com/netflix/atlas/json/CaseClassDeserializerSuite.scala
- project/Dependencies.scala
Have custom case class deserializer honor `@JsonProperty`
annotations on the fields.
> honor jackson annotations on case class params

- atlas-json/src/main/scala/com/netflix/atlas/json/CaseClassDeserializer.scala
- atlas-json/src/test/scala/com/netflix/atlas/json/CaseClassDeserializerSuite.scala
This was getting ignored before.
> fix handling for JsonDeserialize(using=...)

- atlas-core/src/main/scala/com/netflix/atlas/core/index/LazyTagIndex.scala
The largest group of allocations when rebuilding
the index was for Tuple2 objects created as part
of looping over the tags. This adjusts the structure
of the maps a bit so we can avoid creating those
objects.
> reduce Tuple2 allocations when building index

- atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/ExpressionApi.scala
- atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/ExpressionWithFrequency.scala
- atlas-lwcapi/src/test/scala/com/netflix/atlas/lwcapi/ExpressionApiSuite.scala
- atlas-lwcapi/src/test/scala/com/netflix/atlas/lwcapi/ExpressionWithFrequencySuite.scala
Implement ETag header and If-None-Match handling for expression list.
> implement etags

- atlas-core/src/main/scala/com/netflix/atlas/core/model/MathExpr.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/model/PercentilesSuite.scala
In some use-cases the internal legacy system will try to
eval with an explicit no data line being passed to the
percentile operator. This results in an error:
```
java.util.NoSuchElementException: key not found: percentile
```
With this change we just propagate the no data line if
the input does not contain the expected tags.
> workaround for `:percentiles` on no data line

- atlas-akka/src/main/scala/com/netflix/atlas/akka/CustomDirectives.scala
- atlas-akka/src/main/scala/com/netflix/atlas/akka/RequestHandler.scala
Moves the handler for CORS preflight checks to
CustomDirectives and adds a `cors` helper for
wrapping a route with both the preflight handler
and filter to add CORS headers to the inner route.
This change allows the CORS support to be used
without pulling in all of the standard options
from the default request handler.
> allow preflight check to be used separately

- atlas-module-eval/src/main/resources/META-INF/services/com.google.inject.Module
- atlas-module-eval/src/main/scala/com/netflix/atlas/eval/EvalModule.scala
- atlas-module-eval/src/test/scala/com/netflix/atlas/eval/EvalModuleSuite.scala
- build.sbt
Minimal module that can setup an evaluator instance
that can be injected.
> add module for configuring evaluator

- atlas-wiki/src/main/resources/_Sidebar.md
Fixes the spacing so that it will render correctly
on the wiki.
> fix spacing on sidebar header

- atlas-core/src/main/scala/com/netflix/atlas/core/util/Hash.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/util/IntHashSet.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/util/IntIntHashMap.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/util/LongIntHashMap.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/util/RefIntHashMap.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/util/SmallHashMap.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/util/DoubleIntHashMapSuite.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/util/IntHashSetSuite.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/util/IntIntHashMapSuite.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/util/LongIntHashMapSuite.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/util/RefIntHashMapSuite.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/util/SmallHashMapSuite.scala
- atlas-jmh/src/main/scala/com/netflix/atlas/core/util/SmallHashMapModify.scala
- atlas-poller-cloudwatch/src/main/resources/sqs.conf
- atlas-webapi/src/main/resources/reference.conf
- project/BuildSettings.scala
Backport select bug fixes from 1.6 branch to 1.5 branch.
> backport bug fixes to 1.5.x

- atlas-core/src/main/scala/com/netflix/atlas/core/index/RoaringTagIndex.scala
The use of the int set was a carry over from the lazy
set implementation. This removes some steps saving
memory and computation cost when building the index.
> create bitmap directly instead of through int set

- project/Dependencies.scala
Fixes security vulnerability:
http://doc.akka.io/docs/akka-http/10.0.6/security/2017-05-03-illegal-media-range-in-accept-header-causes-stackoverflowerror.html
> akka-http 10.0.6

- atlas-core/src/main/scala/com/netflix/atlas/core/model/StyleVocabulary.scala
In particular discuss the use of variables in the
legends.
> docs: expand description for legend

- atlas-webapi/src/main/scala/com/netflix/atlas/webapi/FetchRequestActor.scala
If there is no data for an expression in a given
chunk window, then drop that data.
> suppress chunks that are all NaN

- atlas-core/src/main/scala/com/netflix/atlas/core/index/RoaringTagIndex.scala
> fix warning for offset

- atlas-webapi/src/test/scala/com/netflix/atlas/webapi/PublishApiJsonSuite.scala
Make sure encoding/decoding of datapoint works as
expected.
> add test case for decoding datapoint

- scripts/publish-test.sh
> fix spelling in publish-test script

- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/EvaluatorImpl.scala
- atlas-eval/src/test/scala/com/netflix/atlas/eval/stream/EvaluatorSuite.scala
Fixes #574. Improves the error message returned if the
input URI is missing required parameters. It has also
been changed to get returned as a diagnostic message
as part of the stream so that a single bad URI will not
stop the processor for all evaluations.
> improve error message when missing uri param

- atlas-poller-cloudwatch/src/main/resources/reference.conf
- atlas-poller-cloudwatch/src/main/resources/s3-request.conf
Collect s3 request metrics if enabled. They need to get
enabled for a given bucket to be available.
> add mapping for s3 request metrics

- .travis.yml
- project/Dependencies.scala
It is supposed to have improved compiler performance.
> update to scala 2.12.3

- atlas-poller-cloudwatch/src/main/resources/sqs.conf
> fix prefix for SQS message size metric

- project/Dependencies.scala
Fixes race condition with the idle timeout on the
host connection pool (akka/akka-http#1245).
> akka-http 10.0.10

- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/Evaluator.java
The usage is:
```
$ cat uris.txt | project/sbt "atlas-eval/run additional.conf"
```
> add simple main to Evaluator for debug uses

- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/DataSourceManager.scala
Before the log line would get really long and unweildy
if there were a lot of sources added or removed. Now
the info level log will just show the overall number and
debug level if enabled will show the individual sources
as separate entries.
> cleanup log messages for added and removed sources

- atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/SubscribeApi.scala
- atlas-lwcapi/src/test/scala/com/netflix/atlas/lwcapi/SubscribeApiSuite.scala
Before when using `/v1/subscribe` the set of expressions
would keep growing. Now the set of expressions will be
synced with the list provided. The user is responsible for
keeping track of the list of needed expressions.
> sync the set of expressions for subscribe requests

- atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/SubscribeApi.scala
- atlas-lwcapi/src/test/scala/com/netflix/atlas/lwcapi/SubscribeApiSuite.scala
Additional test case for syncing multiple expressions
with the `/v1/subscribe` api. Fixes the set of removed
ids to be computed across all expressions rather than
individually for each split.
> add test case for syncing multiple expressions

- atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/SubscribeApi.scala
- atlas-lwcapi/src/test/scala/com/netflix/atlas/lwcapi/SubscribeApiSuite.scala
The actor was removed in #671.
> remove unused ref to subscribe actor

- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/Evaluator.java
The source would stop as soon as the input was processed
and then main would complete. This change adds a repeat
to keep it going until the user decides to stop the process.
> Evaluator.main stops immediately

- project/Dependencies.scala
Improves support for jdk9. Gets us closer to #695.
> akka 2.5.6

- atlas-eval/src/test/scala/com/netflix/atlas/eval/stream/FinalExprEvalSuite.scala
Adds some test cases for the FinalExprEval step of the
atlas-eval library. Could not reproduce #693.
/cc @zimmermatt
> more test cases for FinalExprEval step

- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/EurekaGroupsLookup.scala
- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/EurekaSource.scala
- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/EvaluatorImpl.scala
- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/StreamContext.scala
- atlas-eval/src/test/scala/com/netflix/atlas/eval/stream/EurekaGroupsLookupSuite.scala
- atlas-eval/src/test/scala/com/netflix/atlas/eval/stream/EurekaSourceSuite.scala
- atlas-eval/src/test/scala/com/netflix/atlas/eval/stream/SubscriptionManagerSuite.scala
Fixes the code to discard the entity when the status
is something other than 200 OK.
> consume Eureka response body if status not OK

- .travis.yml
- scripts/buildViaTravis.sh
Update travis so we build on both jdk8 and jdk9.
> fix #695, enable build for jdk9

- project/Dependencies.scala
Fixes possible NPE when computing hash code of ids.
> specator 0.58.2

- .travis.yml
- project/Dependencies.scala
> scala 2.12.4

- project/Dependencies.scala
scala version must be 2.12.3 due to
https://github.com/sbt/sbt/issues/3560.
> set scala version to 2.12.3.

- CONTRIBUTING.md
- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/FinalExprEval.scala
- atlas-eval/src/test/scala/com/netflix/atlas/eval/stream/FinalExprEvalSuite.scala
- project/Dependencies.scala
Insert diagnostic message summarizing input datapoint counts and
post aggregation counts for time series expressions.
> improve diagnostic messages for lwc evaluation (#694).

- atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/ExpressionSplitter.scala
On instance type with a large number of cores the cache
introduced in #730 starts to make things worse because
of heavy thread contention with the `computeIfAbsent`
calls used for interning the queries and internally to
the LoadingCache. This change refactors the calls to
do a get/put which may result in recomputing some values,
but avoids the blocking. See Netflix/spectator#352 for
a similar issue we had before.
This change was manually pushed to a test node and I
confirmed that the blocked threads are no longer present.
/cc @zimmermatt
> reduce thread contention for splitter cache

- atlas-core/src/main/scala/com/netflix/atlas/core/stacklang/StandardVocabulary.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/stacklang/FreezeSuite.scala
Add tests for all words that perform an execute.
> additional test cases for :freeze

- project/Dependencies.scala
- project/build.properties
Fixes some of the previous problems, see #725
and #731 for details.
> update to sbt 1.0.4 and scala 2.12.4

- atlas-core/src/main/scala/com/netflix/atlas/core/db/BlockStore.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/db/MemoryBlockStoreSuite.scala
When looking at some test results related to #737, I'm
seeing that the block stats reported are often higher
than the counts from jmap. Still not sure why, the cleanup
and reporting seems to be working correctly in the test
cases.
> additional test cases for block counts

- project/Dependencies.scala
Has rewrite of client connection pool that might help
with some of the sporadic issues we are seeing. Note,
the new pool needs to be explicitly enabled.
> akka-http 10.0.11

- project/Dependencies.scala
This pulls in a fix for an equality bug, see:
RoaringBitmap/RoaringBitmap#195. This bug may
be the cause of some strange matching issues
we have seen with certain regex queries.
> roaring bitmap 0.6.66

- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/TimeGrouped.scala
- atlas-eval/src/test/scala/com/netflix/atlas/eval/stream/TimeGroupedSuite.scala
If we get timestamps from the the future, then it can
mess up the time based grouping for the input. Before
the buckets for the grouping would adjust to the future
time and current data would get dropped as being too
old.
/cc @ruchirj
> eval: reject datapoints that are from the future

- project/Dependencies.scala
Changes default connection pool implementation. So far the
new implementation looks fine based on test deployment with
the RC2 release.
> akka-http 10.1.0

- atlas-poller-cloudwatch/src/main/resources/rds.conf
This will help detect Transaction ID Wraparound in postgresql databases.
See: https://aws.amazon.com/blogs/database/implement-an-early-warning-system-for-transaction-id-wraparound-in-amazon-rds-for-postgresql/
for details
> Collect maximumUsedTranactionIds from cloudwatch

- atlas-poller-cloudwatch/src/main/scala/com/netflix/atlas/cloudwatch/CloudWatchPoller.scala
For smaller deployments it would take time to fill up the
entire batch causing a significant delay in the publishing.
Now it will flush based on the age even if the batch is not
yet full.
> ensure batches are regularly pushed

- atlas-akka/src/test/scala/com/netflix/atlas/akka/ServerStatsActorSuite.scala
- atlas-poller/src/test/scala/com/netflix/atlas/poller/PollerManagerSuite.scala
- project/Dependencies.scala
Needed to make progress on #721.
> 1.5.x: update dependencies for jdk9

- project/build.properties
Needed to run on jdk9 or higher.
> 1.5.x: sbt 0.13.17

- atlas-poller-cloudwatch/src/main/resources/rds.conf
The value is the number of seconds of lag.
> add mapping for RDS replica lag

- atlas-poller-cloudwatch/src/main/resources/rds.conf
This addresses the following issue:
https://github.com/Netflix/atlas/issues/845
> add cloudwatch rds FreeStorageSpace metric

- atlas-eval/src/main/scala/com/netflix/atlas/eval/graph/DefaultSettings.scala
- atlas-json/src/main/scala/com/netflix/atlas/json/CaseClassDeserializer.scala
- atlas-webapi/src/main/scala/com/netflix/atlas/webapi/ApiSettings.scala
> remove deprecated usage of Class.newInstance

- atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/StreamApi.scala
Allows us to see if elements are being dropped when added
to the queue and track the delays on the SSE stream to the
client.
> add monitoring to response stream for lwcapi

- atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/StreamApi.scala
Ensure that the subscription is removed when the client
goes away.
> unregister when stream terminates

- atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/EvaluateApi.scala
Track this using a distribution summary so it is easier
to compute the average and we can see the max number of
items coming in a request.
> use dist summary for eval payload size

- atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/SubscriptionManager.scala
Checks whether a change to the handlers was actually made
before logging. Makes it easier to understand what the real
changes were instead of all streams in the batch.
> only log the actual changes to the handlers

- project/Dependencies.scala
Adds settings to avoid DoS due to excessive memory usage:
https://akka.io/blog/news/2018/08/30/akka-http-dos-vulnerability-found
> akka-http 10.1.5

- atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/SubscriptionManager.scala
Only log on changes to reduce noise and follow the same
behavior as register/unregister.
> make subscribe logs consistent with register

- atlas-core/src/main/scala/com/netflix/atlas/core/algorithm/OnlineAlgorithm.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/algorithm/OnlineDes.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/algorithm/OnlineSlidingDes.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/model/StatefulExpr.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/algorithm/OnlineDesSuite.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/algorithm/OnlineSlidingDesSuite.scala
Make the DES operations use the base trait adding in #910.
> update des and sliding des to use base trait

- .travis.yml
- project/Dependencies.scala
It is supposed to improve compiler performance.
> update to scala 2.12.7

- atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/StreamApi.scala
In stream api move the mapping from SSERenderable to
a ChunkStreamPart to after the heartbeat source has
been merged with the queue of data coming from the
evaluate api.
> reduce duplication for SSE to chunk part

- atlas-core/src/main/scala/com/netflix/atlas/core/index/QueryIndex.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/model/Query.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/model/QuerySuite.scala
Makes it easier to reuse some of this logic for static
analysis of queries.
> common helper for expanding :in clauses

- atlas-akka/src/test/scala/com/netflix/atlas/akka/StreamOpsSuite.scala
If the stream did not start fast enough and pull on the
queue source, then the first future will be inserted in
the queue rather than passed through and the second future
could be dropped.
> fix flakey test case

- project/Dependencies.scala
Has a number of security fixes:
https://groups.google.com/forum/#!topic/jackson-user/8jdpNS1dQPQ
https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.9.8
> update to jackson 2.9.8

- atlas-core/src/main/scala/com/netflix/atlas/core/algorithm/OnlineAlgorithm.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/algorithm/OnlineDerivative.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/algorithm/OnlineIntegral.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/algorithm/OnlineRollingCount.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/algorithm/OnlineTrend.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/algorithm/RollingBuffer.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/model/StatefulExpr.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/algorithm/BaseOnlineAlgorithmSuite.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/algorithm/OnlineDerivativeSuite.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/algorithm/OnlineIntegralSuite.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/algorithm/OnlineRollingCountSuite.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/algorithm/OnlineTrendSuite.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/model/TimeSeriesExprSuite.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/model/TrendSuite.scala
Updates all of the stateful operators to use the same
online algorithm base classes. This also gives them a
consistent representation of state that can easily be
serialized and deserialized. This is a first step to
possible future work of persisting the state of streaming
evaluations so it can be replayed or the execution can
be transitioned to another instance.
> consistent state model for all stateful operators

- atlas-akka/src/main/scala/com/netflix/atlas/akka/StreamOps.scala
- atlas-akka/src/test/scala/com/netflix/atlas/akka/StreamOpsSuite.scala
In some cases, such as calling `discardEntityBytes` for an
HTTP response, it is useful to access the materializer for
the stage so the stream blueprint can be created without
needing to pass in a materializer.
> add helpers for accessing materializer for stage

- atlas-poller-cloudwatch/src/main/resources/nat-gateway.conf
- atlas-poller-cloudwatch/src/main/resources/reference.conf
See
https://docs.aws.amazon.com/vpc/latest/userguide/vpc-nat-gateway-cloudwatch.html
> Add NATGateway Metrics

- atlas-poller-cloudwatch/src/main/resources/rds.conf
- atlas-poller-cloudwatch/src/test/scala/com/netflix/atlas/cloudwatch/MetricDefinitionSuite.scala
Add collection of `AuroraReplicaLag` and `AuroraReplicaLagMaximum`
(issue #1002).
> Collect additional aurora replica metrics

- atlas-poller-cloudwatch/src/main/resources/lambda.conf
- atlas-poller-cloudwatch/src/main/resources/reference.conf
Add collection of
* `ConcurrentExecutions`
* `UnreservedConcurrentExecutions`
* `DeadLetterErrors`
* `IteratorAge`
Issue #1005
> Collect additional lambda metrics

- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/Evaluator.java
- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/EvaluatorImpl.scala
- atlas-eval/src/test/scala/com/netflix/atlas/eval/stream/EvaluatorSuite.scala
Adds a `evaluator.createDatapointProcessor(DataSources)` method
that can be used to process a generated set of datapoints rather
than getting data from an LWC cluster. This can be used for tests
or for using Atlas expressions over arbitrary event streams.
Fixes #798.
/cc @vshirikian @ruchirj
> support generated dataset for eval

- atlas-eval/src/test/scala/com/netflix/atlas/eval/stream/FinalExprEvalSuite.scala
Verify that rolling window for stateful operators moves
for intervals that have no data for the expression.
> add test case for stateful windows with no data

- atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/ExpressionSplitter.scala
Switches from a ConcurrentHashMap to a Cache for the interned
queries. This avoids a slow leak over time with churn in the
set of queries. In practice, we have not seen enough churn for
it to matter, but now queries that are no longer in use will
expire and go away.
Fixes #729.
> expire interned queries after 12h

- atlas-core/src/main/scala/com/netflix/atlas/core/db/MemoryDatabase.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/db/MemoryDatabaseSuite.scala
The set of tags for the aggregated lines should be limited
to the set that are exact matches in the query or are a part
of a group by. Otherwise the grouping can have incorrect
duplicates in the result set.
Fixes #629.
> fix tag results on MemoryDatabase.execute

- atlas-akka/src/main/scala/com/netflix/atlas/akka/RequestHandler.scala
Adjust the default to use `BEST_SPEED` to reduce the
computation overhead of compressing the results.
> adjust compression level for request handler

- .travis.yml
- atlas-core/src/main/scala-2.13+/com/netflix/atlas/core/util/IdentityMap.scala
- atlas-core/src/main/scala-2.13+/com/netflix/atlas/core/util/SmallHashMap.scala
- atlas-core/src/main/scala-2.13-/com/netflix/atlas/core/util/IdentityMap.scala
- atlas-core/src/main/scala-2.13-/com/netflix/atlas/core/util/SmallHashMap.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/db/MemoryDatabase.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/util/IdentityMapSuite.scala
- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/EvaluatorImpl.scala
- atlas-eval/src/test/scala/com/netflix/atlas/eval/stream/FinalExprEvalSuite.scala
- atlas-eval/src/test/scala/com/netflix/atlas/eval/stream/TimeGroupedSuite.scala
- atlas-poller-cloudwatch/src/main/scala/com/netflix/atlas/cloudwatch/DefaultTagger.scala
- project/BuildSettings.scala
- project/Dependencies.scala
Most changes our minor. For some of the custom collections
they needed to be specific to the new version. I expect that
to be temporary as 2.11 and 2.12 support will likely be dropped
for 1.7.x at some point.
> cross build for 2.13.0-RC3

- atlas-jmh/src/main/scala/com/netflix/atlas/akka/UriParsing.scala
Compare performance of various ways to modify the uri.
> add benchmark for uri handling

- project/build.properties
Check to see if this helps resolve the publishing issue
in #1054.
> try disabling gigahorse

- atlas-core/src/main/scala/com/netflix/atlas/core/model/FilterExpr.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/model/FilterVocabulary.scala
Provides better symmetry with the legend as this was the
only stat that wasn't supported.
> add support for `count` with `:stat`

- .travis.yml
> update travis config to use latest scala versions

- atlas-json/src/main/scala/com/netflix/atlas/json/Json.scala
- project/Dependencies.scala
Update to latest jackson release. Should help resolve
the frequent stream of CVEs related to default typing:
https://medium.com/@cowtowncoder/jackson-2-10-features-cd880674d8a2
> jackson 2.10.0

- atlas-poller-cloudwatch/src/main/resources/ec2.conf
- atlas-poller-cloudwatch/src/main/resources/reference.conf
For more details see:
https://docs.aws.amazon.com/AWSEC2/latest/APIReference/monitor.html
> add mapping for EC2 API call metrics

- atlas-core/src/main/scala/com/netflix/atlas/core/validation/ValuePatternRule.scala
Improves performance in many cases. For more details,
see Netflix/spectator#651.
> use PatternMatcher helper for validation

- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/EurekaSource.scala
- atlas-eval/src/test/scala/com/netflix/atlas/eval/stream/EurekaSourceSuite.scala
Do lwcapi instance lookup via Edda, if the uri looks like edda (contains "/autoScalingGroups")
> support lwcapi instance lookup via edda 

- atlas-wiki/src/main/scala/com/netflix/atlas/wiki/GraphHelper.scala
Use builder for creating the JsonFactory instance.
> fix Jackson deprecation warnings

- atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/SubscribeApi.scala
- atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/WebSocketSessionManager.scala
- atlas-lwcapi/src/test/scala/com/netflix/atlas/lwcapi/WebSocketSessionManagerSuite.scala
allow updating lwc stream subscriptions via web socket API
> allow updating lwc stream subscriptions via web socket API

- atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/QueueHandler.scala
- atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/WebSocketSessionManager.scala
- atlas-lwcapi/src/test/scala/com/netflix/atlas/lwcapi/WebSocketSessionManagerSuite.scala
Adds a debug level log to see specific messages that are
dropped because they cannot be enqueued.
> debug log for dropped messages

- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/EvaluatorImpl.scala
Currently in eval stream, "Datasources broadcast" is getting back-pressured by FinalExprEval under heavy load and new DataSources can not flow to LWC API calls timely and causes out of date subscriptions.
This change avoid back pressure at sub streams of Datasources broadcast, so that they will not block each other; and keeping only latest DataSources is fine for both sub stream when under heavy load.
> atlas-eval: avoid back pressure at sub streams of datasources broadcast

- project/Dependencies.scala
Update to latest jackson version to pick up security
fixes.
> update to latest jackson version

- atlas-wiki/src/main/resources/Getting-Started.md
Bump the version in the wiki to the latest.
> update version in wiki to 1.6.5

- atlas-poller-cloudwatch/src/main/resources/dx.conf
- atlas-poller-cloudwatch/src/main/resources/reference.conf
For the connection level metrics just map in the state
as that is the only metrics currently getting produced.
> add mapping for CW direct connect

- .travis.yml
Update to latest since we only support 2 LTS plus
latest.
> update travis to use jdk15

- atlas-poller-cloudwatch/src/main/resources/reference.conf
- atlas-poller-cloudwatch/src/main/resources/route53.conf
Add mappings for the basic healthcheck, hosted zone, and
resolver metrics.
> add mapping for route53 cloudwatch metrics

- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/EvaluatorImpl.scala
- atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/StreamApi.scala
- atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/SubscribeApi.scala
Updates the queue source used for writing diagnostic
messages to use a BroadcastHub instead of Publisher.
The main reason is that under newer versions of akka
there is a 5s subscription timeout for the underlying
FanoutProcessor created with the Publisher.
All other users of `asPublisher` were also converted
unless the `Publisher` type was explicitly needed as
part of the public API for the method.
> eval: use BroadcastHub instead of Publisher

- atlas-core/src/main/scala/com/netflix/atlas/core/index/QueryIndex.scala
Cleanup unused private method from QueryIndex.
> remove unused method

- atlas-poller-cloudwatch/src/main/resources/elb.conf
- atlas-poller-cloudwatch/src/main/resources/reference.conf
add mapping for elb processed bytes
> add mapping for elb processed bytes

- atlas-poller-cloudwatch/src/main/resources/rds.conf
- atlas-poller-cloudwatch/src/main/resources/reference.conf
Use the right dimension "DbClusterIdentifier" for rds metric "VolumeBytesUsed".
> fix dimension for rds metric: VolumeBytesUsed

- atlas-core/src/test/scala/com/netflix/atlas/core/validation/ValidCharactersRuleSuite.scala
Ensure that null chars would get rejected by validation
rules as expected.
> add test for validation of null chars

- project/Dependencies.scala
Pull in fix for some performance regressions:
https://akka.io/blog/news/2021/02/23/akka-2.6.13-released
> update akka to 2.6.13

- project/Dependencies.scala
That is the latest version that is on maven central.
> move back to RoaringBitmap 0.9.3

- atlas-akka/src/main/resources/reference.conf
- atlas-akka/src/main/scala/com/netflix/atlas/akka/WebServer.scala
- atlas-standalone/src/main/resources/log4j2.xml
Updates the server config so it is easy to run on multiple
ports. SSL config can optionally be provided for a given
port for HTTPS.
> config setting for multiple ports

- atlas-webapi/src/main/resources/reference.conf
> Expose expr api by default.

- .github/workflows/pr.yml
Update the PR workflow to build the scaladoc so we'll
notice problems prior to merging.
> build scaladoc for PRs

- atlas-module-cloudwatch/src/main/scala/com/netflix/atlas/guice/CloudWatchModule.scala
- atlas-poller-cloudwatch/src/main/scala/com/netflix/atlas/cloudwatch/CloudWatchPoller.scala
- atlas-poller-cloudwatch/src/main/scala/com/netflix/atlas/cloudwatch/Conversions.scala
- atlas-poller-cloudwatch/src/main/scala/com/netflix/atlas/cloudwatch/DefaultTagger.scala
- atlas-poller-cloudwatch/src/main/scala/com/netflix/atlas/cloudwatch/GetMetricActor.scala
- atlas-poller-cloudwatch/src/main/scala/com/netflix/atlas/cloudwatch/ListMetricsActor.scala
- atlas-poller-cloudwatch/src/main/scala/com/netflix/atlas/cloudwatch/MetricCategory.scala
- atlas-poller-cloudwatch/src/main/scala/com/netflix/atlas/cloudwatch/MetricDefinition.scala
- atlas-poller-cloudwatch/src/main/scala/com/netflix/atlas/cloudwatch/MetricMetadata.scala
- atlas-poller-cloudwatch/src/main/scala/com/netflix/atlas/cloudwatch/NetflixTagger.scala
- atlas-poller-cloudwatch/src/main/scala/com/netflix/atlas/cloudwatch/package.scala
- atlas-poller-cloudwatch/src/test/scala/com/netflix/atlas/cloudwatch/ConversionsSuite.scala
- atlas-poller-cloudwatch/src/test/scala/com/netflix/atlas/cloudwatch/DefaultTaggerSuite.scala
- atlas-poller-cloudwatch/src/test/scala/com/netflix/atlas/cloudwatch/MetricDataSuite.scala
- atlas-poller-cloudwatch/src/test/scala/com/netflix/atlas/cloudwatch/MetricDefinitionSuite.scala
- atlas-poller-cloudwatch/src/test/scala/com/netflix/atlas/cloudwatch/NetflixTaggerSuite.scala
- project/Dependencies.scala
Update the cloudwatch poller to use the v2 Java SDK.
> move cloudwatch poller to v2 sdk

- atlas-poller-cloudwatch/src/main/scala/com/netflix/atlas/cloudwatch/GetMetricActor.scala
If there is a sub-second portion of the Instant, then the
remote CloudWatch service will reject it as an invalid
timestamp.
> cloudwatch: truncate times to second boundary

- atlas-poller-cloudwatch/src/main/resources/neptune.conf
fix typo in neptune cloudwatch metrics mapping
> fix typo in neptune cloudwatch metrics mapping

- atlas-poller-cloudwatch/src/main/resources/neptune.conf
make two Neptune metric alias shorter
> make two Neptune metric alias shorter

- atlas-core/src/main/scala/com/netflix/atlas/core/index/RoaringTagIndex.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/index/RoaringTagIndexSuite.scala
Fix ClassCastException for casting the array based on
the generic type.
> fix CCE for RoaringTagIndex.empty

- atlas-core/src/main/scala/com/netflix/atlas/core/model/ItemIdCalculator.scala
Update the id calculator util to use the common helper
function for sorting the pairs to reduce code duplication.
> use sortPairs for id calculator

- atlas-postgres/src/main/scala/com/netflix/atlas/postgres/BinaryCopyBuffer.scala
- atlas-postgres/src/main/scala/com/netflix/atlas/postgres/CopyBuffer.scala
- atlas-postgres/src/main/scala/com/netflix/atlas/postgres/TextCopyBuffer.scala
- atlas-postgres/src/test/scala/com/netflix/atlas/postgres/BinaryCopyBufferSuite.scala
- atlas-postgres/src/test/scala/com/netflix/atlas/postgres/PostgresCopyBufferSuite.scala
- atlas-postgres/src/test/scala/com/netflix/atlas/postgres/TextCopyBufferSuite.scala
- build.sbt
- project/Dependencies.scala
Adds buffer types that can be used to collect data in
memory in a format that can be passed to the Postgres
COPY operation.
> helpers for working with Postgres COPY

- atlas-core/src/main/scala/com/netflix/atlas/core/util/ArrayHelper.scala
Update visibility of merge helper function.
> make merge function public

- atlas-core/src/main/scala/com/netflix/atlas/core/model/FilterVocabulary.scala
Remove the unstable flag for the topk/bottomk operators.
> make topk/bottomk operators stable

- atlas-core/src/main/scala/com/netflix/atlas/core/util/SortedTagMap.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/util/SortedTagMapSuite.scala
Update SortedTagMap implementations of equals and hashCode
to improve the performance.
> improve equals/hashCode performance

- project/Dependencies.scala
Update to pick up version with further hardening for
security issues.
> log4j 2.16.0

- atlas-webapi/src/main/scala/com/netflix/atlas/webapi/PublishPayloads.scala
Reduce allocations for decoding payloads by reusing
the array for the string table across invocations.
> reuse array for string table

- atlas-lwcapi/README.md
> Add a readme file to the atlas-lwcapi module starting documentation

- .github/workflows/pr.yml
- .github/workflows/release.yml
- .github/workflows/snapshot.yml
https://github.com/actions/setup-java/blob/main/README.md
> GitHub Actions cache sbt

- project/Dependencies.scala
Update to latest ASL licensed Akka and Akka-HTTP and add comment about license change.
> add note about akka versions

- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/TimeGrouped.scala
Batch the counter updates in time grouped to avoid updating them in a tight loop for high throughput
streams.
> batch meter updates for TimeGrouped

- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/EvaluatorImpl.scala
Moves the step for parsing messages after the merge of streams from each of the LWCAPI nodes. This makes it easier to keep track of the overall number of concurrent requests and ensure it backpressures rather than enqueues.
Also changes to use the ordered variant. Preserving the order could be important to avoid newer messages getting pushed through first and moving the cutoff point for the time grouping.
> parse messages after merge of streams

- project/Dependencies.scala
Pull in some memory and performance optimizations in jackson ([2.14.1]).
[2.14.1]: https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.14.1
> jackson 2.14.1

- .github/workflows/pr.yml
- project/BuildSettings.scala
In preparation for Spring 6, drop support for jdk8 and jdk11.
> set baseline java version to 17

- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/Evaluator.java
- project/Dependencies.scala
Only code chagne is to remove an unnecessary use of the Inject annotation.
> update to spring 6

- .github/workflows/pr.yml
> ci: add jdk20

- atlas-core/src/main/scala/com/netflix/atlas/core/model/EventExpr.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/model/EventVocabulary.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/model/ModelExtractors.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/model/TraceQuery.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/model/TraceVocabulary.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/model/EventVocabularySuite.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/model/TraceVocabularySuite.scala
Adds vocabularies for event and trace queries that will be used via LWC.
> lwc: add stack lang operators for events

- atlas-spring-lwc-events/src/main/scala/com/netflix/atlas/lwc/events/LwcEventConfiguration.scala
- atlas-spring-lwc-events/src/test/scala/com/netflix/atlas/lwc/events/LwcEventConfigurationSuite.scala
- build.sbt
It was overlooked and not getting published.
> add spring-lwc-events project to aggregate

- atlas-postgres/src/test/scala/com/netflix/atlas/postgres/PostgresCopyBufferSuite.scala
Update test method to close result set.
> ensure result set is closed

- project/Dependencies.scala
Pull in fix for spin loop in TLSActor.
> akka 2.6.21

- atlas-pekko/README.md
> Update README.md (reference to pekko)

- atlas-core/src/main/scala/com/netflix/atlas/core/model/MathExpr.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/model/MathVocabulary.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/model/ModelExtractorsSuite.scala
- atlas-webapi/src/test/scala/com/netflix/atlas/webapi/ExprApiSuite.scala
These can be useful for defining synthetic data when demoing operations.
> core: add support for basic trig functions

- atlas-standalone/src/main/resources/static.conf
> standalone: add ExprApi to static config

- atlas-core/src/main/scala/com/netflix/atlas/core/stacklang/Interpreter.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/stacklang/StandardVocabulary.scala
- atlas-core/src/test/scala/com/netflix/atlas/core/stacklang/InterpreterSuite.scala
- atlas-webapi/src/main/scala/com/netflix/atlas/webapi/ExprApi.scala
Update interpreter API to be more consistent with recent changes in 1.8.
> 1.7.x: add default values for interpreter execute

- project/Dependencies.scala
Pull in fix for ORing run containers.
> roaringbitmap 1.0.6

- atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/SubscribeApi.scala
- atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/WebSocketSessionManager.scala
- atlas-lwcapi/src/test/scala/com/netflix/atlas/lwcapi/WebSocketSessionManagerSuite.scala
Some messages such as the subscription metadata need to go through in order to properly process data. In some cases we would see a lot of input data come in almost immediately and result in the subscription info messages getting dropped. The consumer was then unable to match the datapoints with an expr.
This changes the messages for setting up a new subscription to be a high priority path that bypasses the queue for incoming data points.
> lwcapi: avoid queue for high priority messages

- atlas-eval/src/main/resources/reference.conf
- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/DataSourceRewriter.scala
- atlas-eval/src/test/scala/com/netflix/atlas/eval/stream/DataSourceRewriterSuite.scala
Move the config settings to be explicitly in the config so it is easy to confirm when checking settings.
> eval: add rewrite settings to reference.conf

- atlas-core/src/main/scala/com/netflix/atlas/core/model/ItemId.scala
- atlas-core/src/main/scala/com/netflix/atlas/core/model/ItemIdCalculator.scala
Use Arrays utility method for comparing the byte arrays.
> core: simplify id compare

- atlas-core/src/main/scala/com/netflix/atlas/core/norm/NormalizationCache.scala
Avoid reference to outer class.
> core: make CacheValue helper class static

- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/EvaluatorImpl.scala
Update so that the set of subscriptions sent to the LWC API servers are encoded before sending into the cluster grouping operator. This means the encoding will only happen once per cluster rather than once per node.
> eval: reduce encoding overhead

- atlas-eval/src/main/resources/reference.conf
Update default setting to compress subscription messages.
> eval: compress sub messages by default

- atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/SubscribeApi.scala
- atlas-lwcapi/src/test/scala/com/netflix/atlas/lwcapi/SubscribeApiSuite.scala
Client usage is all updated at this point.
> lwcapi: always use v2 subscription message

- atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/EvaluatorImpl.scala
- atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/ExpressionMetadata.scala
- atlas-lwcapi/src/test/scala/com/netflix/atlas/lwcapi/SubscribeApiSuite.scala
It will be used with sampling operators.
> eval: preserve step for event URIs

- atlas-lwc-events/src/main/scala/com/netflix/atlas/lwc/events/AbstractLwcEventClient.scala
- atlas-lwc-events/src/main/scala/com/netflix/atlas/lwc/events/DatapointConverter.scala
- atlas-lwc-events/src/main/scala/com/netflix/atlas/lwc/events/RemoteLwcEventClient.scala
- atlas-lwc-events/src/test/scala/com/netflix/atlas/lwc/events/DatapointConverterSuite.scala
Log expression hitting max groups limit.
> lwc-events: add log for max groups limit

- atlas-lwc-events/src/main/scala/com/netflix/atlas/lwc/events/DatapointConverter.scala
- atlas-lwc-events/src/test/scala/com/netflix/atlas/lwc/events/DatapointConverterSuite.scala
If new events update the value after the step boundary, but before flushing, then the sample would be missing. Simplify the logic to mark the sample stale and refresh on the next update. If no new update comes in, the previous sample will be used again.
> lwc-events: fix sporadic missing samples

- atlas-lwc-events/src/main/scala/com/netflix/atlas/lwc/events/DatapointConverter.scala
Use info level for exceeding max group by size.
> lwc-events: update log level

- atlas-webapi/src/main/scala/com/netflix/atlas/webapi/FetchRequestSource.scala
Update fetch to honor a larger step size from the data response. Avoids errors in cases where the data actor adjusts it based on the data that is accessed.
> webapi: have fetch honor response step

- atlas-lwcapi/src/main/scala/com/netflix/atlas/lwcapi/SubscribeApi.scala
Clean up metric indicating the number of expressions being for a subscription.
> lwcapi: use dist summary for subscription sizes

- atlas-lwc-events/src/test/scala/com/netflix/atlas/lwc/events/LwcEventClientSuite.scala
Use delta for double comparison to avoid spurious
test failures.
> lwc-events: fix flakey test case
